### ISSUE TITLE
Play videos automatically only if tab is in focus

### ISSUE THREAD

**Issue by ignacy0109** [ParticleCore/Iridium#10]
It would be great if you added an option to play videos automatically only if tab is in focus. (If you open a video in current tab it plays normally, if you open it in new tab it is stopped.) Maybe also with an option of auto playing that stopped video when you switch to its tab (though that's a fancy feature almost nobody bothers to implement).

Also an option to allow buffering on auto stopped videos would be nice, though no longer essential as Youtube upped their buffering speed.

**Comment by ParticleCore** [comment]
I know this comes after you've opened your requests, but there are now instructions for when opening issues: https://github.com/ParticleCore/Iridium/blob/master/.github/ISSUE_TEMPLATE.md

It is alright, this didn't exist before, which is why I will be splitting your requests.
