### ISSUE TITLE
[bug] mini player when navigating to different pages 

### ISSUE THREAD

**Issue by yjlintw** [ParticleCore/Iridium#100]
Browser Name: Chrome
Browser Version: 59
Operating System: macOS Sierra
Software Type: Userscripts
Software Version: 0.0.9b
Userscript Manager: Tampermonkey
Userscript Version: v4.3.6

Problem Description: 
The mini player is not visible when switching to a different page, but the video is still playing. The mini player did show up when I scroll down on the video page.

**Comment by ParticleCore** [comment]
I can't believe I made such a foolish mistake, brb, updating the script with the quick fix.

**Comment by ParticleCore** [comment]
Should work now, sorry for this mess.

**Comment by DioBrando141** [comment]
sorry if im not doing this correctly, but i think this patch added another problem. now if one disables this option, the player always starts in mini form.

Browser Name: Chrome
Browser Version: 60
Operating System: Windows 10
Software Type: Userscripts
Software Version: 0.1.0b
Userscript Manager: Tampermonkey

**Comment by ParticleCore** [comment]
No, you are doing it almost right, better would be it on a separate issue, but will recycle this one this time.

**Comment by ParticleCore** [comment]
Latest version should finally have both problems fixed correctly, my apologies for the mishap.
