### ISSUE TITLE
Iridium in Firefox Violentmonkey

### ISSUE THREAD

**Issue by eberhardweber** [ParticleCore/Iridium#101]
Does Iridium load with Violentmonkey?

I understand that official support is reserved only for Tampermonkey in Firefox, but with [Violentmonkey ](https://addons.mozilla.org/en-GB/firefox/addon/violentmonkey/) becoming a very viable open-source alternative to Greasemonkey as well as the closed-source Tampermonkey with the move to WebExtensions in Firefox, I figured I would bring the issue up.

On my setup, with Youtube's new layout turned on in Firefox (55.0) using Violentmonkey (2.6.3), the Iridium icon never loads, and visiting https://www.youtube.com/iridium-settings gives a 404 error, with the FF web console giving a "Use of Mutation Events is deprecated. Use MutationObserver instead." error.

I noticed that there have been earlier bugs like this, like [here](https://github.com/ParticleCore/Iridium/issues/61). 

Has anyone else loaded the script successfully with Violentmonkey?

**Comment by ParticleCore** [comment]
This issue tracker is not to be used for unsupported platforms, please use other places for this kind of question.

**Comment by SW1FT** [comment]
This is an issue with Violentmonkey and started happening when Iridium 0.0.8b was released.
