### ISSUE TITLE
Cannot pause video after a certain sequence of steps with player always playing enabled

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#103]
With the player always playing enabled, after clicking on a video from the main or subscription page, letting it play, then transition to another page will cause the pause function to stop working

**Comment by SW1FT** [comment]
By doing the same STR, after entering fullscreen mode and going out of it by pressing ESC on Firefox (this doesn't happen if you press the "Leave fullscreen mode" button on the fullscreen warning for some reason) the video derps out.
![miniplayerbug](https://user-images.githubusercontent.com/6627739/29304136-68a26f46-8189-11e7-9681-5a54704cf735.png)

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/releases/tag/0.1.3b

**Comment by ParticleCore** [comment]
@SW1FT Could you open a separate issue with the details for that? I think I was able to get it a couple of times, but now I am having a hard time getting it to happen again.
