### ISSUE TITLE
[Updated] This project has been placed on hold

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#104]
Update: I have discovered that the cause of multiple problems I was having while trying to develop the extension was due to a Firefox update (version 55) that kinda screwed things up, big time. After solving this, I immediately went from more than 20+ experience breaking problems down to 1 feature bug.

I can now say with pleasure that I restarted development of the extension and hope that no more problems like this occur.

Sorry for the trouble and thank you for the support and understanding.

______

The announcement has been detailed here: https://github.com/ParticleCore/Iridium/releases/tag/0.1.3b

**Comment by blaenk** [comment]
I'm sorry to hear about this and I sympathize with the struggle.

The primary, and if it came to it, sole, feature that I am interested in is preventing videos from being auto-played. Can you share your insight into whether that particular tweak is as difficult to reverse engineer and work around relative to the others? More generally, are some features vastly easier to reverse engineer and work around? If so, do you think you might be open to putting the harder, infeasible features on hold but continuing to support the drastically simpler ones? Potentially coming back to the harder ones once the new YouTube settles down and stabilizes, if that ever happens.

If not, I understand, though I'm curious to know if are you aware of any other project/tool that does track and actively develop for that feature, that you may be able to recommend.

**Comment by joridiculous** [comment]
Oh snap :/  Cant blame you really. How much and often those GoogleYouTube devs change and screw stuff up, it must take its toll on you guys trying to make YouTube great again.

For what it is worth. Im using particle (extention) on Chrome and it does what i want it to do, and does it good (So far). For how long, who knows. 
@blaenk The "Turn off the light" extension works ok for stopping AutoPlay videos. Not only on YouTube but all over. You just have to turn the feature ON in its settings.
https://www.turnoffthelights.com/

**Comment by ParticleCore** [comment]
The issue has been updated.

**Comment by tympapost** [comment]
@ParticleCore 
You might have to keep at least one webkit browser installed and test things out to avoid these kind of problems. 
I really found myself wondering why all the negativity with this post, when my experience with Iridium is actually great so far. The only feature I really miss is full-browser video mode and this extension will be perfect to my eyes.
But as far as bugs or broken things, the experience I have with Chrome+Tampermonkey is great, especially after finding that workaround with settings not being saved as they should.
You do realise that you are the only **active** author left on Github, working on the material layout of youtube. All other extensions I know (at least for Chrome) are from shady companies with closed code which is raising many concerns.
So, please, keep up the good work. We really appreciate your hard work.

**Comment by ParticleCore** [comment]
The versions I publish are always (at least as best as I can) fully functional, it is during the development phase before releasing each version the headaches surface. I do have Chrome and the problems were not occurring with it, but on Firefox YouTube is almost a completely different source code, filled with poly-fills for the new layout and it was on Firefox that all hell was broken loose.
If I can't make it work for Firefox then I would rather not do it at all, it is my favorite browser and I wouldn't dream not supporting it on my extension.

I will try to do my best, as always, but, again, with so little free time I am afraid that users will have to be patient for each release, new feature and bug fixes.

I am not the only one working on the new layout, YePpHa, YouTube Center's developer, is also [working on the new layout](https://github.com/YePpHa/maia-yt), although he has been quite inactive lately, but I understand what you mean. And now I noticed that both our repo's descriptions are almost the same, I gotta change mine...
