### ISSUE TITLE
Video on miniplayer isn't centered after leaving the fullscreen mode

### ISSUE THREAD

**Issue by SW1FT** [ParticleCore/Iridium#106]
**Browser Name:** Firefox

**Browser Version:** 57.0a1

**Operating System:** Windows 10

**Software Type:** Userscript

**Software Version:** 0.1.3b

**Userscript Manager:** Tampermonkey

**Userscript Version:** 4.4.5484

**Problem Description:** Title sums it up pretty well. Here's a picture of what happens: 

![](https://user-images.githubusercontent.com/6627739/29304136-68a26f46-8189-11e7-9681-5a54704cf735.png)

**Steps to reproduce:** 
1. Load a video page and play the video.
2. Click on the YouTube logo.
3. Press the fullscreen button in the miniplayer.
4. Press ESC to leave the fullscreen mode.

**Additional details:** If, instead of pressing ESC to exit fullcreen mode, you click on the "Leave fullscreen mode" button on the fullscreen warning, the bug doesn't occur. This makes it look like it might be a Firefox bug rather than Iridium, but I have no idea because I didn't test with Chrome.

**Comment by ParticleCore** [comment]
Thanks for the detailed explanation, will try to find out what is going on.
