### ISSUE TITLE
Ability to reposition floating player like in the old extension

### ISSUE THREAD

**Issue by BitGrub** [ParticleCore/Iridium#108]
First of all, this is great. I'm using the material version of youtube and Iridium (name subject to change?) is a must-have. The only thing I'm missing is the ability to drag the floating player (when you scroll down the comments or change page) to reposition it, just like in the old extension. 

Also if you could change the size in real time that'd be great as well.
Cheers

**Comment by ParticleCore** [comment]
In the future please read the instructions, especially the part about including more than one request in one issue:

> Do not include more than one subject (problem, request or both) in one issue.

https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by hyperfekt** [comment]
For reference, changing the position of the floating player is already possible by dragging it with it's border, one has to be rather exact though to click neither the video nor the website behind.
