### ISSUE TITLE
Disabling autoplay doesn't work for new tabs (firefox)

### ISSUE THREAD

**Issue by MattSturgeon** [ParticleCore/Iridium#113]
In firefox, but not chromium, opening a video in a new tab (or reloading an open video) will bypass the autoplay setting. Opening a video in the current video (soft load) will respect the autoplay setting.

EDIT: Firefox testing done on Greasemonkey, Chromium was tested using Tampermonkey. I've not tested using Violentmonkey

**Comment by eduzappa18** [comment]
i have the same issue on firefox 55.0.3 (64-bit)
and this is also happening in the old youtube layout with YouTube+ too

**Comment by d4k0** [comment]
Same problem here since a few hours. Disabling autoplay somehow doesn't work anymore. I'm using Firefox 55.0.3 x64 and Tampermonkey.

**Comment by Corruptinglyneedful** [comment]
Can confirm, happening on both Particle and Iridium.

**Comment by TheCuza** [comment]
Will the fix be for Youtube+ as well? I'd rather stick with the old layout for as long as possible until Youtube forces the new one on me.

**Comment by ParticleCore** [comment]
@TheCuza Yes, the fix will come to YT+ as well once one is found.

**Comment by ParticleCore** [comment]
Closing this for now since the original feature is working correctly again. Will re-open if the problem occurs again.

**Comment by ParticleCore** [comment]
Looks like this problem has returned.

**Comment by ParticleCore** [comment]
Version 0.2.0b received the previous temporary patch while I try to find a proper fix for this problem.

**Comment by nanisise** [comment]
OK, Here is the issue: On new version Youtube, Firefox load and play video first, then load other elements in the page.  Disabling autoplay only works after entire page loaded, so it causes the video to be played few seconds and stopped. In right case, Iridium should stop autoplay immediately after the video loaded.
Another issue is when disabling autoplay, the last playback progress will not be saved.
These issuses are on firefox 55.0.3, 53.0.3

**Comment by ParticleCore** [comment]
@nanisise I am aware of what it should be doing, that is what I am trying to get it to do again with a proper fix, the current fix is just a patch, as I clearly explained in my previous reply.
