### ISSUE TITLE
Installed no control panel or access to settings?  How do I use this?

### ISSUE THREAD

**Issue by Corruptinglyneedful** [ParticleCore/Iridium#114]
I installed the userscript 0.1.7b and I have no options on Youtube?  

I'm on Firefox v55.0.2 x64
I am on Greasemonkey v3.11
I am trying to use Iridium 0.1.7b

I'm really confused, I figured it was just like Particle but I guess I"m wrong.  You install it into and an icon appears and you click it to access the settings.  I can't find any help documents that tell me how to access the control panel for the  settings.  I don't see any icon, there's nothing.  Is this incompatible with that version of Greasemonkey or Firefox?

Can't be a Firefox profile issue either, as I just literally created this profile for v55 bug.  By literally I mean about 1 hour ago.

Can someone help me?

**Comment by ParticleCore** [comment]
First you need to make sure that you are using the new Material Layout on YouTube by going to youtube.com/new, then on your top right you will see a white or grey triangle which will lead you here: www.youtube.com/iridium-settings.

**Comment by Corruptinglyneedful** [comment]
DOH
