### ISSUE TITLE
How is with new features in Iridium comparing to YouTube+?

### ISSUE THREAD

**Issue by Piter432** [ParticleCore/Iridium#116]
Hello, I have question about features in Iridium.

As I and some people know, some features in YouTube+ couldn't be added, 'cause you have limited time or resources in framework or something like that.

Is it the same in Iridium or not?
Thank you for any short answer 😃

**Comment by ParticleCore** [comment]
You can find the **current** list of features here: https://github.com/ParticleCore/Iridium/wiki/Features

More will be added in the future.

**Comment by Piter432** [comment]
So, some features from YouTube Center you could add to Iridium, am I thinking right?

**Comment by ParticleCore** [comment]
Yes, but only the ones I find useful.

**Comment by Piter432** [comment]
Okay, thank you for the answer 😃
