### ISSUE TITLE
When did we get a Firefox add-on?

### ISSUE THREAD

**Issue by Daisenki** [ParticleCore/Iridium#117]
When did we get the finish add-on or a .xpi? 

YouTube lunch his new design and not every user uses userscript manager at Firefox. 

And yes, I know we can still go back to the old design now, but how long will this work... if the lunch it now for everyone.

Don't get me wrong, no one ask for a 100% working and perfect add-on or .xpi, do it like every dev and update the add-on at the Firefox App Store.

**Comment by ParticleCore** [comment]
When I can, there are no dates marked, things will evolve when I have some free time.
