### ISSUE TITLE
Main player rezising?

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Iridium#118]
Is this a feature you are intending to add?

With the new design, the player, when in theatre mode, stretches all the way across the page which in my opinion is absolutely idiotic, It should stay 16:9 just like before.

So I'd love it if we could change the size to something custom like in Youtube+.
Perhaps take advantage of the 'default view' not stretching across and changing the size of that instead?

**Comment by ParticleCore** [comment]
I don't know yet.
