### ISSUE TITLE
Issue with 'player always visible'

### ISSUE THREAD

**Issue by Eisys** [ParticleCore/Iridium#119]
Browser Name: Chrome
  Browser Version: Version 61.0.3163.59 (Official Build) beta (64-bit)
  Operating System: Win 10 Pro
  Software Type: Userscript
  Software Version: Iridum 0.1.9b
  Userscript Manager: Tampermonkey
  Userscript Version: 4.3.6

  Problem Description: When 'player always visible' is enabled and you scroll down and  back up, the main player can now be moved around.

  Steps to reproduce: On a video page scroll down until the floating player appears, scroll back up and hover over the top of the main video. The moving cursor appears and the player can be moved.

  Additional details: http://i.imgur.com/fN01Xye.gifv
Sorry if this is already known to you and/or related to #109

**Comment by ParticleCore** [comment]
The move feature is still under development and was only pushed incomplete due to the recent autoplay issue patch: https://github.com/ParticleCore/Iridium/releases/tag/0.1.8b . Thanks for letting me know though.
