### ISSUE TITLE
Add feature to repeat video playback

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Iridium#12]

**Comment by ParticleCore** [comment]
You are aware that YouTube already has a built-in option like this in their player? Right-click on the player and in the menu you have a "Loop" option.

**Comment by Keith94** [comment]
Oh, I was not aware of that! Is there a way to enable loop by default?

**Comment by ParticleCore** [comment]
That I do not know.

**Comment by Paramirage** [comment]
Have to click on loop each time but want to create loop by default. Is there any possibility so that i dont have to click on loop each time ?

**Comment by Keith94** [comment]
@Paramirage I found a script that can set loop by default:
https://greasyfork.org/en/scripts/27308-youtube-html5-auto-loop

Install with [Greasemonkey](https://addons.mozilla.org/addon/greasemonkey/) or similar.

**Comment by Eric1212** [comment]
This feature is a most, specially on music listening sessions...
