### ISSUE TITLE
Make it compatible with YouTube Resize Script , or implement one in this one.

### ISSUE THREAD

**Issue by Kristijan1001** [ParticleCore/Iridium#121]
I was using the old Youtube + for long time now with the new layout, it breaks youtube resize script,  when u scroll down the video pops up on the whole screen instead of in the corner. Note to say that the YoutubeResize also moves the top youtube bar below the video (Picture of the toolbar i am actually talking about: http://i.imgur.com/fmD2gX5.png ) , to make the fully full screen experience without going in actual fullscreen. With Youtube + This actually worked perfectly but it broke now with Iridium.Also hope a resize function is added like the old one for the popup windows. One of the Best Scripts out there Keep up the amazing work

If possible to implement this script into this Iridium will be really awesome .

Here is the script location:
https://github.com/Zren/ResizeYoutubePlayerToWindowSize/
https://openuserjs.org/scripts/zren/Resize_YT_To_Window_Size

Without Youtube Resize Script:
http://i.imgur.com/2dyuBEN.png

With Youtube Resize Script:
http://i.imgur.com/XDF4xu5.png

**Comment by ParticleCore** [comment]
This extension is still in beta phase under development and I have no plans on making it work with other extensions that are not compatible,
