### ISSUE TITLE
Settings menu unavailable when using Nightly.

### ISSUE THREAD

**Issue by Radagast** [ParticleCore/Iridium#122]
Steps to reproduce:
Nightly with a clean profile
Set `extensions.legacy.enabled` to True
Install Greasemonkey 3.11 (Restart)
 Install Iridium 1.9b
Load any Youtube video
Iridium settings page icon is not shown.

Alternate:
As above but with `extensions.legacy.enabled` set to default
Install Violentmonkey Webext
Install Iridium
Load any Youtube video
Iridium settings page icon is not shown.

Alternate 2:
As above with firefox release version
All works with Greasemonkey
No settings page icon with Violentmonkey

**Comment by SW1FT** [comment]
Try with Tampermonkey instead.

**Comment by Radagast** [comment]
Tampermonkey works with Nightly, just not sure I trust the extension.

**Comment by SW1FT** [comment]
I trust AMO so I'm using it until Greasemonkey has a WebEx version.

**Comment by ParticleCore** [comment]
There is no support for Violentmonkey and I doubt I will be able to fix anything for Greasemonkey on Nightly because I suspect this is a limitation on the add-on itself, not with the userscript since it works perfectly fine with Tampermonkey, which is a proper WebExtension.

**Comment by Radagast** [comment]
Thanks for the help. I'll see how things go with Tampermonkey for now.
