### ISSUE TITLE
Playback speed selection for thumbnail preview

### ISSUE THREAD

**Issue by SammysHP** [ParticleCore/Iridium#124]
It would be nice to have an option to increase the playback speed of thumbnail previews, e.g. 8x or 16x.

**Comment by ParticleCore** [comment]
I know this might be confusing, but since YouTube went ahead with their own thumbnail previews I renamed my feature to thumbnail playback, because you actually watch the entire video in the thumbnail and to make it easier to distinguish.
Which one of them are you asking this option for?

**Comment by SammysHP** [comment]
I didn't know that YouTube is working on an own implementation of thumbnail previews. I was talking about a feature of *YouTube Center* where you can get a GIF-like preview of the whole video when you hover over a thumbnail. It was possible to select the speed so you could get an overview of the video from start to end in just a few seconds.

**Comment by ParticleCore** [comment]
Regarding the use of the thumbnails for preview you can read more about it here: https://github.com/ParticleCore/Iridium/issues/27#issuecomment-308708654

**Comment by SammysHP** [comment]
I know the restrictions of the thumbnail images. The YouTube player (that seems to be used for the thumbnail preview as well) seems to support a playback speed ranging from 0.25 to 2 (you can set it in the video options). Maybe it is possible to increase this value even more and it would be just another parameter for the player.
