### ISSUE TITLE
"stats for nerds " can't closed ; window position can not be fixed.

### ISSUE THREAD

**Issue by wangbolizhong** [ParticleCore/Iridium#125]
Windows 7 64bit Chrome 60.0.3112.113  Tampermonkey 4.3.6  Iridium 0.2.0b

1. When you open "stats for nerds" and scroll the page down then you can't close it.
![image](https://user-images.githubusercontent.com/11750269/29938090-2e7103c6-8eba-11e7-8a36-cf098bf9e296.png)

![image](https://user-images.githubusercontent.com/11750269/29937955-c2f7ec90-8eb9-11e7-99ba-39f53d05b093.png)

2. When you scroll down and adjust the video window location then scroll up and down again，
![image](https://user-images.githubusercontent.com/11750269/29938329-fd8b3cb2-8eba-11e7-9dbb-b6ddd2a2ef35.png)

The window position is restored to its original position (Should the window position be fixed?).
![image](https://user-images.githubusercontent.com/11750269/29938434-4a068f2e-8ebb-11e7-94be-1efc9c748951.png)

**Comment by ParticleCore** [comment]
Window position is still under development, it wasn't suppose to go live except for the recent autoplay urgent patch. Once it is actually completed the issues you pointed out will not exist. Please be patient because I don't have a lot of free time.
