### ISSUE TITLE
Settings page not showing up, a blank page

### ISSUE THREAD

**Issue by erayerdin** [ParticleCore/Iridium#126]
# Environment

 - Xubuntu 16.04
 - Opera 45.0.2552.898
 - Tampermonkey 4.2.5291
 - Iridium v0.2.0b

***

As in the title, settings page shows blank. However, page title "Iridium" and a darker Youtube favicon shows up. See below:

![image](https://user-images.githubusercontent.com/2399084/29945567-45b699b6-8eaa-11e7-8c5a-e6a429856a2f.png)

**Comment by ParticleCore** [comment]
Support is not available for Opera: https://github.com/ParticleCore/Iridium/blob/master/README.md

**Comment by erayerdin** [comment]
Just in case if anyone uses this plugin with Opera and Tampermonkey, they should update to latest version of Opera, which worked for me.

**Comment by ParticleCore** [comment]
@erayerdin Thank you for posting an update to this, I am sure other Opera users will find it useful.
