### ISSUE TITLE
Shouldn't Dark Theme on Iridium settings force Dark Theme on YouTube too?

### ISSUE THREAD

**Issue by omperus** [ParticleCore/Iridium#128]
Just a pet peeve, it would be nice not having to put youtube on dark theme every time i watch a video (i don't save cookies)

**Comment by ParticleCore** [comment]
No, the setting is independent on purpose. There is no guaranteed method to force Dark mode on YouTube without creating an actual dark theme.

**Comment by omperus** [comment]
Found this script that does it https://greasyfork.org/en/scripts/32954-automatic-material-dark-mode-for-youtube in case anyone else has the same problem as me.
