### ISSUE TITLE
Feature request: subscriptions grid view

### ISSUE THREAD

**Issue by AlexFolland** [ParticleCore/Iridium#129]
The new subscriptions view is awful and the grid view I used with YouTube+ was awesome, so here's a request for the return of that feature!

**Comment by AlexFolland** [comment]
I'm just curious, which reason was this closed for?

-feature already exists and user doesn't know about it
-feature accepted and implementation in progress
-feature implemented locally and not yet pushed
-feature not intended in final design
-feature not possible to implement
-implementation would be too arduous for now
-duplicate feature request
-accident

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by AlexFolland** [comment]
That explains it.  Thanks, and sorry for wasting your time.
