### ISSUE TITLE
Iridium doesn't activate for "youtube.com/[channel name]"

### ISSUE THREAD

**Issue by TheCuza** [ParticleCore/Iridium#140]
If you go to a channel directly by typing in the URL like this, Iridum doesn't work, and you must go to another page and then refresh before it activates.

Tested on both Firefox and Chrome.

**Comment by ParticleCore** [comment]
Everything is working correctly if I enter directly a channel url, example: https://www.youtube.com/user/HardwareCanucks or https://www.youtube.com/HardwareCanucks

Please follow the instructions for reporting a problem: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
