### ISSUE TITLE
Off topic: how to access current playing video?

### ISSUE THREAD

**Issue by canufarm** [ParticleCore/Iridium#142]
Hi ParticleCore,

sorry for opening an issue which is off topic, but I did not find any information how to contact you.

I wrote a small script some time ago to open potplayer from any youtube-video. This worked fine with old youtube design. But now there is this issue:

When I open a video link to get to youtube and after that click on my potplayer-link, youtube stops playing and potplayer opens and continues to play the video (all on Windows 7). But when I first click in youtube on another video and after that I click my potplayer-link, potplayer opens as usual, but youtube reloads the current videopage and starts playing the video again.

I use this code:

`ytpl = document.getElementById('movie_player');`
`[...]`
`ytpl.pauseVideo();`

Any hint how to solve this? Thank you!

![youtube](https://user-images.githubusercontent.com/1532881/30081954-5d547448-9289-11e7-8b41-3128c08bc7f9.png)

**Comment by ParticleCore** [comment]
I am sorry, but this is not something that should be asked here, this issue tracker is for Iridium only and I really do not have the time for this. You would be better off asking for help on dedicated forums like stackoverflow, reddit or even userscript forums, such as greasyfork.
