### ISSUE TITLE
Memorize player size Not working properly 

### ISSUE THREAD

**Issue by fable2** [ParticleCore/Iridium#148]
Videos are always playing in the large sized player, even when i switch to small size on earlier videos.
i'd also like to request a feature to enforce player size regardless of what i chose earlier... i need all video to start in small or large size for ex.
using latest stable firefox build and latest greasemonkey.
obviously i have memorize player size switched on.

**Comment by ParticleCore** [comment]
Can't reproduce this problem. Read the instructions: https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md
