### ISSUE TITLE
Errors in the userscript code

### ISSUE THREAD

**Issue by thepcwiz101** [ParticleCore/Iridium#152]
Browser: chrome
Browser Version: 61.0.3163.79
OS: Windows 10 (All updates installed)
Userscript manager: Tampermonkey
Userscript version: 0.2.3b
Problem: Errors when checking syntax of code. 2 warnings and one error. the first two gives a "better written in line notation message" the last one is an error in line 4725 "Expected assignment or function call and instead saw an expression."

**Comment by ParticleCore** [comment]
Same setup and I neither have any warnings nor any errors. Please read the instructions: https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

If you are using a JS validator and not referring to the developer console output log, do note that these validators are often biased, prone to "break" and the warnings and errors may vary according to each one you use. For example, a current test done just now on JSlint interrupts validation on valid RegExp patterns. This is one of the many reasons why I never use them.
