### ISSUE TITLE
Mostly blank page if cookies are disabled.

### ISSUE THREAD

**Issue by sumyungguy** [ParticleCore/Iridium#153]
Hi, looking forward to using this...

I don't accept any Google/YouTube cookies. Because of that, I get a mostly-blank page:
![screenshot_233](https://user-images.githubusercontent.com/5410893/30290479-c898ed1a-972f-11e7-833d-e19aa97b8935.png)

Tested with a new profile, only Greasemonkey 3.11 installed, Iridium 0.2.3b. Unchecking `Privacy-->Accept Cookies from Sites` causes the blank page.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by ParticleCore** [comment]
I don't understand what you are trying to do, is this a feature request or something else? Please read the instructions: https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by sumyungguy** [comment]
It's a bug report. Not sure how that's not clear... I posted a screen shot where it's almost completely blank, no content except a black square and the three widgets. 

I did read and follow the instructions first. I'm using the latest released/stable versions of everything, and I included all the information asked for. Here it is again, in your template form:

 Browser Name: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0

  Browser Version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0

  Operating System: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0

  Software Type: Iridium 0.2.3b userscript

  Software Version: Iridium 0.2.3b userscript

  Userscript Manager: Greasemonkey 3.11

  Userscript Version: Greasemonkey 3.11

  Problem Description: I don't accept any Google/YouTube cookies. Because of that, I get a mostly-blank page

  Steps to reproduce: 
1. Create new profile, install only Greasemonkey 3.11 and Iridium 0.2.3b.
2. Uncheck Privacy-->Accept Cookies from Sites
Expected results: script functions the same as it does with cookies enabled.
Actual results: A nearly-blank page is displayed, with no content.

  Additional details:

**Comment by ParticleCore** [comment]
>Problem Description: I don't accept any Google/YouTube cookies. Because of that, I get a mostly-blank page

Then that is not a problem caused by this extension and you should instead report it to YouTube/Google. This issue tracker is for problems only caused by the extension, not by your decision or YouTube decision.

**Comment by ParticleCore** [comment]
Just checked, looks like this is a problem being caused by the extension. Will check to see what is causing it.

**Comment by ParticleCore** [comment]
Actually my tests show that Iridium does not cause any problems. Please check to see if the problem goes away when the extension is disabled and make sure that you are using the Material layout in YouTube.

**Comment by ParticleCore** [comment]
Appears to be caused by this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=980023

**Comment by ParticleCore** [comment]
As a temporary workaround remove the following blocks of code:

https://github.com/ParticleCore/Iridium/blob/fc8a1472d2616e55f04b081a62e2f18e7ccf30de/src/userscript/Iridium.user.js#L1774-L1777

and

https://github.com/ParticleCore/Iridium/blob/fc8a1472d2616e55f04b081a62e2f18e7ccf30de/src/userscript/Iridium.user.js#L2101-L2111

Let me know if it begins to work correctly again.

Do note that modifying the source code will probably turn off automatic update of the script, meaning that when a new version is released you might have to update it manually.

**Comment by sumyungguy** [comment]
Yes, it works after removing that code, thanks.
