### ISSUE TITLE
When video quality is set to auto it defaults to 1080p

### ISSUE THREAD

**Issue by tgn-ff** [ParticleCore/Iridium#155]
### Bug report

**Browser Name:** Firefox

**Browser Version:** 55.0.3 (and 57.0a1)

**Operating System:** GNU/Linux (for v.55 I tested both downstream and official builds)

**Software Type:** Userscript

**Software Version:** 0.2.4b (and 0.2.3b, 0.2.2b 0.2.1b, 0.2.0b)

**Userscript Manager:** Greasemonkey, (and Tampermonkey, Violentmonkey)

**Userscript Version:** 3.11, (4.4.5484, 2.8.8)

**Problem Description:** When the default video quality is set to auto and you change the quality of the video, when you reload the page or load any other video, the quality will default to 1080p.

**Steps to reproduce:** 1) Create a new profile, install a script manager and then install Iridium. 2) Visit youtube.com and open a video. 3) Change the quality to 720p. 6) Reload the page or open another video and check the quality. -- **Expected result:** the quality should be at 720p. **Actual result:** the quality is at 1080p, and even when you change it back to 720p it'll get back to 1080p after page reload or in new video pages. **Reproducible:** always.

**Additional details:** When Iridium is disabled, the quality is saved properly. Since it worked perfectly until a few days ago and now it doesn't even work in older versions (of Iridium), it's probably a change in youtube itself.

**Comment by ParticleCore** [comment]
It is even worse, it is defaulting to the highest quality possible. Will see what I can do to fix this.
