### ISSUE TITLE
No playback, just black screen

### ISSUE THREAD

**Issue by UserWithProblem** [ParticleCore/Iridium#156]
Hello. Around the time of 0.2.2b, Videos suddenly stopped working. There's no playback at all, just a black screen. I made sure that no other scripts affects it and tested deactivating uBlock Origin, but to no avail.

**Comment by ParticleCore** [comment]
The latest version is 0.2.4b, update it and see if the problem still persists, if it does follow the instructions: https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by ParticleCore** [comment]
Closing this for now, if you still have problems follow the instructions in the previous reply.
