### ISSUE TITLE
Channel trailer is ALWAYS played automatically

### ISSUE THREAD

**Issue by d4k0** [ParticleCore/Iridium#160]
# Bug report

**Browser Name:** Firefox

**Browser Version:** 55.0.3 x64

**Operating System:** Windows 10

**Software Type:** Userscript

**Software Version:** 0.2.5b

**Userscript Manager:** Tampermonkey (and Violentmonkey)

**Userscript Version:** (The userscript manager version you are using; 3.2beta1, 3.10.84)

**Problem Description:** Since a few days I noticed that channel trailers are always played even though I deactivated "Play channel trailers automatically". I also tried a portable version of Firefox with a fresh profile, but the problem also occurs there.

With Chrome 61 I get the same result.

**Steps to reproduce:**
1. Go to a channel with a trailer. This one for example has one: https://www.youtube.com/user/Autobild

1. The trailer will be played automatically event though it is disabled in the Iridium settings. In Firefox the trailer will be played as soon as it is loaded, in Chrome you have to go to the tab first in order for the trailer to be played.

**Comment by Tigoreetur** [comment]
Same

**Comment by RadioActiveLobster** [comment]
Can confirm same issue

**Comment by Nemesis31** [comment]
Hi there, i have the same issue.

**Comment by PplusS** [comment]
I also have the same issue.
