### ISSUE TITLE
[Feature] Enable force use of H.264(AVC) instead of VP9

### ISSUE THREAD

**Issue by mikhaelkh** [ParticleCore/Iridium#161]
Hardware acceleration for vp9 is avalible for Kaby Lake and newer processors. For older processors it may be preferable to use H.264 instead of VP9. Example of implementation: [h264ify](https://github.com/erkserkserks/h264ify)

**Comment by tgp1994** [comment]
For reference, there's an [open source](https://github.com/erkserkserks/h264ify) Firefox extension called h.264ify that does exactly this. My understanding is that it's very beneficial to Firefox users to have YouTube play in h264, so it would be really great to have this implemented.

**Comment by mamuf** [comment]
It would be great if it did some auto-detection, if that's even possible. I mean I have my extensions synced across my machines, but one is a powerful desktop with Kaby Lake and Geforce GTX card and the other is an older MacBook Pro with Haswell CPU, so it would be great if it forced the H.264 only on the MacBook but let the VP9 on the other one. It seems higher video resolutions (4K, 5K...) are supported for VP9 and I would like to play that on my desktop. On the MacBook it really doesn't matter, 1080p is fine.

**Comment by thepcwiz101** [comment]
it is perfectly fine to use h264ify as it actually does not conflict with iridium unless you use the disable 60 fps option.

**Comment by Ryusennin** [comment]
Choosing a prefered codec based on resolution would be a nice feature to add in Iridium, especially since AV1 is finally available for testing on YouTube.

https://www.youtube.com/playlist?list=PLyqf6gJt7KuHBmeVzZteZUlNUQAVLwrZS

**Comment by Fannste94** [comment]
Yes add the option to change the video codec

**Comment by ParticleCore** [comment]
@Fannste94 Do not spam the issue tracker. These issues have already been discussed at length, you are not contributing anything.
