### ISSUE TITLE
Some improvements?

### ISSUE THREAD

**Issue by nulledone** [ParticleCore/Iridium#165]
Hello there, I recently discovered you have finally port 'Youtube +' to material layout, good job! Everything seems working currently except for blacklist button (which disappears on video search). And I have an idea to this addon. How about adding some features like downloading videos etc from YoutubeCenter script?

Script:
https://github.com/YePpHa/YouTubeCenter

**Comment by ParticleCore** [comment]
Iridium will never have a download feature for two main reasons:

 - It would never be accepted in the Chrome Webstore
 - It would not be "enough" for the many users that want more than just the default download options, they are better off using dedicated downloaders for that.

As for the bug, I cannot replicate it. Please read the instructions: https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md
