### ISSUE TITLE
"Dark Header" everywhere with "Memorize Player Size" option enabled

### ISSUE THREAD

**Issue by davideassis** [ParticleCore/Iridium#170]
**Browser Name:** Chrome
**Browser Version:** 61.0.3163.91
**Operational System:** Windows 10
**Software Type:** Userscript
**Software Version:** 0.2.7b
**Userscript Manager:** Tampermonkey
**Userscript Version:** 4.4

**Problem Description:** The "Dark Header" that appears only when the player size is set to "full width" is appearing in the whole site (home, subscriptions, search results and etc) when the option "Memorize Player Size" is enabled, while the standard "light header" appears in the player page.

**Steps to Reproduce:** Just enable Iridium and next enable the option "Memorize Player Size" within "Video Settings" and after that keep the player size "full width" and navigate for a while".

**Additional Details:** Sometimes the site header keeps the correct styles, but most of the time the styles are switched. It doesn't occurs if I disable the "memorize" option and make the player full-width manually, but always happens if I use the option.

![screenshot-www youtube com-2017-09-17-10-57-54-549](https://user-images.githubusercontent.com/31664493/30521509-1220f020-9b97-11e7-9b4e-6f5dc47925a6.png)

**Comment by ParticleCore** [comment]
I cannot replicate this problem in any way. Please provide better steps to reproduce other than "navigate for a while". Additionally share your Iridium settings (no need to include the blacklist).

Also make sure that this problem does not occur with Iridium disabled (not just the feature turned off, but the userscript disabled).

**Comment by davideassis** [comment]
There's no "better steps" because there's no specific way to replicate the problem since it just happens randomly when the option "memorize player size" is selected. But if I disable this option or disable the entire script the header style doesn't changes no matter how much time I spend navigating.

And what I noticed is that new YouTube have a CSS rule that changes the header based in certain conditions and for some reason is being enabled in wrong contexts with this option:

![img_001_17-09-2017](https://user-images.githubusercontent.com/31664493/30522559-7534d26a-9ba8-11e7-8ef2-72a405dc9baa.png)

And those are my current settings:

`{
    "broadcast_id": "bab7dad5-8573-4c3d-892b-9a41637ee53b",
    "userVolume": 100,
    "default_logo_page": "subscriptions",
    "default_channel_tab": "home",
    "square_avatars": true,
    "improved_logo": true,
    "thumbnail_preview": true,
    "thumbnail_preview_mute": false,
    "enable_blacklist": "home",
    "blacklist_settings": {},
    "channel_video_count": true,
    "channel_video_time": true,
    "player_quality": "highres",
    "player_auto_play": true,
    "channel_trailer_auto_play": false,
    "player_annotations": false,
    "player_subtitles": false,
    "player_loudness": false,
    "player_ads": false,
    "subscribed_channel_player_ads": false,
    "player_hfr": true,
    "player_memorize_size": true,
    "player_memorize_volume": false,
    "player_quick_controls": true,
    "player_max_res_thumbnail": true,
    "comments_visibility": 1,
    "shortcuts_always_active": true,
    "player_volume_wheel": false,
    "player_always_visible": false,
    "player_always_playing": false,
    "player_hide_end_screen": true,
    "iridium_dark_mode": false,
    "theaterMode": true
}`

**Comment by ParticleCore** [comment]
Thanks, I will keep testing using your settings to see if I can reproduce it, if not I will try to look for a different way to memorize the player size, otherwise I am unable to fix it.

**Comment by davideassis** [comment]
I don't know if it's related or if it helps, but I remember the "Structured Page Fragments" causing trouble with the "auto quality" and "player size" because everything was loading so fast so those options didn't work... so I always used the "Disable SPF" option in the old YouTube+ extension.

Maybe this is something to take a look on, enable in the new script and see if fixes the problem.

**Comment by ParticleCore** [comment]
I was finally able to reproduce it following these steps:

 - Play a video in theater mode
 - Search anything (top bar turns white)
 - Enter a channel from the search results (top bar turns black)

Thing is the top bar only stays black on the channel I visit. Once I go somewhere else it returns to being white and stays white.
However, I do believe I know what is happening, this feature that I developed "forces" the last mode (in this case, theater) everytime the pages load or transition. It was designed this way so that the user wouldn't see the transition when the video started playing, since it was already in theater mode. Now, because it is doing that on every page, there happens to be some pages where the top bar style also changes because it thinks it is in a video page and changes to the expected theater theme: black.

Now that I know what is causing this to happen, I will try to find a solution for it. Ideally it will have to be "implement the theater mode only when a video is playing", but still got to find a way around the transition.

Thanks for the help @davideassis

**Comment by davideassis** [comment]
Glad that I could help in some way. 😸

**Comment by ParticleCore** [comment]
Let me know if the fix in version 0.2.8b works, if you can.

**Comment by davideassis** [comment]
So, the header style is not changing anymore, but the option to remember the player size is not working anymore as well — I need to enlarge the player manually, but if I close the browser and open it again the player size is reseted. 😞

**Comment by ParticleCore** [comment]
Can you please follow the troubleshooting instructions? The player is resizing automatically for me even if I disable cookies. If the problem still persists open a new issue since it is different than this one.
