### ISSUE TITLE
Thumbnail sometimes doesn't display in Cinema Mode when autoplay turned off...

### ISSUE THREAD

**Issue by shonay** [ParticleCore/Iridium#174]
Hi there,
Just wondering if it would be possible to fix a small issue I am having.
I have my YouTube Videos set to NOT autoplay and to open up in the large video mode thereby allowing me to view the thumbnail before I click play.

I believe a recent change you made to the feature makes it so that the thumbnail on the videos displays the high resolution thumbnail image - but I see some videos for example all on YouTube channel "DramaAlert" do not seem to have optimized high res thumbnail images and hence the video just shows a greyed out thumbnail as though the video doesn't exist. However I am still able to play the video its just the high res thumbnail that doesn't display.

Not sure if you can fix it so that if it doesn't find a high res thumbnail that it just displays the standard thumbnail - but for quite a few videos lately the thumbnails don't show once you click on it to open up in large video.

STEPS to reproduce:
1. Make sure videos are set to open in "Cinema Mode" and "Autoplay" is turned off.
2. (Going to use DramaAlert's channel because thats the one I can reproduce it on) Click on any video on his channel.
3. You will now notice the thumbnail doesn't show up (default thumbnail placeholder is shown) once its in Cinema Mode.
4. Click the video (blank thumbnail) and the video plays as normal just no real thumbnail image.

Hope this makes sense.

**Comment by ParticleCore** [comment]
The feature description clearly explains this situation:

>When autoplay is disabled the video thubmnail will be set to the highest resolution possible. If this is not available it will display a generic grey YouTube icon.

https://github.com/ParticleCore/Iridium/wiki/Features#player_max_res_thumbnail

It could "pre-download" all image resolutions every single time for every video to check if it is available, but it would be resource intensive and it is not worth it.

**Comment by shonay** [comment]
OMG! I'm so sorry I didn't even notice that a new feature to Force High Quality Thumbnails was added and enabled by default! I just disabled it now. Sorry about that.

**Comment by ParticleCore** [comment]
No worry, in the end everything worked out!

**Comment by ParticleCore** [comment]
The new version comes with an attempt at solving this issue, defaulting to standard definition thumbnail if high quality is not found. If you wish to try it out again let me know if it works well for you.

**Comment by shonay** [comment]
Yes the feature is now working perfectly! It falls back to standard image when no high res image is found. Thanks so much!
