### ISSUE TITLE
Video Player doesn't resize correctly in the first access to YouTube

### ISSUE THREAD

**Issue by davideassis** [ParticleCore/Iridium#179]
**Browser Name:** Chrome
**Browser Version:** 61.0.3163.91
**Operational System:** Windows 10
**Software Type:** Userscript
**Software Version:** 0.2.9b
**Userscript Manager:** Tampermonkey
**Userscript Version:** 4.4

**Problem Description:** With the option "Memorize Player Size" the Video Player doesn't resize correctly in the first access to YouTube. If I access YouTube for the first time in the day or if I close the browser and open it again later, the Video Player is presented "small" (no matter the video) and I need to refresh the page to enlarge it. After that the enlarged state is memorized.

**Steps to Reproduce:** Open any video for the first time after closing and opening the browser and you'll notice the video is in the small state. Refresh the page (F5) and the player will be enlarged (full width) and stay that way until you close the browser again.

**Additional Details:** Seems like that's the default behaviour of YouTube without the plugin. The full width state is usually saved during the "session", but if you close the browser everything is reseted. It's like the "memorize size" option is not really working as it should, since it's only activate to resize the video once (after press F5) but not to actually memorize the state after that.

**My Settings**

`{
    "broadcast_id": "bab7dad5-8573-4c3d-892b-9a41637ee53b",
    "userVolume": 100,
    "default_logo_page": "subscriptions",
    "default_channel_tab": "home",
    "square_avatars": true,
    "improved_logo": true,
    "thumbnail_preview": true,
    "thumbnail_preview_mute": false,
    "enable_blacklist": "home",
    "blacklist_settings": {},
    "channel_video_count": true,
    "channel_video_time": true,
    "player_quality": "highres",
    "player_auto_play": true,
    "channel_trailer_auto_play": false,
    "player_annotations": false,
    "player_subtitles": false,
    "player_loudness": false,
    "player_ads": false,
    "subscribed_channel_player_ads": false,
    "player_hfr": true,
    "player_memorize_size": true,
    "player_memorize_volume": false,
    "player_quick_controls": true,
    "player_max_res_thumbnail": true,
    "comments_visibility": 1,
    "shortcuts_always_active": true,
    "player_volume_wheel": false,
    "player_always_visible": false,
    "player_always_playing": false,
    "player_hide_end_screen": true,
    "iridium_dark_mode": false,
    "theaterMode": true
}`

**Comment by ParticleCore** [comment]
I have been testing this since our last talk, but I can never reproduce the problem. It does start in normal size, but it quickly switches to theater mode as you can see in this recording (click it to see in bigger size if needed):

![ss](https://user-images.githubusercontent.com/9222661/30613829-fad213b6-9d78-11e7-8b49-7eff7c14b740.gif)

I used your settings, same browser version, userscript manager and followed your steps, I cannot reproduce your problem. I even tested on Windows 7 and 10, still nothing.

Questions:

 - Does this still happen if you disable every extension and userscript you have except Iridium?
 - During the first time, when it doesn't change size automatically, open the console. Is there anything? An error or something else?

**Comment by davideassis** [comment]
I just tested in some different contexts, with all extensions disabled but TM + Iridium only, but the player is not resizing correctly here.

Sometimes, if I refresh the home before accessing any video the auto-resize works 100% from the start. Same if I disable the "auto-play" option. Sometimes stay resized even if I close the browser. But most of the time is not working.

And here's the console content during the video loading when the resize doesn't works:

![img_001_19-09-2017](https://user-images.githubusercontent.com/31664493/30641502-b89445a4-9ddd-11e7-8005-e8b5348b2485.png)

**Comment by ParticleCore** [comment]
I am afraid that I still haven't managed to get it to happen with me. The console shows no errors belonging to the script, they are mostly Adblocker or similar extensions cutting tracking and ad services. I'd like you to try following the troubleshooting steps in this guide, including the test in a new Chrome profile: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by davideassis** [comment]
I just tested with a new profile, only TM + Iridium and I disabled everything in the script settings but the "resize" option... and worked fine, resizing all the time, even after I close the browser. Then I started to enable option per option and the only option that makes the player shrink is the "auto-play" option.

Same in my regular profile. Everything here is up to date and only the latest and stable versions.

**Comment by ParticleCore** [comment]
Very strange, because as you could see I also have auto play enabled, those are your settings in that recording, and still no issues. I will still take a look at it to see if I can figure out what might be going on. In the mean time, when you turn that option off then it works correctly all the time? Is this something that becomes consistent (doesn't resize, does resize) with that feature on or off?

**Comment by davideassis** [comment]
Yes, if I disable the "auto-play" so the "resizing" works fine and keep that way, no matter if I close the browser. In fact I can't even notice the resizing, because the videos opens already in full-width.

But if I enabled it again the problem will happen: **1)** player small at the first access; **2)** full-width only if I reload the same page or open another page; **3)** player small again if I close the browser and open it after some time.

So... I don't know if it's possible or if it makes sense, but maybe you can make the "resizing" happen before the "auto-play" or just make the "auto-play" wait for the "resizing" to start the video?

**Comment by ParticleCore** [comment]
I have no idea of what can be done because I am not having the problem to test any possible fix, I'll just have to read through the code and figure out what might be causing it or come up with a different way to implement this feature.

**Comment by davideassis** [comment]
I just noticed one weird thing here, right now: the problem only occurs if I access the videos through the Home or Subscriptions page, but if I open any video through the Google search results page or through any external source (including URLs), the player will resize correctly. The resizing also works when I don't finish the video, close it and open again so YT starts the video it in the middle to resume the playback.

Very weird, I don't know if it makes any difference but maybe is something to verify.

**Comment by ParticleCore** [comment]
So:
 - Open Home or Subscriptions page
 - Click on any video
 - Resize does not work correctly  

But:
 - Open search results or external links or restart video page before video finishes playing
 - Resize works correctly

Is this correct?

**Comment by davideassis** [comment]
Exactly, but... search Results from Google (the "Video" tab) but doesn't work from YT Search Results.

**Comment by ParticleCore** [comment]
Success! I am able to replicate the problem, now I can finally figure out what is going on and find a way to fix it. Thanks a ton for keeping up with the feedback.

**Comment by davideassis** [comment]
Awesome! Glad to help... as soon you release the next update, I test and report the results. 😃

**Comment by ParticleCore** [comment]
Latest version should fix this issue, let me know when you can.

**Comment by davideassis** [comment]
Awesome! So far is really fixed and working flawless! Thanks!
