### ISSUE TITLE
Custom player size possible?

### ISSUE THREAD

**Issue by paduser** [ParticleCore/Iridium#180]
Hey,
First a thanks for the development, it makes youtube so much more usable after the latest updates.

Before I switched here I used YouTube Center and they had the possibility to give the player a custom size. Like I did on the screenshot:

![player](https://user-images.githubusercontent.com/17303871/30613073-0db33218-9d87-11e7-84fe-e5564e32c4ac.png)

Is this possible with Iridium? If found "Memorize player size" in Settings but I don't know how to acctualy change the size?

Thanks for your help.

**Comment by ParticleCore** [comment]
That feature is not for that purpose, it only memorizes your last player mode: theater or normal. I might implement a custom size feature for the player, but it is not a priority now.

**Comment by paduser** [comment]
Okay, thanks
