### ISSUE TITLE
Injected code runs in sloppy mode

### ISSUE THREAD

**Issue by Orochimarufan** [ParticleCore/Iridium#183]
Since the injected code is no longer lexically inside the main script body function after being injected into the page, and it doesn't contain a use strict directive, it runs in sloppy mode. If this is intended, sorry for bothering you and feel free to ignore this issue.

To make the injected code compliant, (at least) two issues need to be attended to:

- Undeclared i at https://github.com/ParticleCore/Iridium/blob/2f2dd44df0e3d3792f583634af0cf152b85acda4/src/userscript/Iridium.user.js#L4335

- function.caller is prohibited in strict mode: https://github.com/ParticleCore/Iridium/blob/2f2dd44df0e3d3792f583634af0cf152b85acda4/src/userscript/Iridium.user.js#L2795
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Securing_JavaScript
While I'm not sure what that particular piece of code is trying to achieve, a different solution would have to be found since it's not possible to examine one's callers in strict mode.

use strict can then be added to the top of inject().

I'll end with a thank-you for all the work you put into YT+ and Iridium, I wouldn't want to miss some of their features these days. And having dealt with YouTube internals before myself, I know quite well how frustrating it can get when they change things around and break your stuff for the Xth time over. Keep up the good work!

**Comment by ParticleCore** [comment]
Thanks for bringing this up, I've fixed the missing variable declaration, will be part of the next update. Regarding the other one, I wish I could make it strict, but to achieve the seamless 0-buferring no autoplay we have today I have to read the function in which the variable is being used by in order to change some values. Without that, I cannot make the autoplay off work as well as it is now.

**Comment by Orochimarufan** [comment]
Yeah I figured as much, after having another look at that function. Well, maybe a different way to stop it from playing is going to turn up at some point. Until then, I'll just comment it out. Personally, I like videos auto-playing anyway (channel trailers are a different story tho). Thanks anyway

**Comment by ParticleCore** [comment]
No problem, just remember that userscript managers usually turn off auto-update when you edit the code, meaning that you won't get new versions automatically if that is something you want.

**Comment by Orochimarufan** [comment]
I'd hope so, wouldn't want to have my changes wiped out.
I'm already maintaining a fork anyway so it's no more work than it is now. Feel free to have a look and see if you find anything useful.

Also, if you have any pointers as to what makes youtube autoplay/not autoplay and where to look for it, I may look into a strict-mode compliant solution.
I have a rough idea what the current code is trying to do, but I'm not familiar enough with the player internals to know where to look

Fun fact on the side: Edge works just find despite the strict mode violation; apparently MS decided proper strict mode is too much trouble. I seriously hope this is an oversight and not indication that they're on their way to their own little world of non-standards a la IE again...
