### ISSUE TITLE
Unnecessary requests to github for icon and css

### ISSUE THREAD

**Issue by ganego** [ParticleCore/Iridium#184]
Why do you connect to github to get the icon for the script, instead of just base64 encoding the image and putting it in the script (base64 png works perfectly fine in the GM metadata)? 
Same for the css.
With the old YT+ I get "waiting for github.com" quite often, so it's wasting time.

**Comment by ParticleCore** [comment]
Base64 is not allowed on AMO, which I intend to host in the future, and the requests are controlled by the Userscript Manager (Greasemonkey or Tampermonkey), not by the userscript itself. This kind of question would be better off made to the userscript manager developer, not here.
