### ISSUE TITLE
Intent to add a coin miner for a trial run

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#189]
This ties a bit with #149 since I really dislike the idea to profit from telemetry, but I also need to find a way to make this hobby profitable.

I intend to add a coin miner together with the extension for a trial run to see if it is even worth it. Although I might change my mind about this later, initially this will be enabled by default because I assume that the current user base is too small to spare the "extra hand" in order to achieve a reliable projection of this trial. Nevertheless it would have an option to disable and control the number of threads it can use.

At the moment I have been studying the available options and so far it seems that coin hive is the best option overall.

The plan is to:

 - have only one instance of it running at any session (session = one or more browser windows that can communicate between tabs)
 - only the lowest "performance" by default (1 thread running)
 - pause/stop when a video starts playing

I also understand how this feels like a stupid idea, but I do not have any means to make any profit that is worth the time I am dedicating to this extension, and I need to understand if this will be worth while before investing it for the stable release, which I am planning to reach before October starts, although I might have to push that date a bit further, unfortunately.

I only ask that any upset users understand my position, I am trying to make this profitable without making this a pay-to-use extension, and I am not finding a lot of options. I have looked through ads (*I hate it and most likely wouldn't work*), selling telemetry (*I don't like the idea*) and now mining currency, which appears to be a good option.

This goes without saying; if donations do improve with the aging of the extension, this or any other method for profiting would be halted seeing that they would no longer be needed, however the past almost 3 years showed that this wasn't something that would be achieved any time soon.

I would really appreciate constructive feedback as well as alternatives to coin hive, if you know of better options, or another option to make this extension profitable.

---

EDIT 1: adding an index of my replies here as a follow up of this post

https://github.com/ParticleCore/Iridium/issues/189#issuecomment-331713912
https://github.com/ParticleCore/Iridium/issues/189#issuecomment-331723510
https://github.com/ParticleCore/Iridium/issues/189#issuecomment-331748125
https://github.com/ParticleCore/Iridium/issues/189#issuecomment-331893366
https://github.com/ParticleCore/Iridium/issues/189#issuecomment-331927662
https://github.com/ParticleCore/Iridium/issues/189#issuecomment-332127099
https://github.com/ParticleCore/Iridium/issues/189#issuecomment-332299057
https://github.com/ParticleCore/Iridium/issues/189#issuecomment-332988550

EDIT 2: adding updating feature design for easier insight

 - This feature will be opt-in
 - The users will be informed of its implementation and asked if they want to help out or not (still undecided whether to do this via a modal window or a dedicated window)
 - The summary of the feature will link to a more detailed explanation, including details about the inner works of the miner itself
 - The feature will only run when videos are not playing, but for the sake of curiosity there will be an option where users can enable to let it run while videos are playing
   - Alternative: keep it running on lowest possible setting when videos are playing (sessions on YouTube are heavy on video watching, meaning that the miner would be for the most part stopped)
 - The feature will allow control of how much mining the user allows: number of threads and throttle slider (less threads and higher throttle = less CPU usage and less mining)
 - Default feature values will be set for half the number of CPU threads at 0.75 throttle or 1 thread at 0.5 throttle (still learning this because I haven't fully grasped how it works)
 - This feature will never run on laptops that are not charging and on mobile devices (tablets, for example)
 - Only one mining instance can run at any time, meaning that if there are multiple tabs open, only one tab can be mining and the rest will be paused/stopped (ideally this should be controlled via active page is the one the miner can start/resume, all inactive pages pause/stop)

**Comment by mooms06** [comment]
You should not do that without warning your users with a window or something, otherwise it's a malware.
Do you plan to add it in the user script as well or only the extension ?

**Comment by demonkingzaine** [comment]
I'll probably stop using Iridium in the event mining software is added.

**Comment by Deranox** [comment]
What happened to developers making an addon purely out of the goodness of their hearts in their free time ? You know - because it would be useful for you and the people. A hobby doesn't necessarily mean you need to make a profit. If you're not happy with the time you spend on it because you're losing money by not getting a real job because of the time needed - don't do it. Someone else might do it in their free time. I'll never use your product now. Good day.

**Comment by Roph** [comment]
How to destroy your userbase and/or trigger a fork in one fell swoop.

**Comment by Timvde** [comment]
I understand that this may sound like a good idea. Computers usually have cycles to spare, you don't have to show annoying ads to your users, and you make a small profit out of it. However, just imagine for a second that coin miners become a *common* thing. A user would easily have a handful or even a dozen of coin mining threads running, which would quickly deteriorate overall performance and decimate battery life. Please, don't set this trend.

**Comment by alphachung** [comment]
What if the user (like me) are on a laptop, wouldn't this reduce the battery life dramatically? Watching YouTube is already power intensive for laptops, but when the video is not playing the battery is draining, you can see how this would impact users using laptops.

**Comment by p4pergoat** [comment]
I would support this decision if, and only if, it is guaranteed to be an opt-in feature in it's final release.

**Comment by krisu5** [comment]
No thank you, I move to Maia-yt (when it's ready) rather if this happens.

**Comment by BubiBalboa** [comment]
Rather than do this coin miner thing you should nag people for donations. Maybe a page that opens on every update. This has the benefit to show people how much work you put into this addon.

Maybe we should petition Mozilla to add the option for paid premium addons. Devs have a reasonable expectation to be compensated for their work and a donation button is not enough for that. Food for thought.

**Comment by Betsy25** [comment]
This isn't the first time you showed your users your try colors, step out of the game, time for other players.

**Comment by Morphello** [comment]
This is a sure fire way to destroy any good will you've had with your community and userbase and instantly destroy your credibility as a developer. I understand the desire to monetize your hard work but this is not the way to do it. A lot of the community have already moved away from your addon because you sold the chrome extension to a 3rd party and didn't inform anyone until after it was turned into malware.

At best you'll succeed in creating better competition to your addon, or at worst, someone will just steal your code and take the miner out of it, drawing away your entire user base.

Consider an update page after each major change with a donate link. Consider (strictly opt in) telemetry with an explanation of what is data is sent. Consider adding a support link that directs the user to a paid advertisment, as per free games with advertising allow you to do to support them.

**Comment by TheFinalCut83** [comment]
Sure way to lose the lion's share of the audience. At least it must be opt-in and off by default, but it's naive to believe that the author will agree to this.

**Comment by RibShark** [comment]
I would be fine with this if the following conditions were met:
1) The ability to opt-out of the coin miner is included.
2) As soon as the extension is loaded for the first time, a clear (possibly modal) message is displayed describing the functionality of the coin miner and how it helps you develop the extension.
3) A clear opt-out button is included in the afformentioned message.

FWIW I would not opt-out of such a thing.

**Comment by surashu** [comment]
@TheFinalCut83 what do you mean by "it's naive to believe that the author will agree to this"? This thread was opened by the script's author himself.

**Comment by ImSpecial** [comment]
This is one incredibly stupid move if you go through with it, I don't care if it's optional or opt-out, I don't want this add-on to become bloated with even more lines of miner code, even if it is inactive just sitting there. Hope this kind of stuff never finds a way onto AMO.

**Comment by eberhardweber** [comment]
I would consider this to be an "opt-in" feature instead of an "opt-out". 

I think at the very least you should consider advertising Patreon and Paypal on the Iridium Settings page before resorting to such measures. 

Not everyone comes to Github to follow up on updates/issues, so an announcement section on the settings page is probably a good idea as well.

**Comment by TheFinalCut83** [comment]
@surashu it was about "at least it must be opt-in and off by default", but something tells me that if the author wants to add a miner, it intends to enable by default.

**Comment by ParticleCore** [comment]
I am glad to see a lot more users input about this, I appreciate everyone cluing in and showing how they feel about having a feature like this in some way and having it at all.

This is a tricky situation, as I tried to explain, because I have already looked at other alternatives and expressed my position about them.

I am perfectly OK with having this feature opt-in only (which is how it should be), but the goal is to check the results of this trial run to see if this feature is even worth having, it might end up not being worth having at all, and having it enabled by default will yield more users participating than the other way around.

As I understand there are users that are against having this at all, meaning that even if the feature was added and made opt-in only, they are still against it, which makes this even more problematic to deal with, but others are OK with having it, as long as it is opt-in.

Adding a feature like this would obviously be clearly informed to the user in a modal window as soon as it was updated, or perhaps I should start considering an update info page dedicated to things like this, just like @BubiBalboa  and @Morphello suggested.

Let's see, how about this, to make things clear and better (the main concern) as best as I can:

 - This feature will be opt-in only, off by default
 - The user will be prompted with a request to enable it if he wants to contribute/participate in the trial run, linking to a more detailed explanation in the short description of the feature.
 - The rest of the details are the same as the ones in the first post

Regarding the concerns of battery brought up by @alphachung , this would only run on a computer with no battery (desktop PC) or only while the computer is charging (laptop). This will NOT run on a mobile platform, such as tablets, regardless of their battery status.

@mooms06 This would be available throughout all the versions, if it works at all, but not before the trial run results

@Timvde I see your point and would be a troublesome situation indeed, but this would always be an option that users can turn off/on whenever they want to, at least anything made by me it will be.

And the "better" allternative is to "nag" users for donations? I really hate that and I am sure that others will hate it too, but that's not even the core problem. The main problem here is to see if this option is actually viable, because it might not be worth having at all and be discarded, which is why it is important to test it and see how it pans out.

**Comment by Azraelle** [comment]
>add a coin miner together with the extension

This is where your addon gets marked as "RiskWare.BitCoinMiner" and your reputation goes down the drain forever.

**Comment by ParticleCore** [comment]
@Azraelle moot point. If it has ads it gets marked as "RiskWare.Adware", if it has donation requests it gets marked as "RiskWare.Nagware", etc.

Regardless, that is not the focus of this issue, but I do appreciate that concern.

**Comment by ybnrmalatall** [comment]
Are you fucking retarded? If you can't keep doing this completely free, give it up. 
I hope idiots will stop downloading this addon, regardless of an opt-in/out option. Nagware? Coinminer? Coin miner is 10x worse, you will be ruining the battery and making it impossible for people who aren't computer savvy in the least on old computers.
You are shameless. Do you not feel like scum even talking about this? If it's too much of a problem for it to not be profitable for you, then give it up and let the free market take over.

**Comment by ParticleCore** [comment]
@ybnrmalatall This issue was not opened to post insults. Further behavior like that will result in the respective users being blocked permanently.

No one here is forcing you to use anything and the feature hasn't been implemented at all. If you don't like that this is being discussed then you can stop using the userscript, leave this repository and use any other extension that does what you want.

**Comment by ybnrmalatall** [comment]
I've made it pretty clear that I don't care about being blocked as I am already done with your userscript on principle alone. I find you disgusting now. Good riddance.

**Comment by ParticleCore** [comment]
>I've made it pretty clear that I don't care about being blocked

You actually didn't, not even after you edited your reply to add more insults, but now you made it pretty clear. Stay well.

**Comment by surashu** [comment]
I don't get why there's a need to be slinging insults in an otherwise level-headed discussion thread.

**Comment by sheddup** [comment]
@ybnrmalatall 
> you will be ruining the battery and making it impossible for people who aren't computer savvy in the least on old computers.

Clearly not impossible if its an opt-in feature, you're just being reactionary. Don't let your emotions control you like that and think rationally.

**Comment by ParticleCore** [comment]
The main post has been updated with the feature design in order to make it easier for new comers to grasp the overall idea at glance.
This design can change over time according to the discussion.
I plan on going forward with the trial run after 1 week (starting on October 1st) with the duration of 1 month. This discussion will stay open until then.
The goal is to have a decent insight of the trial run before moving to release stage, which I want to be on November, but, again, this might change depending on the development of the extension.

**Comment by Morphello** [comment]
If you are determined to put this method of monetisation in your product, you must frame it strictly from a volunteer and "helping the developer" standpoint. "Default on" trials are not the way to do it. Even as a test, people will be quick to forget what is going on, notice their browser eating up CPU cycles and panic.

You must staunchly ask your userbase (in a popup update page) if they like they addon and if they are willing to donate their CPU time to you. Explain the situation, explain what they can do to help. A lot of people would be more than willing to donate idle CPU time if it can directly translate into making the addon better. A lot of people simply wouldn't. I personally would personally go to ad generating links, white list popups with ad displays and specifically click and follow through adlinks to maximize the revenue for the developer. I would also provide detailed bug reports with as much information as I can to help developers eliminate bugs. I would not personally donate CPU cycles because where I live, I pay 43c USD per kWh in power and it would cost me far more in power than an actual donation would.

People are more than willing to donate their time, effort and money to a good cause. Look at all the CPU power that gets donated to Folding@Home. You just need more awareness and to come at the problem from a humble position. Also keep in mind that you aren't trying to cure cancer or other diseases, you've written an addon to provide extra functionality to an existing platform. Every bit of functionality you have can be found in other addons, you're just one of the better options at the moment.

**Comment by ParticleCore** [comment]
@Morphello I had already posted an updated design of the feature in the main post at the top covering basically all that you've said, but with bulletpoints, and I understand that there are users which CPU time is not something cheap. The message itself is not a priority right now seeing that this is suppose to be a trial run, the only thing it will inform is just that and an explanation for why the trial is taking place. If it works out, then a proper message will be created for the purpose of final integration.

Ads are not a viable option for 3 main reasons, basically: 1) I hate ads and I do not trust them at all 2) I am certain the Chrome Webstore would never allow it 3) I am almost certain AMO wouldn't either

I approached this idea from my POV as a user and I would rather have an option to donate CPU time in exchange for ads on websites, paywalls or subscription services. When comparing it to the donations I concluded that it would be worth giving it a try.

I am fully aware that I am not doing clinical research here and I know very well what this extension is, I have been saying it since I created YT+, it is not a replacement for anything, it is just another option for anyone that wants what it offers.

But again, this is not final integration, it is just a trial run. It might even show that it is not worth it, which is what I am expecting after having read plenty of testimonies from others that tried the same, in which case it is removed from the extension.

**Comment by p671366** [comment]
unacceptable, you just killed your userbase and the only people who will still use this are brainless loyalists or people who are simply unaware that you are planning to place malicious crap into their browsers. Good riddance to your greed, I'm moving onto enhancer for youtube at least they claim that they respect user privacy unlike you. Embarrassing to be honest...

**Comment by ParticleCore** [comment]
>at least they claim that they respect user privacy unlike you

> I use Google Analytics to analyse traffic on my website, and also use third party advertisements. Some of these advertisers may use technologies such as cookies and web beacons when they advertise on my website, which will also send these advertisers (such as Google through the Google AdSense program) non-personally identifiable information including your IP address, your ISP, the browser you used to visit my website, and in some cases, whether you have Flash® installed or not.

>I also may use DART cookies for ad serving through Google’s DoubleClick, which places a cookie on your browser when you are browsing the web and visit a website using DoubleClick advertising (including some Google AdSense advertisements).

https://www.mrfdev.com/privacy

I have 0 telemetry in the extension or anywhere, for that matter. There's no privacy concerns to begin with, but if their word is far more valuable to you than not having any privacy concerns at all then good for you, and if their software is better for you then good for you too. The objective is for us to have the better experience on YouTube, be it with this extension or another, it is your choice to make every single time.

However, I will not allow any further lies claiming that I intend to place malicious "crap" to the users of this extension when I have been crystal clear about this even before it has been integrated and explained exactly everything that I intend to do.

**Comment by Tsutsukakushi** [comment]
It's not a hobby if your goal is to make profit.

**Comment by adiov** [comment]
@ParticleCore Just here to voice my support for you.

At the end of the day, everybody has to make a living. Yes, of course, it's a very beautiful thing when somebody dedicates their time and energy for the community for free, but not everybody is able to do that all the time. If we wanna embrace hippieness, why not start by being compassionate and understanding towards the creators and maintainers of the tools we like? They have their own obligations, life, hopes, and dreams outside this one project.

It's a shame that the discussion has morphed into arguing whether or not you should make money at all. I find it much more productive to discuss whether _this_ particular method you're choosing is the most optimal.

On that note, I'd rather you take a small portion of my processing power for the duration of using your tool than you selling my browsing/watching history or eye-blasting me with annoying ads. If done in a smart and considerate way (minimal impact on my usage of the machine), then by all means go for it. Inform me, give me an option to disable it, and don't make my machine slow.

**Comment by ParticleCore** [comment]
@Tsutsukakushi hobby and profit is not mutually exclusive, both can co-exist. The line only ends when the hobby changes into a business. This feature would just enable users to contribute in a different way other than with money, but if semantics is what is bothering you then interpret in any way you want, just not here because this issue is not for that subject. Let's keep the discussion focused on the main objective.

@adiov I really appreciate those words. The goal is to not disrupt the user experience on the website, which is why the feature will have included options to tweak the miner in case the default settings are having a negative impact.

**Comment by abba23** [comment]
On https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews#Policies under `User Experience` it says:

> We expect all add-ons to work **without significantly degrading users' experience** with the browser. In particular, add-ons may **not adversely affect browser performance**, break built-in features, or damage the user interface. For add-ons listed on AMO, we likewise expect a consistent generally positive user experience for any functionality provided by the add-on.

Would such a change even be compatible with this policy?

**Comment by ParticleCore** [comment]
@abba23 The change is not even integrated yet, the trial run is to take place before developing the Firefox Addon version, meaning that it will only be available in userscript. As for the browser performance, I have already detailed that the users will have the ability to tweak how much the miner can work and, in case the lowest settings are still too much (some computers might be too weak to handle it in any way) the users can always disable it.

It won't be enabled by default, so this will be a user conscious choice which does not violate the AMO policies. Were it to be enabled by default then that would be against policy, but even before coming to that this needs to be tested to see if it is even worth keeping it, otherwise it will be removed.

**Comment by abba23** [comment]
>The change is not even integrated yet, the trial run is to take place before developing the Firefox Addon version, meaning that it will only be available in userscript.

Yes, I'm only referring to the AMO extension here. My point was just that I'm not sure you will be able to publish the addon version on AMO like that.

>so this will be a user conscious choice which does not violate the AMO policies

Do they say so somewhere? In their policy they certainly don't specify any exception for specific user configurations. Just because it doesn't do so by default it still CAN adversely affect browser performance while the policy states that '[it] may not adversely affect browser performance'.

Regardless of my personal opinion on this topic, if I understand these policies correctly your addon shouldn't pass the AMO review if you add the option to mine coins for you.

**Comment by ParticleCore** [comment]
@abba23 It has become clear that your interest in this discussion is not honest, in which case I ask you to stop insisting on discussing the AMO policies when they aren't even a concern at this time, as I already explained in my previous reply. The policies will be enforced by the AMO team -not you- when the time comes, regardless of this feature staying or not. You explain that you are only referring to the AMO extension, but there is none yet and this issue was not opened to discuss about the AMO extension.

Please return to the focus of this issue, or cease this if you are not interested. There are plenty of users receiving email updates of this thread each time you post a new reply, which can become very annoying if the updates are unrelated to the issue at hand.

**Comment by Tsutsukakushi** [comment]
> The line only ends when the hobby changes into a business.

If you wouldn't continue it because it's not profitable it's a business, not a hobby.

**Comment by ParticleCore** [comment]
@Tsutsukakushi I have already been clear about that subject and I have been working on the previous project for close to 3 years with essentially 0 profit; I am still here. I would appreciate if you were to return to the actual discussion of this issue, if you actually want to continue participating, and stop arguing about what you believe to be or not to be a hobby according to your own standards. There are other proper places where you can discuss your "ifs" and assumptions, this is not one of them.

And to stop current and other users from wasting more time of people actually interested in discussing the main subject, any further derailing will be interpreted as a user that is only interested in disrupting the discussion, and that user will be blocked permanently.

If there are users that want to circlejerk then go to Reddit.

**Comment by brodycas3** [comment]
I would gladly opt into this but seeing how other people react without even thinking is upsetting.

**Comment by ORBAT** [comment]
> I would gladly opt into this but seeing how other people react without even thinking is upsetting. I believe that you could have a paid and free version, The paid version being a way to donate a one-time fee, no extra features and be thanked in some sort of credits.

The problem with schemes like the one you described is that very few people are actually willing to pay for software they use; voluntary donations very rarely amount to anything even close to e.g. ad revenues. Donating CPU cycles instead of money seems like a fair tradeoff (and much more likely to happen than donations), and a better choice than ads which can get fairly intrusive.

**Comment by ParticleCore** [comment]
@ORBAT very likely managed to explain in the best way possible why I am even considering implementing this option in the first place, thank you.

**Comment by surashu** [comment]
I'm mostly concerned about the precedent this will set. Sure one or two developers doing it will be manageable but what happens when everyone and their grandmas who are working on a userscript or add-on want a piece of that cryptocoin pie too?

**Comment by ParticleCore** [comment]
@surashu that is not the focus of this issue, but it is indeed a concern and has already happened, people are abusing it for some time and coin miners are already earning their place in ad-blocking lists. There is nothing stopping them from unaware visitors, but I chose one that allows great control to the user as well as the ability to easily define rules based on already running instances in other tabs: 

>The optional mode parameter specifies how the miner should behave if a miner in another tab is already running.

https://coin-hive.com/documentation/miner#miner-start

If this is the moment it becomes a precedent in this context then I hope that it sets a good precedent, including the option for it to be disabled whenever the user wants and vouch for not having a negative impact on the overall user experience.

**Comment by IMNdi** [comment]
Just 2 cents:

a) If you ask, I'll say no. I have had folding@home for a while trying to help a noble cause and it killed my hardware. The CPU was fine, but the GPU wasn't meant to be used this long on a consumer card. Ever since, I am wary of people saying "it's spare cycles". It's power, heat, stress and a chance to fail plus the definite lifespan hit. 

b) If you add mining, I'm going to assume it was worth it and any goodwill that you may have had towards Patreon will be gone. I'm not saying I'm right, I'm saying it's what a lot of people will think. I'm never going to donate to someone that has ads, I'm never going to support a YouTuber that shills for merch, etc, etc. No double dipping.

c) If you want to just monetize this, then there are options. If you want to monetize AND maintain the goodwill of the people using the (in my case) script, then you have hit a barrier. An addon is something people don't like to keep paying on. I don't need a contract for every single thing I do, especially addons and mods, since many people have dozens of them. Any transaction that people would be willing to send your way monthly would be trivial and get buried by taxes and fees.

Which is why I think that (even though the mining was a good idea on principle) you are kinda sorta out of luck on this one with microtransactions.

You could (and feel free to laugh at these ideas)

a) Sell it. Leave the core features free (autoplay, etc) and only give the lots-of-work features for cash. A one time sale of $1.99 buys you the premium addon with guaranteed updates for at least 2 years. I'd pay a decent two bucks as support to you IF I'm getting something back. As a free, I do what I want when I want project you ain't getting cash. And I feel like users could give you 1 or 2 bucks if it's a one time payment. We don't need to bring Patreon into this.

Besides, if not enough people pay, you could simply not support the more heavily maintained features. After a while. How people are going to take not having all the features is another issue. Feathers will be ruffled either way.

b) Bundle up. Talk to one or a few other people that do a good addon, make sure they are compatible, and do a bundle development. If your Iridium partners up with Youtube Black (not a real addon) and Youtube Better Comments (not a real addon) then you can develop faster as the work is spread and then you could put this suite up for a dollar a month on Patreon, with the profits divvied up. You could get more people to contribute.

Now, I don't know how much you want to make from this, these ideas may be a shot in the dark. For example, I don't think any of these are going to make you around 1000 USD a month, in any shape or form. You may be down to mining, assuming you have the userbase and assuming the people who would kill a person that allowed "acceptable ads" are OK with mining.

If your aim is "a nice cup of coffee in the morning" then I think your best bet would be the bundle.

I am, personally, against nagware. I hate addons that open tabs so much that I would, if I could, flip a switch that kills the ability of an addon to open links. When update time comes, my browser explodes in 10-15 new tabs. It is one of the reasons I left Firefox (Pale Moon now). I guard against adware to have my adware delivered. It's so upsetting to me that I have blocked the domains of the people doing that; at least they stop calling home.

I don't think a dollar a month is reasonable for an addon. If everyone did that, I'd owe 100 bucks a month to Patreon and that's unacceptable by an order of magnitude. I'd never pay for mods. I would be OK with paying a sum to NexusMods and let them do whatever they feel like it. I run 219 mods on FO4. I am not paying 219 dollars for them.

Yes, I am aware this is a needlessly long post. My tub is filling up.

**Comment by ParticleCore** [comment]
@IMNdi 
a ) It uses CPU only, no GPU, but this does not eliminate the same concerns, however those are only valid if the mining tool is run on "fast speeds", this is not meant to run that way, otherwise it would have a negative impact on browser experience.

b ) It is optional, off by default. It is another way that users can contribute if they don't have or want to give money away. It is also going to be a trial run to see if it is actually worth it.

c.a ) It is not a compatible model if I intend to publish on AMO, which I do.

c.b ) That would be interesting, really, but the little free time I have would not let this reach anything anytime soon.

>I am, personally, against nagware.

I know the feeling, which is why I tried my best to not do it over the almost 3 years I have been behind the projects. I honestly would be perfectly fine if people chipped in $0.1 every month, but the available channels eat it up with commissions and whatnot, and not everyone has or wants to, which is why we are at this point.

Regardless, thanks for the dedication on your reply, it does give something to think about.

**Comment by jackblk** [comment]
Please no. I'm using extensions and scripts to avoid having ads and annoying stuffs like that. Adding a coin miner will just destroy the whole reason.

I know you're doing hard work, and you need profit from it.

I suggest 2 ways:
1. Pay to use. I think if you should just make it an extension, making us to purchase to use. Tampermonkey script will die if you do so.
2. Limited features. Pay to get. I think this gonna be great.

Either way, I probably gonna pay. But please think about pricing. Under 10$ and promising to update is a win-win for all of us.

**Comment by jackblk** [comment]
@ParticleCore Thanks for the reply. Sorry for not reading them all, I just read few of them, so bear with me :P.

After reading more, I think I'm supportive for your choice, but there will be people not understanding. I hope you a nice day :D.

**Comment by IMNdi** [comment]
Passing thought.

I think Patreon allows for a per-delivery payment, so one can pay $1 or $2 every X months and group it. For example, you could set up a per-delivery payment of $1 and deliver yearly or something.

Patreon takes 5%, so with transaction fees it's like 70-80 cents to a dollar.

It's up to you to decide if you want to go insta-cash or pledge and then get yearly infusion based on accumulated good will. Depends on the frequency of updates and the amount of bugfixes, I guess. Happier customers are more likely to pledge and leave it on (delayed payment) IMO whereas instant-pay protects against people changing their minds.

**Comment by ParticleCore** [comment]
@IMNdi Thanks for the suggestion, but the problem with that is that almost no one has Patreon or are willing to or have the possibility to send money. This option would allow those users that want to contribute, but can't.

**Comment by nick-s-b** [comment]
Coin miner? That's malware. Time to fork this script.

**Comment by brodycas3** [comment]
@nick-s-b 

![tylanax](https://user-images.githubusercontent.com/19770864/31038255-a683c08e-a543-11e7-8f6b-37dd59da2807.png)

 
Pretty sure that you're wrong. Anyways it is going to be opt-in.

**Comment by ParticleCore** [comment]
@nick-s-b 

Malware:

>Malware is an abbreviated term meaning “malicious software.”  This is software that is specifically designed to gain access or damage a computer without the knowledge of the owner. There are various types of malware including spyware, keyloggers, true viruses, worms, or any type of malicious code that infiltrates a computer.

https://us.norton.com/internetsecurity-malware.html

If any other users want to keep trying to drive this discussion to the malware path, you showed that you are not only not interested in this discussion at all, but you are trying to spread fear-mongering through lies, and like I said before, I will not allow that any longer.

>Coin miner? That's malware. Time to fork this script.

Good bye and say hello to all the other forks that have already been made before and after this issue was opened: https://github.com/ParticleCore/Iridium/network/members

**Comment by ParticleCore** [comment]
This feature has been implemented in version 0.3.1b

For feedback related to this feature please use this thread from now on: https://github.com/ParticleCore/Iridium/issues/198

**Comment by ParticleCore** [comment]
Locked by mistake, apologies.

**Comment by VinLark** [comment]
This is just a though from an outsider. I don't really imagine a person with a Pentium 4 or a pretty old AMD chip to be using this extension, and even if, this is an opt-in feature. Personally, I would be fine if this is the future of supporting devs like yourself. I am also happy about a developer being so transparent about this type of thing. It's crazy people still get mad over it. Ads are old news, and donations are not guaranteed. Good luck in the future.

**Comment by ParticleCore** [comment]
@VinLark You are right, that's why I even warn users that if they still feel the performance lacking with the lowest settings they should turn it off. This wasn't added to make their experience worse, the opposite of that supersedes the trial/feature itself.

>ATTENTION Do not turn this on if:
>
 >  - You are on a mobile device (i.e. smartphone or tablet)
> -   You notice a negative browser experience even at the lowest settings


https://github.com/ParticleCore/Iridium/wiki/Features#miner

Thanks for the kind words, I appreciate them.

**Comment by HyphenSam** [comment]
I have a beefy computer so I don't mind using my PC to help out.
Right now I have it set up so it uses 10% mining speed over 12 threads, and I'm only experiencing 25-30% of CPU usage. So far I haven't run into any issues.

**Comment by ParticleCore** [comment]
@HyphenSam glad to hear that, but for that specific feedback I've already opened a dedicated issue just for that here https://github.com/ParticleCore/Iridium/issues/198

**Comment by HyphenSam** [comment]
Ah sorry, I thought that issue was only specifically for people who are experiencing problems, and not general thoughts like my comment. I'll be sure to post there in the future.

**Comment by dfgdfg12** [comment]
Pirate Bay tried this shit and got burned. What a disgrace.

Delted this addon/script and will not reinstall it.

**Comment by Tharn** [comment]
I don't think a coin miner has any place in a browser extension. I want my browser to be fast and efficient, coin mining is anathema to that idea. It wastes CPU and battery, increases temperatures and may produce slowdown. IMO if people want to help, they can donate. You may give them several effortless options for donations to reach the biggest possible audience.

Mining, telemetry etc. are both ways to monetize a thing beyond what I'd consider a reasonable median, and a browser extension is not a stand-alone program worth a lot of money but a cog in the machine that's first and foremost supposed to work efficiently and without a fuss. Imagine if the flash plugin, built-in pdf reader or popular browser themes all started running their own schemes to siphon CPU cycles. Horrible!

I sympathize with your desire to make money off the work you put into the extension, but I would strongly recommend to rip the mining/telemetry part of the code out as soon as the trial run is over and return to traditional methods of monetization.

On the positive side: Your extension is one of the best, if not the best YouTube settings extension out there. If I'd want any extension to be financially feasible, it would be this one. You may consider a 'splash screen' on first startup that asks the user to donate. I would consider that benign.

**Comment by ParticleCore** [comment]
@Tharn it is optional and turned off by default, if the user does not want to use it he is not forced to, there are no features blocked until mining is enabled. The extension is exactly the same with the exception of the "welcome" screen and the existence of such option.
Also the *idea* of telemetry is on hold, at least for the duration of this trial run. I don't want to rush on that one, it is not something I am very inclined to integrate.

**Comment by Tsutsukakushi** [comment]
@ParticleCore, you might want to edit the issue to reflect that. Currently it says:

>initially this will be enabled by default

**Comment by ParticleCore** [comment]
@Tsutsukakushi Please read the full issue, especially the second edit notes, not just the first paragraph:

> - This feature will be opt-in

**Comment by Hegezcc** [comment]
@Deranox I understand that. But I am 90% sure that nobody will start making a project so big and great like this. In the history of open source mods for proprietary code there are lots of stories about someone making things in their free time, but then stopping at the top for lack of motivation. Money is a great motivator, but who will pay $25/hr for improving this add-on continuously? Nobody is the one for that, but maybe thousands of fans would pay a few bucks for month via service like Patreon. That would make a pay of a reasonable full-time job. And the best people in IT have always started it as a hobby.

Who would be the best person to be that coder? I think that the original dev has proved their skill and knowledge here.

**Comment by jcdenton2k** [comment]
Or I'll just fork Iridium, change the name, and work alongside some other devs I know to improve/maintain it.  Your license is pretty crap (you could easily just use a Creative Commons or GPL-compatible license) and doesn't protect you or your users from abuse by others.

If you are unable/unwilling to maintain the codebase then it may be useful to just open-source it and permit GPL-based rights such as reuse, modification, etc.

**Comment by ParticleCore** [comment]
> 
> 
> Or I'll just fork Iridium, change the name, and work alongside some other devs I know to improve/maintain it. Your license is pretty crap (you could easily just use a Creative Commons or GPL-compatible license) and doesn't protect you or your users from abuse by others.
> 
> If you are unable/unwilling to maintain the codebase then it may be useful to just open-source it and permit GPL-based rights such as reuse, modification, etc.
> 
> I've poked through the code and I'm thinking I could probably write up something better. If I'm motivated by money to be compensated for my time then I'll throw up a Patreon and have at it. If not, then I'll do a one-time crowdfunding and then only start up Patreon to handle maintenance after the first year.

I wish you good luck.
