### ISSUE TITLE
Default channel tab 

### ISSUE THREAD

**Issue by Jyrka98** [ParticleCore/Iridium#19]
YT+ had an option to switch to another tab when visiting a channel, I hope it gets added back. :)

**Comment by ParticleCore** [comment]
It will be implemented.

**Comment by Jyrka98** [comment]
Hey, thanks for adding this feature back. I tried it and it seems to work with some channels but not others.

**Comment by ParticleCore** [comment]
@Jyrka98 In that case please open a new issue and remember to follow the guidelines.

**Comment by ParticleCore** [comment]
@Jyrka98 Actually I think I was able to replicate it in the comments section. Press Ctrl + Shift + R and see if the problem still persists, if it does then please open a new issue.

**Comment by Jyrka98** [comment]
@ParticleCore It seems to work now. I just finished writing everything for the new issue as i noticed your comment, heh. Thanks for the quick fix!

**Comment by ParticleCore** [comment]
@Jyrka98 Glad to hear that. If you happen to find any other case in which this happens again let me know in a new issue.
