### ISSUE TITLE
Coin miner feedback here

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#198]
This issue has been opened just for the users that want to give feedback regarding the coin miner trial run implemented in version 0.3.1b of the extension.

I am not demanding any feedback, this is just so that anything related to this subject stays organized here. Each user that wishes to give his feedback about this feature feel free to do so.

There is zero tolerance for any users that want to be just disruptive. Stay in the subject otherwise the user will be permanently blocked.

This is not for users to give their opinion on how they feel about the feature and similar subjects, but about problems or positive aspects that users are having with the use of the feature itself.

For other topics please use the previous discussion instead: https://github.com/ParticleCore/Iridium/issues/189

**Comment by Tharn** [comment]
Not knocking you for doing it, but I'm against these kinds of things on principle. As a user, I want a browser (and a set of extensions) built for speed and efficiency. Coin mining is an activity that flat-out takes CPU for its operation. So people would be paying in CPU time (heat, noise, battery, reduced performance) instead of monetary donations.

It's good that it is optional, but I can't foresee this option to be very well received. Monetizing extensions is tricky at best and damaging to image & popularity at worst. I would let the miner run its trial if it has to, then remove it as soon as possible.

**Comment by ParticleCore** [comment]
@Tharn Please don't use this issue for that subject, the previous one already discussed that extensively, this one is just for the users that are using the feature.

**Comment by ParticleCore** [comment]
@Tharn There is no problem, you can post that in the other issue if you want to.

**Comment by amulecregg** [comment]
I think it's awesome you added an opt-in for coinhive! We all benefit, indirectly—and you too, directly.

About mobile devices and battery, please check this reddit [post](https://www.reddit.com/r/Monero/comments/71okng/some_advice_for_all_you_guys_using_coinhive/).

FYI, I had to go back to an old Iridium version because 0.3.1b doesn't play the videos, they always stay at 0:00. Maybe it's just me, I don't know.

**Comment by EverEve** [comment]
Sorry, I personally didn't like the feature. Many people don't know what is that for, and could end up blaming you for installing malware on their PC.
I understand that you need support as a developer, but I prefer contributing using PayPal. 

Thanks for your attention and keep up the good work.

**Comment by ParticleCore** [comment]
@EverEve Please use the other issue for that kind of discussion, specifically read https://github.com/ParticleCore/Iridium/issues/189#issuecomment-333253492 for that topic.

This issue is for feedback from users that are using the new feature, not for users to express how they feel about the tool.

**Comment by ParticleCore** [comment]
@amulecregg Please use the other issue for this kind of discussion. Regarding the thread you linked, I already explained in the announcement about the problem with that method:

>This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getBattery

**Comment by ParticleCore** [comment]
It has become clear that users do not understand why this issue was opened for. 

This issue was opened for users that are actually using the feature and want to provide some feedback like how it is not turning off, or if it is working well, etc.

This issue was not opened for users to tell how they feel about the idea or anything else not included in the above topic.

**Comment by dfgdfg12** [comment]
Pirate Bay tried this shit and got burned. What a disgrace.

Delted this addon/script and will not reinstall it.

**Comment by brodycas3** [comment]
I just wanted to say I am using it on max settings with no problems or slowdown.

**Comment by ParticleCore** [comment]
@brodycas3 I am really glad to hear that! During my tests I noticed that having threads at max was not a problem until the speed was equal or higher than 70%. To play it safe I set the allowed max speed at 50% which should be low enough for most cases.

It still won't be sufficient for very slow CPUs, but in those cases it is better for users to not enable that feature since their browsing experience is a priority over this feature.

**Comment by SamTheGr8est** [comment]
Ever since the update, I have experienced noticeable slow downs at the beginning of videos, even with the miner off. Any chance of looking into this? Happy to use it, but those who don't might have slow downs with it off (for some reason).

**Comment by ParticleCore** [comment]
@SamTheGr8est The miner was designed to not even try to do anything, including loading the necessary code, so this shouldn't be the cause. Nevertheless I want to investigate this, can you open a new issue after following the troubleshooting instructions please? https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by SamTheGr8est** [comment]
Ignore what I said, managed to fix it. 

For those who care: it was Discord being stupid and eating my resources.

**Comment by ParticleCore** [comment]
@Really happy to hear that, you got me worried for a while.

**Comment by ng4ever** [comment]
Hope this is the right spot but if I donate will I not have to use Coin miner or will there be a version without if I pay? Sorry a little confused.

**Comment by ParticleCore** [comment]
@ng4ever You never have to donate or enable this feature trial run in order to use this extension, it is completely free, the donations and this feature are completely optional.

**Comment by ng4ever** [comment]
Ok thank you for the quick reply!

**Comment by theorist-complex** [comment]
I, personally, absolutely hate these coin mining scripts on websites. Was very unhappy when TPB decided to use a coin miner on its pages. BUT, as one of your patreons, I have absolutely no problem with you going down this road so long as it stays opt in/out. More power to you. 👍  In fact, if folks don't have a problem with donating cpu cycles, then I think that's fantastic and very well could be a great way to monetize your work - though in my case, I value my cycles immensely and would rather give you a few dollars on Patreon. :)

**Comment by erkinalp** [comment]
Mining needs to be explained well, otherwise it may be considered illegal levying.

**Comment by erkinalp** [comment]
`MINER TERMS OF SERVICE
If you click ... this software will operate a voluntary proof-of-work scheme in order to help the developer. Do not start proof of work if you live in a jurisdiction that bans cryptocurrencies or considers this activity illegal levy.`

**Comment by ParticleCore** [comment]
@erkinalp an optional, not imposed user choice, off by default feature cannot be considered a levy.

As for the terms of service, that sounds like a good suggestion and one that I might implement after the trial has ended and the feature stays.

**Comment by erkinalp** [comment]
> an optional, not imposed user choice, off by default feature cannot be considered a levy.

I will not. But there are some jurisdictions with laws saying "all tax matters are regulated by law" (Turkey, where I live, is one of them) and someone else mining coins on others' computer may be considered levying by tax authorities in there.

**Comment by ParticleCore** [comment]
I see, there are certainly countries with strict laws which vary drastically from country to country. I will have to check on that with caution to make sure this feature is, like you said, explicitly clear to the user in a way that it is able to abide to the law or at least inform him that it might infringe law(s) in his country, if such is the case.

**Comment by silentbrains** [comment]
Not sure where else to mention this, but in my case Windows Defender seems to now be picking up on the Coinhive miner and removing it from Firefox's cache directory.

**Comment by ParticleCore** [comment]
@silentbrains Same thing happened with me, the situation has already been forwarded to the CoinHive team earlier today. Thanks for letting me know.
