### ISSUE TITLE
Comment section: Always load option

### ISSUE THREAD

**Issue by p0358** [ParticleCore/Iridium#199]
This could be useful, as YouTube sometimes takes time to load these, sometimes they don't load at all, and they could be already ready when we want to read them.
Also, I don't think hide should be the default option, why is it? I mean, everybody does read comments under most videos, so clicking button each time is probably pointless.

**Comment by ParticleCore** [comment]
> Also, I don't think hide should be the default option, why is it? I mean, everybody does read comments under most videos, so clicking button each time is probably pointless.

You are assuming based on your opinion, you cannot infer that to "everybody" from your point of view. I chose to leave the default in between: not removing and not showing by default, but allow users to choose. They can also change the setting if they want to.

**Comment by p0358** [comment]
@ParticleCore Not referring to "everybody" only from my point of view. I mean literally every person I've met is reading those comments, that's what I based this on.
I appreciate the option to change those, but I just think that options like squaring user images, disabled autoplay or visibility of comments should be kept to YouTube's native to not distract new users, and they could tweak them as they like in case.
