### ISSUE TITLE
thumbnail video preview not working 0.3.1b

### ISSUE THREAD

**Issue by Daisenki** [ParticleCore/Iridium#203]
Browser Name: Firefox
  Browser Version: 56 (64-bit)
  Operating System: W10 Home 15063.632
  Software Type: Iridium
  Software Version: 0.3.1b
  Userscript Manager: Tampermonkey
  Userscript Version: 4.5.5564beta (newest)
  Problem Description: thumbnail video preview not working

<img width="91" alt="unbenanddnt" src="https://user-images.githubusercontent.com/22057956/31079392-c33b15ee-a785-11e7-8170-4d541a6f2503.PNG">

**Comment by Tigoreetur** [comment]
Same
