### ISSUE TITLE
Can't blacklist channel by clicking on channel thumb

### ISSUE THREAD

**Issue by AL3x3y0** [ParticleCore/Iridium#204]
![image](https://user-images.githubusercontent.com/29476322/31084871-a819656a-a7a6-11e7-9cb7-0987e4583339.png)

Why there is "block" button, if I can't blacklist it? I only can blacklist channels by clicking on that button on their videos, not on channel thumbs.

Here is error in console after I click it:
![image](https://user-images.githubusercontent.com/29476322/31084829-8bf69f38-a7a6-11e7-95c8-4492016f199c.png)
`VM53:1135 Uncaught TypeError: Cannot read property '0' of undefined`
`at Object.addToBlacklist (<anonymous>:1135:65)`
`addToBlacklist @ VM53:1135`

Google Chrome 61.0.3163.100
Iridium 0.3.1b

**Comment by ParticleCore** [comment]
Can you tell me in which page that channel is showing?

**Comment by AL3x3y0** [comment]
https://www.youtube.com/feed/channels

https://www.youtube.com/results?search_query=diablo+channel

**Comment by ParticleCore** [comment]
Thanks, it is happening to me as well, will try to fix it as soon as I can.
