### ISSUE TITLE
Not loading video while on fullscreen

### ISSUE THREAD

**Issue by fedex-bermu** [ParticleCore/Iridium#206]
When you watch a video, at the end appears the sugested videos, while on fullscreen if you click on one video you will get an error YTP_ERROR_GENERIC_WITHOUT_LINK, the same can be replicated on the playlists, if you are on fullscreen, when a video ends and tries to play the next one it has the same error.

"debug_error": {
    "errorCode": "manifest.net.retryexhausted",
    "errorDetail": "successButUnplayable.1",
    "message": "Se ha producido un error. Vuelve a intentarlo más tarde.",
    "messageKey": "YTP_ERROR_GENERIC_WITHOUT_LINK"

Already tried disabling all the other extensions, and also with a new profile.

**Comment by RaitaroH** [comment]
This appears to be exactly the same problem as the one I wanted to file an issue for:
![screenshot from 2017-10-05 08 03 42](https://user-images.githubusercontent.com/19552720/31211740-3a6c6e36-a9a4-11e7-9bb0-6801f10e0375.png)

**Comment by ParticleCore** [comment]
Happening with me as well, will try to fix it asap.

**Comment by ParticleCore** [comment]
This should be fixed in version 0.3.4b
