### ISSUE TITLE
0.3.4.b is not working

### ISSUE THREAD

**Issue by mooms06** [ParticleCore/Iridium#207]
The script updated itself today, and it's not working since.
It's marked active in Greasemonkey but no settings and no effects.
Firefox 56.0 x64 on W7 x64, Greasemonkey 3.17.

**Comment by ParticleCore** [comment]
Same configuration and it is working correctly, please follow the instructions as requested when opening an issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by mooms06** [comment]
I have tried GM 4.0 alpha6 to see if it makes any differences, and none of my scripts are working !
Reverted back to v3.17 , Iridium is working again.
Weird.

**Comment by ParticleCore** [comment]
Very likely a bad script update, either a mistake on my end or a bug on the Greasemonkey side. Whatever the case may be I am happy to hear it is working again for you.

The GM 4 is bleeding edge version and all the APIs it uses have been changed, almost 0 userscripts should be compatible with it today:

>As a result, version 4 of Greasemonkey is a nearly complete re-write.  Its interface and feature set have been rebuilt in order to best to work with coming Firefox versions.  A variety of compromises have been made.  We've elected to make a rare backwards incompatible change.

http://www.greasespot.net/2017/09/greasemonkey-4-announcement.html

Do not update it unless you are sure your userscripts are GM4 compatible! Iridium still isn't, but I am planning on making it compatible.

**Comment by mooms06** [comment]
I'm aware of the Greasemonkey 4 announcement, but I thought not backward compatible changes were minor, so I was shocked to see not a single script is compatible !
The thing is, some of my scripts are not updated/maintained anymore, they still works because the websites weren't updated either...

Once Firefox 57 released, I will likely must use TamperMonkey or ViolentMonkey instead...
This Fx 57 is a big pain in the ass !

Thank your for your support anyway.
