### ISSUE TITLE
Right-click menu opens behind the mini player

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Iridium#208]
Browser Name: Firefox Nightly
Browser Version: 58.0a1
Operating System: Windows 8
Software Type: Userscript
Software Version: 0.3.4b
Userscript Manager: Tampermonkey
Userscript Version: 4.5.5564
Problem Description: Right-click menu opens behind the mini player when at the bottom right corner

Steps to reproduce:

1. Enable setting 'Video stays always visible while scrolling'
2. Go to a video page and scroll down so the player moves to the bottom right
3. Right-click anywhere on the small player

 ![image](https://user-images.githubusercontent.com/5490615/31266031-bc43993e-aa26-11e7-92ef-4c3c4aff7802.png)

**Comment by ParticleCore** [comment]
They changed how the context menu shows. It used to resize itself to the size of the player before because it was contained within the player itself, not anymore. Will see what I can do.

**Comment by ParticleCore** [comment]
I am really sorry for the delay, this past month has been a huge rollercoaster and I haven't had almost any free time. I just want you to know that I have not forgot about this and will tackle it as soon as I am capable.

**Comment by Keith94** [comment]
@ParticleCore No worries, take your time on this.
