### ISSUE TITLE
Page moves in the background when pressing PAGE UP or PAGE DOWN in full browser mode

### ISSUE THREAD

**Issue by omperus** [ParticleCore/Iridium#210]
Title is pretty descriptive, you can see the page moving in the background when pressing the keys page up and page down (i have them binded to my mouse for easy browsing) in full browser mode.

**Comment by ParticleCore** [comment]
The entire background should be black outside the area where the video is visible, I don't understand how you can even see the page behind the player in the first place.

Please provide an example showing the problem.

**Comment by ParticleCore** [comment]
This is how it should look like:

![ss](https://user-images.githubusercontent.com/9222661/31313220-04758ac2-abcc-11e7-9791-edefa2f76563.png)

As you can see, there isn't a way to see the page at all.

**Comment by omperus** [comment]
![image](https://user-images.githubusercontent.com/4312673/31313236-9a85cef0-abb3-11e7-9ab2-70620f70f1e1.png)

After pressing page down

![image](https://user-images.githubusercontent.com/4312673/31313238-ae2ec542-abb3-11e7-8878-cb0d93ab9336.png)

You can notice the borders and the thumbnail to the related videos under his facecam

**Comment by ParticleCore** [comment]
That is nothing I can fix, the player extends to the limits of the visible browsing area, literally:

https://github.com/ParticleCore/Iridium/blob/db8aa1077c1fb5e793e241092c708921311dd0d7/css/Iridium.css#L540-L548

What is happening on your end is very likely a side effect of the heavy browser customization which is causing the page to overlap by a pixel under the browser limits or something else unrelated to normal page behavior.

If you pay attention to your screenshot you will notice that the entire area around the page has a weird border/spacing that is not normal, especially this area which shows page rendering outside the expected page limit, which is in fact in line with your tabs (that is not normal).

![ss](https://user-images.githubusercontent.com/9222661/31313310-c7435af0-abce-11e7-9097-99e5a1cb8859.png)

Whatever is causing that is not related to the extension, but either to your changes to the browser style via the userChrome.css file or via Stylish. To correct that you will have to fix your browser style that is causing that.
