### ISSUE TITLE
description box not working / showing 0.3.4b on any video 

### ISSUE THREAD

**Issue by Daisenki** [ParticleCore/Iridium#212]
Browser Name: Firefox
Browser Version: 56 (64-bit)
Operating System: W10 Home 15063.632
Software Type: Iridium
Software Version:  0.3.4b
Userscript Manager: Tampermonkey
Userscript Version: 4.5.5570beta (newest)
Problem Description: description box not working / showing 0.3.4b on any video or any channel 

<img width="459" alt="1" src="https://user-images.githubusercontent.com/22057956/31330825-3d618178-ace0-11e7-929c-be820a9d7faf.PNG">

**Comment by ParticleCore** [comment]
Can't reproduce, please follow the troubleshooting instructions as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Daisenki** [comment]
It works again, it was a problem with a uBlock filter, a update fix the issue. You can close the ticket.

**Comment by ParticleCore** [comment]
Glad to hear that you got it working again!
