### ISSUE TITLE
Disabled autoplay is not need in playlists

### ISSUE THREAD

**Issue by TokcDK** [ParticleCore/Iridium#213]
It is also in the YT+. When autoplay is disabled it is also disabled in playlists. It would be good to add suboption like 'Disable autoplay' --> '...but allow autoplay for playlists'. Because disabled autoplay is not need in playlists. Before it addon I was using Youtube center but it have no more updates and there is was it feature and it was very convenient.

**Comment by ParticleCore** [comment]
Duplicate of https://github.com/ParticleCore/Iridium/issues/191
