### ISSUE TITLE
Option to block YouTube Red advertisements

### ISSUE THREAD

**Issue by tgp1994** [ParticleCore/Iridium#215]
Lately, YouTube seems to be getting aggressive with their Red advertisements. I thought I had already indicated to them that I was not interested when I closed out the past 7 adverts, yet they persist.

It would be great if Iridium could block e.g the 250px-tall ad on the home page, and the little popup on individual video pages. Please see below for screenshots of the offenders.

----

**Front page:**
![YouTube Red Ad - Front page](https://user-images.githubusercontent.com/842942/31520529-f131e16c-af5a-11e7-8337-02da42bcb58d.png)

**Video page:**
![YouTube Red Ad - Smaller video ad](https://user-images.githubusercontent.com/842942/31520530-f14ee032-af5a-11e7-8813-f884214db447.png)

**Comment by ParticleCore** [comment]
The first one will be handled when I add the feature to disable ads outside the video page. The other one, I've never got it, will have to check it out when I revisit your request again.

**Comment by tgp1994** [comment]
Just wanted to check in since this issue was closed, is the feature to block ads site-wide being tracked elsewhere? The autoplaying banner ads reminded me that this would be a nice feature to have.

**Comment by ParticleCore** [comment]
@tgp1994 Issue #361 will tackle that aspect.
