### ISSUE TITLE
YouTube logo changed, breaking default tab and improved logo features

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#216]

**Comment by Hippyjake** [comment]
Not fixed when using dark theme.

**Comment by ParticleCore** [comment]
@Hippyjake Confirmed just now, it is working correctly with the version 0.3.5b

![ss](https://user-images.githubusercontent.com/9222661/31707151-e99f62e2-b3da-11e7-9614-626c246c611e.png)

Make sure you follow the instructions: https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md
