### ISSUE TITLE
Suggestion: Add option to always show progress bar

### ISSUE THREAD

**Issue by LunarBear** [ParticleCore/Iridium#22]
Low priority feature request if/when you have the time: add an option to always show the progress bar at the bottom of the video. Example of a script that does that and works with the new material UI: https://greasyfork.org/en/scripts/30046-youtube-always-show-progress-bar
Screenshot: http://i.imgur.com/Sad3P69.jpg
Simple tweak, super useful, but almost no addon/script has this option.

Thank you for your great work on this amazing script, it makes using Youtube a pleasure again. Thank you especially for the option to disable HFR (60 FPS), it allows people with slow connections like me to be able to watch youtube in 720p/1080p without buffering!

**Comment by Keith94** [comment]
I hope that's implemented here someday, would be nice to have.

**Comment by ParticleCore** [comment]
@shonay https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md
