### ISSUE TITLE
[enchancement] Advertising donation possibility

### ISSUE THREAD

**Issue by Hegezcc** [ParticleCore/Iridium#221]
I know that you are a great person with a ton of work given to this masterpiece and its predecessor, YT+. However, most of us don't know what is happening around the codebase. I saw your posts where you are struggling with motivation, and checked your Patreon page. I saw a very low amount of $23/mo and thought that something has to be made to improve your motivation. And money is a very good motivator, just after popularity.

Could you add a donation link somewhere in the plugins settings? Lots of users are just using the plugin, but don't even have a thought that somebody is working hard for this. They don't know that you are sometimes lacking of motivation and you are struggling with keeping this up and running. There are still lots of people, who could donate if they knew about your struggles. Describing the problem in a place they see would make everything better, you could get motivation and they'd get a better mood.

So, my suggestion is to add either the links where you can be helped, or some kind of motivation meter and work load meter.

**Comment by ParticleCore** [comment]
Thanks for the warm words, but the links are already displayed in the settings menu of the extension under the Donate section available here https://www.youtube.com/iridium-settings

Is this what you were referring to?

**Comment by Hegezcc** [comment]
Oh! Must have missed that. Thank you.
