### ISSUE TITLE
Freezing With Video Thumbnails enabled.

### ISSUE THREAD

**Issue by RadioActiveLobster** [ParticleCore/Iridium#224]
Browser Name: FireFox

Browser Version: 56.0.2 (64-bit)

Operating System: Windows 10 Pro 64bit

Software Type: Userscript

Software Version: 0.3.5b

Userscript Manager: (Remove this line if you are not using the userscript version) TamperMonkey

Userscript Version: (Remove this line if you are not using the userscript version) v4.5.5570

Problem Description: If the option for "Play videos by hovering the thumbnails" is enabled I get a complete lockup and freeze of FireFox for anywhere from 1-5 seconds when I hover over any thumbnail and also when attempting to play a video (auto play video is off) from a video page.

Steps to reproduce: Set the "Play videos by hovering the thumbnails" option to on and then just attempt to hover over a thumbnail or go into a video and try to play it.

**Comment by ParticleCore** [comment]
Can't reproduce this problem, no stutter is present, tested just now

![ss](https://user-images.githubusercontent.com/9222661/32359889-8df48d6a-c040-11e7-85b6-db06e7e5f2dc.gif)

Make sure you follow all the troubleshooting steps in the provided instructions and not just the steps you think are worth following, it is possible you have an add-on or something else causing this conflict: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by RadioActiveLobster** [comment]
I went through all that and it was still doing it. I did a complete uninstall/reinstall of FireFox and it seems fine now.

I'll continue to monitor but it looks like it may not have been related to the script after all.

**Comment by ParticleCore** [comment]
Glad to hear you got it fixed.
