### ISSUE TITLE
I have absolutely no idea how to install this.

### ISSUE THREAD

**Issue by XxTheAlmightyPotatoxX** [ParticleCore/Iridium#226]
I can't find a way to install .js or .json files on firefox (which are the only types of files used in this addon), so there must be another way I'm supposed to install it. This probably looks like a stupid question, since clearly many others have managed to install and use this to the point where they can actually use it, but I really can't figure out a way to do this. Do I need to be a contributor in some way or is this completely available for use to the public? It would be great if these questions could be answered, because I love using YouTube+, but I've finally gotten tired of reverting to the old layout pretty much every day, so I'd love to install the newer version. If you read through this, thanks a lot and I hope you can help.

**Comment by Tigoreetur** [comment]
you need tampermonkey here (https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/ extentions) download the extension form here (https://github.com/ParticleCore/Iridium/raw/beta/src/userscript/Iridium.user.js) and press install.

**Comment by ParticleCore** [comment]
@XxTheAlmightyPotatoxX as @Tigoreetur explained you need a userscript manager to install a userscript, which is the current deployment version that is available.

Follow his steps and you'll have installed your first userscript. If you still have any doubts feel free to ask here.

**Comment by XxTheAlmightyPotatoxX** [comment]
Thanks a lot! It installed correctly.
