### ISSUE TITLE
[Feature Request] Toggle Disable MPEG-DASH

### ISSUE THREAD

**Issue by mkasst** [ParticleCore/Iridium#229]
Add option to disable MPEG DASH (Dynamic Adaptive Streaming over HTTP) to force Youtube to buffer videos in full.

**Comment by ParticleCore** [comment]
Although DASH can be toggled, doing so no longer has any effect since YouTube is also controlling the buffer for the non-DASH format in Chrome and probably Firefox as well, see https://github.com/ParticleCore/Particle/releases/tag/1.5.0

**Comment by mkasst** [comment]
This is news to me. Thanks!
