### ISSUE TITLE
fullbrowser video mode. 

### ISSUE THREAD

**Issue by JourneyOver** [ParticleCore/Iridium#23]
I know you aren't really taking any requests for features or anything but since this is already a feature that you plan to implement into the release version of iridium, I was wondering if at all possible if you could make the full browser video mode actually fill the whole browser window and possibly have the video stretch to fill the whole player instead?

Current implementation of full browser video mode on youtube+ has black bars on the side of the player (dunno if that's how you intend to do it on iridium or not yet since it's slated for the release version at the latest currently), if you where to implement the way I am asking it would fill the whole browser window width.

Examples on what I'm talking about to get a better understand ---

Current implementation:
![Image](http://i.imgur.com/SkWuDhO.png)

Current implementation but filling the whole browser window:
![Image](http://i.imgur.com/HqMJyIv.png)

Current implementation but filling the whole browser window & stretching the video to fill player (the method I am requesting):
![Image](http://i.imgur.com/KNkWctl.png)

Maybe you could make it an extra option as well so that people who don't like it can turn it off (and have the default method of how youtube+ currently does it) while people who do like it can have it turned on.

**Comment by ParticleCore** [comment]
Fullbrowser mode will be implemented the same way it was first developed. AR (Aspect Ratio) control is a feature that I might consider in the future.

**Comment by TaylerUva** [comment]
I would love if it was implemented the way this userscript does it. 
https://github.com/Zren/ResizeYoutubePlayerToWindowSize/
"Moves the video to the top of the website and resizes it to the screen size." As this way it is a truly full screen. I used to use this and YouTube+ together with the "Video stays always visible while scrolling" however they are now incompatible for the scrolling feature :/
