### ISSUE TITLE
Release Firefox Addon

### ISSUE THREAD

**Issue by thegranddesign** [ParticleCore/Iridium#230]
I'm creating this as a placeholder so that people can subscribe to this issue either in Github or via https://tellmewhenitcloses.com

Feel free to update this description with the actual details of the release.

**Comment by ParticleCore** [comment]
Kind of screwed up here with the labels now, I don't have a proper one for this so I'll label it as feature without the beta target.

**Comment by GeekinaCave** [comment]
The new addon is gonna be WebExtension compatible?

**Comment by ParticleCore** [comment]
@GeekinaCave Yes it will.

**Comment by Yamazaki-wu** [comment]
@ParticleCore Iridium in the 57.0 version of Firefox does not load properly, what is wrong set up?
Greasemonkey 4.0
