### ISSUE TITLE
Mini player displayed behind related videos

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Iridium#231]
Browser Name: Nightly

  Browser Version: 58.0a1

  Operating System: Windows 10

  Software Type: Userscript

  Software Version: 0.3.6b

  Userscript Manager: Greasemonkey

  Userscript Version: 4

  Problem Description: 

  Steps to reproduce: 

  Additional details: 

![image](https://user-images.githubusercontent.com/5490615/32537762-9a1e16ac-c418-11e7-8c18-8c6c60e7bd19.png)

**Comment by ParticleCore** [comment]
Side effect of fix for #208 , will see what I can do.

**Comment by ParticleCore** [comment]
While on that page press `Ctrl + Shift + R` and see if the problem still exists.

**Comment by Keith94** [comment]
Looks to be fixed now.
