### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Denzof** [ParticleCore/Iridium#232]
Hello, with the last updated Iridium stopped working, TM says that it's enabled but the youtube site isn't displaying the icon and the functions aren't working.

Google Chrome Version 62.0.3202.89 (Official Build) (64-bit)
Tampermonkey 4.4
Version 0.3.6b.

**Comment by Rubeek** [comment]
Same issue.

Firefox 56.0.2 (64-bit)
Greasemonkey 3.17

**Comment by Dunkh4n** [comment]
Same here

Vivaldi | 1.13.971.8 (Version officielle) (64 bits)
Iridium | 0.3.6b
Tampermonkey 4.4

**Comment by webfischi** [comment]
New Iridium AAAAND youtube changes the design, to something between the old and new design.

The same software as Rubeek

**Comment by gershik** [comment]
Same
Chrome 62.0.3202.89 (Official Build) (64-bit)
Tampermonkey 4.4
Version 0.3.6b.

**Comment by ParticleCore** [comment]
Probably a bad polly fill for the new userscript API 4, will take a look at it later.

@Rubeek Update Greasemonkey to version 4 and try again.

@Dunkh4n There is no support for Vivaldi.

**Comment by ParticleCore** [comment]
Looks like Firefox is on early bird for the new API over at Tampermonkey, but Chrome is still only with the old version: http://tampermonkey.net/changelog.php?version=4.5.5570&ext=fire

Nevertheless it should be compatible with both API versions, so this needs to be fixed.

**Comment by Dunkh4n** [comment]
Vivaldi use chromium, it's praticaly the same as chrome..
I use firefox, chrome and vivaldi on regular basis.. Iridium has stopped working for all of them..

**Comment by SW1FT** [comment]
The script isn't working for me on Firefox Nightly 58, using the latest Violetmonkey.

**Comment by ParticleCore** [comment]
>Vivaldi use chromium, it's praticaly the same as chrome..

It's a fork which makes it different than Chrome and I am beyond tired of hearing fork users using that nonsense talk as if it was "all that works on Chrome/Chromium HAS TO work on all of its forks". I don't provide support for any forks and I don't plan to any time soon.

As for the Firefox, update either your Greasemonkey to version 4 or Tampermonkey to the newest version I linked.

@SW1FT I don't provide support for Violentmonkey.

This is a known issue and I am working on it, I did inform that problems could appear with this updated: https://github.com/ParticleCore/Iridium/releases/tag/0.3.6b

**Comment by Dunkh4n** [comment]
Ok man, don't beat me :)
I was not aware off you beyond tired of hearing that.. i don't follow all topic here..

**Comment by ParticleCore** [comment]
@Dunkh4n It's OK, it has been a rough couple of weeks and it gets tiring.

**Comment by ParticleCore** [comment]
This should be fixed in version 0.3.7b, apologies for this.

**Comment by Tigoreetur** [comment]
It work now for me.

**Comment by SW1FT** [comment]
Same, it's also working while using Violentmonkey.
