### ISSUE TITLE
Full Browser mode issue

### ISSUE THREAD

**Issue by LazyBoot** [ParticleCore/Iridium#234]
Full Browser mode seems to have stopped working properly in the last update.
Screenshot below:
![untitled](https://user-images.githubusercontent.com/3827482/32626950-1e2d6910-c591-11e7-9596-acf0fcc38ce4.png)

**Comment by ParticleCore** [comment]
Will fix it asap, thanks!

**Comment by LazyBoot** [comment]
Awesome, thanks for the quick fix :)
Can confirm it's working like it should now.
