### ISSUE TITLE
Firefox 57 + Greasemonkey 4 Not detecting Iridium

### ISSUE THREAD

**Issue by roaminghawk** [ParticleCore/Iridium#235]
Hi,

When you click on download the Greasemonkey does not pick up the script for installation while it detects other scripts.
Is that an issue with Iridium or with GM?

Thanks.

**Comment by Keith94** [comment]
https://github.com/greasemonkey/greasemonkey/issues/2631

**Comment by roaminghawk** [comment]
Thanks.

**Comment by ParticleCore** [comment]
@roaminghawk I hope you got your issue resolved, if not let me know.
Thanks @Keith94 for the help.
