### ISSUE TITLE
Not working with greasemonkey 4.0 firefox 57

### ISSUE THREAD

**Issue by meve90** [ParticleCore/Iridium#236]

**Comment by ParticleCore** [comment]
Please follow the instructions for reporting a problem as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by jnv** [comment]
For anyone who bumped into the same issue, Iridium does work with Greasemonkey 4.0, but needs to be updated to the latest beta version. Also, there is [a known bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1411641) which prevents installation of the userscript from GitHub, so your best bet is to manually copy & paste script's source into Greasemonkey.

**Comment by ParticleCore** [comment]
Duplicate of #235
