### ISSUE TITLE
Script not being identified as a userscript on Greasemonkey 4.0 on Firefox 57

### ISSUE THREAD

**Issue by BlueNinja0** [ParticleCore/Iridium#239]
Clicking the script available in the Downloads page opens the script in plain text in Greasemonkey 4.0 on Firefox 57, probably because of the Greasemonkey 4.0 backwards incompatibility.

I assume this is not going to affect the Firefox Addon version.

**Comment by ParticleCore** [comment]
Duplicate of #235

**Comment by BlueNinja0** [comment]
My apologies.
