### ISSUE TITLE
Add A Disable DASH Option

### ISSUE THREAD

**Issue by GKid94** [ParticleCore/Iridium#241]
Browser Name: Chrome

  Browser Version: 62.0.3202.94 (Official Build) (64-bit)

  Operating System: Windows 10 Pro 64bit

  Userscript Manager: Tampermonkey

  Userscript Version: 4.4

  Problem Description: No Disable DASH Option

  Steps to reproduce: Add a Disable DASH Option

**Comment by ParticleCore** [comment]
Duplicate of #229
