### ISSUE TITLE
add functionality and modify existing

### ISSUE THREAD

**Issue by Artlant** [ParticleCore/Iridium#243]
Hi!
I use two extensions, this is yours and one more. **Iridium** fulfills 90% of my requirements. But there are those who were good to drag here. It's working with YouTube's new design POLYMER LAYOUT. That it's theoretically easy to copy the missing/better functionality
The extension itself is located here:
https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle

Personally for me, where it is more conveniently implemented:
- Control volume level with the mouse wheel when hovering the video player with the mouse cursor. 
- Info: Use the mouse wheel to control playback speed when hovering this button with the mouse cursor. Click it to use the default playback speed. You can also use the mouse wheel to control playback speed when hovering the video player, and click it to use the default playback speed, if you maintain the "Control" key (Ctrl) pressed.(HTML5 player only)

Drop-down curtain at the top of the video is just beautiful

From the functions that are absent in Iridium is:
- Do not pause videos in playlists.
- Automatically expand the videos descriptions.
- Automatically sort comments from newest to oldest.

it would not be bad to add them.

Regards Raingart

**Comment by ParticleCore** [comment]
Please follow the rules as requested: https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by Artlant** [comment]
@ParticleCore 
Can I find out the reason for refusing to add new features? Recently, I have not noticed an increase in options. I understand that the project is free and I have no right to demand. But what are you still doing. Current opportunities do not expand and are rather meager.
Do you work on architecture or do not know how to rewrite in a new language? Or is this due to a lack of desire to modify? 
I hope my questions will not be ignored. If I did not appreciate your product, I probably would not have written this issue

**Comment by Tigoreetur** [comment]
Feature requests:
The one issue per issue applies as well, do not request more than one feature in the same issue

**Comment by ParticleCore** [comment]
I am not refusing anything:

>There is currently no intention to accept feature requests, but they can be requested nonetheless for future consideration
>The one issue per issue applies as well, do not request more than one feature in the same issue

https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

(added the last one today to make more clear what was already said at the start)

I also do not want to make an extension containing everything everyone requests, ending up not being able to maintain anything and with most features not working as a result of that. That is why I am willing to accept feature requests for future consideration, but most will never be implemented.

I also have very limited time, which I dedicate to this project whenever I can. This project returns almost no income and I need to work to pay my bills, until this project becomes a better income source my time will remain mostly focused on what is actually more important for me right now.
