### ISSUE TITLE
Disabling autoplay problem

### ISSUE THREAD

**Issue by varkmat** [ParticleCore/Iridium#244]
Hi,

i am using vivaldi browser 

Disabling auto play works great on youtube site, (no preloading of video) 

But youtube videos embedded in other websites still auto preloads and plays.

Any ways to stop it ?

**Comment by ParticleCore** [comment]
This extension is only built for Chrome and Firefox, Vivaldi is not a supported browser.
Also this extension is not designed to work outside the YouTube pages, meaning that there is no embedded videos support.

**Comment by varkmat** [comment]
Point noted. 
Thanks for the reply and this amazing script and extension !
