### ISSUE TITLE
Show selected video quality in the settings icon

### ISSUE THREAD

**Issue by 07416** [ParticleCore/Iridium#246]
> * There is currently no intention to accept feature requests, but they can be requested nonetheless for future consideration

In terms of bitrate, there's a massive difference between 720p, 1080p and 4K on YouTube. The setting icon only shows if the video is running in "HD" or not, quality ranges between 720p and 8K (144p and 480p for SD):

![capture](https://user-images.githubusercontent.com/14923168/33474014-6e833ace-d681-11e7-91a6-499832822902.PNG)

**Comment by BlueNinja0** [comment]
I would also like to see this feature implemented. It would be extremely useful in my use case.
