### ISSUE TITLE
Iridium stop working

### ISSUE THREAD

**Issue by Denzof** [ParticleCore/Iridium#247]
Hello. Looks like Youtube updated or something happened because I can't seem to get Iridium working again. I have Tempermonkey 4.4 and Iridium 3.8b. Sorry if I'm wrong. Using Chrome Version 62

**Comment by Tigoreetur** [comment]
This setup works for me.

**Comment by Denzof** [comment]
Thanks it does work I just clear cache and seems to work now. Sorry for the issue report you can close it.
