### ISSUE TITLE
How to block 'Coin Hive' ?

### ISSUE THREAD

**Issue by rackstraw** [ParticleCore/Iridium#248]
"October has ended and along with it the trial run for the crypto currency miner. I would like to thank to everyone that chose to participate on this trial run and would also like to say that to those that only participated just for the test it is alright to turn it off if that was your only goal."

Contrary to the message above, I installed the Iridium user script with Tampermonkey only last night 12/01/17, and when I opened Chrome I got immediately got the following CoinHive popup, which I am unable to [remove](https://imgur.com/gallery/cOqx6)

When I disabled Iridium and restarted YouTube the popup disappeared.  I tested this several times and there is no doubt it is coming from Iridium; whether by accident or design I not know. 

Chrome popup blocker does not detect it.  Moreover I can not even scroll the window down to see the rest of the popup, or use YouTube for any purpose.

Could someone please give me some help in blocking or removing this infection?

**Comment by ParticleCore** [comment]
Had you followed the instructions (https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting) before opening the issue you would have noticed that this extension is for the new YouTube Material layout, which is not the one you have installed. Either disable Iridium or enable the new YouTube layout here https://www.youtube.com/new

**Comment by rackstraw** [comment]
After originally starting your script I opened YouTube in order to switch
to the new layout, but as stated, I found it frozen by the coinhive
parasite; it looked like  a virus to me, and I didn't want to experiment
any further.

So the rule is "always switch layouts BEFORE starting Iridium the first
time". Right?

**Comment by ParticleCore** [comment]
There is no rule, it is only compatible with the new layout, period. If it is not enabled then it has to be enabled before using Iridium (like you said).
