### ISSUE TITLE
Descriptions for keys ',' and '.' are reversed in "Local Shortcuts" Wiki section

### ISSUE THREAD

**Issue by todd31** [ParticleCore/Iridium#251]
The keys are functioning correctly (ie. QWERTY ',' is backwards, and '.' is forward), but the Wiki needs fixing to reflect the keys' actual effect.

From:  
[https://github.com/ParticleCore/Iridium/wiki/YouTube-shortcuts#local-shortcuts](url)

,    Skip one frame forward (Video must be paused)   **_<--- [should SAY backwards in wiki]_**
.    Skip one frame backwards (Video must be paused)   **_<--- [should SAY forward in wiki]_**

**Comment by ParticleCore** [comment]
Thanks, this has been corrected on both repos.
