### ISSUE TITLE
[Suggestion] Allow video downloading ?

### ISSUE THREAD

**Issue by sylvainsab** [ParticleCore/Iridium#252]
Hi Particle, first of all thanks for your work and your wonderful extension. I'm eager being able to use the stable version with the new YouTube display.

My suggestion is quite straightforward, I wonder if you haven't done it before for lack of time or interest, or perhaps for legal reasons ?
In any case, I would find this extension the absolute best -and would be ready to bring some modest financial contribution- if it would allow to download YouTube video in various formats (especially HD formats, of course).

Currently I attempt to use this one but it's not working very well even though I've paid for it... https://addons.mozilla.org/en-US/firefox/addon/easy-youtube-video-download/

Thanks !

Sylvain

**Comment by ParticleCore** [comment]
Duplicate of https://github.com/ParticleCore/Iridium/issues/165

Also no feature of this extension is monetarily driven. I do appreciate the interest, but I only implement features that I find to be useful.

**Comment by sylvainsab** [comment]
Thanks for the quick reply. My apologies, I didn't find the first request despite performing a quick search.
