### ISSUE TITLE
Disabling video autoplay stopped working

### ISSUE THREAD

**Issue by TheCuza** [ParticleCore/Iridium#253]
It stopped some time yesterday. Tested on both Firefox and Chrome.

For some reason though, if I open a video in a new tab on Chrome, it will start playing and then pause itself after a second or so.

**Comment by iPaulis** [comment]
It worked until 19:00-20:00 or so, then stopped working at all, so it doesn't disable autoplay anymore.

**Comment by ParticleCore** [comment]
YouTube changed something making the first load to fail when trying to stop autoplay, but subsequent video plays do not autoplay correctly, unless you change from single video to playlist and vice versa. Will check to see what can be done.

**Comment by JEmlay** [comment]
Same here.  If you open videos in new tabs those tabs do not auto play.  But once you go to that tab the video starts playing. automatically  There's also some weird new icon on those table with a play symbol that I've never seen before.  As if to let you know, when you go that tab something will play.  Not sure if Youtube is somehow able to do that or if FF knows and is warning you.

**Comment by ParticleCore** [comment]
@JEmlay That's the default Firefox behavior they implemented recently, has nothing to do with this extension.

**Comment by practik** [comment]
> YouTube changed something

Not sure this is relevant, but I notice that whenever I load a new YouTube page (open in new tab or reload existing tab), the "improved" black logo appears for a split second but is then replaced by an animated "YouTube Rewind" logo that links to `https://www.youtube.com/user/theyearinreview` instead of `https://www.youtube.com`.

**Comment by ParticleCore** [comment]
@practik Unrelated to this one, please open a new issue instead.

**Comment by TheCuza** [comment]
Looks like whatever is breaking the autoplay setting is also breaking the default video quality setting. Videos are defaulting to Auto for me now instead of 1080p.

**Comment by ParticleCore** [comment]
Please follow the instructions for opening issues, no more than one per issue. If there is a new issue that is not this one then open another issue.

**Comment by TheCuza** [comment]
It seems to be caused by the same thing, so I felt like it was close enough to count as the same issue.

**Comment by ParticleCore** [comment]
@TheCuza I understand, there's no harm done, it could be, but in this case it is not.

**Comment by ParticleCore** [comment]
The latest version should fix this issue, let me know if it works correctly for you now.
