### ISSUE TITLE
Full Browser Mode Bugs/Suggestions

### ISSUE THREAD

**Issue by crumbl3d** [ParticleCore/Iridium#258]
Browser Name: **Firefox Developer Edition**

Browser Version: **58.0b10**

Operating System: **Windows 10 Fall Creators Update Build 16299**

Software Type: **Userscript**

Software Version: **0.4.0b**

Userscript Manager: **Tampermonkey**

Userscript Manager Version: **v4.5.5648**

Problem Description:
1) When scrolling down while **follow player** is _enabled_ and launching **full browser** mode, the **background** is _**not** black_ but _dimmed_. If the **follow player** is _disabled_, the **whole background** is _black_ which was to be expected.
2) Also, if you **resize the window** while in **full browser** mode, the **player** is _**not** resized_ and _does **not** fill_ the whole **browser window**. A fix for this would be most appreciated, if possible.

Steps to reproduce:
1) Video stays always visible while scrolling is enabled, and full browser mode is then enabled.
2) Full browser mode is enabled and then the window is resized.

Additional details:
I have tried to edit the script myself but fail to grasp most of the code and the api used. Previously I have made a script that resizes the player if the browser window is resized but that was before Material Design layout. I have not attempted to adapt it to the new layout. If I could be of any help please do ask.

![Issue 1](https://user-images.githubusercontent.com/5552449/33829528-f18e4444-de70-11e7-830f-9436536fc7b3.png)

![Issue 2](https://user-images.githubusercontent.com/5552449/33829295-f7569db4-de6f-11e7-9f8c-d3cd191fc2cc.png)

Suggestion:
While I do like pressing the Esc key to exit full browser more, I think it would be more convenient if you could add a button to exit full browser mode to player controls. I have done this before in my script with success. You could copy the theater mode button and just reassign the behavior.
PS: I know it is not that easy but this is an idea.

**Comment by ParticleCore** [comment]
@crumbl3d Latest version should fix these issues. As for your suggestion I've opened a workable alternative in #265
