### ISSUE TITLE
Iridium does not load anymore under Tampermonkey

### ISSUE THREAD

**Issue by CyberAP** [ParticleCore/Iridium#264]
Since latest update Iridium stopped working for me. It seems that it does not even load. I checked Tampermonkey and it's still there, updated to the latest version. It also has the correct settings.

![Preview](https://i.imgur.com/um5BanV.png)

![Settings](https://i.imgur.com/g2kB6tI.png)

**Comment by ParticleCore** [comment]
Everything is working correctly here, please follow the troubleshooting guide as requested before opening the issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by BondiBear** [comment]
just fyi: this fixed the identical issue for me:

**_Make sure that you are using the new YouTube Material layout. If you aren't then enable it and try again: https://www.youtube.com/new_**

for some reason, Jewtube reset itself to classic after I had restarted FF.

**Comment by ParticleCore** [comment]
I will close this for now. @CyberAP If you still have any issues, please follow the instructions in my previous reply.

**Comment by CyberAP** [comment]
For anyone having the same issue there were 2 problems I had to solve:

* Tampermonkey required hard reset for some reason, that prevented it from auto updating.
* YouTube center was conflicting with Iridium and for some reason was re-enabled (though seen as disabled in Tampermonkey). Uninstalling it and reinstalling Iridium solved the problem.
