### ISSUE TITLE
Use `suppress_autoplay_on_watch` with `autoplay`

### ISSUE THREAD

**Issue by YePpHa** [ParticleCore/Iridium#266]
YouTube has added a config property called `suppress_autoplay_on_watch` that makes the `autoplay` property work on the watch page. This makes the need of having this ["hacky code"](https://github.com/ParticleCore/Iridium/blob/beta/src/userscript/Iridium.user.js#L2904) obsolete.

To use it you simply include it with [autoplay](https://github.com/ParticleCore/Iridium/blob/beta/src/userscript/Iridium.user.js#L1781):
```javascript
args.autoplay = "0";
args.suppress_autoplay_on_watch = true;
```

You can see my implementation of it [here](https://github.com/YePpHa/maia-yt/blob/master/src/modules/autoplay/index.ts#L56).

**Comment by ParticleCore** [comment]
Well, this just became a bit scary, I actually stumbled on that while working on reverse playlist a few minutes ago and now you are confirming my suspicion. I can't wait to get rid of the injection points, they are horribly prone to break.

I will test it out and implement it as soon as I can. Thanks a lot for the help.

**Comment by ParticleCore** [comment]
@YePpHa Just an update, some users are receiving an enabled experiment which overrides this setting, setting `html5_new_autoplay_redux` to false in `fflags` returns autoplay control to normal behavior.

**Comment by YePpHa** [comment]
@ParticleCore Thanks I will make sure that it's set.

**Comment by ParticleCore** [comment]
@YePpHa It appears that `suppress_autoplay_on_watch` was completely removed: https://www.youtube.com/yts/jsbin/player-vfl8swg2e/en_US/base.js

Will have to resume the hackish method. Why do they always have to make this hard.

**Comment by YePpHa** [comment]
That's a real shame. I looked at the code again to check whether there was a better method, but I couldn't find anything. I will just revert my hacky code too :(
