### ISSUE TITLE
[Request] Disable Dash loading.

### ISSUE THREAD

**Issue by SirLagsalot83** [ParticleCore/Iridium#270]
Fist of let me say that I'm not familiar with any kind of programming language and I have no idea how this black magic actually works.
But I know from another plugin that the Dash buffering YouTube uses (might have a new name by now) is really disruptive to a person like me who often use the shortcut keys to jump 5 or 10 seconds back and forward. Almost every time I do this however YouTube needs to re-buffer a part of the video I've already seen. This wasn't a problem a few years ago.
Back in the days YT buffered the whole video in one swoop and you could jump back and forward to your hearts content without problems.
Is there a way to force that kind of (old style) buffering today?
And if there is, could it possibly be included in Iridium?

**Comment by ParticleCore** [comment]
Duplicate of https://github.com/ParticleCore/Iridium/issues/229
