### ISSUE TITLE
Full Browser Mode

### ISSUE THREAD

**Issue by adeep** [ParticleCore/Iridium#276]
I just read your "current status update" so i don't expect this update asap.
But could you make fulll browser mode to use standart  Youtube player, instead of Chrome html5 player based player. 
Why i want you to change it cause when you right click to video it gives you different menu when in full browser mode .
Like i said its not priority of course, maybe if it is possible you already make that version instead of this.
Thanks.
Browser Name: Chrome 

Browser Version:  63.0.3239.108

Operating System: Windows 10 Fall Creators Update x64

Software Type: Userscript

Software Version: 0.4.1b

Userscript Manager: Tampermonkey

Userscript Manager Version: v4.4
![1](https://user-images.githubusercontent.com/374042/34493852-cd9b4074-effe-11e7-9cc8-ac5c89e79ddd.png)
![2](https://user-images.githubusercontent.com/374042/34493853-cdd742f4-effe-11e7-90a6-dc49007500c2.png)

**Comment by ParticleCore** [comment]
This is actually a bug, the default YouTube menu should be the one showing, not the browser's default. Thanks for reporting it.

**Comment by adeep** [comment]
:) I assume it was a sideway you found after youtube change to new ui. I am happy to know it is bug so it can be fixable.

**Comment by ng4ever** [comment]
I have the same issue!
