### ISSUE TITLE
Default video player is small now?

### ISSUE THREAD

**Issue by FengLengshun** [ParticleCore/Iridium#278]
Hello, I recently restarted Firefox and it seems to have a new update (or the youtube site has an update) that makes the default player smaller now, even though I have a 1920 x 1080 resolution on my second monitor. It used to be a lot bigger before, almost as big as YouTube's Theater Mode player, but still have room on the side for the video recommendation and live stream's chat (which are very handy).

Help please?

**Comment by ParticleCore** [comment]
Please follow the instructions for opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

Additionally the YouTube website adjusts the size of the player according to the size of your browser. If your toolbar is bigger or anything else is making your visible window smaller then the player will decrease in size on its own and this is controlled by YouTube itself, not by Iridium.

**Comment by ParticleCore** [comment]
Closing this for now, if you still have any problems please follow the instructions in my previous reply.
