### ISSUE TITLE
Question about Reverse Playlist

### ISSUE THREAD

**Issue by thekcool** [ParticleCore/Iridium#281]
Is Reverse Playlist only available during playlist playback but not on the Playlist's page?
<a href="https://imgur.com/WfBoOzV"><img src="https://i.imgur.com/WfBoOzV.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/MHCektT"><img src="https://i.imgur.com/MHCektT.jpg" title="source: imgur.com" /></a>

Also, small aside, is there a forum or subreddit where I can ask questions? I don't want to take up anyone's time if it's something along a "How to" question or just something I didn't see.

Thanks.

**Comment by ParticleCore** [comment]
That is correct, it is only available while playing a playlist and no, there isn't any other location other than this repository.
