### ISSUE TITLE
YouTube Player Drops Frames and the Buffer Health increases.

### ISSUE THREAD

**Issue by briank6932** [ParticleCore/Iridium#283]
It works perfectly fine disabled and it is definitely not due to my computer.
My Specs:
R7 1800x (liquid cooled)
1080 ti (liquid cooled)
16gb DDR4 (3600mhz cl15)

**Comment by ParticleCore** [comment]
Please follow the instructions for opening a new issue as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closing this for now, if you still have problems follow the instructions in my previous reply.
