### ISSUE TITLE
Have Live Video Chat be hidden by default

### ISSUE THREAD

**Issue by Mperor** [ParticleCore/Iridium#284]
I know you said you don't intend to accept feature requests, but if it isn't too much hassle, an option to have it so that the live video chat area is collapsed by default (similar to the option you already have for the comment section) would be appreciated. It's a really minor thing, so I'd understand if you don't think it to be worth the effort.

**Comment by Betsy25** [comment]
I have this by default by adding the following list to uBlock Origin.
https://raw.githubusercontent.com/Betsy25/Custom-uBlock-filters/master/Youtube-Block_livestream_chat.txt
