### ISSUE TITLE
Default channel tab not functioning

### ISSUE THREAD

**Issue by Matakor** [ParticleCore/Iridium#293]
Seems to be a very new problem. Personally on Vivaldi browser, but the plugin has functioned perfectly up to this morning. Maybe a youtube change?

I have it set to default to the videos tab so I can actually watch the latest vids on my subscriptions, but now it's not doing that.

**Comment by ParticleCore** [comment]
I can reproduce this bug, but in the future be aware that there is no support provided for any browser other than Chrome and Firefox.

**Comment by windowlicker79** [comment]
If its any help I can confirm that this is also happening for me, on the same set-up described in my recent bug report about the "youtube default logo page" problem.

**Comment by ParticleCore** [comment]
@windowlicker79 Thanks, but once I confirm the bug exists it is OK because I have something to work on from that point on.

**Comment by Matakor** [comment]
Yay, it's fixed!

Thank you so much!
