### ISSUE TITLE
Setting "default youtube logo page" to subscriptions no longer works.

### ISSUE THREAD

**Issue by windowlicker79** [ParticleCore/Iridium#294]
Browser Name: Firefox

  Browser Version: 58.0

  Operating System: Windows 10 Pro

  Software Type: userscript

  Software Version: 04.4b

  Userscript Manager: Tampermonkey

  Userscript Version: 4.5.5660
  
  Problem Description: Changing the "default youtube logo page" option to subscriptions no longer has any effect. Instead it reverts to default behaviour of going to the youtube home page.

  Steps to reproduce: Try to set the "default youtube logo page" option to subscriptions then click the youtube logo.

**Comment by ParticleCore** [comment]
I can confirm this, I'll see what I can do to fix this.

**Comment by windowlicker79** [comment]
I also had another bug but I didn't submit a report as it is intermittent and kind of difficult to describe.
Basically sometimes when I finish viewing a video in fullscreen, then exit fullscreen after the video has stopped, if I click anywhere on the screen (for example clicking the uploader's name to go to their channel) it will instead start playing one of the suggested videos that is displayed after the video being watched ends. Its almost as if it thinks its still in fullscreen and responding to a click on what would have been a suggested video, if it was still in full screen mode. 
I think it usually happens after I have watched 2 videos (the first video and then a suggested video after it ends) without leaving full screen, then exiting fullscreen after the 2nd video.

As I said kind of difficult to describe and doesn't happen that often. But I thought I'd mention it here just in case you might have an idea of what caused it.

**Comment by ParticleCore** [comment]
@windowlicker79 If you can find steps to recreate the problem describe them in a new issue so that I can see what I can do.
