### ISSUE TITLE
Show more not working on firefox

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#297]
Clicking "Show more" in the recommended menu makes itself disappear.
Self-Identification: 58.0b16 (64 bit)
UA-String: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by ParticleCore** [comment]
Closing this for now, if you are still having problems follow the instructions in my previous reply.
