### ISSUE TITLE
Iridium is out of beta (finally)

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#301]
I would like to thank to everyone that has contributed to the development of this extension; be it via donations, debugging, feedback or translations.

I would also like to apologize for this day to come so late, the initial plan was for the beta to end in 2017, but situations that were out of my control forced the  changes in the plan.

Regarding the crypto currency miner, it will remain available only for the userscript version as previously announced. This is a decision made due to the abuse that this system has suffered and the resulting backlash from the unaware users. Including this in the extension versions would definitely be a risk without a clear position from the extension stores. This means that until the Firefox AMO and Chrome Webstore make it clear that they authorize this method of contributing to developers, the miner will not be available outside the userscript version.

If by any chance it becomes available before that time comes please report it here immediately.

The current focus now is on developing the Firefox WebExtension and Chrome extension versions.

Going further I will be implementing new features, including some that were available in the previous extension YouTube + as well as any bugs that might be found.

As some of you may already know, the time I have to dedicate to the development of this extension is very scarce and this is something that should not change in the foreseeable future seeing that until the income generated from this extension is significant I have to focus on my personal and professional life.

I do not like to ask for donations, those of you that have been following me know this from previous discussions, but I am now trying some of the suggestions that have been discussed before, with this being one of them.

If you want to contribute you can do so by going to the donation page and choosing the available options here: https://github.com/ParticleCore/Iridium/wiki/Donate

You can also use your computer to contribute, you can read more about this option here: https://github.com/ParticleCore/Iridium/wiki/Features#miner

Any help is always appreciated. Even something as simple as translating the extension will help make this extension better: https://github.com/ParticleCore/Iridium/wiki/Locale-instructions

Thank you to everyone and I hope this extension makes your experience on YouTube better.

**Comment by wickles** [comment]
How do I change to release channel, as it says to do on first visit to youtube?

**Comment by ParticleCore** [comment]
@wickles You only need to install it again via either one of the links available here: https://github.com/ParticleCore/Iridium/wiki/Download

They have been updated with the release channel version already so all you have to do is install via one of those links.

**Comment by Royalgamer06** [comment]
You should use 1.x.x for release, so the script will be auto-updated for everyone.

**Comment by ParticleCore** [comment]
@Royalgamer06 It would not make a difference since userscript managers memorize the download origin of the userscript, this means it would always try to check for a new version on the beta branch no matter how high the new version would be on the release branch.

**Comment by Royalgamer06** [comment]
@ParticleCore you can actually change the download origin of the userscript with `@downloadURL` and `@updateURL`. So, if you do that on the beta channel, you can make people auto update to the release channel.

**Comment by ParticleCore** [comment]
That would break other means of distribution, such as GreasyFork and/or OpenUserJS since all three would point to the exact same origin due to the meta tags.

**Comment by Zarggg** [comment]
Seconded for using 1.x versioning for releases. Both GreasyFork and Tampermonkey flagged this as a "downgrade," and I had to do a double-take for a moment.

**Comment by GKid94** [comment]
Can you add a remove Autoplay switch option and also add a repeat video option in the options under the video
