### ISSUE TITLE
PayPal links to portuguese version

### ISSUE THREAD

**Issue by BubiBalboa** [ParticleCore/Iridium#302]
I want to support you but I can't read the PayPal page you have linked to and there is no way to change the language on the page itself. I don't want to check a wrong box or something.

**Comment by ParticleCore** [comment]
I have no idea why it is doing that, but you should have a drop down on the top right of PayPal where you can change the language to English. Can you confirm this?

**Comment by ParticleCore** [comment]
Also if you can try the links in this page: https://github.com/ParticleCore/Iridium/wiki/Donate

I have updated them with an extra parameter that should force English by default.

**Comment by BubiBalboa** [comment]
The new link works, thank you.

No dropdown menu on the page though. I looks like it could be a mobile version. Everything is very minimalistic and comparatively big.

**Comment by ParticleCore** [comment]
Thanks reporting back, I will be updating the links in the extension with that change as well on the next update.
