### ISSUE TITLE
Userscript version will not show settings icon on Firefox

### ISSUE THREAD

**Issue by fhoshino** [ParticleCore/Iridium#305]
Userscript version will not show settings icon on Firefox, tested on fx 60, tampermonkey 4.5

**Comment by ParticleCore** [comment]
The icon is showing correctly on my end with same setup, please follow the troubleshooting instructions as requested before opening the issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by ParticleCore** [comment]
@fhoshino Sorry for bothering you, but were you able to fix the problem?

**Comment by fhoshino** [comment]
New material design not loaded on first place in firefox, enabled via link, problem resolved.
