### ISSUE TITLE
Possible bug with video upload age

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Iridium#31]
https://www.youtube.com/watch?v=1wLTxlgMND4

This video was uploaded almost three years ago but Iridium shows "1 month ago".

![image](https://user-images.githubusercontent.com/5490615/27226329-5045b5a8-5253-11e7-99ae-a7dd9fa84a08.png)

**Comment by ParticleCore** [comment]
Grabbing info from something like this: https://www.youtube.com/user/AuToMaNiAk005/search?query=%221wLTxlgMND4%22

Unlucky that the first result happens to have a link to the actual result we want. Will try to fix it as soon as I can.
