### ISSUE TITLE
Disabling video autoplay stopped working (again)

### ISSUE THREAD

**Issue by KuroiLight** [ParticleCore/Iridium#311]
Tampermonkey 4.5.5660, Firefox 59.0b5
It stopped working again, cant find any cause on my end.
#253

**Comment by Zero-ELEC** [comment]
Same issue, started within the last 12 hours.

**Comment by graycatgrayhat** [comment]
Same running Iridium v0.0.1, Violentmonkey v2.8.27 under Firefox 58.0.1

**Comment by TheFinalCut83** [comment]
Same with Tampermonkey 4.5.5660, Firefox 59.0b5 and Iridium 0.0.1. Cleaning cookies and cache doesn't work. Looks like next change of Youtube stream protocol by Google.

**Comment by ParticleCore** [comment]
I can confirm this on my end as well, will see what I can do to fix this.

**Comment by joshg253** [comment]
Repro'd on Windows 10 / Firefox 58.0.1 (64-bit) / Tampermonkey 4.5.5660 / Iridium 0.0.1

**Comment by JEmlay** [comment]
Thank you!
