### ISSUE TITLE
Add Some Options

### ISSUE THREAD

**Issue by GKid94** [ParticleCore/Iridium#315]
Browser Name: Chrome

  Browser Version: 64.0.3282.140 (Official Build) (64-bit)

  Operating System: Windows 10 Pro 64bit

  Software Type: Iridium

  Software Version: 0.4.7b

  Userscript Manager: Tampermonkey

  Userscript Version: 4.5

  Problem Description: Missing some options

  Steps to reproduce: Add an option to remove the Autoplay switch and also add an option to repeat the video in the options under the video

**Comment by ParticleCore** [comment]
Please read the instructions for **feature requests** with attention or I will be forced to block any further submissions to prevent further spam to the subscribed users: https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md
