### ISSUE TITLE
Many bugs

### ISSUE THREAD

**Issue by Nallat** [ParticleCore/Iridium#317]
![2018-02-03_17-25-44](https://user-images.githubusercontent.com/33554398/35769227-3a33a63c-0908-11e8-9bd5-f9e0a1801396.png)
![2018-02-03_17-26-48](https://user-images.githubusercontent.com/33554398/35769228-3a4d7d5a-0908-11e8-9e47-a8deb473bb46.png)
![2018-02-03_17-27-39](https://user-images.githubusercontent.com/33554398/35769327-a8b9c0f4-0909-11e8-8ddb-563002175130.gif)

**Comment by ParticleCore** [comment]
Please read the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

There is no support for any browser other than Firefox and Chrome.
