### ISSUE TITLE
[Bug] The button to display more videos overlap the mini video player

### ISSUE THREAD

**Issue by Nallat** [ParticleCore/Iridium#318]
Browser Name:  Vivaldi

  Browser Version: 1.15.1089.3

  Operating System: Windows 10 Fall Creators Update Build 16299

  Software Type: Userscript

  Software Version: v0.0.2

  Userscript Manager: ViolentMonkey

  Problem Description: the button to display more videos (on the home page) overlap the mini video 
  player

![ww](https://user-images.githubusercontent.com/33554398/35769522-ace2c268-090c-11e8-84cb-bdf8f7ab9791.png)

**Comment by ParticleCore** [comment]
Please read the instructions as requested before opening an issue, this is the last time I ask; https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

There is no support for Vivaldi.

**Comment by Nallat** [comment]
@ParticleCore Vivaldi is based on chromium and perfectly supports chrome extensions and userscripts, I will try it on Google Chrome but I'm sure this bug is a general bug.

**Comment by ParticleCore** [comment]
It makes no difference in what Vivaldi is based on. If it isn't Firefox or Chrome then there is no bug support for it. The fact that the problems exist in Vivaldi and not in Chrome shows clearly how Vivaldi being based on Chromium means nothing.
