### ISSUE TITLE
[Bug] The button to display more videos overlap the mini video player

### ISSUE THREAD

**Issue by Nallat** [ParticleCore/Iridium#320]
Browser Name: Google Chrome

Browser Version: 64.0.3282.140

Operating System: Windows 10 Fall Creators Update Build 16299

Software Type: Userscript

Software Version: v0.0.2

Userscript Manager:  TamperMonkey beta

Problem Description: the button to display more videos (on the home page) overlap the mini video
player
![ww](https://user-images.githubusercontent.com/33554398/35769743-e85eae30-090f-11e8-8b03-2f378df4e110.png)

**Comment by ParticleCore** [comment]
Thanks, I was able to confirm it on my end too.

**Comment by ParticleCore** [comment]
@Nallat Can you press `Ctrl + Shift + R` in that page and see if the arrow button is still over the player?

**Comment by Nallat** [comment]
@ParticleCore The bug is gone! Did you change anything? I close the issue

**Comment by ParticleCore** [comment]
No need to close, I'll do it once I push the new update with the extension versions as well. I updated the CSS file, which was re-downloaded once you pressed the shortcut to empty page cache allowing you to confirm the fix, thanks for that.

**Comment by NallatRebord** [comment]
@ParticleCore I still have this problem on the latest version of the Chrome extension
![2018-02-04_16-43-07](https://user-images.githubusercontent.com/36114925/35779284-c09aa8a2-09ca-11e8-9c5e-e27a9938f741.png)

**Comment by ParticleCore** [comment]
@NallatRebord I know, the fix did not go through with 0.0.3 due to a bug with the compiler (same one that caused the version number to not increase), the fix will be shipped with the next version, sorry for this.
