### ISSUE TITLE
Iridium Firefox and Chrome extensions are now live

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#322]
It is with great relief that I announce the release of the Firefox and Chrome extension versions.  
The links for these are available here: https://github.com/ParticleCore/Iridium/wiki/Download

[As I said before](https://github.com/ParticleCore/Iridium/issues/223), these versions do not have the crypto currency mining option for donation for the reasons previously stated and that should be the only difference in features between the UserScript and Extension versions.

I would like to thank again to everyone that has been helping and contributing to the development of Iridium.

The future plans are focused on adding more features (there are a few that I'd like to bring from YT+ again) as well as fix any bugs that appear.

**Comment by Antony256** [comment]
Mining is still mentioned in the welcome popup and might scare some users off.

**Comment by ParticleCore** [comment]
@Antony256 It is also saying that it is only available on the UserScript version: 

https://github.com/ParticleCore/Iridium/blob/42943f29fa69f2751754b6daf0701f16c9fff52f/i18n/en_US.json#L43

I chose to leave the message in the extension versions as well so that anyone transitioning from and to UserScript version is always informed of this.

If users are put off because of the miner mention then even better because if users are not experience enough to understand what it is and how it works, I'd rather they play it safe, even though the extension versions don't have it included.

**Comment by webfischi** [comment]
There is no direct way of changing languages. I still have to copy paste the script.

**Comment by ParticleCore** [comment]
@webfischi If you change the language on YouTube and Iridium has it available on the repository (https://github.com/ParticleCore/Iridium/tree/master/i18n) then the language will be downloaded automatically.

**Comment by webfischi** [comment]
Well, it didn't work for me, I just manually copied the german translation into Iridium. The language of the country is automatically detected by Google so I normally don't have to change the language of the site.

**Comment by ParticleCore** [comment]
@webfischi If you enabled [`Use modified locale`](https://github.com/ParticleCore/Iridium/wiki/Features#iridium_custom_language) then the locale will never change because that is meant to use your own version, made by you locally. This option is to prevent your custom language from being lost via update.

**Comment by adeep** [comment]
I updated userscript to v0.0.3 but there is no monero mining setting in donate page. Did you remove it both extension and script for this update or is it bug?
![screenshot_2](https://user-images.githubusercontent.com/374042/35782784-5c853faa-0a0e-11e8-97cc-ce5732e94253.jpg)

**Comment by ParticleCore** [comment]
@adeep I just noticed the same, definitely a bug, will fix that with the next update.

**Comment by ParticleCore** [comment]
@adeep Version 0.0.4 should now show the monero donation option correctly in the userscript version, thanks for bringing it up to my attention.

**Comment by uminin** [comment]
I removed a video accidentally
Where can I find it?

**Comment by ParticleCore** [comment]
@uminin You can find in the blacklist in the iridium settings: https://github.com/ParticleCore/Iridium/wiki/Features#enable_blacklist

**Comment by aacunningham** [comment]
Is this new extension at feature parity with the older Particle? Just curious before I make the switch

**Comment by ParticleCore** [comment]
@aacunningham Not all, but planning to implement most of the ones that are left.
