### ISSUE TITLE
Iridium and musixmatch

### ISSUE THREAD

**Issue by Jose76Tron** [ParticleCore/Iridium#329]
If you have iridium installed and musixmatch too youtube bugs a lot, videos dont autoplay and i cant see the comments or anything else, only the video musixmatch = https://chrome.google.com/webstore/detail/musixmatch-lyrics-for-you/gfenjblodoldnbiddmggcbkcapiolbig

**Comment by ParticleCore** [comment]
Both extensions make deep changes to the YouTube page, if they don't work together then they are not compatible with each other and should not be used at the same time.
