### ISSUE TITLE
download doc lacks instruction to navigate to Extensions [very minor documentation bug]

### ISSUE THREAD

**Issue by BlueberryFoxtrot** [ParticleCore/Iridium#333]
In this section: 
https://github.com/ParticleCore/Iridium/wiki/Download#firefox---how-to-install-add-on-from-github
after the instruction to "Open Firefox and enter about:addons in the url bar", you may wish to add that users may optionally have to click on Extensions in the left hand side column as well, because depending on what they last did with Firefox, it is also possible that they will not be on Extensions by default upon entering about:addons.

**Comment by ParticleCore** [comment]
Thanks for the heads up, the behavior has changed since last time the guide was created, certainly needs that step.
