### ISSUE TITLE
Question about youtube thumbnail

### ISSUE THREAD

**Issue by GeekinaCave** [ParticleCore/Iridium#342]
Hi, i used Iridium since was a script; but recently now it's a Firefox plugin i noticed something: the thumbnail before have a bar to show the point were you leave the video, but now there's no bar, just a box show "viewed" when you see the full video. how can turn it back?

**Comment by ParticleCore** [comment]
This has nothing to do with Iridium, that's a watch time feature from YouTube itself which disappears when you finished watching the video.  
If you want help with that feature the google forums are the appropriate place for that.

**Comment by GeekinaCave** [comment]
OK, thanks.
