### ISSUE TITLE
Can't close "quick controls"

### ISSUE THREAD

**Issue by fireattack** [ParticleCore/Iridium#344]
In the [help](https://github.com/ParticleCore/Iridium/wiki/Features#player_quick_controls), it says 

>This section is located above the video description and is **closed by default**

But as far as I find, not only it's not closed by default, I can't even find a way to close it.

IIRC this description indeed is the behavior of old YouTube Plus, where you can close/fold it; not anymore I guess.

Maybe we just need to upload the help page to match the behavior of Iridium.

**Comment by ParticleCore** [comment]
You are correct, that section was meant to behave like the previous version, but final implementation showed this toggling to be unnecessary. I've updated the description to match the current behavior.
