### ISSUE TITLE
When autoplay is enabled and "Video keeps playing when changing pages" is disabled, switching video will show a "thumbnail" view briefly

### ISSUE THREAD

**Issue by fireattack** [ParticleCore/Iridium#346]
Browser Name: Firefox and Chrome

Browser Version: 58 and 65

Steps to reproduce:

1. Enable "Play videos automatically"
2. Disable "Video keeps playing when changing pages"

Now, play any video first. Then, click any video in the right side menu to switch.

When the video is changing, it will briefly show the thumbnail view of the *current* video, which makes it feel less smooth and slightly annoying.

This GIF show the problem better:

![heh3](https://user-images.githubusercontent.com/4130991/36290978-076af950-128e-11e8-83f2-1364019dca25.gif)

**Comment by graycatgrayhat** [comment]
I would bet this is related to #347

**Comment by ParticleCore** [comment]
I can confirm this is happening, will see what I can do to fix it.

**Comment by fireattack** [comment]
@ParticleCore this fix seems to cause some side effect. 

Now, (with these two settings), if I switch to say, a playlist or main page, the video will continue to play (like when "Video keeps playing when changing pages" is enabled) but worse, since they're invisible now.

**Comment by ParticleCore** [comment]
@fireattack I see, so the problem is fix in between video pages, but now if you switch from a playing video page to a non-video page (like home page) the video stays playing in the background.

Will see what I can do to fix that one as well.

**Comment by windowlicker79** [comment]
I am also seeing this, although I have autoplay disabled.
When I click the Youtube logo to go back to my subscriptions the video audio continues to play in the background. 
Firefox 58.0.2
Running script on TamperMonkey 4.5.5660

**Comment by ParticleCore** [comment]
Interestingly enough I found out that this is in fact a YouTube bug and not related to Iridium. This can be confirmed with Iridium disabled, turning off "autoplay" in the video player and repeating the steps described in this issue.

**Comment by fireattack** [comment]
I assume you mean what @windowlicker79 said, right? 

I can't seem to reproduce it, at least not in a new browser profile (without logging in). Also, he said "When I click the Youtube logo to go back to my subscriptions", but the logo goes to front page, not subscription.

**Comment by windowlicker79** [comment]
@fireattack
I have the "make YouTube logo link to subscriptions" option activated.

**Comment by ParticleCore** [comment]
@fireattack No, I was referring to your steps.  
By disabling Iridium and turning off "autoplay" in the YouTube native video player, changing videos while one is playing does cause the thumbnail to also show momentarily exactly like in your example.  
Tested on clean profile today with nothing installed, not even Iridium.

**Comment by fireattack** [comment]
OK, I see lots of confusions here. I'd like to clarify so we are on the same page.

1. The "auto play" I mentioned in step is the feature of Iridium, called "Play videos automatically", i.e. when you open a video link, it plays immediately instead of asking you to click the thumbnail to play (YouTube does this by default). I'm *not* talking about the "autoplay" feature of the YouTube, which used to be called "auto next" or something, that means to autoplay the next video when the current video is finished. Totally irrelevant feature. 

2. In my step, I said to turn ON "autoplay" ("Play videos automatically"), not OFF. 

3. Even with your new steps (disable Iridium totally, turned off *YouTube's* autoplay), I still can't reproduce the "bug“ (cause the thumbnail to also show momentarily):

![heh3](https://user-images.githubusercontent.com/4130991/36357409-54fef87e-14c3-11e8-867b-69a9ccbd8697.gif)

**Comment by fireattack** [comment]
I'm also sorry for the confusion, since it seems to be caused by my ambiguous term of "auto play".

Anyway, what I want is just YouTube's default behavior: 

1. When you open a video link, it auto plays;
2. When you exit the video page, it doesn't play any more.
3. But when I switch between videos, it shouldn't have that "thumbnail to also show momentarily".

Any I should also stress that **it has been fixed** since https://github.com/ParticleCore/Iridium/commit/2530666688baf813238e6e29542a143aab9945a6. So I have no issues now.  I don't think it (my initial problem) is a YouTube bug, though.

**Comment by ParticleCore** [comment]
@fireattack There was no confusion, I understood it perfectly and it is definitely better after the fix, I was just adding that I found out that this problem was also happening without Iridium being active, thus confirming that the issue was not related to the extension.

This could very well have been a momentary thing, a botched YouTube update, since it began stopping the videos when changing them without hiding the player (thus showing the thumbnail). In your new example I can see it is no longer doing that, but on my end it was.

Let's not forget that YouTube is constantly changing and that means that one user might have a problem caused by YouTube itself, but others don't have it yet or will never have it. The page you are receiving might be a version that is completely different than the one I am receiving, even though they are visually identical.

**Comment by fireattack** [comment]
Ah, thanks for clearing it up. So you we indeed are doing the same steps, just different results. 

Again thanks for the hard work!
