### ISSUE TITLE
Disabling video autoplay stopped working (again) (again)

### ISSUE THREAD

**Issue by Zero-ELEC** [ParticleCore/Iridium#347]
Tamper Monkey 4.5, Google Chrome 64, can't find cause for this on my end.
#253 #311

**Comment by graycatgrayhat** [comment]
Just posted the same then closed it.

Firefox 58.0.2
Iridium 0.0.7, Both extension and script version.

**Comment by Zero-ELEC** [comment]
Replicated on Firefox 58.0.2, webextension, issue began within the last hour or so.

**Comment by kjm16** [comment]
Tampermonkey 4.5.5660
Firefox 58.0.2 
Iridium is not doing it's job for me either suddenly.

**Comment by ParticleCore** [comment]
Can confirm, will see what YouTube changed again that caused this to stop working.

**Comment by ParticleCore** [comment]
I am considering dropping the userscript version so that I have considerably more freedom to preemptively account for these constant changes YouTube does, something that is currently not feasible with the userscript version, as well as other limitations associated with the userscript version.

**Comment by graycatgrayhat** [comment]
It's nice to have it as an option for situations where their is no extension.. But I don't use the script myself as I find they can load slower on older systems.
