### ISSUE TITLE
Many features doesn't work - Firefox

### ISSUE THREAD

**Issue by michaldybczak** [ParticleCore/Iridium#349]
I switched from YT Plus to Iridium to support new layout, however, I have problems with the extension. Basically what I like the most is to open a pop-up window with a video, however, there are no icons to do that. It's easier to point what works:

- Changing icon (red to black)
- on one computer video in a corner when scrolling shows up, on other not so it works partially
- there is Iridium icon in the browser panel
- on one computer there is Iridium icon on YT, on the not - so this work also only partially

Since there are so many features I can't test them all but... I don't see anything besides things mentioned above and the feature I wanted most - video pop-up windows are not present despite that those features are turned on.

I'm not sure am I missing something? On YT Plus I got a row of icons with various features, here all is gone and I'm not sure how to use this plugin.

In both cases system: Manjaro.

EDIT: In case of second system/browser that some features don't work, Iridium has installed automatically through FF sync and there is no pop-up with the agreement that I allow it to modify YT page so maybe that's the reason YT page on the second system is void of any Iridium features.

**Comment by ParticleCore** [comment]
Please follow the instructions for opening a new issue as requested: https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by michaldybczak** [comment]
I have read it and my topic should be fine, It's in English. I cannot single out issues because the whole plugin seems to be bugged and I can't point out one specific bug. My guess is, something is generally off and that is the issue mentioned here.

Also, please read my edit in the first post where I added some extra explaining that may point to the reason why some things don't work on the second system.

I realize that such a thread is hard to work out and I don't expect miracles but maybe I missed something and there might be some easy solution? It's worth to ask. On the second thought, I can open two separate threads:
a) pop-up window doesn't work in all cases
b) YT site is not changed at all (not icons or any trace of Iridium).
If you insist, I can do that.

**Comment by ParticleCore** [comment]
You might have read it but clearly you are not willing to follow it and without those instructions followed I am unable to provide any support.

Unless you choose to follow the instructions I can't help and this issue will be closed for that duration.
