### ISSUE TITLE
Pop-up window doesn't work - there are no function icons under the video

### ISSUE THREAD

**Issue by michaldybczak** [ParticleCore/Iridium#350]
Firefox 58.0.1 
OS: Manjaro
Iridium 0.0.7

Like in the topic, there are no icons on under the video (looks like vanilla YT page) so I see no way how to open a pop-up window.
Restarting browser or plugin didn't help.

EDIT: Will try to check if the new layout is on tomorrow, although Iridium icon in the upper, right corner suggest that I do.

**Comment by ParticleCore** [comment]
Follow the instructions as requested for the 3rd time:

>- Make sure that you are using the new YouTube Material layout. If you aren't then enable it and try again: https://www.youtube.com/new

>  - This extension is built just for the new layout, it will not work with the classic layout.

https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by michaldybczak** [comment]
On first computer new layout was turned on. Restarting computer helped and now Iridium works. No idea what was that about. Sorry for bothering.

**Comment by ParticleCore** [comment]
No problem, I am glad that you got it working in the end!
