### ISSUE TITLE
Clicking back from a video leaves a mini player under the YT menu top left

### ISSUE THREAD

**Issue by mr-bo-jangles** [ParticleCore/Iridium#354]
I click through to any video, which automatically full screens in my config. I then click the browser's back button and I get a mini youtube player stuck top left under the menu. I also am no longer able to scroll up and down the page

Image showing issue
![image](https://user-images.githubusercontent.com/291570/36403242-9abaa3ea-15db-11e8-8616-97c08aedc6fb.png)

**Comment by ParticleCore** [comment]
I can confirm the same happening on my end, will try to fix it as soon as I can.

**Comment by mr-bo-jangles** [comment]
No worries, it's easy to fix with a page reload
