### ISSUE TITLE
Firefox: Volume at full when tab first loads

### ISSUE THREAD

**Issue by MrSmite** [ParticleCore/Iridium#356]
Firefox: 52.6.0 ESR
OS: Win 7 Pro
CPU: Core i5 7500
RAM 8 GB
Iridium: Userscript (plugin not available for this FF version)

When you first open a tab the volume is at 100% until the player resizes itself. The strange thing is it happens twice, once for each method of opening a tab: right-click and "open in new tab" and direct click.

After you open a video and the player resizes, the volume is properly set to the remembered position. The problem is the video begins playing before either of these two steps and it is extremely loud. Also note that once this issue happens (per opening method), it does not happen for subsequent videos for that session. When you close and reopen Firefox it starts again.

**Comment by ParticleCore** [comment]
Perfectly normal since Iridium is currently only setting the volume after it receives the player API, which is delayed on purpose by YouTube themselves. I understand how this can be very annoying and I will try to see if this can be improved in the future, but for now it will stay as it is.

**Comment by MrSmite** [comment]
Out of curiosity, why does it work for subsequet tabs (in same FF session) if it's a delayed API issue?

I am not clearing cookies so I would expect that if the player itself isn't remembering the volume level then Iridium would still suffer the delay and set it to full on every video.

**Comment by ParticleCore** [comment]
Because once it sets the volume for the first time it also saves a session storage value that YouTube picks up immediately, which is always gone whenever you restart your browser due to the browser settings you have set.
