### ISSUE TITLE
Settings cannot be saved in Maxthon

### ISSUE THREAD

**Issue by kliop00023** [ParticleCore/Iridium#357]
All settings get a reset once you close the pop-up setting page tab.
Running in userscript with the newest version of Maxthon.

A "404 Not Found" error displays in a short instant on the tab description while opening the setting page; yet the page can be properly opened.

**Comment by kliop00023** [comment]
Also, I hope that settings can be exported in a zip file and can be restored using a file instead of codes.

**Comment by ParticleCore** [comment]
Read the instructions before opening a new issue as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
