### ISSUE TITLE
Channel collections or grouping?

### ISSUE THREAD

**Issue by graycatgrayhat** [ParticleCore/Iridium#359]
Recently I found extension for Firefox and Chrome that implements a collections feature back in to YouTube.  [Youtube Subscription(Collection) Manager ](https://addons.mozilla.org/en-US/firefox/addon/youtube-subscription-groups/)

Though functional it is rough and the overall UX is under whelming, but something has to be said for it working at all.

I was wondering what the Devs behind Iridium think of collections in general.  And if it something that might make its way in the Iridium at some point?  I prefer more of all in one solutions, I normally only run one extension that effects YouTube to keep the site stable.

I wouldn't want to discredit the original extensions or its author Dmitry Nabok in anyway for his work.

**Comment by ParticleCore** [comment]
Most feature requests sound interesting and would be nice to implement them, but the YouTube nature of constantly changing results in a high maintenance for this extension, meaning that only a few features end up being implemented if they are very useful for me.
