### ISSUE TITLE
Resize floating player

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#360]
Split from original request #108

**Comment by adeep** [comment]
And when you adding that option, could you add "Back to top" button on floating video?

**Comment by ParticleCore** [comment]
@adeep Yes I will.

**Comment by Piter432** [comment]
And when the video player itself (not floating one) will be resizeable like in YouTube+?

**Comment by Piter432** [comment]
@ParticleCore: And when the video player itself (not floating one) will be resizeable like in YouTube+?

**Comment by exadeci** [comment]
The documentation states that you can resize the pop-up player but I can only move it, where is the resize handle?

https://github.com/ParticleCore/Iridium/wiki/Features#popup_player

**Comment by ParticleCore** [comment]
@exadeci The Iridium pop up player does not show if YouTube's default is showing. You are probably getting YouTube's native player which is not resizable.

**Comment by exadeci** [comment]
@ParticleCore I'm pretty sure I got the right one:
![Screen Shot 2019-06-28 at 9 55 45 am](https://user-images.githubusercontent.com/1394130/60316344-77371000-99ad-11e9-95eb-e30b672eb8e7.png)

**Comment by ParticleCore** [comment]
@exadeci I apologize, I have that feature because it was being developed on my side and haven't released it yet. I've updated the wiki accordingly to avoid misleading other users in the future.
