### ISSUE TITLE
Add more options to control ads outside video page

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#361]
Includes #81

**Comment by tgp1994** [comment]
Hi PC,

In 2017 I opened the above (closed) issue to address the giant banner ads on YouTube's homepage. I'd like to keep supporting my YT'ers by viewing ads on their channels thanks to the option you have, so carte-blanch adblocking on youtube isn't an option for me. Do you know if you'd be able to revisit this issue?

Thanks!

**Comment by ParticleCore** [comment]
This ended up being implemented in #888
