### ISSUE TITLE
Restore on floating player when not on video page make video dissapear but it keeps playing

### ISSUE THREAD

**Issue by matjojo** [ParticleCore/Iridium#363]
Browser Name: Firefox

  Browser Version: 58.0.2 (64-bit)

  Operating System: Windows 10

  Software Type: Addon

  Software Version: Don't know how to see, firefox store reports as newest.

  Problem Description: Restore on floating player when not on video page make video dissapear but it keeps playing

  Steps to reproduce: open a video, scroll down to make it float, go to the subscribtions page, and then press restore. It does not stop the video, but does make it dissapear.

  Additional details: I am using firefox quantum, it shouldnt make any difference according to mozilla, but maybe you think it does

**Comment by ParticleCore** [comment]
Happening to me as well, will try to fix it soon
