### ISSUE TITLE
Iridium >Facebook comments bugs 

### ISSUE THREAD

**Issue by Floppyboy** [ParticleCore/Iridium#365]
Hello !
On Chrome (64.0.3282.186 (64 bits)), the option "hide comments of videos" makes my Facebook bugs : I can not enter text in the comments section and menus (messenger, notifications) load to infinity... Disabling the Iridium extension automatically corrects this problem :/
Good Work !

Floppy

Browser Name: Chrome 64.0.3282.186 (64 bits)
OS: Windows 10

**Comment by Tigoreetur** [comment]
1. Iridium works only with youtube.
2. It doesn't happen to me. 
3. Not enough steps to reproduce

**Comment by Floppyboy** [comment]
Maybe because of previews of Youtube videos on Facebook ?
Sorry for the disturbance, i'm not a english speaker and a noob in developpement !

**Comment by ParticleCore** [comment]
No, Iridium will not work for anything outside YouTube domain. That includes any embedded videos. It only runs inside YouTube pages and nowhere else.

**Comment by Floppyboy** [comment]
Okay ! So, i don't understand why :/
I'll follow my research !
Thanks again.

**Comment by ParticleCore** [comment]
Closing this for now.
