### ISSUE TITLE
Keyboard Shortcuts for Buttons below the player

### ISSUE THREAD

**Issue by shonay** [ParticleCore/Iridium#366]
Hi,
This is not an "issue", just wanted to find out if its at all possible to add a feature whereby there are keyboard shortcuts to activate some of the buttons that you place below the video? For example, the Full-Browser View, Thumbnail Pictures, etc.

Thanks.

**Comment by evenfrost** [comment]
@ParticleCore any update on this? Haven't succeeded in finding any info about it.

**Comment by ParticleCore** [comment]
@evenfrost Please see #673
