### ISSUE TITLE
Setting "default Youtube logo page" option to "subscriptions" no longer works.

### ISSUE THREAD

**Issue by windowlicker79** [ParticleCore/Iridium#375]
Browser Name:  Firefox

  Browser Version:  58.0.2

  Operating System: Windows 10

  Software Type: Userscript

  Software Version:  0.0.9

  Userscript Manager: Tampermonkey

  Userscript Manager Version: v4.6.5709

  Problem Description: Setting "default Youtube logo page" option to subscriptions no longer works and continues default behaviour of going to the home page.

  Steps to reproduce: Set "default Youtube logo page" option to "subscriptions" then click the Youtube logo.

**Comment by thekcool** [comment]
I have the same problem on both Chrome 64.0.3282.186 (Official Build) (64-bit), ViolentMonkey v2.8.29, and Waterfox 56.0.4.1 (64-bit), FF extension. Both using version 0.0.9.

**Comment by ParticleCore** [comment]
Same thing, YouTube change something that caused this to stop working. Will try to fix it as soon as I can.

**Comment by thekcool** [comment]
Seems like whenever YT is promoting something, like Black History Month, through the YT Logo it screws up the "Subscriptions" redirect. I've noticed it happening in previous promotions.

**Comment by shonay** [comment]
Just so you know this same issue occurs on when setting the Default Channel Tab.
