### ISSUE TITLE
Problems with age restricted videos

### ISSUE THREAD

**Issue by bnscv** [ParticleCore/Iridium#377]
Browser Name: Firefox

  Browser Version: 58.0.2

  Operating System: Windows 10 Pro

  Software Type: Extension

  Software Version: 0.0.9

  Problem Description: When I try to watch videos like this one (https://www.youtube.com/watch?v=58hpQ7QVXCQ), I just get a black screen instead. When I turn off Iridium, the video loads correctly if I'm logged, or shows a screen telling that, to watch this video I must login due to age restriction required by the author of the video.

  Steps to reproduce: Just try to load the video in question with Iridium activated.

**Comment by ParticleCore** [comment]
Can't reproduce this problem, the video plays correctly while logged in and shows the age message while not logged in.

![ss](https://user-images.githubusercontent.com/9222661/36945356-32f0841c-1f9c-11e8-96f5-25b65cf8ed1b.png)

Please follow the instructions for opening a new issue as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Glad to hear you found out the problem.

**Comment by stonecrusher** [comment]
So... no attempt to get them both compatible?
I don't know the code well enough to fix it by myself, but maybe it's just a small change?
Last info we got from the author of the other script Volkan K. is "They are not compatible".

**Comment by ParticleCore** [comment]
@stonecrusher If they are not compatible then they shouldn't be used together. If I go out of my way to try making it compatible with one extension, I'd be forced to do the same for any other that isn't compatible and that is not something I am willing to do, especially when considering the constant breaks caused by YouTube itself, I'd also had to be on the lookout for any changes pushed by the other author and any other extension alike.

Just like this is my decision, it is also his and his right as well.

**Comment by stonecrusher** [comment]
1. This is nothing you have to do, never said so.

2. > I'd be forced to do the same for any other

    How many other extensions you came across with incompatibilities? However, you're not forced to anything.

3. It's just about if someone competent has looked into it. If you see that a workaround would be necessary which are mostly not good to maintain of course it's better understandable. But sometimes it's just a small fix, making a new wrapper, using more strictly best practice or stuff like that.

4. > I'd also had to be on the lookout for any changes pushed by the other author

    Wrong. If he pushes changes which make it break it's his fault. You already made the step for compability, so it's his turn. And you don't have to look after anything, users will report if it's not working. Or did you plan to advertise with "compability to that script"?

5. Exactly the same goes for the other author. Maybe he sees something small which should be changed in Iridium which would make life easier for both.
