### ISSUE TITLE
[bug] youtube pages show no signs that iridium is enabled

### ISSUE THREAD

**Issue by mikeloeven** [ParticleCore/Iridium#379]
I am guessing that youtube may have updated or refactored their layout or made some other change that is preventing Iridium from rendering parts of the page. To the best of my knowledge the only feature that is currently working is the floating video window and most of the controls/buttons are not present such as playlist ordering and the dark theme is not applied to the page if enabled.  

Tested this with both the Firefox add on and userscript versions

**Comment by ParticleCore** [comment]
Please follow the instructions for opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by mikeloeven** [comment]
One of the troubleshooting steps says to use most recent release please be advised that on the releases page only the source code is available not everyone has the knowledge to compile it from scratch and there should be link to the actual builds on the release page

**Comment by ParticleCore** [comment]
There is no compiling; the latest release indicates the version. If you are using an extension version make sure it is the same version number as the [latest release](https://github.com/ParticleCore/Iridium/releases/latest), same for userscript version. They are all in sync.

**Comment by ParticleCore** [comment]
Closing for now, if you still have any trouble follow the instructions in my previous replies.
