### ISSUE TITLE
Contents of videos will not update

### ISSUE THREAD

**Issue by Kontorted** [ParticleCore/Iridium#38]
Open any random youtube video, go fullscreen and to the end of the video. Allow autoplay to go to a new video. When you exit the fullscreen, you will see the old video title, description e.tc, with the new video in the player.

**Comment by ParticleCore** [comment]
@Kontorted One of the troubleshooting steps indicates to test if the bug still happens with the extension disabled: 

> - Disable the extension and restart the browser.
>
>   - If the problem still persists then it is not related to the extension. It might be caused by another extension, browser setting or by the website itself

https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

Had you followed the instructions you would have confirmed that this problem still happens even with the extension disabled, which I have also found out some time ago, so this is a YouTube bug. It might help if you also report it to the YouTube team via the "Send feedback" link located on the top right menu or at the bottom of the left sidebar.

Thanks for the feedback, but please try to follow the instructions the next time.
