### ISSUE TITLE
Ads not working with adguard ?

### ISSUE THREAD

**Issue by Playzire** [ParticleCore/Iridium#381]
Hello,
I installed the plugin because of the permission to allow ads for subscribed channel, i turned it on but there is no ad on videos on channels i subscribed, maybe adguard is blocking it despite of this ?
Thanks

**Comment by ParticleCore** [comment]
Please follow the instructions for opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

And yes, AdGuard blocks ads as well, so turn it off as well during your tests.

**Comment by ParticleCore** [comment]
Closing this for now, if you still have any issues follow the instructions in my previous reply.
