### ISSUE TITLE
Nothing happens when left clicking "Number of Uploaded Videos"

### ISSUE THREAD

**Issue by thekcool** [ParticleCore/Iridium#382]
Waterfox 56.0.4.1 (64 bit) / Iridium 0.1.0
Chrome 65.0.3325.146 (Official Build) (64-bit) / Violentmonkey 2.8.29 / Iridium 0.1.0

Windows 10 Pro 1709 16299.248

Nothing happens when clicking on "Number of Uploadeed Videos". Does not redirect to uploaded videos page. However, right click, Open in New Tab/Window, opens videos page.

**Comment by TheFinalCut83** [comment]
Same issue with script/extension.
Waterfox 56.0.4.1 (64-bit) / Violentmonkey 4.6.5709 / Iridium 0.1.0
Firefox 60.0b3 (64-bit) / Violentmonkey 4.6.5709 / Iridium 0.1.0
Windows 7 Pro
Temporary fix: set default channel tab to "Videos".
