### ISSUE TITLE
Issue with keep video visible while scrolling

### ISSUE THREAD

**Issue by rayman89** [ParticleCore/Iridium#384]
On the latest version of the script on firefox beta latest version on windows when you scroll down with the option to keep the video visble after it appears if you scroll up to see the whole video you'll realize that it's width is now permanently changed to the width of the the mini floating player.

![imagen](https://user-images.githubusercontent.com/5449042/37175233-8a88389c-22de-11e8-8a25-8792f7167dd3.png)

**Comment by ParticleCore** [comment]
Can't reproduce. Please follow the instructions for opening a new issue as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by rayman89** [comment]
Sorry was an issue with an other script I just assumed wrong.
