### ISSUE TITLE
Default video quality isn't working for certain videos.

### ISSUE THREAD

**Issue by OmkAR2013** [ParticleCore/Iridium#387]
My default video quality is set to 144p or 240p, but certain videos will start as 480p or 720p. This is a new issue that popped up, dunno if anybody else noticed yet. 

example:  https://www.youtube.com/watch?v=DCrX-QEAh4w

**Comment by ParticleCore** [comment]
Please follow the instructions as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by OmkAR2013** [comment]
Browser Name: Chrome / Firefox Quantum

Browser Version: Chrome Version 64.0.3282.186 (Official Build) (64-bit) / Firefox Quantum 58.0.1 (64-bit) 

Operating System: Windows 7 64bit Ultimate Edition

Software Type: Userscript

Software Version: 0.1.0

Userscript Manager: Tampermonkey

Userscript Manager Version: 4.5 2017-12-30

Problem Description: Default video quality is set to 144p or 240p, but certain videos will start playing as 720p. 

Steps to reproduce: 
  
Video's that reproduce problem on both Chrome and Firefox using Tampermonkey:

  https://www.youtube.com/watch?v=ZDdQQB8ZzK0
  
I'll add more examples as I find them, I encountered at least 8 other videos doing it, but I can't remember them now. The above example is good though, shows what's happening. Does it in Chrome and Firefox Quantum both using Tampermonkey.
It will load as 720p, instead of 144p or 240p, and eat all my bandwidth.  I have limited bandwidth internet.
Thank you for looking into this.

**Comment by OmkAR2013** [comment]
Found a partial fix. 
Force high quality player thumbnail set to disabled seems to partially fix it. Although it still goes to 480p (better than 720p) instead of 144p or 240p as set by Default video quality.
The "Force high quality player thumbnail" seems to be connected to the issue.
