### ISSUE TITLE
Home/End keys act onto minimized video instead of page

### ISSUE THREAD

**Issue by Shine753** [ParticleCore/Iridium#390]
Browser Name: Firefox

  Browser Version: 59 x64

  Operating System: Windows 7 Home 64 bits

  Software Type: Firefox plugin

  Software Version: 0.1.0

  Problem Description: 
When viewing a Youtube video, and scrolling down with the mousewheel to read the video comments, using the Home or End key makes the mini-video rewinds to its start or going to its end, instead of bringing the page to the top or its end, as it would be without the mini-video.

  Steps to reproduce: 
See "problem Description"

  Additional details:

**Comment by ParticleCore** [comment]
Those are [YouTube shortcuts](https://github.com/ParticleCore/Iridium/wiki/YouTube-shortcuts) which will act on the video player even if it is not in focus if this option is enabled: https://github.com/ParticleCore/Iridium/wiki/Features#shortcuts_always_active

**Comment by Shine753** [comment]
This is absolutely incorrect. You even did not try to reproduce the problem.
When the page is scrolled down with the wheel, without Iridium activated, these keys do not act onto the video but act onto the page.
But even if the video is in focus, and you click onto the page content, these keys act onto the page. This is not the case when Iridium is active with the mini-video.

**Comment by ParticleCore** [comment]
I clearly said that even if the player is not in focus the shortcut keys will act on the player if you have the Iridium option (linked above) enabled.

**Comment by Shine753** [comment]
OK, but the option was not activated.... I've activated it, then deactivated it, and the problem is gone.
Maybe a writing problem...
