### ISSUE TITLE
No loop feature in Iridium

### ISSUE THREAD

**Issue by Paramirage** [ParticleCore/Iridium#399]
In previous youtube plus there is a loop feature which i use a lot in youtube music but that feature is missing in iridium. Can you add the feature in iridium ? I just created an account in github to request this feature as i am not getting any good addon for loop feature. Please consider adding this feature. I greatly need this feature.

Beside there is no option for resizing the floating video section as the default floating video size is very small in my opinion.

**Comment by ParticleCore** [comment]
Duplicate of #12
