### ISSUE TITLE
Popup player hidden on some google account

### ISSUE THREAD

**Issue by amnacog** [ParticleCore/Iridium#402]
Browser Name: Chrome
  Browser Version: 65.0.3325.181

  Operating System: OSX

  Software Type: extension

  Software Version: 0.1.1

  Problem Description: 
  ```
The player container (ytd-watch-flexy) on popup mode get a hidden prop on it,
it only occurs only on one of my accounts.
  ```
  Steps to reproduce:
    
    - Start in incognito with iridium extension enabled (enable popup videos)
    - Log in with a google account
    - Play a random video
    - Go to any pages on youtube
    - The video will keep playing but the container is not displayed

  Additional details:
    The popup works logged out and only one of my account
    Attributes on main page while playing video
  ``` 
ytd-watch-flexy hidden="" transparent-player-background_="" flexy_="" is-two-columns_="" class="style-scope ytd-page-manager" style="--ytd-watch-flexy-width-ratio:1; --ytd-watch-flexy-height-ratio:0.5625; --yt-watch-flexy-secondary-column-extra-padding:50px; --ytd-watch-flexy-space-below-player:171px;" theater-requested_="" theater="" video-id="ChOhcHD8fBA"
  ```

**Comment by ParticleCore** [comment]
Please follow the troubleshooting steps first as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Amnacog** [comment]
Well, I followed every steps.

I even tried on firefox, same behavior...

**Comment by ParticleCore** [comment]
Do you think yours might be related to #394?

Also YouTube has begun testing their own floating player feature: https://www.androidpolice.com/2018/03/22/youtubes-miniplayer-bar-test-lets-keep-watching-video-read-comments/

It is possible that both are having a conflict. To confirm this try using YouTube in your Google account without Iridium running. See if it shows the mini player like in the linked article.

**Comment by Amnacog** [comment]
I think I'm not part of this a/b testing :)

Also, looking deeper into the desktop_polymer.js this function when triggered by page change is responsible for the player being hidden:

```
:66521 setActivePage_: function(container) {
            if (container != this.currentPage_) {
                var oldContainer = this.currentPage_;
                oldContainer && (oldContainer.hidden = true,
                oldContainer.active = false,
                oldContainer.removeAttribute("role"),
                I("kevlar_page_manager_player_stop") && this.stopOldPlayerOnPageSwitch_(oldContainer, container));
                this.currentPage_ = container;
                oldContainer && this.fire("yt-page-type-changed", {
                    oldPageType: oldContainer.is,
                    newPageType: container.is
                });
                container.hidden = false;
                this.attachPage_(container);
                container.active = true;
                container.setAttribute("role", "main");
                oldContainer && this.setPageOffsetForNavigation(container, 0)
            }
        }
```

**Comment by ParticleCore** [comment]
Ah, I think I understand now what you mean:

Open video in pop-up mode
Navigate to a different page while the pop-up mode is still running
Close the pop-up
Video starts playing in main page in the background.

This is an issue that I was able to reproduce, is this correct?

**Comment by Amnacog** [comment]
I just play a video in normal mode then navigate to another page, the video will keep playing in background. I also can return to the video by pressing back on the browser.

**Comment by Amnacog** [comment]
sure https://youtu.be/DK82Wvb770w

**Comment by ParticleCore** [comment]
Definitely a different YouTube version than mine, I still haven't received that update. I can tell that by the upload icon at the top, it is now a recording camera instead of an up arrow. I will have to wait until I get that YouTube change for me to be able to fix, but I have no doubt after this video that this bug needs fixing.

Thanks for the help, I'll have to wait until I get it before I am able to fix it, can't do much more until then.

**Comment by rEnr3n** [comment]
@ParticleCore For the new version, you can try another browser or a US VPN perhaps. https://greasyfork.org/en/forum/discussion/35504/x

**Comment by ParticleCore** [comment]
@rEnr3n That's not it, I already have the new material layout, otherwise I would have never been able to develop Iridium, it is just a variation of the new layout that I don't have. YouTube is known to do the same version with different features very often called A/B testing, that means @Amnacog has something that is causing issues with the player that I don't have, despite both of us having the new material layout.

**Comment by rEnr3n** [comment]
@ParticleCore That's what I meant. I did have that new variation where there is the camera icon instead of the up arrow.

**Comment by ParticleCore** [comment]
Thanks for the help, but I managed to get the new upload icon a few hours ago via his incognito mode suggestion, still the problem was not showing up. It must be something else different that I haven't gotten yet, which means that I will have to wait until I get it or he doesn't have it any more.

**Comment by wyterabitt** [comment]
I am getting a similar issue suddenly started, but very slightly different. 

If I scroll down on a video playing, no floating player appears it is like it is just not working. But if I then click the youtube logo (for example), the floating player appears in the corner as normal and the video continues while I browse through the main page. 

If I then click restore in the floating player, it goes back to the video and the floating player stops working again.

I wasn't sure if I should post a new issue, it seems very like this issue but reversed (assuming the floating player is actually working for the OP while on the video to start with). 
I get the same issue using the userscript I normally use and the extension (I disabled the userscript when testing the extension). Same issue on a fresh Firefox (59.0.2) profile as well.

**Comment by ParticleCore** [comment]
@wyterabitt Unrelated to this one. It is a temporary patch to prevent conflict with YouTube's new mini player, which is not working 100%. Next update should improve it for the moment until #412 decision is made.

**Comment by ParticleCore** [comment]
Just like with https://github.com/ParticleCore/Iridium/issues/460#issuecomment-405109816 the implemented fix is not guaranteed to work, so I just hope it does when the next update is released.
