### ISSUE TITLE
YouTube theme changed again – Iridium broken

### ISSUE THREAD

**Issue by Atulin** [ParticleCore/Iridium#403]
Youtube started doing their usual "let's change how everything looks at least once a quarter", and due to that – Iridium machine 🅱️roke.

As did the dark theme, since I don't seem to be able to enable it now either.

**Comment by ParticleCore** [comment]
Everything is working well on my end, please follow the troubleshooting guide as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by githubuser88** [comment]
расширение Iridium 0.1.1 хорошо работает с новой темой на Ютуб. Возможно другие расширения добавляющие значки в страницу могут немного портить дизайн.
 Iridium 0.1.1 fine work for new Youtube theme. But is extensions adds button in page - it can broken page

**Comment by Atulin** [comment]
It's... Weird. The YouTube look turned back to the current, flat one again.
Might be YouTube rolling out changes selectively and rolling them back? I don't know.

So far the problem doesn't exist anymore, so the issue can be considered solved and closed.

**Comment by ParticleCore** [comment]
YouTube probably restored the classic layout and then moved to the new layout again. Iridium is absolutely not compatible with the classic layout.

**Comment by Atulin** [comment]
It seems YT rolled out the new/old layout again, in my case:
![image](https://user-images.githubusercontent.com/11233299/38628904-d7dd42ba-3db2-11e8-9370-cd57ca593a83.png)
![image](https://user-images.githubusercontent.com/11233299/38628940-edf62b66-3db2-11e8-896a-b59d6df0d677.png)

Went back to the current layout after visiting youtube.com/new, so the issue can still be marked as resolved/invalid.
Just thought you should know about the possibility of YouTube potentially rolling out some changes to the layout, since it seems they're A/B testing again.
