### ISSUE TITLE
[Question] How do I run the script?

### ISSUE THREAD

**Issue by NovaViper** [ParticleCore/Iridium#41]
Hey, I'd like to test out the plugin.. but I'm not sure how to run it. How would I run this script on Vivaldi/Chrome?

**Comment by ParticleCore** [comment]
To run any userscript you need a userscript manager extension. For Chrome there is [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo).

Once you have your userscript installed all that is left to do is head to the download section and click on the preferred userscript links, which in this case is just one for now: https://github.com/ParticleCore/Iridium/wiki/Download

After that is done your userscript manager should detect the userscript and ask if you want to install it or not.

**Comment by NovaViper** [comment]
Ah ok! Thanks for the tip. Though.. I do feel like there should be a note on that somewhere on the download page (in case another doesn't know either)
