### ISSUE TITLE
"Video stays always visible while scrolling" not working since 0.1.2

### ISSUE THREAD

**Issue by d4k0** [ParticleCore/Iridium#415]
**Browser Name:** Firefox

**Browser Version:** 59.0.2

**Operating System:** Windows 10

**Software Type:** Add-on

**Software Version:** 0.1.2

**Problem Description:** "Video stays always visible while scrolling" doesn't work anymore since the update to 0.1.2. When scrolling down, the video player stays at its position. Another user on the Firefox add-ons site also reported this. I also tested this with a portable version of Firefox and a fresh profile with only Iridium 0.1.2 installed, but I got the same result.

**Steps to reproduce:**

1. Go to a video and start it.

2. Scroll down.

3. The video player isn't following.

**Comment by bahhax404** [comment]
Same here, it stopped after updating Firefox to 59.0.2

**Comment by ParticleCore** [comment]
Temporary patch until decision in #412 is achieved. Unfortunately some users already have the new YouTube mini player but it isn't active, I'll fix this with the next update.
