### ISSUE TITLE
Blacklist is not working after clearing it

### ISSUE THREAD

**Issue by AL3x3y0** [ParticleCore/Iridium#420]
1. Add some channels to blacklist right after installing script
2. Clear blacklist
3. Try to add channels to blacklist via "block" button on videos/channels again
4. You can't
5. But you can import old blacklist

And even before clearing I got error when clicking "block":
![image](https://user-images.githubusercontent.com/29476322/38405697-36565596-3982-11e8-86d4-cee5d7590ba9.png)
But this error is not interfere adding channel to blacklist before clearing it.

Only settings reset helps.

And why in default settings there is "home" in blacklist setting? Not "false" or "true"?
![image](https://user-images.githubusercontent.com/29476322/38406042-45d07e1e-3984-11e8-9874-29472e9f7a11.png)
After changing blacklist to disabled and again to enabled this line becomes to "true".

Iridium v0.1.2 from [github](https://github.com/ParticleCore/Iridium/raw/master/src/Userscript/Iridium.user.js)
Violentmonkey v2.9.0
Google Chrome 65.0.3325.181 64bit

**Comment by ParticleCore** [comment]
There is no bug support for ViolentMonkey, please try again with the supported userscript managers Greasemonkey or Tampermonkey: 

https://github.com/ParticleCore/Iridium/blob/master/README.md

**Comment by AL3x3y0** [comment]
Ok. Same problem with Tampermonkey 4.5.

**Comment by Answer-Man** [comment]
After blacklisting one or more channels, using the filter "Upload date" becomes impossible if it triggers the display of a blacklisted channel.
![](https://i.imgur.com/Oa6N6q2.png)

**Comment by duracotton** [comment]
I discovered the following:
1. Go to trends, blacklist some channel
2. Open Iridium settings, click "edit" of blacklist: it's empty
3. Sometimes the channel is added. But then click "export" and then just click on "close". The channel disappeared from the list.

Installed from Firefox AMO store (v. 0.1.3).

**Comment by ParticleCore** [comment]
Got it to happen to me, finally, will see what is going on. Sorry for the delay, this one took some time to replicate on my end.
