### ISSUE TITLE
Not work on firefox

### ISSUE THREAD

**Issue by wahuka** [ParticleCore/Iridium#426]
since today the iridium configuration icon in firefox 59.0.2 (64-bit) has disappeared

**Comment by ParticleCore** [comment]
Please follow the instructions before opening a new issue as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by shogunreaper** [comment]
doesnt work for me either on firefox 52 esr.

turning off the script causes the video to play instantly, but with it on it just sits there loading indefinitely.

**Comment by ParticleCore** [comment]
Closing for now, if you are still having trouble please follow the instructions in my previous reply.
