### ISSUE TITLE
pop-up player resize breaks it.

### ISSUE THREAD

**Issue by mr-fionn** [ParticleCore/Iridium#428]
Browser Name: Firefox

 Browser Version: 59.0.2 (64-bit)

  Operating System: Windows 10

  Software Type: Extension 

  Software Version: 0.1.4

  Problem Description: when you do the pop-up player and then try to resize that window. It breaks the hole player to only show half off it.  But only happens when you do the player bigger. Not smaller

  Steps to reproduce: Just press the pop-up icon and try resize the window. 

![screenshot-2018-4-20 tech talk 158 - we say farewell coconutmnky - youtube](https://user-images.githubusercontent.com/19495533/39046187-9e7f7b02-4495-11e8-9ded-dd16f416b56d.png)

**Comment by ParticleCore** [comment]
Can't reproduce this bug, please follow the troubleshooting instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by wyterabitt** [comment]
I was just about to post that I couldn't reproduce using extension or userscript either, Firefox 59.0.2 on Windows 7 (recent downgrade due to unrelated problems). 

Your comment popped up as I came back to the page, thought I would let you know anyway.

**Comment by ParticleCore** [comment]
Glad to hear that you find out the issue and just to clarify, Iridium is not compatible with that extension, so issues are assured to show up due to conflicts like this one.
