### ISSUE TITLE
New Youtube layout overrides Iridum, plays ads

### ISSUE THREAD

**Issue by Tharn** [ParticleCore/Iridium#429]
Browser: Firefox 59.0.2 x64
Operating System: Windows 8.1 x64
Software Type: Userscript
Software Version: v0.1.4
Userscript Manager: Violentmonkey
Userscript Manager Version: 2.9.3

Problem Description: 

Ever since Youtube changed a couple of days ago (it started with the display of 'blank' icons and fields for text and images that have not yet been loaded) Iridium is no longer able to intercept autoplay and remove ads. Autoplay may be a speed issue; the ads are probably not - they also play throughout the video.

The icons below the player sometimes show up, and sometimes they don't.

Steps to reproduce: 

Open a link to a Youtube video. This happens both if the link starts the browser, and if the browser has already been started and all extensions had time to load.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Tharn** [comment]
Went through the process & fixed up the description.

**Comment by ParticleCore** [comment]
As explained in the instructions, there is no support provided for browsers that are not Firefox or Chrome and I also cannot reproduce the issues you report with the recent YouTube placeholder layout update.
