### ISSUE TITLE
Settings Menu

### ISSUE THREAD

**Issue by stctn** [ParticleCore/Iridium#43]
Hello,

Is there a settings menu? How can I reach it?

I'm using Tampermonkey.

**Comment by ParticleCore** [comment]
Hello. Yes, there is a settings menu. You can either go directly to it via this link: https://www.youtube.com/iridium-settings

Or you can click on the triangle icon located on the top right of the YouTube page:

![ss](https://user-images.githubusercontent.com/9222661/27563475-61f82f62-5ac1-11e7-87fd-1f1a05bbe5f1.png)

**Comment by stctn** [comment]
The link is working, but the triangle icon is not there on my browser. You might want to look into that.

**Comment by ParticleCore** [comment]
If there is a problem please open a new issue after following the report instructions: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

Additionally make sure that you are using the new YouTube Material layout, this extension is being developed just for that, it does not work on the classic layout.

**Comment by Keith94** [comment]
Is it worth mentioning how to opt into the material layout? E.g. this page: https://www.youtube.com/new

**Comment by stctn** [comment]
Yeah, I wasn't using the material layout. I switched to Particle for the time being.

Thank you for your responses.
