### ISSUE TITLE
It seems to be normal in the morning, but it will not work at noon.

### ISSUE THREAD

**Issue by Yamazaki-wu** [ParticleCore/Iridium#431]
Google translate
The pop-up window is gone and tampermonkey shows that the script is working, but U2B's entire page looks like it wasn't running Iridium.
chrome: 65.0.3325.181
Iridium: 0.1.4

**Comment by ParticleCore** [comment]
Follow the instructions for reporting an issue as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Yamazaki-wu** [comment]
It's very strange that using the same version of chrome + tampermonkey + Iridium at home is normal!
When I go to work tomorrow, I'll see if this is the case. How to report BUG, I also go to see thank you!
