### ISSUE TITLE
Iridium's quick control bar is broken for custom DPIs

### ISSUE THREAD

**Issue by Answer-Man** [ParticleCore/Iridium#433]
I have a 14" 1080p laptop that is calibrated at 150% DPI (from Window's settings).
I've noticed that with the recent updates, iridium's quick control bar was broken (only in the userscript version). The only way I could come up with to fix this was to put the zoom level at 90% in Firefox.
This is what it actually looks like: ![img](https://i.imgur.com/kgjLWWz.png)
Side note: the extension doesn't have this issue.

**Comment by ParticleCore** [comment]
There is no available horizontal space and the buttons start piling up to compensate. An alternative would be to provide an overflow button, but that's something that I do not find worth doing, it would require keeping track of the available space and collapse the icons accordingly.
