### ISSUE TITLE
coin miner blocks by antivirus

### ISSUE THREAD

**Issue by kliop00023** [ParticleCore/Iridium#434]
please split it from the main js or add some rule or contact Avira.

**Comment by ParticleCore** [comment]
The miner is not part of the Iridium source code and never will: 

https://github.com/ParticleCore/Iridium/blob/1fe1540112ac8fe89febb16d571dc2ee02b0ddfb/src/Userscript/Iridium.user.js#L4875-L4878

Also this is covered in the wiki: https://github.com/ParticleCore/Iridium/wiki/Features#miner

**Comment by Classy-Cube** [comment]
Had this happen to me just now.
