### ISSUE TITLE
long delay when you press the mouse and keyboard buttons

### ISSUE THREAD

**Issue by KOT040188** [ParticleCore/Iridium#439]
I use opera 52. when I watch enough long clips in the current tab, mouse and keyboard presses are triggered with a long delay. The longer the time since the tab was loaded, the longer the delay after clicking the mouse or keyboard. This happens only if the movie starts to load in the player and even on a pause. When the delay becomes very large, I have to reload the tab.

**Comment by ParticleCore** [comment]
There is no support for browsers that are not Firefox or Chrome: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
