### ISSUE TITLE
Black list not working

### ISSUE THREAD

**Issue by Crossik9** [ParticleCore/Iridium#445]
Black list not working at all.
Manjaro 4.14
Firerfox 59.0.2
Iridium 0.1.4

**Comment by Bluscream** [comment]
Possible duplicate of #420 :gras:

**Comment by ParticleCore** [comment]
There is no support for other browsers that are not Firefox or Chrome: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Please follow the instructions for reporting a problem as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closing this for now, if you still have any issues please follow the instructions in my previous reply.
