### ISSUE TITLE
video stops to load if one seeks to much with the arrow keys

### ISSUE THREAD

**Issue by DioBrando141** [ParticleCore/Iridium#449]
Browser Name: Chrome

  Browser Version: 66.0.3359.170 

  Operating System: Windows 10

  Software Type: Userscript and extension

  Software Version: v0.1.4

  Userscript Manager: Violentmonkey

  Userscript Version: v2.9.4

  Problem Description: if i seek with the arrow keys too much, the video stops to load and buffers forever, necessitating a refresh of the page. happens with the extension or script.

  Steps to reproduce: seek on any video.

  Additional details: something similar happens without the script or extension, but it quickly buffers again.

**Comment by ParticleCore** [comment]
I cannot reproduce with the extension version. I tried tapping and pressing constantly the arrow keys as well as the 10s skip ahead shortcuts, the video never stalls.

Please provide better steps to reproduce this problem.

**Comment by DioBrando141** [comment]
discovered what the problem was, which i should've tested sooner. it was a youtube extension called gif it. probably some specific problem with Iridium, but not your fault. my bad for not testing every extension that interacted with the site.
