### ISSUE TITLE
[Feature Request] Volume OSD

### ISSUE THREAD

**Issue by tympapost** [ParticleCore/Iridium#45]
If more people are interested, you can add this to your todo list.
An OSD appearing **while** you are changing the volume levels with your mouse wheel. It could be a simple number in a corner of the video, or maybe if you have the time in the future, be something like the screenshot below.

![](http://springfiles.com/sites/default/files/images/spring/lua-scripts/screen00129.png)

**Comment by ParticleCore** [comment]
The feature was set up to display the default player volume slider when using the mouse wheel to provide visual feedback to the user, adding another volume slider is not something that I am interested in adding.
