### ISSUE TITLE
Use of period and comma buttons to control the video frame by fame

### ISSUE THREAD

**Issue by sudhanvaah** [ParticleCore/Iridium#453]

**Comment by ParticleCore** [comment]
This is already native in the YouTube player itself: https://github.com/ParticleCore/Iridium/wiki/YouTube-shortcuts

**Comment by sudhanvaah** [comment]
On the YouTube website, the period and comma buttons can be used to control frame by frame, but it doesn't seem to work with Iridium installed. Any suggestions as to what I can try?

**Comment by ParticleCore** [comment]
I literally just linked to a list where you can read the following:

Keys `QWERTY`|`AZERTY`|Function
:--|:-:|:--
`,` || Skip one frame backwards **(Video must be paused)**
`.` |`;`| Skip one frame forward **(Video must be paused)**

Yet you clearly did not bother to read anything.

**Comment by sudhanvaah** [comment]
I know these shortcuts, and I _did_ open your link. Only reason I commented was because these aren't working for me.
