### ISSUE TITLE
Iridium works incorrectly when i login to youtube.

### ISSUE THREAD

**Issue by kotenok2000** [ParticleCore/Iridium#460]
Browser Name: Firefox

  Browser Version:  61.0b6

  Operating System: Windows 10 build 17134.48

  Software Type: Addon

  Software Version: 0.1.4

  Userscript Manager: 

  Userscript Version: 

  Problem Description: When i use Iridium while logged in to youtube the quick controls do not work. 
 Playlist control also does not work

  Steps to reproduce: 
[bandicam 2018-05-20 22-31-04-814.zip](https://github.com/ParticleCore/Iridium/files/2020634/bandicam.2018-05-20.22-31-04-814.zip)

  Additional details: 
It happens on freshly installed firefox.

**Comment by ParticleCore** [comment]
The video cannot be extracted due to an unknown error and please do not zip files, they might be used to pack malware. Upload it online.

I cannot find any issues with the quick controls following the scenario you detailed. Try with the userscript version to see if the problem is also present with that version.

**Comment by kotenok2000** [comment]
I tested userscript version. The problem is present.
i reuploaded video. 
[bandicam 2018-05-20 22-31-04-814.avi.txt](https://github.com/ParticleCore/Iridium/files/2020800/bandicam.2018-05-20.22-31-04-814.avi.txt)

**Comment by kotenok2000** [comment]
remove .txt

**Comment by ParticleCore** [comment]
Can you open the console while logged in? Press `F12` or `Ctrl + Shift + C` and send me a sreenshot.

**Comment by ParticleCore** [comment]
I cannot fix this until I get it too since there is nothing I can use to troubleshoot. I was hoping the console would show any issue, but the only issue there is unrelated to the rest.

**Comment by RedCometTyson** [comment]
i ran with a similar problem with chrome 
![iridium1](https://user-images.githubusercontent.com/39931277/40947860-64b31acc-683b-11e8-9702-d5a823264fc0.PNG)
logged off buttons show up and work
![iridium2](https://user-images.githubusercontent.com/39931277/40947861-64d843e2-683b-11e8-8a29-9b5190740d45.PNG)
video stll plays in a mini window
![iridium3](https://user-images.githubusercontent.com/39931277/40947862-64fe2dbe-683b-11e8-868f-023d5a5a1868.PNG)
logged in buttons don't show up and dont work, also the mini player plays in a invisible window
![iridium4](https://user-images.githubusercontent.com/39931277/40947863-6522671a-683b-11e8-8b6d-c8a8aa5ab9a6.PNG)
capture of the console
![iridium5](https://user-images.githubusercontent.com/39931277/40947864-6545e21c-683b-11e8-8529-272d9fae25d4.PNG)

i tried in another account and it works perfectly

**Comment by yoannf** [comment]
Same issue here: most of the functions of Iridium are gone when I login with one specific account. The buttons do not appear, neither does the mini player (but it does still work somehow, as I'm still hearing the sound of the previous video when I browse YouTube).

<img width="1118" alt="capture d ecran 2018-06-05 a 14 02 01" src="https://user-images.githubusercontent.com/19262498/40974821-193752b4-68c9-11e8-89ad-50df430aafd7.png">

<img width="749" alt="capture d ecran 2018-06-05 a 14 01 54" src="https://user-images.githubusercontent.com/19262498/40974832-1ed42008-68c9-11e8-873b-9a46db60b09f.png">

Everything works properly right when I log off, or switch to another account. You can see the buttons for screenshot, fullscreen etc. are all back. 

<img width="1158" alt="capture d ecran 2018-06-05 a 14 03 20" src="https://user-images.githubusercontent.com/19262498/40974873-44daab8c-68c9-11e8-95cf-99aa22115446.png">

<img width="749" alt="capture d ecran 2018-06-05 a 14 03 36" src="https://user-images.githubusercontent.com/19262498/40974904-6a1314c0-68c9-11e8-924f-63e78dc3ced3.png">

The console seems to not be of much help. I'm on Chrome 67.0.3396.62 for macOS and I use the userscript version of Iridium with Tampermonkey. Everything is up-to-date.

What information may I provide to help you diagnose this?

**Comment by ParticleCore** [comment]
There is nothing else for now that you guys can do to help more than you've already did, it is a matter of time until I get hit with whichever YouTube version you have so that I may be finally able to fix it.

**Comment by LPFchan** [comment]
i have been experiencing the same thing, rendering the entire plugin useless.
moreover, the "video keeps playing when changing pages" feature still works and i have no control of stopping the video, which made me delete the extension altogether in the end.

**Comment by OkanEsen** [comment]
I too have this issue, that the quick controls aren't showing up, so I decided to debug the issue via the UserScript.

The issue is in line https://github.com/ParticleCore/Iridium/blob/master/src/Userscript/Iridium.user.js#L3249, precisely this condition: `document.querySelector("ytd-watch:not([hidden]))` which returns null, because there is no node `ytd-watch`. In my case there is this new (?) node `ytd-watch-flexy`, which seems to replace the _old_ node.

My suggestion would be to change the condition to: `document.querySelector("ytd-watch:not([hidden]), ytd-watch-flexy:not([hidden])")` which would work for both versions.

**Comment by ParticleCore** [comment]
Thanks for the detailed help, I'll include it in the next update. The CSS also needs to be covered with these changes.

**Comment by ParticleCore** [comment]
I've implemented the fix suggested by @OkanEsen and will be available with the next update. I am afraid that I was never able to test it since I never gotten the problem all these days, so this is a hopeful fix.
