### ISSUE TITLE
Channel video count and video published date not working on first page load

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#462]
YouTube recently changed the way pages load for the first time with deferred placeholders, causing information fetch to fail.

**Comment by Paramirage** [comment]
Bug still exists and don't work even after multiple reload.

**Comment by Paramirage** [comment]
Notify me about the issue. I keep watching on this issue. Some video works
but they 1-2 videos in total 10 vids.

**Comment by ParticleCore** [comment]
@Paramirage Pinging as requested

**Comment by eduzappa18** [comment]
looks like when the page load for the first time, the video count link adds a extra "/videos" at the end, on firefox only.
Image:

![videos](https://user-images.githubusercontent.com/11097763/41209004-560953a0-6cf6-11e8-9a17-de756dc363e4.png)

**Comment by ParticleCore** [comment]
@eduzappa18 That's not happening on my end. Pease open a new issue with your details after following the instructions: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
