### ISSUE TITLE
Channel page url without "/user" does not load Iridium

### ISSUE THREAD

**Issue by wyterabitt** [ParticleCore/Iridium#466]
This is reasonably low priority I think, but it seems like a bug.

If you load a channel page using just the username of the channel, without /user first, Iridium does not load.

Go to any channel such as https://www.youtube.com/user/ScreenRant/ and Iridium will load correctly. Going to https://www.youtube.com/ScreenRant/ loads the channel as normal but without Iridium. 

I tried using both Userscript and Add-on

Firefox 60.0.1
Windows 7
Iridium 0.1.4

**Comment by Keith94** [comment]
Can confirm.

**Comment by ParticleCore** [comment]
Oh man, this will be a tricky one to fix. YouTube allows both channel name redirects and their own pages with the same path level, ie: www.youtube.com/create_channel/

**Comment by ParticleCore** [comment]
I have no choice for this one, I have to go with the blacklist method and list all the pages Iridium shouldn't run since there is no way to distinguish channel pages from YouTube option pages just from the Url alone.
