### ISSUE TITLE
"Hide end screen cards on mouse hover" seems broken

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Iridium#467]
Browser Name: Firefox

  Browser Version: 62.0a1

  Operating System: Windows 10

  Software Type: Userscript

  Software Version: 0.1.4

  Userscript Manager: Greasemonkey

  Userscript Version: 4.4.0

  Problem Description: "Hide end screen cards on mouse hover" broken; cards always visible

  Steps to reproduce:
1. Enable "Hide end screen cards on mouse hover"
1. Play any video until the end (click cancel if autoplay screen appears)

**Comment by ParticleCore** [comment]
Working fin here.

![ss](https://user-images.githubusercontent.com/9222661/40574873-f253299a-60c9-11e8-87bd-fb4900b1e6e9.gif)


Can you try with the AMO WebExtension version or the Userscript with the Tampermonkey? This problem might be caused by of Greasemonkey.

**Comment by ParticleCore** [comment]
Exactly, those are not the same as endscreen cards, they are suggested videos. I assume then that the feature is working as expected, if not then let me know.
