### ISSUE TITLE
Iridium sometimes fails to load in background tabs

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Iridium#468]
Browser Name: Firefox

  Browser Version: 62.0a1

  Operating System: Windows 10

  Software Type: Userscript

  Software Version: 0.1.4

  Userscript Manager: Greasemonkey

  Userscript Version: 4.4.0

  Problem Description: Iridium doesn't load in certain tabs when opening several background tabs

  Steps to reproduce:
1. Search any youtube video through google
1. Open video link in new background tab multiple times

One of the tabs may not load Iridium correctly, like below:

![2018-05-25_21-09-22](https://user-images.githubusercontent.com/5490615/40572391-5e8dcda0-6060-11e8-8894-89524ac22fe6.gif)

**Comment by ParticleCore** [comment]
Can you try with the WebExtension version in the AMO store instead? Greasemonkey has been known to be problematic since its migration to WebExtension and this might be caused by it.

**Comment by Keith94** [comment]
It seems to work better with the WebExtension version; I haven't been any able to reproduce it yet.

Now, is there something specific we can report to Greasemonkey for bug fixing?

**Comment by ParticleCore** [comment]
From the last few times I used it with GM it was taking too long to insert the userscript into the pages, which results in the behavior you described. I'd say that this issue is a good example of what should be reported to the Greasemonkey developer.
