### ISSUE TITLE
save changes select subtitles other language ?

### ISSUE THREAD

**Issue by jojojololo** [ParticleCore/Iridium#473]
Tell me please, iridium can save changes select subtitles other language ?

**Comment by ParticleCore** [comment]
I don't understand the question, can you try to be more clear?

**Comment by jojojololo** [comment]
1) open  youtube 
2) click: settings\ subtitles/CC \ auto translate\ russian
3) closed youtube 
my select dont save...

**Comment by ParticleCore** [comment]
Iridium does not have that feature, you can see the available features listed here: https://github.com/ParticleCore/Iridium/wiki/Features

**Comment by jojojololo** [comment]
this function will do in future versions?
