### ISSUE TITLE
Iridium's elements appear broken after disabling add-on

### ISSUE THREAD

**Issue by tp78903** [ParticleCore/Iridium#474]
Browser Name: Firefox

  Browser Version: 62

  Operating System: Windows 10

  Software Type: Add-on

  Software Version: 0.1.6

  Problem Description: Iridium elements are visible on page in broken state

  Steps to reproduce: Visit youtube.com video page. Then disable Iridium from Add-ons Manager

  Additional details: 
![firefox_2018-06-10_17-51-47](https://user-images.githubusercontent.com/32758295/41208344-544275a2-6cd7-11e8-9128-fb25348ba6e4.png)

**Comment by ParticleCore** [comment]
That's how Firefox handles it, you have to refresh the page after you disable your add-ons.
