### ISSUE TITLE
video count link adds a extra "/videos" at the end on first page load

### ISSUE THREAD

**Issue by eduzappa18** [ParticleCore/Iridium#479]
Browser Name: Firefox
Browser Version: 60.0.2 (64-bit)
Operating System: Windows 10
Software Type: Userscript
Userscript Manager: Tampermonkey 4.6.5757
Userscript Version: 0.1.6

Problem Description: 
Steps to reproduce:  When the page load for the first time or opening a video in a new tab, the video count link adds a extra "/videos" at the end, on firefox only. like in the image below.

Additional details:  Tested in a fresh new firefox profile, only Tampermonkey and Iridium userscript installed (default settings).  

![41209004-560953a0-6cf6-11e8-9a17-de756dc363e4](https://user-images.githubusercontent.com/11097763/41331316-7cf3ee74-6ea6-11e8-80f6-d0c9d046646c.png)

**Comment by eduzappa18** [comment]
Apparently the error is in the line 1669

https://github.com/ParticleCore/Iridium/blob/6d1c7e9d8d29fde4a7100c236cdc5efa48df8fdf/src/Userscript/Iridium.user.js#L1669

i replaced this
```js
channel_url = "/channel/" + channel_id + "/videos";
``` 
whit this
```js
channel_url = "/channel/" + channel_id;
``` 
and it seems to fix the issue in firefox without affecting chrome
@ParticleCore can you take a look to this please?

**Comment by ParticleCore** [comment]
Finally got it to happen to me!
