### ISSUE TITLE
Comments not showing

### ISSUE THREAD

**Issue by SirLagsalot83** [ParticleCore/Iridium#483]
Comments are not showing up anymore after clicking the highlighted text. It gives me an option to click it again but it leads to a world of emptiness.

**Comment by ParticleCore** [comment]
The comments are showing correctly on my end, please follow the troubleshooting guide as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by SirLagsalot83** [comment]
After fully refreshing my browser this was not an issue anymore.
I am sorry for the false alarm.

**Comment by ParticleCore** [comment]
It's ok, there are problems that are actually user dependent (see #460) for some time, so until the guide is followed we don't know what it can be.

**Comment by SirLagsalot83** [comment]
As I've said before. I do not understand this black magic you do. It is a
complete mystery to me and I only see the results of your mighty spells.
And when it fails I will tell you, even when I am wrong I will let you know
that something broke. It might not be your spell... But ONE SPELL broke.
Perhaps your spell is part of it.
