### ISSUE TITLE
Bug? Youtube Iridium settings page 404 not found; Tampermonkey Safari

### ISSUE THREAD

**Issue by TheUnderstated013** [ParticleCore/Iridium#485]
Browser Name: Safari

Browser Version: 11.1.1 (13605.2.8)

Operating System: MacOS High Sierra 10.13.5 (17F77)

Software Type: Userscript

Userscript Version: 0.1.6

Userscript Manager: Tampermonkey

Manager Version: 4.6.5757

Issue: Iridium settings page is unavailable using "https://www.youtube.com/iridium-settings". Icon shortcut on Youtube is also missing from the top bar. Similar issue was noted in the end (last comment) of [this](https://github.com/ParticleCore/Iridium/issues/324) thread. I have tried with all other add-ons disabled, no change. Suggestions? 

As that previous thread mentioned, iridium isn't really meant for Safari right now far as I'm aware. No issues on same machine on Firefox with Firefox extension (not userscript). 

<img width="1435" alt="screen shot 2018-06-19 at 14 02 05" src="https://user-images.githubusercontent.com/40403442/41615798-39b37ab6-73ca-11e8-84ca-7cdedb5453e0.png">

**Comment by ParticleCore** [comment]
Please read the instructions for opening a new issue, support is only provided for Firefox and Chrome: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Luminaii** [comment]
I got it working by commenting out the lines 5601, 5602, 5734 and 5735. Probably broke something but everything I want form the add-on seems to be working.

**Comment by BitGrub** [comment]
> I got it working by commenting out the lines 5601, 5602, 5734 and 5735. Probably broke something but everything I want form the add-on seems to be working. The lines 5601 and 5734 throw a unhandled promise rejection in Safari

Hey, could you help me figure out which lines I have to comment out in the current version? Or how to downgrade mine to whatever version you had when you found this workaround?

**Comment by ParticleCore** [comment]
If users wish to extend support for other browsers please do it so on their own fork instead of here.
