### ISSUE TITLE
French mispelling

### ISSUE THREAD

**Issue by Kimaul37** [ParticleCore/Iridium#486]
Congratulations for your awesome work !!
I noticed that, in French language, the description of the full screen browser button is not spelled correctly.
It is written "Navigateur en pleinE écran" and the capital E should not be here.
![capture](https://user-images.githubusercontent.com/28737149/41616536-7d767012-73fe-11e8-8487-786808aa9092.PNG)

**Comment by ParticleCore** [comment]
Thanks for bringing this up to my attention, unfortunately the locales are contributions from the community and unless I know the language well enough I choose not to change it unless absolutely necessary. If you want to you can push an updated version with the correction by following the instructions: https://github.com/ParticleCore/Iridium/wiki/Locale-instructions
