### ISSUE TITLE
Player size glitches in new background tabs

### ISSUE THREAD

**Issue by FREEZEball** [ParticleCore/Iridium#488]
Browser Name: Mozilla Firefox

Browser Version: 60.0.2 (64-bit)

Operating System: x86_64 Linux 4.17.2-1-ARCH

Software Type: Add-on

Software Version: 0.1.6

Problem Description: player size flickers between "Cinema Mode" and "Default Size" when opening YouTube video in a new tab.

Steps to reproduce: 1) open any YouTube video in a new tab (I'm using middle-click by default); 2) switch to that tab; 3) player size is set at the last used; 4) about a second later it sets itself to "Default size"; if you opened video in fullscreen, it undoes that; 5) immediately after that player sets itself to the last used size (one in step 3); 6) no more issues after that.

Additional details: When opening videos in current tab, issue is not present.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by FREEZEball** [comment]
Updated opening post.

**Comment by ParticleCore** [comment]
I'm afraid I am not able to recreate this problem, I don't have any of the problems you described. Can you upload a recording showing the behavior you described?

**Comment by RayKoopa** [comment]
I experience something similar. Not sure if it has to do with background tabs though. Happens quite rarely. I try to find a way to reproduce it and then post details.

**Comment by ParticleCore** [comment]
Closing this for now, if you still have any issues please follow the instructions in my previous reply.
