### ISSUE TITLE
Reverse playlist

### ISSUE THREAD

**Issue by miticocampo** [ParticleCore/Iridium#490]
I am using so much reverse playlist feature, but I am experiencing this problem.
When I reverse the playlist, strange numbers appears instead of the regular one, so it is also difficult to understand if the playlist is going in the right direction without missing any video.

In the second image, it is possible to see the problem with strange number.

![normal playlist view](https://user-images.githubusercontent.com/16059281/41898204-a4ee15d4-7929-11e8-8250-e0473a0806f3.png)
![reverse playlist view](https://user-images.githubusercontent.com/16059281/41898205-a50887c0-7929-11e8-9719-3e23f5aeabdb.png)

**Comment by ParticleCore** [comment]
I don't understand what you are trying to say, please be more clear.

**Comment by Zarggg** [comment]
I think he's referring to the video index: -202 and 272. It looks like he may have inserted the images in the wrong order.

**Comment by miticocampo** [comment]
Yes, I am sorry the 2 image are in the wrong order.
I expect that when I reverse the playlist the number 272 does not change.
I hove noticed that the strange number has not a specif reason, a video -202 and the following -200

**Comment by ParticleCore** [comment]
I don't know why it is causing this, but I will see if there is anything I can do to fix it.

https://www.youtube.com/watch?v=pZbD6GTXmWg&list=UUudKvbd6gvbm5UCYRk5tZKA&index=272

**Comment by thepcwiz101** [comment]
i have this bug also. Youtube's site code might not like using reverse playlists as it wasn't intended to be a feature yet by google. I have to admit this is a strange bug though.

**Comment by thepcwiz101** [comment]
In my testing i found that the reverse playlist feature is redundant in this extension. no matter what when i disable the setting the reverse playlist feature still works on any playlist including non-randomly generated ones.

**Comment by ParticleCore** [comment]
@thepcwiz101 It remains active after disabling the extension because the page was not refreshed. If you press F5 it will be gone.
