### ISSUE TITLE
Iridium redirects from home page to youtube.com/feed/subscriptions/u, which gives a 500 Internal server error

### ISSUE THREAD

**Issue by jasonTong68** [ParticleCore/Iridium#492]
Browser Name: Chrome

  Browser Version: 67.0.3396.99 (Official Build) (64-bit)

  Operating System: Windows 10 64bit

  Software Type: Add-on

  Software Version: 0.1.6

  Userscript Manager: Tampermonkey

  Userscript Version: 4.6

  Problem Description: Whenever I enter youtube.com, Iridium automatically redirects me to the Subscriptions page. However, it redirects to youtube.com/feed/subscriptions/u, with a **/u** at the end.
This returns a 500 Internal Server Error. I need to remove /u from the address to go to the subscriptions page.

  Steps to reproduce: Type "youtube.com" in the address bar and enter site. The site redirects in a second or two, to the /u page.

  Additional details: This started occurring yesterday, I have tried reinstalling Iridium, restarting Chrome. These are my Iridium settings: 

> {
>     "broadcast_id": "db7f1056-d735-4e4b-9b4b-8e33ab57916a",
>     "default_logo_page": "subscriptions",
>     "default_channel_tab": "videos",
>     "square_avatars": true,
>     "improved_logo": true,
>     "thumbnail_preview": true,
>     "thumbnail_preview_mute": false,
>     "enable_blacklist": "home",
>     "blacklist_settings": {},
>     "channel_video_count": true,
>     "channel_video_time": true,
>     "player_quality": "hd720",
>     "player_auto_play": true,
>     "channel_trailer_auto_play": false,
>     "player_annotations": false,
>     "player_subtitles": false,
>     "player_loudness": false,
>     "player_ads": false,
>     "subscribed_channel_player_ads": false,
>     "player_hfr": true,
>     "player_memorize_size": true,
>     "player_memorize_volume": true,
>     "player_quick_controls": true,
>     "player_max_res_thumbnail": true,
>     "comments_visibility": 1,
>     "shortcuts_always_active": true,
>     "player_volume_wheel": false,
>     "player_always_visible": false,
>     "player_always_playing": false,
>     "player_hide_end_screen": false,
>     "iridium_dark_mode": true,
>     "miner": false,
>     "miner_threads": 2,
>     "miner_throttle": 75,
>     "userVolume": 32,
>     "theaterMode": true,
>     "welcome_closed": true,
>     "popup_player": false,
>     "playlist_reverse_control": true,
>     "iridium_custom_language": false,
>     "fullBrowser": false,
>     "miniPlayer": {
>         "position": {
>             "X": 527.357666015625,
>             "Y": 765.4791870117188,
>             "snapRight": false,
>             "snapBottom": true
>         },
>         "size": 352
>     },
>     "playlist_reverse": false
> }

**Comment by ParticleCore** [comment]
The extension does not possess any sort of capabilities to redirect the user to any page via address bar other than the settings page. Follow the troubleshooting guide as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by jasonTong68** [comment]
Sorry, I have made a mistake. This was caused by a different extension.
