### ISSUE TITLE
Cropped viewport inside mini player

### ISSUE THREAD

**Issue by Keith94** [ParticleCore/Iridium#493]
Browser Name: Nightly

  Browser Version: 63.0a1

  Operating System: Windows 10

  Software Type: Add-on

  Software Version: 0.1.6

  Problem Description: Cropped viewport inside mini player

  Steps to reproduce: 
1. Go to a video page and play a video
2. Scroll down and click the fullscreen button on the mini player
3. Exit fullscreen and observe mini player

**Comment by ParticleCore** [comment]
Can't replicate, the page is scrolled to the top to reset the video to its initial position when exiting fullscreen while in mini player mode. Please follow the troubleshooting guide to rule out the possibility of a conflict caused by something outside the control of Iridium: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Keith94** [comment]
Hmm, page is not scrolled for me. I can reproduce in a clean Nightly profile with Iridium (add-on) only.

![2018-06-29_18-27-27](https://user-images.githubusercontent.com/5490615/42120089-289413aa-7bca-11e8-934f-ea565088f229.gif)

**Comment by ParticleCore** [comment]
I am not able to recreate this problem, can you try on Chrome to check whether this is restricted to Firefox only?

**Comment by ParticleCore** [comment]
The pc you're using, is it powerful or not really that good? I can't think of any reason for this to be happening.

**Comment by Keith94** [comment]
I mean... it's just a [laptop](https://www.amazon.com/Acer-Aspire-i3-8130U-Memory-E5-576-392H/dp/B079TGL2BZ/). Anyways, I'll close this.

**Comment by ParticleCore** [comment]
I was asking so that I would test it on a weaker PC. If I can replicate it then I can try to find a way to fix it, otherwise it's a wild goose chase for anyone involved.
