### ISSUE TITLE
Video takes forever to load after skipping over the buffered portion

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#495]
Iridium version 0.1.6 (AMO version)
User-Agent: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0`
Locale: Turkish
OS: `Linux hostname 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Reproducibility: Always
How to reproduce: As title says

**Comment by ParticleCore** [comment]
Follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
