### ISSUE TITLE
Can't disable play videos by hovering the thumbnails

### ISSUE THREAD

**Issue by thepcwiz101** [ParticleCore/Iridium#497]
I use the latest google chrome as of july 4th, 2018 on windows 10 april 2018 creators update. Despite me turning off the toggle for this feature videos still play when i hover over thumbnails on youtube. Idk if this is a bug or if google decided to just add in this feature natively.

**Comment by ParticleCore** [comment]
YouTube has their own 3s video preview thumbnails. Iridium offers the ability to watch the entire video instead, it does not disable the native YouTube previews.

**Comment by thepcwiz101** [comment]
oh ok
