### ISSUE TITLE
YouTube Plus is not compatible with the YouTube beta Material Layout

### ISSUE THREAD

**Issue by siIverfox** [ParticleCore/Iridium#500]
Don't know if this is just a recurring error every chrome update or if I've downloaded something wrong, but despite having Iridium from the chrome webstore I'm getting this popup again:
![image](https://user-images.githubusercontent.com/19816688/42421515-b8432bde-82ce-11e8-84ac-07cdf290a7ef.png)
The "new version for the layout" goes here: https://github.com/ParticleCore/Particle/issues/448

**Comment by ParticleCore** [comment]
This repository does not provide support for YouTube Plus.

**Comment by ParticleCore** [comment]
By the way, you need to disable or remove the YouTube Plus extension if you upgrade to Iridium.

**Comment by siIverfox** [comment]
Thanks, I have done but still get the message. Not sure!

**Comment by ParticleCore** [comment]
That message is only showing up because you either have YouTube Plus extension still installed or the userscript version of YouTube Plus still installed. Iridium does not show that message whatsoever.
