### ISSUE TITLE
"Always visible" mini-video player (after scroll down) doesn't resize, thus crops

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [ParticleCore/Iridium#501]
Hello!

Firefox 61.0.1 64 bits stable here, with Iridium 0.1.6.

A bug that I noticed today, but it might have been here for longer, I'm not an avid youtube user: when I scroll down and Iridium loads a mini-player in the bottom-right, the video isnt' shrunk to fit the mini-player, so I see the upper-left corner of the video only.

Screenshots: 
https://imgur.com/nah5mM5 (normal viewing, video is paused to make it easier)
https://imgur.com/pJxsmmE (after I scrolled down, it only shows the upper-left of the video in the mini player)
https://imgur.com/0VmogpB (the settings for Iridium in my Firefox.)

No big issue for me, so it's not a vibrant cry for help, I thought I'd mention it in case it's important. 
Good day everyone!

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

By the looks of it you have other add-ons for YouTube, they might be causing conflicts with Iridium, please follow the instructions to make sure whether this is or isn't a bug in Iridium.

**Comment by Keith94** [comment]
It's the same as my bug #493
