### ISSUE TITLE
Feature request: Be able to hide the "Up Next" panel on the right-hand side.

### ISSUE THREAD

**Issue by reversebreak** [ParticleCore/Iridium#504]
It's pain to glance to the right and get instantly spoiled on a movie or game.

I think this would be a simple matter of hiding the
`<div id="secondary" class="style-scope ytd-watch-flexy">`
DIV...

**Comment by Eisys** [comment]
This would be easier done with a userstyle on your end rather than be added to this addon.

**Comment by duianto** [comment]
For anyone else that's looking to hide the youtube "Up next" section, here's a user script:

```
/* the "up next" section, has two css selectors:
"secondary" when browser width >= 1017px, "up next" right of video player
"related" when browser width < 1017px, "up next" below video player */
#secondary, #related {display: none;}
```

#### System Info:
Windows 10 Version 1803
Google Chrome | 68.0.3440.106 (Official Build) (64-bit) (cohort: Stable)
Chrome Extension: Stylus 1.4.20
https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne
https://github.com/openstyles/stylus/
