### ISSUE TITLE
Blacklist 'X' does not function on Up Next, generally does not work on Search results

### ISSUE THREAD

**Issue by reversebreak** [ParticleCore/Iridium#505]
Browser Name: 
Firefox

  Browser Version: 
61.0.1 (64-bit)

  Operating System: 
Windows 7

  Software Type: 
Firefox addon from AMO

  Software Version: 
0.1.6
  
  Problem Description: 
The Blacklist 'X' does not function on Up Next, generally does not work on Search results.  It appears when the thumbnail is mouse-overed but does not do anything when clicked.
I'm not sure whether the actual blacklisting functionality is affected, or whether it's just the X button to add new stuff to the blacklist.

  Steps to reproduce: 
View any search or video page.  Mouse over the Up Next thumbnails and try and click the X.

  Additional details: 
Blacklisting does seem to work on the main Youtube homepage, though!

**Comment by ParticleCore** [comment]
Please do not join two issues into one, split them into separate issues, this was requested in the instructions before opening a new issue.

**Comment by reversebreak** [comment]
> Please do not join two issues into one, split them into separate issues, this was requested in the instructions before opening a new issue.
I'm not sure I understand what you mean - I only posted about one thing here in this issue - that the X button wasn't working right.
