### ISSUE TITLE
Sometimes after watching another video you get the same video.

### ISSUE THREAD

**Issue by 1ll3g4l** [ParticleCore/Iridium#507]
This happens quite often, however I don't know what it's causing it.

Basically, sometimes I might be watching or finish a video and click on another one, but the video doesn't switch even though the url has updated, so you end up with the same video and not the one you wanted to watch.

I am on 0.1.7

**Comment by ParticleCore** [comment]
Please follow the instructions for reporting a problem as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by 1ll3g4l** [comment]
I will try resetting the extension to default to see if I still get this problem however most of them I had already tried except making a new profile on firefox/chrome the day I posted the issue

**Comment by 1ll3g4l** [comment]
This is still happening, even worst the videos still keep playing on the background sometimes when you go back to the homepage or a new video, sometimes the video website doesn't fully load as well.

Anyway I can give you a log of some sort? I'll try and see if I can make any recording videos of it happening.

**Comment by ParticleCore** [comment]
If I cannot make it happen on my end I cannot fix the problem, which is why the instructions need to be followed as requested, all of them.

**Comment by 1ll3g4l** [comment]
@ParticleCore https://kuuv.io/i/486d57d.webm Here is a video of it happening

Just so you understand the video more, it starts when I have already clicked on another video, but shows the previous video, so than I refresh the page and it takes me to the video that it was supposed to.

**Comment by ParticleCore** [comment]
I'm sorry but that clip does not help in any way for me to understand what is going on or how to replicate it. You also haven't told me me if you followed the rest of the troubleshooting instructions as requested, specifically trying on a new profile and any other step you decided to not follow through.

**Comment by 1ll3g4l** [comment]
I followed almost all the steps except the profile one, I'll try and do that step later.

1. Click on video (doesn't seem to matter if it's from homepage or from the list of recommended of a video you were watching beforehand)
2. Click on another video
3. The first video will still be the one playing until you refresh the page

**Comment by ParticleCore** [comment]
No matter how many times I try your problem never happens to me:

![ss](https://user-images.githubusercontent.com/9222661/43369409-546aa502-935d-11e8-9714-a8e2c4d9135e.gif)

**Comment by ParticleCore** [comment]
I also don't see you clicking on any video in both of your clips, the mouse cursor is pointing nowhere over any video link.

**Comment by 1ll3g4l** [comment]
Yes, I am just pressing F5, since I have already clicked on the video.

**Comment by ParticleCore** [comment]
Closing this until it is possible to replicate the issue.
