### ISSUE TITLE
Typo in userscript

### ISSUE THREAD

**Issue by aslafy-z** [ParticleCore/Iridium#508]
I found an error in the source code when looking at the diff from the 1.7 update.

The square brackets surrounding "theater" are not closed for the ytd-watch-flexy selector.

https://github.com/ParticleCore/Iridium/blob/master/src/Userscript/Iridium.user.js#L3931
https://github.com/ParticleCore/Iridium/blob/master/src/Webextension/js/Iridium.user.js#L3931

It should look like:
```diff
- is_in_theater_mode = document.querySelector("ytd-watch[theater], ytd-watch-flexy[theater");
+ is_in_theater_mode = document.querySelector("ytd-watch[theater], ytd-watch-flexy[theater]");
```

**Comment by ParticleCore** [comment]
Thanks for letting me know, I'll push a fix for this today.
