### ISSUE TITLE
Disabled pages does not match

### ISSUE THREAD

**Issue by aslafy-z** [ParticleCore/Iridium#509]
Since last version, the function in charge of disabling the extension for some page does not work anymore.

https://github.com/ParticleCore/Iridium/blob/master/src/Webextension/js/Iridium.user.js#L5638
https://github.com/ParticleCore/Iridium/blob/master/src/Userscript/Iridium.user.js#L5638

It can be verified on this page where Iridium gets injected but it sould'nt.
https://www.youtube.com/webcam

This could be fixed by adding back the start `/` like this:
```diff
            disallowed_pages = [
-                "tv",
+                "/tv",
-                "embed",
+                "/embed",
-                "live_chat",
+                "/live_chat",
-                "account",
+                "/account",
-                "account_notifications",
+                "/account_notifications",
-                "create_channel",
+                "/create_channel",
-                "dashboard",
+                "/dashboard",
-                "upload",
+                "/upload",
-                "webcam"
+                "/webcam"
             ];
```

**Comment by ParticleCore** [comment]
Thanks for letting me know, I'll push a fix for this today.
