### ISSUE TITLE
I made an Spanish translation.

### ISSUE THREAD

**Issue by JuanCamilo27** [ParticleCore/Iridium#51]
First of all, your extension is just awesome. Thank you very much.
It looks like all the words doesn't appear translated. I think I may changed something on the code by accident, or maybe because most of the words have accents (á, é, í, ó, ú. Like in number = número). So I guess you should check it. Thanks. 😄 I did it with Notepad++, by the way.
EDIT 1: I forgot, is Spanish (Colombian) translation.

[es_CO.zip](https://github.com/ParticleCore/Iridium/files/1116580/es_CO.zip)

**Comment by ParticleCore** [comment]
Hey there, Juan, but I cannot accept locales like this, you will have to submit your locale via pull -> merge request. The most simple example I can think of is to fork this project, create the new file by yourself in the locale directory and then request for a merge to this repository. I really appreciate the help though.

**Comment by JuanCamilo27** [comment]
Oh, ok then. Sorry for not doing it right.
