### ISSUE TITLE
Coinhive Miner on a different site

### ISSUE THREAD

**Issue by mendel3** [ParticleCore/Iridium#510]
Can you make a site (a github.io page would be fine) dedicated to a coinhive miner? I was saddened that I can no longer support you in the only way I could. Maybe make a fork that has the miner, and one that doesn't?
Thanks!

**Comment by vortexP** [comment]
It is nice that you want to support the developer, but Coinhive if not efficiency at all, so it would probably better just to donate with Paypal or Patreon.

**Comment by ParticleCore** [comment]
At the moment I don't have the time to dedicate to something like this, but I'll consider it in the future. Thanks for the intention.
