### ISSUE TITLE
Support for youtube classic

### ISSUE THREAD

**Issue by killoid** [ParticleCore/Iridium#514]
is it possible to support this [addon](https://github.com/thisdotvoid/youtube-classic-extension)? i am using it mainly for [this](https://twitter.com/cpeterso/status/1021626510296285185) reason.

**Comment by PoorPocketsMcNewHold** [comment]
[Already talked about here.](https://github.com/ParticleCore/Iridium/issues/513)

**Comment by PoorPocketsMcNewHold** [comment]
[Already talked about here.](https://github.com/ParticleCore/Iridium/issues/513) If you do want support for the old interface, [Use the old script](https://github.com/ParticleCore/Particle).

**Comment by Eisys** [comment]
I've tried switching over to the new layout and hate it more every time I try. Been using 1.9.6 Youtube+ for all this time and haven't noticed any bugs so it's fine to use. It also has more features.

**Comment by ParticleCore** [comment]
Duplicate of #513
