### ISSUE TITLE
YouTube is getting ready to launch their own "watch while browsing" mode

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#517]
As of this day YouTube has already begun testing their own mini player version (read #412). While trying to fix some of the recent bugs I discovered that YouTube is also getting ready to implement their own always playing mode that should allow the video to keep playing while navigation on different YouTube pages:

![ss](https://user-images.githubusercontent.com/9222661/43293417-b0ff1bda-9129-11e8-9dd8-4ee589d7a498.png)

Taken from: https://s.ytimg.com/yts/jsbin/player-vflo6HcQb/en_US/base.js

At this point, due to the changes they are making, it is becoming harder to make these two functionalities work and for that reason I might drop the Iridium versions in the future or enhance YouTube's version if it isn't too much trouble.

This is a prior announcement in case anyone is interested in knowing any possible future changes related to these two features.

**Comment by Icarus77** [comment]
The min-player seems to be having issues with scaling the video down now, so I guess they are making progress with this..

**Comment by thepcwiz101** [comment]
![image](https://user-images.githubusercontent.com/31826503/44413364-ceb85400-a530-11e8-994c-4d9c353cabe2.png) This just appeared today on all youtube videos for me. Anyone else confirming?

**Comment by thepcwiz101** [comment]
please note i don't have any extensions enabled besides ublock origin, poper blocker, and h264ify. I did not have this last night.

**Comment by ParticleCore** [comment]
@thepcwiz101 So YouTube is finally ~~adding~~ re-adding their own pop-out player! That means it'll be one less feature I will have to maintain and that makes room for other new features to implement.

Haven't had that here yet, but I can't wait to check it out.

**Comment by thepcwiz101** [comment]
yup but i also found out that you have to be logged into a google account to have the popout player option. it might be still in the rolling out process.

**Comment by thepcwiz101** [comment]
After clearing my cookies on my browser and logging back into all my accounts i lost the pop out video feature that youtube is working on. This is pretty strange honestly i'll update if anything changes in the future.

**Comment by thepcwiz101** [comment]
![image](https://user-images.githubusercontent.com/31826503/45912038-0a209980-bde1-11e8-9e64-c36cd5120a51.png)
![image](https://user-images.githubusercontent.com/31826503/45912054-376d4780-bde1-11e8-9475-f1631ce88056.png)
youtube just got this today. It isn't very useful in its state at the moment in my opinion you cant drag the video or choose to have the mini player shown when looking at comments as it only takes you to the homepage of youtube.

**Comment by dan019** [comment]
It would be nice to have iridium give the option to disable, once youtube rolls the feature out. 

Thanks!

**Comment by Fannste94** [comment]
Add an option to disable or enable the mini player

**Comment by StellarisStudio** [comment]
I made a [fork](https://github.com/StellarisStudio/Iridium) of the userscript (only) which hide the miniplayer button on the playback control and add a new button to use the PiP function of chrome instead !! (I kept the pop up player as there is no playback control in the PiP for now !!)

Obviously it will work with chrome only !! But yeah in case someone need it!! ^^
