### ISSUE TITLE
Miniplayer only showing upper-left corner of video

### ISSUE THREAD

**Issue by leletreee** [ParticleCore/Iridium#518]
Not sure if this is a separate bug or directly related to #412 and #517, if so please delete

Chrome Version 68.0.3440.75
Windows 10 Tampermonkey v4.6

Problem: Miniplayer only showing upper-left corner of video

Screenshot ft. ancient meme for scale:
![corner only medium](https://user-images.githubusercontent.com/41779603/43310876-2818a068-91cc-11e8-8122-c0b74df79528.PNG)

**Comment by Embermaker** [comment]
Same on Firefox since yesterday. Looks like Youtube changed something again.

**Comment by Crash333** [comment]
not fixed
Iridium ver 0.19 (Chrome Web store)
I tried the userscript with Tampermonkey too, also not fixed
Chrome: Version 68.0.3440.75 (Official Build) (64-Bit)
Windows 10.5 (1803) Build 17134.165

**Comment by ParticleCore** [comment]
@Crash333 thanks for the report, I've opened #525

**Comment by Crash333** [comment]
ok, today is another day and it seems it works today... I don't know, maybe just because of the PC restart.
but no bug on my end.
Iridium v0.20 (Chrome Web store)
Chrome: Version 68.0.3440.75 (Official Build) (64-Bit)

**Comment by PoorPocketsMcNewHold** [comment]
@Crash333 Iridium pushed an hotfix for it, 15 hours ago, so this mainly should explain why.

**Comment by leletreee** [comment]
Thanks for the fix dev! Much love
