### ISSUE TITLE
Full Browser view does not display correctly

### ISSUE THREAD

**Issue by bl4ckscor3** [ParticleCore/Iridium#519]
As seen in the picture, the Full Browser view does not fill the complete area that it should. I suspect that this is caused by a change to the default player size which YouTube just implemented.

![](https://i.imgur.com/pWSrC6W.png)

Vivaldi 1.15.1147.55 (32-bit)
Iridium 0.1.8 (User script)
Tampermonkey 4.6

**Comment by LazyBoot** [comment]
Looks like a duplicate of #515

**Comment by bl4ckscor3** [comment]
Ah, I somehow missed that while skimming through the already opened issues, my bad.

**Comment by ParticleCore** [comment]
Duplicate of #515
