### ISSUE TITLE
Suggestion to include PiP functionality

### ISSUE THREAD

**Issue by falcon4fun** [ParticleCore/Iridium#520]
I suggest to include and modify new great PiP Chrome fuctionality, which can work on top of all windows.
Can be interesting option for Chrome users who wants better floating window

https://github.com/beaufortfrancois/picture-in-picture-chrome-extension
https://i.imgur.com/295ckdH.png

**Comment by ParticleCore** [comment]
It's a Chrome only experimental feature that looks promising, but until it is officially supported by Chrome and Firefox there will be no adoption.
