### ISSUE TITLE
Miniplayer always active when blocklist is big

### ISSUE THREAD

**Issue by Lapin0t** [ParticleCore/Iridium#521]
Hi, a couple days ago the miniplayer started being always activated (even when the page is scrolled to the top). The issue disappeared when resetting the settings and apparently the cause is the blocklist: mine currently has 302 items and when deleting any one item the issue seems to disappear.

It might not be related at all but i usually just block every bs that shows up on the landing page (thus big blocklist) and youtube might not like it that much because at some point it just stops trying to feed new channels to the landing page.

Env: firefox 61.0.1; linux; iridium v0.1.8 (from addons.mozilla.org)
Description: the floating player is always active and the usual player is simply black even when it's completely on-screen
Steps to reproduce: go on a youtube video page (with more than 302 blocked items)

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Lapin0t** [comment]
Actually nvm, it just got away right now, i didn't change the settings (only did in another browser profile). I still have the big blocklist so this must not be the issue. So now i don't know how to reproduce nor can i give a screenshot.
