### ISSUE TITLE
Remember Player Size does not work.

### ISSUE THREAD

**Issue by dudeedud4** [ParticleCore/Iridium#522]
As stated.. Remember Player Size is not working for me on the latest Iridium version.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closing this for now, if you still have any issues please follow the instructions in my previous reply.
