### ISSUE TITLE
Mini Player not scaling video.

### ISSUE THREAD

**Issue by Westward12** [ParticleCore/Iridium#523]
**Browser:** Chrome Version 68.0.3440.75 64-bit
**Operating System:** Windows 10 64-bit
**Software:** Iridium 0.1.8
**Userscript Manager:** Tapermonkey v4.6
**Problem Description:** The Mini player window does not scale the video to fit, It crops the upper left corner instead.
**Steps to reproduce:** Play a video in default mode, scroll until the mini player appears.
_**Additional details:**_ 
_Screenshots_ **Default**: https://i.imgur.com/Yb2Krz1.jpg **With mini player:** https://i.imgur.com/fUKVFZg.jpg **Thumbnail** https://i.imgur.com/fnjY0ft.jpg
The thumbnail image that is shown before viewing a video Does scale properly but the video still crops when played.
Mini player does not work at all in Cinema mode.

**Comment by Westward12** [comment]
Already Reported

**Comment by ParticleCore** [comment]
Duplicate of #518
