### ISSUE TITLE
Player size erratic behavior when autoplay is disabled, player always visible is enabled and page is scrolled

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#528]

**Comment by Chibicon** [comment]
Is this https://image.prntscr.com/image/nPKSXhk6QFGGYjJeck6sQg.png a different bug or the same? To fix it I have to go into theater mode and out of it.

**Comment by ParticleCore** [comment]
@Chibicon Not the same thing, but Iridium version 0.2.1 was recently released to fix that problem, if it doesn't fix it follow the instructions for opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by yungthud** [comment]
Is it related to this bug? (Same settings as mentioned; main player is black but mini-player appears instead, even at the top of the page.)
![iridium-bug-playersize](https://user-images.githubusercontent.com/7104818/45912071-d8f89700-bde9-11e8-80d1-b71dcd1218bd.png)

**Comment by ParticleCore** [comment]
@yungthud That's a different bug. Please follow the instructions and if the problem persists open a new issue for that bug: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
