### ISSUE TITLE
Request Firefox setting 

### ISSUE THREAD

**Issue by Osahashi** [ParticleCore/Iridium#532]
There is a new Firefox addon - https://addons.mozilla.org/en-US/firefox/addon/fast-youtube-load - but it does not work with your Iridium at the same time, activate "fast-youtube-load" seems to block Iridium complete at the YouTube page. 

The addon deactivate something on the YouTube page and it loads faster, I test it by myself, maybe if you have time you can check it out and can something use for Iridium as new setting.

**Comment by Daisenki** [comment]
Thanks for checking!
