### ISSUE TITLE
More intuitive YouTube shortcuts for playing speed

### ISSUE THREAD

**Issue by anishmittal2020** [ParticleCore/Iridium#535]
[YouTube shortcuts · ParticleCore/Iridium Wiki](https://github.com/ParticleCore/Iridium/wiki/YouTube-shortcuts)

I would recommend to exchange the shortcuts for play  speed with the subtitle text size. **Rationale**: People are more likely (and often) to change speed of a video than change the text size.

**Comment by ParticleCore** [comment]
Those are YouTube's native shortcuts, there are no intentions to change their standard.
