### ISSUE TITLE
Userscript does not fuction in Microsoft Edge

### ISSUE THREAD

**Issue by MatthewCash** [ParticleCore/Iridium#539]
When using the latest version of Microsoft edge, none of the Iridium versions function. Tampermonkey displays that Iridium is active on youtube.com, but nothing is working. The icon at the top bar does not appear, and the url /iridium-settings returns a 404.

**Comment by metaeatscake** [comment]
I'm on chrome and when I opened chrome up,Tampermonkey had a popup saying it updated. I shrugged it off and tried watching youtube,only to see that Iridium isn't working. The iridium icon isn't on the top bar,and the toolbar next to the like/dislike is gone too.

**Comment by MatthewCash** [comment]
@metaeatscake What update was this? I think it is an Edge thing though, because the userscript works fine on firefox.

**Comment by ParticleCore** [comment]
Support exists only for Firefox and Chrome: https://github.com/ParticleCore/Iridium/blob/master/README.md

**Comment by metaeatscake** [comment]
@MatthewCash  4.7 and yeah nevermind,iridium is showing up now.

**Comment by MatthewCash** [comment]
Welp, that sucks
