### ISSUE TITLE
Iridium Translate to PT-BR 

### ISSUE THREAD

**Issue by Ednerr** [ParticleCore/Iridium#542]
Tradução para Iridium Português Brasil / Translation for Iridium PT-BR

Download: (https://github.com/ParticleCore/Iridium/files/2284363/Iridium.Translate.txt)

Para aplicar basta entrar em:
Settings -> Ativar o "Use modified locale" -> clicar em "English (US)"
Copiar o Conteudo do Arquivo .txt e colar na caixa, depois clique em "Save"

![screenshot_91](https://user-images.githubusercontent.com/28742085/44052610-695def98-9f13-11e8-8643-57f1eddac268.png)

**Comment by ParticleCore** [comment]
Please follow the instructions for contributing to the locales: https://github.com/ParticleCore/Iridium/wiki/Locale-instructions
