### ISSUE TITLE
Player Size Not Correct

### ISSUE THREAD

**Issue by Chibicon** [ParticleCore/Iridium#545]
Browser Name: Firefox

  Browser Version: 61.0.2 (64-bit)

  Operating System: Windows 10 (64-bit)

  Software Type: Userscript

  Software Version: 0.2.1

  Userscript Manager: Tampermonkey BETA

  Userscript Version: 4.7.5826

  Problem Description: Player does not fit correctly; however, it does not happen with every video. https://image.prntscr.com/image/nPKSXhk6QFGGYjJeck6sQg.png

  Steps to reproduce: Here is one video link where it happens https://www.youtube.com/watch?v=UIEYbSdM4Xk

**Comment by thepcwiz101** [comment]
I can confirm this is a bug. A temporary workaround is simply changing the player size up and down a few times. It may be on youtube's side however but i cannot confirm this. If the dev of this extension cannot fix it i would suggest reporting it to google. Btw this occurs on google chrome so its not just a single browser that is affected.

**Comment by ParticleCore** [comment]
This is not happening to me:

![ss](https://user-images.githubusercontent.com/9222661/44231241-fb651800-a18c-11e8-81d2-3d5d28c32d92.png)

Please follow the instructions as requested before opening a new issue including all the troubleshooting steps: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ApacheThunder** [comment]
YouTube's code might have changed. I am also having issues with the layout on a video. It now looks like this:

https://i.imgur.com/NKM37x0.jpg

I changed literally nothing with my setup. This morning it was looking fine then refreshed a video I had in an open tab and that happened. I'm sure I'm alone with this. Using Firefox with the Greasemonkey script version of Iridium.

**Comment by ParticleCore** [comment]
@ApacheThunder That screenshot shows the old YouTube layout, Iridium was designed only for the new YouTube Material layout. To switch to the new layout go to https://www.youtube.com/new

**Comment by ApacheThunder** [comment]
Hmm interesting. It was working fine for the old layout. Aside from ads still showing up until I refreshed the page. Might have been why. I was using YouTube Center up until a month or two ago as they seemed to have stopped updating it for YouTube (it no longer works at all on YouTube). Anyways.....I'm not sure if I want to use the new layout. Is there a preview for it? Afraid that if I do enable it I won't be able to go back.... :(

**Comment by Chibicon** [comment]
Trust me when I say I went through everything in the bug report instructions including creating a brand new profile with nothing on it.

Tried using the Extension version and the Userscript version on a new profile with nothing on it. As @thepcwiz101 said a quick fix is to change the player size.

I can also add that this only happens if autoplay is disabled in the Iridium settings. If I enable autoplay the video is correct size.
https://image.prntscr.com/image/R3Pe8XZ-SmGM3fAEljXbMw.png

**Comment by ParticleCore** [comment]
The screenshot I took was with the autoplay disabled, still no issues. Also in both of your screenshots the player shows a button on the bottom right that does not belong to either YouTube or Iridium, so I assume that you are still using another extension at the same time which may be causing that problem.

The troubleshooting steps include disabling all extensions except Iridium to rule out any conflict between extensions. You said you already "went through everything", if that is true then I can't do anything else until it also happens to me.

**Comment by ParticleCore** [comment]
Actually there is one last thing you can try if you can do me this favor.

Open the console and enter the following:

````js
document.querySelector("ytd-watch, ytd-watch-flexy").calculatePlayerSize_;
````

And screenshot the output.

**Comment by Chibicon** [comment]
New profile, no addons except for Iridium.
https://image.prntscr.com/image/9GuiWf7xTmOm2nl2TQbToA.png

**Comment by A7M2** [comment]
I have the same problem. It only happens when "play videos automatically" option is disabled in Iridium's settings.
![2018-08-18 14_58_37-window](https://user-images.githubusercontent.com/42492926/44299081-de008d00-a2f7-11e8-9876-89d336d6eddf.jpg)

**Comment by ParticleCore** [comment]
Unless I can make it happen on my end there is no way for me to fix something if I can't find what is causing the problem.

**Comment by Lartza** [comment]
Could Iridium stop forcibly sizing the video area to 16:9 to work around this? Not sure if that would work. It seems some call to resize the player after resizing the video area is missing, since it fixes by scrolling down and up so that the video jumps between the mini player and video area.

Also to note is that play/pause works for the whole 16:9 area while the bottom controls are restricted to the wrong width.

The two scenarios where this doesn't happen for me on Chrome are without Iridium and when "Play videos automatically" is enabled, and YouTube doesn't add borders to sides of 4:3 videos without Iridium.

**Comment by ParticleCore** [comment]
@Lartza Multiple conditions require the size to be set for the player to behave correctly while Iridium is in use.

**Comment by ParticleCore** [comment]
I've been able to finally replicate this issue with a colleague's computer, however I couldn't bring with me for troubleshooting, so the fix will be applied based on a hunch and because of that might not be fixed, so I will count on who has this bug to tell if it was fixed or not once the update is public.
