### ISSUE TITLE
Autoplay issue

### ISSUE THREAD

**Issue by thepcwiz101** [ParticleCore/Iridium#547]
I tried on multiple videos and i checked my settings in iridium. I have the latest stable google chrome build as of 8/16. I did not have this issue until very recently. It's possibly on youtube's end or its a bug in iridium. I also can verify that i have the latest iridium which is 2.1

**Comment by thepcwiz101** [comment]
update: Reloading the video page solves the issue but when visiting a new video it pauses after a few seconds again.

**Comment by thepcwiz101** [comment]
Notice this happens randomly out of nowhere. Some videos act normally. If anyone else can confirm this feel free to comment and let the dev know.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by thepcwiz101** [comment]
Browser Name: Chrome Stable

  Browser Version: 68.0.3440.106 (64-bit)

  Operating System: Windows 10

  Software Type: Addon

  Software Version: 2.1

  Problem Description: Videos pause after 1 second despite having autoplay on and noticeable lag on youtube page that goes away after disabling iridium. 

  Steps to reproduce: Go to any video on youtube. 

  Additional details: When disabling iridium the issue goes away. Please note that the issue still occurs when i have only iridium enabled. I also found that iridium causes noticeable lag on the youtube web page and that too goes away after disabling the extension.

**Comment by ParticleCore** [comment]
Same setup and autoplay enabled, the videos never pause themselves:

![ss](https://user-images.githubusercontent.com/9222661/44282183-c1a61700-a249-11e8-95e2-5e8e3181a00f.gif)

**Comment by thepcwiz101** [comment]
It's possibly my computer. I have very low end specs.

**Comment by ParticleCore** [comment]
Closing this for now until there is a way to confirm the issue.

**Comment by thepcwiz101** [comment]
issue is resolved. it doesn't happen on my pc anymore.

**Comment by thepcwiz101** [comment]
no problem
