### ISSUE TITLE
[Feature] Keyboard shortcuts for quick controls

### ISSUE THREAD

**Issue by crumbl3d** [ParticleCore/Iridium#548]
I use the full browser mode often. However, when viewing a playlist you have to scroll a lot to press the button. I would like you to add a keyboard shortcut (possibly modifiable) to full browser button and possibly other quick controls extending the default YouTube's shortcuts. For example:

```
a - Autoplay
v - Full Browser (because b is mapped to Change subtitles/CC background)
s - Screen Shot
t - Thumbnails
p - Pop-up Video
```

**Comment by ParticleCore** [comment]
Duplicate of #366
