### ISSUE TITLE
Memorize player size feature is possibly redundant now.

### ISSUE THREAD

**Issue by thepcwiz101** [ParticleCore/Iridium#551]
Browser: Chrome Stable 
Browser version: 68.0.3440.106 
OS: Windows 10

Iridium type: Addon
Iridium version: 2.1

Problem: Youtube remembers my player size even with remember player size is disabled. Even if i disable iridium entirely youtube remembers my player size even after changing back and forth and reloading pages.

Reproduction steps: Make sure memorize player size is disabled in iridium, Go to a video and set it to larger or smaller player size. refresh page or goto another video. You will get the same result even if you disable iridium.

Additional details: Youtube may have introduced the memorize video size feature at some point making this feature in the addon redundant.

**Comment by ParticleCore** [comment]
YouTube does have it's own implementation, but it does not work if the user has cookies disabled.

**Comment by thepcwiz101** [comment]
oh i did not know that
