### ISSUE TITLE
Number of videos and Relative Time don't update

### ISSUE THREAD

**Issue by Liz-chan** [ParticleCore/Iridium#552]
Browser Name: Chrome

  Browser Version: 68.0.3440.106

  Operating System: Windows 10

  Software Type: Extension

  Software Version: 0.2.1

  Problem Description: When you start watching a video the relative time and number of videos is correct, but if you click to go to another video on the same page, it goes to the next video, but the relative time and number of videos stay the same. Also, when you click on the number of videos, it takes you to the channel that it was actually meant for, which is unintended and confusing.

  Steps to reproduce: Go to any YouTube video, go to another video using the sidebar with relative time and video count turned on, watch it not update. You can also click the video count to be taken to the channel that you were first on. This continues until you refresh the page.

  Additional details: I disabled almost all of my extensions and it still continued (Only extension I left open was The Great Suspender.

**Comment by ParticleCore** [comment]
Looks like it was a YouTube bug and they have fixed it today.
