### ISSUE TITLE
about particle

### ISSUE THREAD

**Issue by ubone** [ParticleCore/Iridium#553]
why was https://github.com/ParticleCore/Particle/ archived?

the old non material youtube is still available either via the url parameter `&disable_polymer=1`
or the youtube `PREF` cookie value `f6=8`

**Comment by ParticleCore** [comment]
There is no longer any support and updates being provided for the old version and the issue tracker was only allowing users to open issues that would never be resolved. There was no point in having it active any longer: https://github.com/ParticleCore/Particle/issues/680

**Comment by ubone** [comment]
would you [all who contribute] consider to reactivate it? it takes two clicks to have the old youtube

**Comment by ParticleCore** [comment]
The linked issue makes it very clear that there are absolutely no intention to continue work on the old version. There will be no reactivation outside of forks users may be willing to maintain, in which case it is no longer related to this project.
