### ISSUE TITLE
Thumbnails stopped appearing

### ISSUE THREAD

**Issue by iPaulis** [ParticleCore/Iridium#556]
Browser Name: Firefox

Browser Version: 59.0.3 (64-bit) and 61.0.2 (64-bit)

Operating System: Windows 10 (64-bit) and Linux Mint 18.3 (64-bit)

Software Type: Firefox plugin

Software Version: 0.2.1

Problem Description: I use the Iridium plugin and also a userscript by Zren (his [Github](https://github.com/Zren/ResizeYoutubePlayerToWindowSize)) called Resize YT To Window Size. Everything was working fine until about 2 weeks ago, when the thumbnails stopped showing up after loading a video with autoplay disabled. 
As Zren's script has not been updated in a long time, I was wondering if there was a change in how Iridium loads a thumbnail and if there could be a way to make the thumbnails appear again.

Steps to reproduce:
1. Have both Iridium and Resize YT To Window Size ([v118 from GreasyFork](https://greasyfork.org/en/scripts/811-resize-yt-to-window-size) and Greasemonkey v4.6) installed.
2. Disable autoplay in Iridium.
3. Load any youtube video and the thumbnail wont show up, just a black background instead.

Let me know if there is any other info I could provide.
Thank you in advance.

**Comment by ParticleCore** [comment]
If they are not working together then they are not compatible with each other and I don't intend to make it compatible.
