### ISSUE TITLE
[Feature Request] Can you Fix the 80 Item limit when displaying large playlists 

### ISSUE THREAD

**Issue by mikeloeven** [ParticleCore/Iridium#559]
Is it possible to fix the playlist display so that it is no longer limited to 80 items? YouTube basically broke very large playlists and when attempting to reverse order the playlist gets truncated due to the 80 item limit

**Comment by ParticleCore** [comment]
The feature simply reverses the order in which the playlist is played from the point it is at, it does not and will not go fetch the rest of the lists. It is a limitation of the feature.
