### ISSUE TITLE
how to access settings page like in particle extension

### ISSUE THREAD

**Issue by oct9** [ParticleCore/Iridium#56]
sorry, this isn't really an issue, but rather a question. i was just wondering if there is a way to access a settings page like in particle - when i launch youtube with extension enabled i see no button to get to settings. if there is, in fact, no traditional settings page, how would i go about changing settings via editing of the script (i'm very novice in scripting, programming, etc). anyways, thank you from the bottom of my heart for your excellent work on particle and iridium - you have made youtube tolerable once more!!!

**Comment by tympapost** [comment]
There is a button. It's near the upload button in the upper right corner of youtube.
If you are not seeing it, it's probable because you don't have the "new material design look" enabled.
![ss1](https://user-images.githubusercontent.com/6545650/28058943-121e6bc6-662b-11e7-96f9-5949cdfd5391.jpg)

**Comment by oct9** [comment]
for some reason said button does not appear even if i disable all other user scripts and extensions (including ublock origin and particle extension). i did, however, find another way to access settings via url, so at least there is a workaround. i'm currently running iridium on a standard unmodified version of chrome browser on windows 10 64 bit. thank you much for the quick response.

**Comment by oct9** [comment]
after accessing settings via url (https://www.youtube.com/iridium-settings), i changed my settings and it now seems to be working. the only problem i'm still encountering is that the dark theme setting doesn't seem to be working.

**Comment by oct9** [comment]
after accessing settings via url (https://www.youtube.com/iridium-settings), i changed my settings and it now seems to be working. the only problem i'm still encountering is that the dark theme setting doesn't seem to be working (and still no button for settings).

**Comment by ParticleCore** [comment]
As mentioned, Iridium is only for the new Material layout, it will not work with the classic YouTube layout. To access the settings page a button will be available at the right of the YouTube search bar. Alternatively you can just go there directly via this link: https://www.youtube.com/iridium-settings

**Comment by Jose76Tron** [comment]
If you dont have the new material layout go to youtube.com/new and click on enable
