### ISSUE TITLE
Features missing when signed in [Chrome]

### ISSUE THREAD

**Issue by Cattywampus-** [ParticleCore/Iridium#560]
Hello
I have just realised that I no longer have the Iridium triangle in the top right of the Youtube website and there are none of the options (full screen, screenshot of current video) on the currently playing video page and it seems that only some of the settings work (for example, the default resolution seems to work, but the 'video stays playing while scrolling' doesn't appear to be working). 

This only seems to happen while signed in and on Chrome, using both the script with Tampermonkey and the Chrome extension version.  If I sign out, it seems to work fine.  Sign in and it flops. 

Seems to work fine with Firefox.  Any thoughts?

Thanks

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closing this for now, if you are still having trouble follow the instructions in my last reply.
