### ISSUE TITLE
Iridium not wokring on Chrome and Firefox on latest Youtube version from 1st of September

### ISSUE THREAD

**Issue by Poutouyou** [ParticleCore/Iridium#561]
Youtube version was changed and Iridium is no longer working with it.
Youtube version changed the 1st of september in Europe.
I tested both chrome and firefox and I could not have Iridium working.
Had no problem before today.

**Comment by ParticleCore** [comment]
Closing this for now, if you are still having issues follow the instructions in my previous reply.
