### ISSUE TITLE
German Language File

### ISSUE THREAD

**Issue by Stopschild** [ParticleCore/Iridium#563]
Hey guys, 

as i was doing this for a friend i thought maybe someone else could need it. Have fun!

German Language Raw Paste
https://pastebin.com/QWHpCjpn

Settings Export
https://pastebin.com/mhh4LDND

**Comment by ParticleCore** [comment]
Please follow the instructions for contributing to the locales: https://github.com/ParticleCore/Iridium/wiki/Locale-instructions
