### ISSUE TITLE
Iridium not working after Youtube update

### ISSUE THREAD

**Issue by Dirk-Manderin** [ParticleCore/Iridium#564]
Browser Name: Chrome

Browser Version: 69.0.3497.81

Operating System: Windows 10 x64 1803

Software Type: Chrome extension

Software Version: 0.2.1

Problem Description: It appears that the latest change to Youtube.com has broken Iridium.  Default page, default channel, memorize player size, etc.

Steps to reproduce: Customize settings

Additional details:

**Comment by ParticleCore** [comment]
Same configuration and the extension is working correctly:

![ss](https://user-images.githubusercontent.com/9222661/45189568-2ccf8180-b229-11e8-8226-fcd4cbcb18f1.png)

Please follow all the troubleshooting steps as requested before opening the issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

**Comment by vsiegel** [comment]
I assume it does not work for me either: If I should see the five buttons to the left of thumb-up button - I do not see them. 
Version 0.2.1 in Chromium  51.0.2704.79 on Ubuntu 15.10

**Comment by ParticleCore** [comment]
Closing this for now, if you are still having trouble follow the instructions in my last reply.
