### ISSUE TITLE
Feature Request: Only show end screen cards on mouse hover

### ISSUE THREAD

**Issue by Danfun64** [ParticleCore/Iridium#567]
Sometimes end screen cards are placed where they're supposed to. Other times they play on videos without an "end screen card" template, which means it's just blocking image that I want to see. I'd like a feature which had three elements: Don't show the end screen cards when the mouse isn't hovering on a video, only show outlines when the mouse is hovering on a video but not on any of the end screen cards, and then finally show the end screen cards when the mouse is hovering over one of them...hiding/outlining them where appropriate when the mouse is moved away from them.

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Features#player_hide_end_screen
