### ISSUE TITLE
Ads on every youtube video with player_ads disabled and subscribed_channel_player_ads enable

### ISSUE THREAD

**Issue by Xoxorgne** [ParticleCore/Iridium#574]
Hi,
I would like to enable ads only for channel subscribed, it worked for a long time but since the last update i have ads on every video i play on youtube ; is it temporary, normal, just on my side, ?
Thanks !
Bests regards

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closing this for now, if you still have any issues follow the instructions in my previous reply.

**Comment by webredjo** [comment]
Firefox 64.0
Windows 10
Iridium extension add-on, version 0.2.4
Problem Description

Hi, I've followed all the instructions and even with new profile and only Iridium as extention, there is no ads on subscribed channels

Steps to reproduce: 

- Create new profile in Firefox
- Add Iridium extension
- Allow ads on subscribed channels
- Go on Youtube and connect
- Watch videos from subscribed channels
- No ads intro nether small popups
