### ISSUE TITLE
Locale doesn't work in Firefox

### ISSUE THREAD

**Issue by HanabishiRecca** [ParticleCore/Iridium#576]
Name | Value
--- | ---
**Browser Name** | Firefox Quantum
**Browser Version** | 62.0.2
**Operating System** | Windows 10
**Software Type** | addon from [store](https://addons.mozilla.org/firefox/addon/particle-iridium/)
**Software Version** | 0.2.2 (autoupdate)
**Userscript Manager** | no
**Userscript Manager Version** | no

### Problem Description
I have "ru-RU" browser locale. But extension language is english and settings page shows "English (US)".

Also on youtube pages I have noticed such error:
![screenshot_1](https://user-images.githubusercontent.com/13597663/46249505-b1d24300-c443-11e8-884b-0ac4a87c72f5.png)
(Refers to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied)

![screenshot_2](https://user-images.githubusercontent.com/13597663/46249512-de865a80-c443-11e8-9220-00c8379252a2.png)

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
The instructions contain troubleshooting steps that need to be followed as well before opening a new issue. Please follow those instructions.

**Comment by HanabishiRecca** [comment]
Of course I tried it all.

**Comment by ParticleCore** [comment]
One of the steps specify that the extension is only compatible with Firefox and Chrome vanilla, yet you're using Firefox Quantum. Have you really tried to see if the problem was still present on normal Firefox version?

**Comment by HanabishiRecca** [comment]
What is "normal" version? All latest Firefox versions (59+) called "Quantum". https://www.mozilla.org/firefox/

**Comment by ParticleCore** [comment]
No, I was not aware that they started calling it Quantum. I have tried with all the available locales and not once it fails or throws an error. Unless I can replicate the problem I will not be able to fix it if it indeed is a bug with the userscript and not something caused by something else.

Have you reset your browser with a fresh new layout and tested with only Iridium installed with its default settings to see if the problem is still happening?

**Comment by HanabishiRecca** [comment]
Yes, I've created a new profile and installed only Iridium. And now installed EN version of Firefox.
So, looks like browser language doesn't matter.

BUT youtube language setting does matter. When list tuned like this:
![screenshot_1](https://user-images.githubusercontent.com/13597663/46250310-4c854e80-c451-11e8-996c-d01c6465ad5e.png)
The error appears.

When tuned to English:
![screenshot_2](https://user-images.githubusercontent.com/13597663/46250313-72125800-c451-11e8-84da-881ee94ed49e.png)
Not appears.

**Comment by ParticleCore** [comment]
I did try it like in your first image, no error showed up.
Please list all the steps needed for me to follow in order to cause that error to show up.

**Comment by HanabishiRecca** [comment]
Nothing special. Now I made fresh Firefox installation with new clean profile. Only Iridium installed, no settings changed.
Youtube log in not required. Just opened random video and changed language to russian.
![screenshot_1](https://user-images.githubusercontent.com/13597663/46250505-6032b400-c455-11e8-8d8d-4e91566b631d.png)

**Comment by HanabishiRecca** [comment]
Script version works as intended without errors. And Iridium settings page has correct locale too.

**Comment by ParticleCore** [comment]
Ok so it is a Firefox bug, I have filed a bug report here, hope it won't take 2 years for them to fix because there is no way to work around this: https://bugzilla.mozilla.org/show_bug.cgi?id=1495243

**Comment by ParticleCore** [comment]
And thanks for being helpful, I really appreciate it, without your help I doubt I would have been able to get to the root of the problem.

**Comment by HanabishiRecca** [comment]
p.s. I have another little report. You know youtube has had an update a few days ago (with new popup player etc). Looks like they made annotations always enabled ignoring user preference. And Iridium annotation setting also can't override this behaviour.

**Comment by ParticleCore** [comment]
Haven't yet noticed any annotations showing up despite user preference. If you don't mind open a new issue for that so I can take a look at it later.

**Comment by ParticleCore** [comment]
Sounds like another bug that Firefox does not want to fix because it refuses to acknowledge it as a bug, or at least I am already expecting that to happen since that's their norm.
Will have to create yet another workaround to hopefully fix this which is sad really since it will increase the toll on performance, again. Yay Firefox.
