### ISSUE TITLE
Annotations self-enabling

### ISSUE THREAD

**Issue by HanabishiRecca** [ParticleCore/Iridium#577]
Name | Value
--- | ---
**Browser Name** | Firefox Quantum
**Browser Version** | 62.0.2
**Operating System** | Windows 10
**Software Type** | addon or userscript
**Software Version** | 0.2.2
**Userscript Manager** | Tampermonkey
**Userscript Manager Version** | 4.8.5847

### Problem Description
This problem was appeared after latest Youtube update. Annotations sometimes can be enabled by default. Reproduce rate is not 100%, reload page few times, annotations has some chance to appear.
Fast way to detect issue: when annotations enabled you can see channel icon in the bottom right corner of the video.

![screenshot_1](https://user-images.githubusercontent.com/13597663/46251018-210a6000-c461-11e8-9c0a-3e9d8afd1704.png)
![screenshot_2](https://user-images.githubusercontent.com/13597663/46251020-24055080-c461-11e8-9fa4-eba3f5239e9a.png)

**Comment by thepcwiz101** [comment]
This happens to me even without the extension installed. It is a youtube bug.

**Comment by HanabishiRecca** [comment]
@thepcwiz101, this is obvious. But the problem is Iridium annotations setting doesn't work on it.

**Comment by thepcwiz101** [comment]
Well yea.

**Comment by thepcwiz101** [comment]
Youtube fixed the annotation problems atleast on my end. I havent seen the option turn back on since yesterday.
