### ISSUE TITLE
Miniplayer out of place

### ISSUE THREAD

**Issue by Dajova** [ParticleCore/Iridium#578]
So i'm not sure how this happened, but it seems that i managed to get 2 players on top of eachother or something like it here:

![pic](https://i.imgur.com/D7xCyoj.png)

I don't have a errorlog or anything and i did try to troubleshoot it myself, but to no avail (still persist everytime i load up a new video like this).

**Comment by ParticleCore** [comment]
Duplicate of #575

**Comment by ParticleCore** [comment]
Temporary workaround for now is to either disable Iridium's always playing feature or don't use YouTube's mini-player button.
