### ISSUE TITLE
Block button have too low strata

### ISSUE THREAD

**Issue by Dajova** [ParticleCore/Iridium#581]
So i noticed that the block button (the one over thumbnails) wasn't working at al the past few days and have been trying to troubleshoot it ever since.
Noticed today that the issue came from Ratings Preview (http://ratingspreview.com/).

The problem that arises is that somehow, the blockbutton gets BELOW the strata of RatingsPreview overlay and hence am im unable to click the button without actually clicking the video itself, opening it instead of blocking it.

I'm not sure if this is a oversight or just a compatibility conflict, but maybe set the strata so its above RP, so it won't get "overclicked"?

**Comment by ParticleCore** [comment]
They aren't compatible with each other. Unless the author of that extension wishes to fix it on his end, both extensions shouldn't be used together.
