### ISSUE TITLE
change subtitles background doesn't work

### ISSUE THREAD

**Issue by nathgit** [ParticleCore/Iridium#585]
The "change subtitles background" shortcut (b) doesn't seem to do anything. Is this a known bug or am I just not understanding something? The other subtitle options work just fine. It doesn't seem to work in particle either, I just hadn't bothered to report it.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by nathgit** [comment]
I read the instructions. I have the latest version of iridium, chrome version is up to date, using material layout as well as html5 player.Iridium/tampermonkey/chrome have all been restarted numerous times. The only feature that doesn't work is the subtitles background. Everything else works. It's not a big deal but since it doesn't work I figured I'd post it here.
