### ISSUE TITLE
Preview in editor bug

### ISSUE THREAD

**Issue by toby3d** [ParticleCore/Iridium#59]
**Browser Name:** Vivaldi
**Browser Version:** 1.10.867.48 (Stable channel) (64 bit)
**Operating System:** Linux Mint XFCE 18.2 (x64_86)
**Software Type:** Userscript
**Software Version:** 0.0.2b
**Userscript Manager:** Tampermonkey
**Userscript Version:** 4.3.6
**Problem Description:** The preview in the youtube video editor does not work if Iridium is active
**Steps to reproduce:** Install and activate Iridium -> Open [editor page](https://www.youtube.com/editor) -> Add random video on timeline -> Click on preview, you must see error message

**Comment by ParticleCore** [comment]
I was able to reproduce the problem, I will have to start adding exclusion pages in which the extension should not work on to prevent normal use.

In the future please note that in the instructions it clearly indicates that support is only available for Firefox Chrome and Opera. Vivaldi is not being supported.
