### ISSUE TITLE
Update The Extension

### ISSUE THREAD

**Issue by Fannste94** [ParticleCore/Iridium#592]
Can you please update the extension

**Comment by ParticleCore** [comment]
It will be updated when I have free time. I understand that there are bugs waiting for a fix for some time now, it just hasn't been easy lately for me to find some time to work on them.

**Comment by ParticleCore** [comment]
Of course, but once I do that the extension stops being free and you'll have to pay to use it in order for the to hire developers.

**Comment by ParticleCore** [comment]
The extension is already free and open source, its code is literally made public in this same repository and you are not paying to use the extension.

Additionally cease with the new account creation to circumvent account blocking meant to stop you from spamming the repository further.
