### ISSUE TITLE
"Allow ads on videos" broken

### ISSUE THREAD

**Issue by voradortc** [ParticleCore/Iridium#601]
Browser Name: Chrome
Browser Version: 70.0.3538.77 (Official Build) (64-bit)
Operating System: Windows 10
Software Type: Extension
Software Version: 0.2.2
Userscript Manager: N/A
Userscript Manager Version: N/A
Problem Description: The "Allow ads on videos" option is now broken
Steps to reproduce: Reproduce any video and skip to the next one, even if "Allow ads on videos" is set to "disabled" an ad will play
Additional details: N/A

**Comment by redjo-bsl** [comment]
Firefox 64.0
Windows 10
Iridium extension add-on, version 0.2.4
Problem Description

Hi, I've followed all the instructions and even with new profile and only Iridium as extension, there is no ads on subscribed channels for Youtube HTML5.

Steps to reproduce:

- Create new profile in Firefox
- Add Iridium extension
- Allow ads on subscribed channels
- Go on Youtube and connect
- Watch videos from subscribed channels
- No ads intro nether small popups
