### ISSUE TITLE
Pop-out button is no longer working.

### ISSUE THREAD

**Issue by scswift** [ParticleCore/Iridium#602]
I think something changed with Youtube, as one minute the pop out player button was working in the latest Firefox beta, and the next minute it stopped working on some videos and eventually all of them. The button does nothing at the moment. It doesn't even open a window with a broken video.  I'm pretty sure no Firefox update occurred at the time which might have caused it. I rebooted and even updated Windows, and cleared my cache, and still no dice.

**Comment by Acid-Crash** [comment]
Hi.
Same here on both Firefox Release and Nightly.
Cleared cookies and tried new profile
Pop-Up button works from Homepage Search results, but fails on the video page.
When I click on it console shows the following error

```
TypeError: player_api.getUpdatedConfigurationData is not a function
popUpPlayer https://www.youtube.com/watch:586:66
startPopUpPlayer https://www.youtube.com/watch:620:33
startPopUpPlayer self-hosted:974:17 
```

**Comment by Acid-Crash** [comment]
Update.
The issue is also present in Chrome with the following error in console
```
VM43:586 Uncaught TypeError: player_api.getUpdatedConfigurationData is not a function
    at Object.popUpPlayer (<anonymous>:586:77)
    at Object.startPopUpPlayer (<anonymous>:620:38)
popUpPlayer @ VM43:586
startPopUpPlayer @ VM43:620
postMessage (async)
quickControlPopUpPlayer @ VM43:3079
quickControls @ VM43:3108

```
