### ISSUE TITLE
some settings don't stick and haven't done for several releases

### ISSUE THREAD

**Issue by crimsonstarr** [ParticleCore/Iridium#614]
please see attached screen shot, the circled settings keep resetting, i change them and they instantly go back to default the next time i launch firefox.

![settingsdontstick](https://user-images.githubusercontent.com/44604304/48209550-62016880-e36d-11e8-85bb-91c906674189.jpg)

**Comment by ParticleCore** [comment]
With the exception of the video continuous play options, the other two are working as expected. Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closing this for now, if you still have any issues follow the instructions in my previous reply.
