### ISSUE TITLE
[Feature Request] Hide premiers from sub box

### ISSUE THREAD

**Issue by WiBla** [ParticleCore/Iridium#616]
Hey there,

I would love to see a "Hide premiers" setting that, as the name suggest, would remove premiers entirely from the subscription feed. In my opinion, this new feature YouTube brought to us is useless.

I've quickly take a look at the HTML and CSS but wasn't able to find a straightforward way of hiding them, I think a bit of JS will be required.

**Comment by Eisys** [comment]
YES please.. Premier is the most idiotic feature ever.

Off topic but sort of related question;
Any particular reason why livestreams(and now the dumb premiers(even after it turns into a normal video)) don't show the watched tag in the subs page? The tag works in the channel's videos page but not in the subs page where I need it most.
Would there be a way to change this?

I rely on the red bar showing up, which I have edited to a full-thumbnail covering watched badge.

**Comment by ParticleCore** [comment]
@Eisys If that issue is still present with the extension disabled I'm afraid I don't know the answer for it.

**Comment by fwosar** [comment]
What about the actual suggestion that this is about? Filtering out premieres from the Subscription page. They are incredibly annoying.

**Comment by ParticleCore** [comment]
@fwosar https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md
