### ISSUE TITLE
Issue with click and drag

### ISSUE THREAD

**Issue by breadbull** [ParticleCore/Iridium#617]
Unfortunately I can't replicate the issue reliably so I have no clue what exactly causes it, but every once in a while if I drag a browser tab out of a window and move it to another one, what'll happen is that the formatting gets screwed up. The page will get cut in half and frozen, and if I reload the page then the whole tab just becomes white/blank.

Using latest version of Chrome (70.0.3538.102) and Iridum on the Web Store.

**Comment by ParticleCore** [comment]
Nothing to do with the extension since it has no hooks or any sort of feature that could cause this kind of behavior, especially nothing to do with window drag behavior.
Try the Google forums for this kind of issue.
