### ISSUE TITLE
Open with Firefox closed: video appears in the down-right corner

### ISSUE THREAD

**Issue by gabri25ele** [ParticleCore/Iridium#619]
I had an external-browser link (for example in a thunderbird message).
I click on the link in the message...
and I see like this

![annotazione1](https://user-images.githubusercontent.com/33927879/48361615-2f73aa80-e6a2-11e8-97f5-415994dcc2e3.png)

video appears in the down-right corner! 
If I click in a video on youtube, that, it does not happen:

![annotazione3](https://user-images.githubusercontent.com/33927879/48361730-6a75de00-e6a2-11e8-849f-34630854c3f9.png)

The only solution to open the external link is disable this voice:
(always show the video as you scroll through the page)
![annotazione2](https://user-images.githubusercontent.com/33927879/48361755-76fa3680-e6a2-11e8-9681-d612e943e0a3.png)

But I suppose is a incorrect behavior.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by gabri25ele** [comment]
Not very sure, do you want this information?

      Browser Name: Firefox 

      Browser Version: 63.0.1

      Operating System: Windows 10

      Software Type: Add-on

      Software Version: 0.2.4

      Problem Description: video appears in the down-right corner if I go from external program

      Steps to reproduce: see images

**Comment by ParticleCore** [comment]
Did you actually follow any of the steps requested in the troubleshooting instructions?
I cannot replicate the problem on my end, so if you can't help me recreate it and ensure that it is really a problem with the extension and not something else by following the troubleshooting steps as requested for the second time this will not have a chance of getting fixed.

**Comment by gabri25ele** [comment]
I found that... to put the video window in the main place, just make a scroll (down and up)...
simple.

**Comment by ParticleCore** [comment]
This was also happening when duplicating the tab, thanks for the video example it helped a lot.
