### ISSUE TITLE
Force new layout?

### ISSUE THREAD

**Issue by notDavid** [ParticleCore/Iridium#62]
Hi there,

when the browser is set to not keep youtube/google cookies, after a browser restart you always have to join https://www.youtube.com/new first and click "try it now"... which is kind of annoying.

So is it not possible for this "extension" to just enforce the new Youtube layout so it always just works?

Thank you :)

**Comment by ParticleCore** [comment]
This is not a feature the extension should have since it will be temporary, meaning that when the layout becomes default the feature is no longer useful. You are better off allowing just that cookie or a create a userscript that sets it for you every time you open your browser.
