### ISSUE TITLE
Audio continues playing after closing floating player

### ISSUE THREAD

**Issue by mikeloeven** [ParticleCore/Iridium#621]
Browser Waterfox: 56.2.5
Steps to reproduce
Open a youtube video
Navigate to all videos page while leaving floating player open
Press X on the floating player to close it. 

Result You will continue hearing the audio play in the background until the tab is closed or you open another video which I assume resets the player

**Comment by ParticleCore** [comment]
Support is only available for Firefox or Chrome stable versions: https://github.com/ParticleCore/Iridium/blob/master/README.md
