### ISSUE TITLE
Audio continues playing after closing floating player

### ISSUE THREAD

**Issue by mikeloeven** [ParticleCore/Iridium#622]
#621 Closed Prematurely due to unsupported browser version
Successfully Reproduced issue in current FF build 63.0.1 (64-bit)

Steps to reproduce Open a youtube video 
Navigate to all videos page while leaving floating player open
Press X on the floating player to close it. 

Result You will continue hearing the audio play in the background  until the tab is closed or you open another video which I assume resets  the player

**Comment by ParticleCore** [comment]
Duplicate of #575
