### ISSUE TITLE
Scroll for details

### ISSUE THREAD

**Issue by AlexFundorin** [ParticleCore/Iridium#624]
Can we have an option to disable that annoying "Scroll for details" new feature with Iridium. When switching to fullscreen at, let's say 16:9 screen and the video is 21:9, instead of having an immersive picture, we get video title, recommended videos and other unneeded BS, instead.
Example: https://i.imgur.com/Z12chJd.jpg

**Comment by AlexFundorin** [comment]
Happens only with cinema mode.

**Comment by ariefpizzuti** [comment]
16:9 screen here, the video plays in fullscreen just fine for me. What cinema mode are you referring to? theater Is it from the iridium or  youtube itself?

**Comment by AlexFundorin** [comment]
This one: https://i.imgur.com/8TVfQfb.png

**Comment by ariefpizzuti** [comment]
It shows theater mode for me not cinema.
![2018-11-13 19_52_33-octavia spencer melissa mccarthy had price is right dreams - youtube](https://user-images.githubusercontent.com/18688192/48411830-b9dd0c80-e77d-11e8-9aa1-0e900ec3e780.jpg)

**Comment by AlexFundorin** [comment]
Depends on a preferred language, I guess. I'm only using Iridium. Anyways, YT doesn't open in fullscreen when cinema/theater/theatre mode is enable and I have it enable by default, since it's more convenient, having video as wide as possible.

**Comment by ariefpizzuti** [comment]
What language are you using? I use english. maybe something got to do with zooming since I saw ur picture got a little bigger font there.

**Comment by AlexFundorin** [comment]
English. Nothing to do with zoom. Default zoom - https://i.imgur.com/MYvo5R8.jpg

**Comment by ariefpizzuti** [comment]
Weird, hope u find a solution and particle can take a look into it, good luck.

**Comment by AlexFundorin** [comment]
Also mini player doesn't show up when scrolling in full screen. Only progress bar can be seen.

**Comment by thepcwiz101** [comment]
I got this showing up also but youtube has removed the scroll down text and instead just has an arrow now and still allows scrolling in full screen.
