### ISSUE TITLE
[Feature Request] Hide Thumbnail Buttons When Disabled

### ISSUE THREAD

**Issue by Shananiganeer** [ParticleCore/Iridium#627]
The "Block" and "Pop-up" buttons should not display on thumbnails if the relevant setting has been disabled.

**Comment by ParticleCore** [comment]
The buttons are arlready not showing when their respective setting is disabled.

**Comment by Shananiganeer** [comment]
I have "Pop-up" disabled, but still get the thumbnail button. I guess this is a bug report instead of a feature request.

https://i.imgur.com/thQtbFB.png

**Comment by ParticleCore** [comment]
Did you refresh YouTube after disabling the setting? If you did then please follow the instructions for reporting a problem on a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Shananiganeer** [comment]
Yes, I refreshed YT after disabling. Going through the troubleshooting steps and then will submit a full bug report should the issue persist.
