### ISSUE TITLE
[Feature Request] Add Setting to Disable Fullscreen "Scroll for details"

### ISSUE THREAD

**Issue by Shananiganeer** [ParticleCore/Iridium#628]
YouTube has implemented a new "feature" that allows for fullscreen videos to be scrolled out of. Add a setting to disable this functionality.

It looks like crap and defies the purpose of fullscreen:
https://i.imgur.com/xLkYTEq.png

**Comment by ParticleCore** [comment]
Duplicate of #624

**Comment by Shananiganeer** [comment]
Sorry, saw that other issue and didn't realize you were using labeled closed issues for tracking.
