### ISSUE TITLE
Pop-out player changes size every time

### ISSUE THREAD

**Issue by Schoggiweggli** [ParticleCore/Iridium#629]
Since a few weeks, the video pop-out player gets progressively bigger every time it is used. This only happens for me on Chrome not on Firefox.

Chrome 70.0.3538.102 / Iridium 0.2.4

**Comment by ParticleCore** [comment]
I am not observing this problem on my end. Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Schoggiweggli** [comment]
Looks like it fixed itself after an update to Chrome 71.
