### ISSUE TITLE
Video preview is not behaving properly with new YouTube 3 seconds preview

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#63]

**Comment by briank6932** [comment]
Yes, when this happens https://www.youtube.com/iridium-settings fails to load.
I will put up the error code and other information here: https://github.com/ParticleCore/Iridium/issues/61

**Comment by ParticleCore** [comment]
@briank6932 Gotcha, after trying to preview and then open the settings they fail.
