### ISSUE TITLE
Full Screen Autoplay in Reverse Playlist - Firefox

### ISSUE THREAD

**Issue by putronoxo** [ParticleCore/Iridium#630]
Possibly due to the recent youtube or firefox update, reverse autoplay seems to be broken in Iridium. Whenever I open a youtube playlist (not one I made myself) and use Iridium to have it playing in reverse order on full screen, the next video loads but gets forced back into not fullscreen and doesn't autoplay, even though that option is enabled. It just sits there with the big play button over it. I've tried disabling iridium and viewing playlists normally and they still autoplay fullscreen just fine, so I assume it's some kind of new incompatibility issue

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
