### ISSUE TITLE
Prevent autoplay not working in background tabs

### ISSUE THREAD

**Issue by olliebean** [ParticleCore/Iridium#631]
With the "Play videos automatically" setting turned off, Iridium works as expected to prevent autoplay of YouTube videos opened in the currently active tab. But if I open a YouTube video in a background tab (i.e., by middle-clicking a link), Iridium doesn't prevent autoplay. Depending on the Firefox `media.block-autoplay-until-in-foreground` setting, the video either starts playing immediately in the background tab, or is blocked by Firefox until the tab is activated and then starts playing immediately.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by olliebean** [comment]
Ah, OK, not reporting this as a bug as it seems to be working as expected in the new layout. I've been using Iridium with the old layout just for the prevent autoplay feature, which worked fine until recently. I guess I'll either have to find an alternative autoplay blocker, or learn to live with the new layout.

**Comment by ParticleCore** [comment]
If you are using Firefox you can tell some websites to not let videos play automatically, a quick google search on this will lead you to plenty of easy to follow examples.
