### ISSUE TITLE
Switching full screen through full browser mode broke progress bar

### ISSUE THREAD

**Issue by adeep** [ParticleCore/Iridium#633]
Browser Name:  Chrome
  Browser Version:  70.0.3538.110
  Operating System: Windows 10 Pro 1809
  Userscript Manager: Tampermonkey
  Userscript Version: 4.7
  Problem Description: Switching fullscreen when on full browser mode progress bar is broken, look like 
 its shrinked to left side. And new Youtube feature scrolling down not working when switch with this 
 order. 
  Steps to reproduce: First start video, switch to Full Browser mode, then switch to fullscreen mode
  Additional details: Here is screenshot of progress bar when fullscreen
![shrinked-progress-bar](https://user-images.githubusercontent.com/374042/48851101-43fb2580-edbb-11e8-8040-5eef2d0a3934.png)

**Comment by ParticleCore** [comment]
I am not able to recreate this problem, please follow the troubleshooting steps as requested to rule out the possibility of a conflict with another extension: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
