### ISSUE TITLE
Home page breaks if trying to load blocked video

### ISSUE THREAD

**Issue by Dajova** [ParticleCore/Iridium#634]
So this is what happens when YouTube tries to load the first video in the "Recommended" list that i have blocked in Iridium:

![Iridium](https://i.imgur.com/5NNHM8P.png)

The only way to fix it is to reload the page, but it's getting annoying to sometimes reload it like 10 times in a row, just because it tries to load a blocked video on the first result.

**edit**: Sometimes it looks like this as well:

![Iridium](https://i.imgur.com/l5vYriO.png)

**Comment by ParticleCore** [comment]
I am not able to replicate this problem, please follow the troubleshooting steps: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

I did detect however that if I block the first recommended video the entire section is being removed, but the same does not happen if any other video is blocked besides the first one.

**Comment by Dajova** [comment]
Well ofc, it doesn't happen all the time for me either, only if it tries to load a channel that i've blocked as the first video that shows up on that section per reload. If i get that page and reload, chances are that it will be normal again after that, but there's also a chance that it will stay that way again. It's random as per youtube algorythm.

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
