### ISSUE TITLE
Autoplay does nothing

### ISSUE THREAD

**Issue by mangoduck** [ParticleCore/Iridium#635]
Play a video in a playlist. Having autoplay on does not autoplay next video. Youtube on its own, does. Latest Chrome, no other cruft. I have read the "guide", I'm not an idiot, and this should be sufficient.
Cheers

**Comment by ParticleCore** [comment]
Reading the guide and actually following what it says are two completely different things, the later being one that you clearly didn't do. No one is calling you an idiot and you are not forced to follow the instructions as requested before opening a new issue, just like I am not forced to help someone that doesn't want to be helped.
