### ISSUE TITLE
Make bullet points bigger (simple find and replace)

### ISSUE THREAD

**Issue by h-h-h-h** [ParticleCore/Iridium#638]
Please replace this character: · (U+00B7)
With this character everywhere: • (U+2022)

Copy me (before, after): `·•`

YouTube itself uses the bigger bullet, and it's just more suitable as a separator.

Example pages of YouTube using the bigger bullet:

- https://www.youtube.com/watch?v=iWAe9zc_tyA
- https://www.youtube.com/playlist?list=PLwnD0jwK0yylXEbz-BpnvBrANJh-b_j5a

### Before (mixed bullet sizes):

![before](https://user-images.githubusercontent.com/13482553/49504107-54aaa180-f879-11e8-9306-51787e417eca.png)

### After:

![after](https://user-images.githubusercontent.com/13482553/49504133-65f3ae00-f879-11e8-9252-307e5a3b4525.png)

**Comment by h-h-h-h** [comment]
Did you forget to close this issue?

**Comment by ParticleCore** [comment]
> 
> 
> Did you forget to close this issue?

Yes I did, sorry and thanks for reminding me.
