### ISSUE TITLE
Reverse Playlist button does not appear

### ISSUE THREAD

**Issue by DoctorFS** [ParticleCore/Iridium#639]
I've installed the extension and some other features are working, but the reverse playlist button does not appear when I watch a video in a playlist - all I can see are the standard repeat and shuffle buttons. I've verified that "Enable reverse playlist control" is toggled on in the extension settings. Chrome version 71.0.3578.80

**Comment by DHPgit** [comment]
Same here. Some Iridium features work, but not Reverse Playlist.
Version 71.0.3578.98 (Official Build) (64-bit)
I have disabled all other extensions and tried disabling and re-enabling Iridium.
It does work on my work PC but I don't know the Chrome version.  Unfortunately I don't have time for YouTube at work.  :)

**Comment by ParticleCore** [comment]
It is showing correctly for me

![image](https://user-images.githubusercontent.com/9222661/50565618-3b81fd00-0d20-11e9-9c4d-b16c7fb931a2.png)

Please follow the troubleshooting steps as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by DHPgit** [comment]
OK, I'm a dumbass.  I was not running the new YouTube format.
Iridium is now working at home as well as at work.

**Comment by ParticleCore** [comment]
Happy to hear that you got it working @DHPgit .

@DoctorFS If you are still having trouble please follow the instructions in my previous reply.
