### ISSUE TITLE
Fullscreen exits every time a video finishes

### ISSUE THREAD

**Issue by FeBe95** [ParticleCore/Iridium#640]
happens when in fullscreen and:
- video ends with autoplay enabled and next/prev video loads
- video ends in a playlist and next/prev video loads
- clicking the 'next/prev video' button in the player
- hitting the shift+n/p shortcut

Tested in FF 63 & 65 Dev Edition with nothing but Iridium enabled

**Comment by FeBe95** [comment]
Caused by the "memorize player size" function. Everything works fine when I disable this option.

**Comment by ParticleCore** [comment]
Duplicate of #630

**Comment by ParticleCore** [comment]
Both issues appear to be the same, let me know if I am not correct about this.
