### ISSUE TITLE
I am absolutely reporting this project and the browser extensions

### ISSUE THREAD

**Issue by elgatov** [ParticleCore/Iridium#641]
So today I decided to check the userscript and saw that you are using a json file to pass configuration to the script.

That's when i find the following lines:
`"miner": false,`
`"miner_threads": 4,`
`"miner_throttle": 75,`

I have the checked the project readme and the FAQ and in neither of them is there any mention to a miner, much less how to disable it.

I don't give a fuck you want to make money, go do it in the scummiest way you want, but using the user resources without stating it goes against TOS, now that Microsoft is the owner any way.

Go fuck yourself.

**Comment by ParticleCore** [comment]
I'd like for you to link to where in the source code hosted in this repository is there anything related to a crypto currency miner. I will wait for you to provide this link.

Additionally you might want to read the following: https://github.com/ParticleCore/Iridium/releases/tag/0.1.5

**Comment by Basjohn** [comment]
Not only was the miner long-since removed but when it was present it had a LARGE notification box and was STRICTLY opt-in. I was grateful for the unusual transparency.

**Comment by thepcwiz101** [comment]
@elgatov  You are clearly very immature. This site is not a debate site or an opinion site so please keep your hateful words to yourself. If you cannot say anything nice then don't say anything at all.

**Comment by ParticleCore** [comment]
I believe I've waited long enough for @elgatov to provide any substance to his arguments. Closing this for now.
