### ISSUE TITLE
Allow ads on subscribed channels seems broken

### ISSUE THREAD

**Issue by redjo-bsl** [ParticleCore/Iridium#642]
Browser Name: Firefox
Browser Version: 64.0
Operating System: Windows 10
Software Type: Iridium extension add-on
Software Version: 0.2.4
Problem Description: Hi, I've followed all the instructions and even with new profile and only Iridium extension, there is no ads on subscribed channels for Youtube HTML5.
Steps to reproduce:
- Create new profile in Firefox
- Add Iridium extension
- Allow ads on subscribed channels
- Go on Youtube and connect
- Watch videos from subscribed channels
- No ads intro nether small popups

**Comment by redjo-bsl** [comment]
Allow ads on videos works fine when it's activate alone (allow on subscribed channels OFF).

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
