### ISSUE TITLE
Thumbnail playback adding videos to history

### ISSUE THREAD

**Issue by ansaksie** [ParticleCore/Iridium#645]
Recently (within the last couple of weeks), thumbnail playback has been adding videos to my history.  Even if it plays back for only a second before I move my cursor, it'll wind up in my history.   It doesn't add the video if you leave the preview before it manages to load (i.e. if you manage leave while the loading wheel is displayed).  I'm using Chrome and I've tested both the Tampermonkey script and the Web Store extension, and they both do it.  Everything is up to date.

**Comment by AncalagonX** [comment]
In related news from the last week or two, I've noticed the official iPhone Youtube app has started playing thumbnails automatically when you're scrolling a list of videos. These auto-played thumbnails also get added to your history, even if you do not interact with them and simply let the thumbnails auto-play.

It may or may not be related.

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
