### ISSUE TITLE
Blacklist (X) button not visible

### ISSUE THREAD

**Issue by aurabindo** [ParticleCore/Iridium#646]
On Debian 9, Firefox 64.0 (64-bit)

Blacklist button is not absent. I cannot block videos. I cannot find the format for manually editing the blacklist either.

How can I debug why blacklist button isnt showing up? It works on fedora 29 and opensuse, but not on my debian installation.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
