### ISSUE TITLE
Added Watched to videos that a persons has already viewed.

### ISSUE THREAD

**Issue by mkruer** [ParticleCore/Iridium#647]
YouTubeCenter by YePpHa https://github.com/YePpHa/YouTubeCenter had a very useful feature a 
“Watched” overlay on all videos that a persons has already viewed.

https://github.com/YePpHa/YouTubeCenter/wiki/Features#Watched_Videos 

Please consider for future implementation

**Comment by ParticleCore** [comment]
Duplicate of #233
