### ISSUE TITLE
Chrome Extension has been taken down from the web store by the Google team

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#648]
I have been forced to post this here because it is currently impossible to submit any review due to a Chrome Web Store bug since it always asks for "Create a profile to rate" when it is already created.
This isn't the first time this bug happens and it has already been reported to the Google team since July: https://groups.google.com/a/chromium.org/d/msg/chromium-extensions/FUjVVOpde4I/muHfAX7mCgAJ

As a result of many users reporting the extension as "Not working" it is now at risk of being removed from the store. I understand that people have little tolerance for bugs and even less waiting for them to be fixed, but I am completely devoid of any time and resources to fix them during this period, I only have my phone with me and I cannot program using a phone nor do I have any computer at my reach.

As some of you already know from my past announcements I don't have the time or health to be worrying about anything that goes beyond fixing the bugs the extension has, as a result of this episode I am considering turning the Chrome extension of Iridium into a paid extension in order to weed out the short tempered users that have a quick trigger when reporting the extension.

If Chrome users want the commodity of having an extension on their browser profile then it will soon become a luxury that will have to be paid for, just like I want to worry less about it being taken down and punished for childish behavior.

I understand that some of the Chrome users will never accept this, which is why **there is the Userscript version available and it is free.**

I am deeply sorry that it is taking me so long to fix bugs but I have been totally transparent about my limitations since the start of this extension, it is sad to see that it had to come down to this.

----

Edit Jan 3rd: The Chrome extension has been taken down by the Chrome Web Store team under the accusation of not working as described. For 3 times since December 31st I was given ultimatums from the CWS stating that the extension was not providing any functionality or working as described and I had 7 days to do something about it. In less than 24h of each of those emails I received another one informing me that the extension was taken down from the web store.

I have been trying to contact the CWS team through multiple channels ever since the first warning, but I have yet to receive a single reply from them. There is nothing else I can do but wait, if they never reply back then that's it for the Chrome Extension version of Iridium.

----

Edit Jan 4th: Today I receive another email explaining that the extension is being taken down (it is already down) because the description and screenshots do not show how the extension works. Remember that before they were accusing the extension of simply not working, now it's just the description and screenshots that are not to their liking. They also failed to explain how this can be fixed since there is absolutely no way for me to guess what they find acceptable or not.

As of this moment I will wait until Jan 12th to have this situation resolved. If it is not resolved by then I will no longer provide an extension version for the store.

----

Edit Jan 5th: Received again today another email accusing the description and/or screenshots not showing how the extension works. The CWS team is showing no intention of being direct and clear about what needs to be changed and continues sending robot emails without any sign of a human actually writing them. I am afraid that the Chrome extension version is done for.

----

Edit Jan 6th: After receiving yet another take down notice email - *do take into account that these have always been emails stating that the extension IS being taken down when it was already taken down in the first time* - I received a new email requesting me to re-publish the extension in order for it to be reinstated. As to what this means I can only imagine the worse and that is it will be taken down again or with some luck it will be finally accepted in the store again.

**Comment by thepcwiz101** [comment]
The internet is full of hate trust me. i doubt google will remove your extension though.

**Comment by TheArcaneBrony** [comment]
seems like the extension got removed. going to the store url brings up a 404

**Comment by TheArcaneBrony** [comment]
nvm somehow i read over the part where you said you were making it paid. I wish I could pay for it, but as i don't have a credit card i cannot. Can sort it out via paypal if you are okay with it

**Comment by ParticleCore** [comment]
@TheArcaneBrony I explained that for users that do not wish to pay for it they can use the Userscript version which is completely free and will stay always free. The extension being taken down at the moment is not my doing and has been explained in my edit note.

**Comment by TheArcaneBrony** [comment]
damn, shame on google.
I would pay for the extension, if i only could!
Also nobody said you cant add nice features only available on non chrome!

**Comment by karldreher** [comment]
Hi, I have had the same experience with my extension: https://github.com/karldreher/netflixplus .  

I am adding this comment to document the fact that we are having a common experience, and may follow your suit to open an issue on my repo.  
It would be really nice to get more information from Google about why this is happening.

**Comment by ParticleCore** [comment]
@sowbug Is there any chances of getting this looked at? I'm at my wits end with this already and the lack of clarity from the CWS team to this date (over 5 years with the same kind of behavior) is still appalling.

**Comment by LesterCovax** [comment]
Sounds like the same type of behavior that occurs within YouTube and their complete lack of communication with affected users.  Real shame.

Thanks for your work on the extension though, and I'll switch to using the UserScript.

**Comment by thepcwiz101** [comment]
@ParticleCore google is known for screwing over people especially on youtube. If someone was to take down google's servers for an extended amount of time that would teach them a lesson for misusing their content creators and extension devs such as yourself. I also believe that google has not tested the extension either like they should and just took it down wrongfully. Oh and making the extension paid will not stop reports and take downs like these from occurring sadly.

**Comment by LesterCovax** [comment]
@thepcwiz101 Making (albeit unrealistic) threats of DDoS or maleficence doesn't do any good.  People just need to become less dependent on their services by moving to different platforms, creating their own, or alternative approaches such as utilizing User Scripts for extensions, or things like Patreon for lost monetary gains.

Of course, that doesn't excuse their lack of due diligence as you mention, or bad actors (whether they be inept end users or malicious third parties such as competing extensions).  It wouldn't surprise me if certain other YouTube extensions that are heavily ad/promotion driven were behind this.  I personally switched from one of those due to how bloated it became with other products for a cleaner solution like Iridium.

**Comment by thepcwiz101** [comment]
@LesterCovax 
Well yea you are right. Sadly though alot of people like the services google offers like youtube for example and the reason google has became so big is because of it's users really. But i do hope that google becomes more consumer friendly.

**Comment by TheArcaneBrony** [comment]
Yikes, companies and their dang robot emails.
I wish there was a way to contact a real person at google.

**Comment by ParticleCore** [comment]
It appears that the extension was restored to the Chrome Web Store. I still don't know what was the cause of the take down in the first place but the situation was resolved before jan 12th, hopefully it will stay stable from now on.

Thanks for everyone's time and sorry for the trouble this may have caused.
