### ISSUE TITLE
Video no longer minimizes when changing page

### ISSUE THREAD

**Issue by bastiel** [ParticleCore/Iridium#651]
Browser Name: Firefox

  Browser Version: 64.0

  Operating System: Windows 10 64 bit

  Software Type: Add-on

  Software Version: 0.2.5

  Problem Description: Just today, when clicking on another non-video page (home page, channel page, liked videos, etc.), the video no longer minimizes into a mini player. Instead, the video simply closes as if I did not have the add-on. It seems like this problem is related to [issue #575](https://github.com/ParticleCore/Iridium/issues/575), but that was back in September and I've kept my add-on up to date. Was the feature removed?

  Steps to reproduce: 
1. Open a video
2. Click on a non-video page (home page, channel page, liked videos, etc.)

**Comment by ParticleCore** [comment]
The feature has been removed as it was explained in the release notes: https://github.com/ParticleCore/Iridium/releases/tag/0.2.5

**Comment by bastiel** [comment]
My bad. I thought the feature was incompatible with just Chrome browsers.
