### ISSUE TITLE
changing volume using mouse wheel resets iridium settings

### ISSUE THREAD

**Issue by minidude2012** [ParticleCore/Iridium#653]
Browser Name: Chrome

  Browser Version:  71.0.3578.98

  Operating System: Windows 10, Ubuntu, Arch Linux

  Software Type: Add-on

  Software Version: 0.2.4/0.25

  Problem Description: when using mouse wheel to change volume iridium resets all its settings back to default as if it was just installed

  Steps to reproduce: enable mouse wheel to change volume, open video scroll to change volume

  Additional details: it works for the first so it will increase or reduce by the 5% as described then will instantly stop and then if you open settings they will be all reset to default

**Comment by ParticleCore** [comment]
I have just tried following your steps under the same configuration (W10 only tho) and the settings are not being reset.

I don't doubt that the issue does exist, it appears you tested it on 3 different OS, but unless I can get it to happen to me I cannot find a way to fix it so I ask you for more help.

 - Have you tested this with only Iridium installed? No other extension, no other userscript.
 - Is this the extension version that is on the Chrome Web Store or is a userscript running on a userscript manager like Tampermonkey? (I know you wrote "addon" but Chrome does not have add-ons, so I want to confirm what type are you using)
 - Could you share the settings you changed to before they get reset?
 - If you are using the extension version could you test the same thing with the userscript version? Or vice-versa if it's the other way around.
 - When the issue occurs or right after you do the action that supposedly resets Iridium can you show what comes up on the developer console? Press F12 to open it.

**Comment by minidude2012** [comment]
seemed after writing bug report it just suddenly started working sorry for wasting time

**Comment by minidude2012** [comment]
i will reopen if it appears again
