### ISSUE TITLE
Prevent autoplay no longer working

### ISSUE THREAD

**Issue by iPaulis** [ParticleCore/Iridium#654]
It seems that the option to prevent videos from autoplaying isn't working, just started 15 mins ago. 

It prevented autoplay while I was opening some tabs, and stopped working with the last 2-3 tabs I opened. Then I reproduced the problem by refreshing any of the tabs, and all of them fail to prevent autoplay, so the feature is not working anymore.
Something must have changed in youtube at that moment.

Firefox v59.0.3
Iridium v0.2.5

**Comment by RadioActiveLobster** [comment]
Can confirm same issue

Firefox v64.0
Iridium v0.2.5

**Comment by juozaspo** [comment]
Noticed this too. On initial page load it's no longer working, clicking links from main page doesn't prevent autoplay too. If I click a link to other or the same video from watch page (such as playlist/related video link) it time works most times.

Workaround for firefox: Set **media.autoplay.default** to **1** in _about:config_ page to disable autoplay globally or **2** to ask each time.

Firefox 64.0
Iridium 0.2.5
Greasemonkey 4.7

**Comment by ch3wy** [comment]
Ditto, was wondering what happened. Same issue on both Chrome and Firefox.

Chrome 71.0.3578.98
Firefox 64
Iridium 0.2.5 (both browsers)

**Comment by briank6932** [comment]
same here

**Comment by SnowyEvans** [comment]
Same

**Comment by jasonycw** [comment]
Same for Chrome Version 71.0.3578.98 (Official Build) (64-bit)
From Chrome Extension store, version 0.2.5

**Comment by prathibha-e** [comment]
I'm experiencing this issue as well.

Firefox 64.0 (64-bit)
Tampermonkey 4.8.5847
Iridium 0.2.5

**Comment by Darkaeluz** [comment]
Can confirm that this bug is back as well

Firefox 64.0 (64-bit)
Iridium 0.2.5

**Comment by gabri25ele** [comment]
same for me
Firefox 64.0.2
video starts automatically in any way

**Comment by HighMans** [comment]
Having the same issues.
Iridium 0.2.5
Chrome 71.0.3578.98

**Comment by promitheus7** [comment]
Same issues on Chrome and Firefox.

Iridium 0.2.5
Firefox 64.0.2
Chrome 71.0.3578.98

**Comment by ElKolossos** [comment]
Same issue here. Only way to prevent YT from autoplay is to choose a video from the suggested ones on the right while playing a video. In any other case, it will start automatically.

Chrome 71.0.3578.98
Iridium 0.2.5

**Comment by ParticleCore** [comment]
Locking this for now, this has already been confirmed and there is no need to keep spaming the users that are subscribed to the case.

**Comment by ParticleCore** [comment]
This has been fixed in version 1.0.0
