### ISSUE TITLE
Where the hell is everything????

### ISSUE THREAD

**Issue by SiberYid** [ParticleCore/Iridium#656]
I couldn't find any sign of it?!?! 
Settings page? I read about its existence, saw no trace of it, though..........
I'm by no means a stranger to failure when I'm at a pc, the idea of providing instruction being as unpopular as it is, is a factor........
Sadly, the innate knowledge, I'm apparently lacking, often sees me hamstrung, as was the case here........
In Japan, a can of coke has written + pictorial instructions.........

**Comment by practik** [comment]
Yep, it's a bit unintuitive. You want to look for the Iridium icon at the top of any YouTube page. Click it to open the settings.

**Comment by ParticleCore** [comment]
Working as intended, see https://github.com/ParticleCore/Iridium/wiki/Features#thumbnail_preview
