### ISSUE TITLE
Text-hover thumbnails no longer autoplay if image-hover thumbnails are played

### ISSUE THREAD

**Issue by AncalagonX** [ParticleCore/Iridium#658]
The bug itself is explicitly laid out in the **last paragraph,** and before that is a bunch of extra info to make this bug report clear. So...

Without Iridium, there is only one kind of thumbnail that auto-plays on mouse hover:
1) Hover over BLUE or RED rectangle zone in the image below, and Youtube plays its default animated thumbnail: Three seconds long, muted, from somewhere in the middle of the video, plays only once per mouse hover but will play again if un-hovered and then hovered again.

With Iridium, there are two kinds of thumbnails that auto-play on mouse hover in Youtube:

1) BLUE RECTANGLE ZONE: Default Youtube thumbnail, three seconds long, from somewhere in the middle of the video.
2) RED RECTANGLE ZONE: Iridium thumbnail, showing the (entire?) video starting from the very beginning, with no skips.

![2019-01-11_03-42-39_ honeyview](https://user-images.githubusercontent.com/37827291/50989536-fbf2b680-1552-11e9-8eb6-8e0154209db3.png)

**BUG:** The blue rectangle zone works as intended, and shows the default Youtube thumbnail, *unless* the user hovers over the red rectangle zone for the Iridium thumbnail. At this point, the blue rectangle zone ceases to function for that particular video and the user can no longer view the default three-second Youtube thumbnail unless the page is refreshed. Intended behavior would be for the blue rectangle zone to always be able to show the default three-second Youtube thumbnail when the user hovers there.

**Comment by ParticleCore** [comment]
Working as intended, see https://github.com/ParticleCore/Iridium/wiki/Features#thumbnail_preview
