### ISSUE TITLE
Full Browser Mode doesn't do anything...

### ISSUE THREAD

**Issue by pwndguy** [ParticleCore/Iridium#662]
![fullscreen failure before](https://user-images.githubusercontent.com/22206139/51070436-f8fcd200-15f5-11e9-9a7a-1fd8ac5e668f.PNG)
![fullscreen failure after](https://user-images.githubusercontent.com/22206139/51070437-00bc7680-15f6-11e9-8b35-7f5b1adf49d1.PNG)

As you can see, the mode is active, but it didn't change the size at all...
The only thing it really does is disables the Floating Player thing when I scroll down...

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by pwndguy** [comment]
Browser Name: Chrome

Browser Version: 71.0.3578.98

Operating System: Windows 10

Software Type: Extension

Software Version: 0.2.5

**Comment by pwndguy** [comment]
Sorry, i thought i tried restarting chrome, but apparently not... that worked...
