### ISSUE TITLE
Settings Page Doesn't save

### ISSUE THREAD

**Issue by Travisplo** [ParticleCore/Iridium#663]
The settings page often doesn't save your set settings, and even when it does, often resets the settings after a certain amount of videos viewed, or times the home page is reviewed.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
