### ISSUE TITLE
Shift key toggles audio on video thumbnail playback not working in chrome

### ISSUE THREAD

**Issue by harry-public** [ParticleCore/Iridium#664]
Shift key toggles audio on video thumbnail playback is not working in Chrome, it does show the speaker icon, but it does not turn on the volume.

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
