### ISSUE TITLE
list of Playlist 

### ISSUE THREAD

**Issue by gabri25ele** [ParticleCore/Iridium#665]
With Iridium I see that:
![on](https://user-images.githubusercontent.com/33927879/51191201-34441d00-18e4-11e9-84f6-05ad177aa9b3.PNG)

If I disable Iridium I see correctly:
![off](https://user-images.githubusercontent.com/33927879/51191242-3e661b80-18e4-11e9-831f-1cd8860880fb.PNG)

which options I must disable to see the list of playlist?

**Comment by ParticleCore** [comment]
Please follow the instructions as requested before opening a new issue: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
