### ISSUE TITLE
Playlist container isn't filled with Iridium enabled?

### ISSUE THREAD

**Issue by marbuser** [ParticleCore/Iridium#667]
Browser Name: Google Chrome

Browser Version: 71.0.3578.98

Operating System: macOS Mojave 10.14.2

Software Type: Chrome Web Store

Software Version: 0.2.5

Problem Description: 
Playlists don't list videos and are left empty. If Iridium is disabled this isn't an issue.
Example of what is happening:
![image](https://user-images.githubusercontent.com/34422459/51622297-44599d80-1f71-11e9-95c1-534fcc74bc0d.png)

Steps to reproduce: 
1. Install Iridium.
2. Open any video playlist.

Additional details: 
Figured I'd open this because while there is another issue open for this, that person didn't use the right format and also seems to have abandoned the issue.

**Comment by thepcwiz101** [comment]
I don't have this issue surprisingly. Seems to be a rare occurance.

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
