### ISSUE TITLE
Spacebar to pause broken

### ISSUE THREAD

**Issue by ch3wy** [ParticleCore/Iridium#668]
Hitting the spacebar to pause after using directional buttons no longer works with Iridium enabled, works perfectly normal when disabled.

Edit: Nevermind? I think this actually an issue with either Firefox or Youtube itself. It did it once on Chrome but stopped and it now does it on Firefox even with Iridium disabled.

Can anyone else confirm or deny that this is an issue with Iridium or Youtube please so I can know if I need to close this or leave it open. Thank you.

OS: Windows 10 Enterprise 64bit
Firefox: 64.0.2
Iridium: 0.2.5

**Comment by kilara1988** [comment]
With iridium enabled and the always active shortcuts option enabled spacebar only plays the video and it does not pause it.

If you disable the always active shortcuts option you can get spacebar to pause the video only if the player is not in focus(you have to click outside the player).If the player is in focuse(you clicked on it) then spacebar does not pause the video.
If iridium is disabled altogether the behavior is the same - focused player equals no spacebar pause.
Tested this with Internet  Explorer and it works as expected there.
So it seems it might be a Firefox or YouTube bug.

The weird thing is i am using Firefox 65 beta and Win 10 and  noticed this behavior today,but you have the same problem on FF 64.Also my brothers FF 64 on Win 8.1 has no such issues(he does not use iridium).So i am confused what is causing this.Will have to test a bit when i have more time.

**Comment by ch3wy** [comment]
Thank you for testing this. You're right about disabling the always active shortcuts option and using spacebar when the video is out of focus, it worked like you'd imagine.

I'll close this issue as it does not seem to be an issue with Iridium, if anything the option to disable always active shortcuts seems to fix it. Even in a private session with all extensions disabled, it still causes the issue.
I will report the issue instead to Youtube and Firefox and see if either of them can make sense of the problem.

Thank you again kilara1988!
