### ISSUE TITLE
The "wide screen" option is enabled by itself

### ISSUE THREAD

**Issue by KOT040188** [ParticleCore/Iridium#669]
When you click on links to similar videos or in the notification center from full-screen mode, the next video is loaded with the wide screen option enabled. 71.0.3578.98

**Comment by KOT040188** [comment]
Update. Я отключил расширение и понял, что при переходе к новому видео полный экран не отключается сам. Но при включённом расширении полный экран отключается и включается широкий экран. I turned off the extension and realized that when I switch to a new video, the full screen does not turn off by itself. but when the extension is turned on, the full screen is turned off and the wide screen is turned on.

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
