### ISSUE TITLE
Videos no longer loading at all if Iridium is enabled.

### ISSUE THREAD

**Issue by RadioActiveLobster** [ParticleCore/Iridium#671]
**Browser Name:** Firefox 
**Browser Version:** 64.0.2 (64-bit)
**Operating System:** Windows 10 Pro 64Bit
**Software Type:** Addon
**Software Version:** 0.2.5
**Problem Description:** YouTube videos no longer play. They forever set at a buffering icon. The Play/Pause buttons do not respond when clicked, using shortcuts (k for example) or the space-bar. If you manage to find a video that doesn't autoplay (because that's broken as well but there is already a bug report filed for that) clicking the play icon in the center of the video does nothing.
**Steps to reproduce:** Attempt to watch a video with Iridium enabled.
**Additional details:** Unknown if it affects all videos but I've been able to reproduce on basically all videos I've tried, even videos I know worked without issue prior. This problem just started within the past few hours.

**Comment by nathgit** [comment]
Same issue on chrome os with tampermonkey. As rberlew said enabling autoplay fixes the problem.

**Comment by Joshdw** [comment]
> 
> 
> If you enable videos to autoplay in the settings they will work again. And since the prevent autoplay is bugged right now anyway you aren't losing anything with this current workaround.

I can confirm this works. Enabling autoplay fixes the issue.

**Comment by ttggzz** [comment]
confirming workaround by rberlew, and restating from elsewhere that Firefox in about:config now allows control of media autoplay. So, turning autoplay _on_ in Iridium and [in Firefox] setting media.autoplay.default to "1" gets you back to square 1: videos play, autoplay disabled.

**Comment by bonelifer** [comment]
> 
> 
> Again confirming workaround by rberlew, and restating from elsewhere that Firefox in about:config now allows control of media autoplay. So, turning autoplay _on_ in Iridium and [in Firefox] setting media.autoplay.default to "1" in about:config gets you back to square 1: videos play, autoplay disabled.

Thanks. It stopped working today for me about 2 or 3 hours ago. Making these changes fixed it for me. Hopefully this isn't Youtube(google), doing a Facebook(FBPurity) on extension that change how YT works for users.

**Comment by spiderkitten** [comment]
I too have this issue.  

Browser Name: Chrome
Browser Version: 71.0.3578.98 (Official Build) (64-bit)
Operating System: macOS High Sierra 10.13.6
Software Type: Addon
Software Version: 0.2.5  

Just adding that refreshing the page sometimes allows the video to play. And in those cases, once the video loads and plays, loading a new video from within the same tab, seems to work. But if I navigate away from youtube and go back, or refresh the page or navigate to youtube page that requires the entire page to load and not just the bit that loads within that red loading bar at the top of the screen (sorry, don't know what its called), the issue occurs again. 

Turning Autoplay on has allowed a workaround for me too.

**Comment by perdolka** [comment]
Same here

**Comment by Nawaf-NM** [comment]
I agree with you, videos no longer play definitively.

i used: Firefox Quantum 64.0.2

**Comment by BondiBear** [comment]
Autoplay workaround works for me too.

**Comment by pmusial** [comment]
With Firefox 66 Beta released today the autoplay is disabled by default.

**Comment by thepcwiz101** [comment]
Same here i just installed iridium on firefox and had this occur. Got the new Firefox 65.0 update last night also.

**Comment by dougbenham** [comment]
> I was going through the entire script to see which line was causing the issue when autoplay is off. By searching "!user_settings.player_auto_play", I got to this section of code that loads the video.
> ![2019-01-30 01_14_20](https://user-images.githubusercontent.com/20297783/51961928-6ef19d80-242c-11e9-8eea-b261ad9f09fc.jpg)
> By commenting out this section of code, the video loads just fine without having to turn on autoplay, which also makes the video play automatically when the tab goes into focus.

This solution works well! Thanks Recchan.

**Comment by psonnosp** [comment]
> I was going through the entire script to see which line was causing the issue when autoplay is off. By searching "!user_settings.player_auto_play", I got to this section of code that loads the video.
> ![2019-01-30 01_14_20](https://user-images.githubusercontent.com/20297783/51961928-6ef19d80-242c-11e9-8eea-b261ad9f09fc.jpg)
> By commenting out this section of code, the video loads just fine without having to turn on autoplay, which also makes the video play automatically when the tab goes into focus.

If I do this the video play, so yay for that, but they autoplay even if I have it turned off in settings. Any way to fix that?

**Comment by dougbenham** [comment]
> > I was going through the entire script to see which line was causing the issue when autoplay is off. By searching "!user_settings.player_auto_play", I got to this section of code that loads the video.
> > ![2019-01-30 01_14_20](https://user-images.githubusercontent.com/20297783/51961928-6ef19d80-242c-11e9-8eea-b261ad9f09fc.jpg)
> > By commenting out this section of code, the video loads just fine without having to turn on autoplay, which also makes the video play automatically when the tab goes into focus.
> 
> If I do this the video play, so yay for that, but they autoplay even if I have it turned off in settings. Any way to fix that?

The point is that you can open videos in a new tab and they won't play until you activate that tab. Not perfect but better than nothing.

**Comment by Recchan** [comment]
`//Autobuffer
'use strict';

var prefs = {
  playlist: false,
  visible: true,
  hidden: true
};

var script = document.createElement('script');
// pause the video if spfready is not yet emitted and video is not a playlist
{
  const canplay = e => {
    document.removeEventListener('canplay', canplay);
    if (script.dataset.act !== 'true') {
      const href = location.href;
      if (prefs.playlist === false && (href.indexOf('&list=') !== -1 || href.indexOf('&index=') !== -1)) {
        return;
      }
      e.target.pause();
    }
  };
  document.addEventListener('canplay', canplay, true);
}

Object.assign(script.dataset, prefs);
script.textContent = `
  var yttools = window.yttools || [];
  yttools.noBuffer = {
    prefs: document.currentScript.dataset
  };
  yttools.push(e => {
    const policy = () => {
      const prefs = yttools.noBuffer.prefs;
      const href = location.href;
      return prefs.playlist === 'true' || href.indexOf('&list=') === -1 || href.indexOf('&index=') === -1;
    };
    const stop = () => {
      if (e.stopVideo) {
        yttools.noBuffer.prefs.act = true;
        e.stopVideo();
      }
    };
    // Method 0
    stop();
    // Method 1; stop subsequent plays
    document.addEventListener('yt-page-data-fetched', () => policy() && stop());
    // visibility
    document.addEventListener('visibilitychange', () => {
      const prefs = yttools.noBuffer.prefs;
      if (prefs.visible === 'true' && document.visibilityState === 'visible') {
        //e.playVideo();
        if (prefs.hidden === 'false') {
          yttools.noBuffer.prefs.visible = 'false';
        }
      }
      if (prefs.hidden === 'true' && document.visibilityState === 'hidden') {
        //e.pauseVideo();
      }
    });
  });
  // install listener
  function onYouTubePlayerReady(e) {
    yttools.forEach(c => {
      try {
        c(e);
      }
      catch (e) {}
    });
  }
  // https://youtube.github.io/spfjs/documentation/events/
  window.addEventListener('spfready', () => {
    if (typeof window.ytplayer === 'object' && window.ytplayer.config) {
      window.ytplayer.config.args.jsapicallback = 'onYouTubePlayerReady';
    }
  });
`;
document.documentElement.appendChild(script);
script.remove();`
This should disable autoplay and disable autobuffering until you click the video. This can be ran in another script or within the same script at the very top.
I uncommented the sections of code that I listed before and it was still working just fine.

**Comment by Recchan** [comment]
It seems like any attempt I'm doing at disabling autoplay through other means fails to load the video.

**Comment by psonnosp** [comment]
After I did the comment thing Firefox wont run the add-on after a restart cause it can't be verified.
And I have xpinstall.signatures.required set to false so don't get why that happen, what am I missing?

**Comment by ViperCode7** [comment]
[dougbenham](/dougbenham)
> The point is that you can open videos in a new tab and they won't play until you activate that tab. Not perfect but better than nothing.

IDK, tested youtube videos on a clean Chrome profile, opening videos in background does not activate them, so they don't play. Maybe something's up with your browser if it plays them in background.

**Comment by dougbenham** [comment]
> [dougbenham](/dougbenham)
> 
> > The point is that you can open videos in a new tab and they won't play until you activate that tab. Not perfect but better than nothing.
> 
> IDK, tested youtube videos on a clean Chrome profile, opening videos in background does not activate them, so they don't play. Maybe something's up with your browser if it plays them in background.

Yes I think you're right, I have some other extensions that might be affecting that behavior.

**Comment by Orrielel** [comment]
Don't know how related it is, but my videos wouldn't autoplay, even with Iridium told to do it.
Then I figured out it was Firefox's permissions for youtube that had Autoplay sound set to block

![Permissions](https://orrie.s-ul.eu/czP9vpYI)

**Comment by buitim** [comment]
> 
> 
> Don't know how related it is, but my videos wouldn't autoplay, even with Iridium told to do it.
> Then I figured out it was Firefox's permissions for youtube that had Autoplay sound set to block
> 
> ![Permissions](https://camo.githubusercontent.com/268dc206c1a4e91fd59ce9ff9ab4b553daa652aa/68747470733a2f2f6f727269652e732d756c2e65752f637a503976705949)

This is possibly a decent workaround for autoplay for now. Just keep autoplay enabled in Iridium. If you want autoplay, allow audio to automatically play in Firefox. If you don't want the video to autoplay, just block the video from automatically playing. Personally just tried both allowing and blocking autoplay using this method and it works. Thanks @Orrielel

**Comment by jasonhemann** [comment]
I think I'm seeing a similar issue w/ Iridium 0.2.5 on Chrome 71.0.3578.98 x64, OSX 10.13.6. However, even with the autoplay setting checked on the Youtube site, videos don't play. Disabling Iridium resolves this issue. I do have Tampermonkey 4.7.54 installed and enabled.

**Comment by touchnova** [comment]
> 
> 
> Don't know how related it is, but my videos wouldn't autoplay, even with Iridium told to do it.
> Then I figured out it was Firefox's permissions for youtube that had Autoplay sound set to block
> 
> ![Permissions](https://camo.githubusercontent.com/268dc206c1a4e91fd59ce9ff9ab4b553daa652aa/68747470733a2f2f6f727269652e732d756c2e65752f637a503976705949)

You're a savior.  Ever since the Firefox add-on debacle, videos haven't been autoplaying for me.  Your comment fixed this issue for me - THANK YOU!

> 
> 
> Don't know how related it is, but my videos wouldn't autoplay, even with Iridium told to do it.
> Then I figured out it was Firefox's permissions for youtube that had Autoplay sound set to block
> 
> ![Permissions](https://camo.githubusercontent.com/268dc206c1a4e91fd59ce9ff9ab4b553daa652aa/68747470733a2f2f6f727269652e732d756c2e65752f637a503976705949)

This suggestion actually fixed autoplay issues and 'click to unmute' issues I have only recently been experiencing on two different platforms.  Thank you!!!

**Comment by Nancok** [comment]
I still have this issue, when will it get fixed?

**Comment by swakefield81** [comment]
> I was going through the entire script to see which line was causing the issue when autoplay is off. By searching "!user_settings.player_auto_play", I got to this section of code that loads the video.
> ![2019-01-30 01_14_20](https://user-images.githubusercontent.com/20297783/51961928-6ef19d80-242c-11e9-8eea-b261ad9f09fc.jpg)
> By commenting out this section of code, the video loads just fine without having to turn on autoplay, which also makes the video play automatically when the tab goes into focus.

Yes but who wants it to play on focus. I want it to play when I click play. None of the fixes achieve this. It’s one of the main reasons I even used this plugin

**Comment by ElhemEnohpi** [comment]
[**@swakefield81**](https://github.com/swakefield81) commented on [Jun 21, 2019, 3:32 PM GMT+2](https://github.com/ParticleCore/Iridium/issues/671#issuecomment-504426853 "2019-06-21T13:32:08Z - Replied by Github Reply Comments"):
> > By commenting out this section of code, the video loads just fine without having to turn on autoplay, which also makes the video play automatically when the tab goes into focus.
> 
> Yes but who wants it to play on focus. I want it to play when I click play. None of the fixes achieve this. It’s one of the main reasons I even used this plugin

@swakefield81 commenting out that section and also adding the script from https://github.com/ParticleCore/Iridium/issues/671#issuecomment-459957104 does achieve that. Did you try it? You might have to switch to the userscript version if your browser won't let you modify your extensions.

**Comment by ParticleCore** [comment]
This issue has run its course and turning into a support issue for someone's script, there is nothing more to add to this issue at the moment. Locking it to avoid further derailment.

**Comment by ParticleCore** [comment]
Unlocking since version 1.0.0 has been released, let me know if this problem still persists.

**Comment by BobbyWibowo** [comment]
Yeah, the thing I commented in https://github.com/ParticleCore/Iridium/issues/734#issuecomment-538792214 should apply to all autoplay-related issues.

**Comment by chiptus** [comment]
still having a problem on chrome. You say v1 was released? I only see v0.25 on my computer

**Comment by gluons** [comment]
@chiptus Please see [1.0.0](https://github.com/ParticleCore/Iridium/releases/tag/1.0.0) release note.

> Unfortunately the API required for this method to work (webRequest.filterResponseData()) is only available in Firefox, Chrome appears to have decided to not implement it. It is only for this reason Chrome no longer has any support.
