### ISSUE TITLE
Development is currently on pause

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#673]
I apologize for not being able to post this sooner, but due to personal reasons I will be unable to resume development for the following weeks.

**Comment by silentbrains** [comment]
Take care, man, best of luck with whatever's going on.

**Comment by bahhax404** [comment]
Thank you  for your work. Youtube is not the same without your script. 
Take care

**Comment by DevAspirerKlaus** [comment]
> Youtube is not the same without your script.

I totally agree with that. I found it after I'd grown unsatisfied with others "most popular extensions". But Google/YouTube knows how to break things hehehe

@ParticleCore, take care. We will wait anxiously.

**Comment by JEmlay** [comment]
Just weeks?  That's nothing.  You do you.  We'll be here when you get back.

**Comment by mario98** [comment]
Wow, just one week of development paused and some functionality is already broked. This makes me realize how much effort it is to keep up with the development of the YouTube website, and how much effort you already put in this during the past years. Thank you very much for this wonderful script! Wishing you all the best!

**Comment by Navneet-Suresh** [comment]
Thank you for creating this awesome extension. Be well!

**Comment by Corruptinglyneedful** [comment]
I hope things are well and you get better with whatever is making you place the project on hold.

Maybe another user can fork the project in the meantime.  A lot of the features are broken right now and 
Google does this all the time, they regularly change and update things with no consideration into how it affects 3rd party scripting.

So yah, get better dude.

**Comment by pkmatador** [comment]
> Wow, just one week of development paused and some functionality is already broked. This makes me realize how much effort it is to keep up with the development of the YouTube website, and how much effort you already put in this during the past years. Thank you very much for this wonderful script! Wishing you all the best!

Well said!

--
**For those who don't know:** #679, #671, #672, ...

**Comment by mozkan007** [comment]
Hi, when will you continue developing? Thanks.

**Comment by Mattia98** [comment]
It has been a while that there hasn't been an update. There are quite a few bugs open. I'm not saying that you have to start developing again but this would not be a problem if you released this extension under the GPL. Then people could continue developing it and fix bugs. Please relicense this extension under the GPL. I hope you consider this proposal. Thanks.

**Comment by Gorthezar** [comment]
Anyone have any good alternatives since it seems for now this project is done?

**Comment by bahhax404** [comment]
> Anyone have any good alternatives since it seems for now this project is done?

Try Enhancer for Youtube. [here](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/)

**Comment by ParticleCore** [comment]
I'm locking this topic for now because this issue tracker is not meant for publicizing other extensions, anyone can do a quick search and find plenty of good or decent alternatives and also it was getting off-topic.
Work will resume when I have free time again.

**Comment by ParticleCore** [comment]
A new announcement has been made in 737
