### ISSUE TITLE
Support managed storage

### ISSUE THREAD

**Issue by klausenbusk** [ParticleCore/Iridium#674]
This make it easier to deploy Iridium automatic preconfigured.

Documentation:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#Managed_storage_manifests
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed

**Comment by ParticleCore** [comment]
What is the reason behind this suggestion? Any benefits over the current method or something else?
