### ISSUE TITLE
Userscript version with Violentmokey but it stopped working

### ISSUE THREAD

**Issue by ctorbaoglu** [ParticleCore/Iridium#676]
Browser Name: Maxthon
Browser Version: 5.2.7.400
Operating System: Windows 10 Pro 64Bit
Software Type: Userscript
Software Version: 0.2.5
Problem Description:
I read about Iridium became paid extension in Chrome but not the userscript version.
I am using the userscript version with Violentmokey but it stopped working yesterday without any warnings.
Youtube videos are on loading loop. Disabling all other extensions and userscripts (except Iridium) restarting the browser not helped

Steps to reproduce:  Enabling autoplay in the settings solved the problem.
Sorry for bothering.
Thanks for this extension

Thanks

**Comment by mikeloeven** [comment]
Is there a fix for the most recent version of Firefox ??
Running user script version under tamper monkey 
Getting endless spinning loop even with auto play disabled in iridium

**Comment by ParticleCore** [comment]
There is no support provided for Maxthon browser: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
