### ISSUE TITLE
[Feature Request] Move the Full Browser to the actual player controls

### ISSUE THREAD

**Issue by starmatt** [ParticleCore/Iridium#677]
Hello,

Instead of having the full browser button below the video, could we instead have it in the player controls (next to the fullscreen toggle, player settings button, etc.)? It would be easier to access and more natural/explicit when full browser is on and when using the mouse. I don't know if it is at all possible but it sure would be a nice QoL feature.

Thanks for your attention, and for your awesome work on this extension. It's really appreciated!

**Comment by impulsiva** [comment]
It would look messy...
