### ISSUE TITLE
iridium breaks with new youtube beta release

### ISSUE THREAD

**Issue by in1t3r** [ParticleCore/Iridium#679]
Iridium breaks the play of youtube videos. Page loads but video not. 
I tried to search for debugs in the console and developer tools but nothing was useful I guess its some function in your extension. I would need to study the extension to find it. Its annoying as there are some nice features that I use to make youtube more usable with your extension.

**Comment by Dr1Rabbit** [comment]
I have the same problems. Have to reload each video I open. If Iridium prevents autoplay, then it can`t be played be clicking on thumbnail.

Vivaldi v2.2.1388.37
Iridium v0.2.5

**Comment by Zarggg** [comment]
Duplicate of #671, #672. See those threads for an explanation.

**Comment by mattyount28** [comment]
I found a temporary fix: go to settings, video, and turn play videos automatically on. :)

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
