### ISSUE TITLE
Thumbnail playback not working on chrome os

### ISSUE THREAD

**Issue by nathgit** [ParticleCore/Iridium#681]
Thumbnail playback no longer works on Chrome OS (Version 71) as of a few minutes ago. All other features seem to work. I don't know if this is an iridium bug or not but I thought I'd submit it in case I'm not the only one having the issue.Obviously I have the option enabled.

**Comment by nathgit** [comment]
Am I the only one who has had this issue?

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
