### ISSUE TITLE
[Feature Request] Add "All Videos" link on channel pages

### ISSUE THREAD

**Issue by KoenigKrote** [ParticleCore/Iridium#684]
YouTube has, for some incomprehensible reason, removed a default "All videos" link for all channels by default.  I'm not a content provider so presumably there's a button somewhere hidden in the depths of the control panel to enable this, but the fact remains that there's no consistent easy way to just get a nice, big, old-school endless-scroll page of a channels content.
You can, however, always get to it by appending `/videos/` to the end of a channels home link, in the fashion of `youtube.com/user/channelnamegoeshere/videos/`

If there's a way to insert that link by default onto a channels homepage, that'd be swell.  I'm often trying to find content from somebody that I know vaguely chronologically, but is now impossible to find because the only videos accessible by the channel page are popular uploads and playlists, and it's super tedious to have to manually add the `/videos/` bit to the URL.

EDIT: To be more specific, this occurs on FireFox 61.0

**Comment by thepcwiz101** [comment]
I don't have this issue. 
![image](https://user-images.githubusercontent.com/31826503/52766821-038ffa00-2fee-11e9-9de5-325b441d029a.png)

**Comment by KoenigKrote** [comment]
Not sure what the issue is then.  I don't ever get header banners or the home/video/playlists selection, I just get these sorts of things that appear to be playlist collections.  Varies from channel to channel but most of them lack an explicit "uploads" link.

![iridium](https://user-images.githubusercontent.com/16270792/52894955-e7b46180-316f-11e9-9b93-6c3c1425fcee.png)

**Comment by thepcwiz101** [comment]
@KoenigKrote Well this is strange. I would try to delete all browsing data and re-login to everything your signed out of. Something is either corrupted or it may be related to youtube's end.

**Comment by thepcwiz101** [comment]
![image](https://user-images.githubusercontent.com/31826503/52896105-ad0af300-3188-11e9-81f5-b169d25284df.png)
wow i just turned youtube blue. (btw theres a better dark mode theme)
