### ISSUE TITLE
consider to join the Force...

### ISSUE THREAD

**Issue by kliop00023** [ParticleCore/Iridium#687]
Not star war lol and i am please that YePpHa is back lol
YePpHa/maia-yt: Currently codenamed maia-yt is a userscript (and browser extension) that enhances the user's experience on YouTube.
https://github.com/YePpHa/maia-yt

it is really a challenge since the Google engineer advancement and i hope there will be a stronger forage lol
Don't blame anyone:
“to learn and not to do is really not to learn. To know and not to do is really not to know.” 
― Stephen R. Covey

“Success is not final, failure is not fatal: it is the courage to continue that counts.” 
― Winston S. Churchill

**Comment by SW1FT** [comment]
Huh? That extension has been in the making for a long time and it's nowhere near close to Iridium in terms of features or completeness.
