### ISSUE TITLE
Can video Autoplay be suspended for playlists?

### ISSUE THREAD

**Issue by IMNdi** [ParticleCore/Iridium#69]
Question/enhancement:

Stopping autoplay for videos is one of the most cherished features of this script. However, it kinda defeats the purpose of having a playlist just run in the background.

Can we have a checkbox (or, if it already exists, where is it) that allows video to auto-start if in a playlist?

Ideally, this will only work if the page has advanced because of the Auto-Play next video; this way, regular links and browser session restores won't auto-play the video.

**Comment by ParticleCore** [comment]
There will be a quick controls section where the user will be able to toggle a few settings directly without having to go to the settings menu every time. Auto play control will be one of them, I just haven't had the time to get to that part yet.
