### ISSUE TITLE
[Feature Request] Expose block list in settings

### ISSUE THREAD

**Issue by user3200** [ParticleCore/Iridium#691]
It would be great if the list of blocked channels was exposed in settings as a plain text list with channel IDs on each line. The list could be updated, exported (via copy paste), and appended by simply pasting in channel IDs. Currently block channels are not exposed.

rationale:

- see the channels that I've blocked by their channel ID
- quickly delete channels from block list by removing them from the list
- add channels I want to block by simply appending them to the list
- can copy and paste in channels

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
