### ISSUE TITLE
Disable Scrolling When Mouse Hovering Over Video?

### ISSUE THREAD

**Issue by GT500org** [ParticleCore/Iridium#693]
YouTube has a new feature where the entire page scrolls even in fullscreen videos when you scroll the mouse wheel:
https://techdows.com/2018/11/youtube-in-full-screen-now-lets-you-scroll-down-video-to-see-description-and-comments.html

This is obnoxious, as when you scroll down to turn the volume down, it now scrolls the page as well.

I'm hoping that Iridium can be updated to suppress this when the option to "change volume using the mouse wheel" is enabled.

**Comment by LatGeek** [comment]
This totally broke scroll volume control for me as of a few days ago. In any view, having the cursor on the video would prevent it from scrolling, now it'll scroll even in fullscreen mode.

**Comment by EmilyxFox** [comment]
I installed this extension (for Chrome) specifically because I'm addicted to this feature, but it seems completely broken no matter if watching in full screen or not.

**Comment by Suddow** [comment]
I have the same issue, with volume control enabled the screen will still scroll up and down.

**Comment by MrAureliusR** [comment]
+1 here. I installed this extension primarily for this feature, as the only other extension that does this has gone to complete crap. Please fix this! <3

**Comment by wadawada** [comment]
Actually it's not completely broken
If you scroll up, you can still turn up the volume
but ya you can't turn down the volume by scrolling now!

**Comment by GT500org** [comment]
When I tried it, I noticed that the volume did change when scrolling down as well, however only while the mouse pointer was still over the video (which should be expected as that's how it works when a video isn't fullscreen), and scrolling back up would turn the volume back up (making it appear that the volume hadn't changed). I imagine that preventing the video from scrolling out of view when the player is in fullscreen mode would resolve any issues here, although admittedly that's merely an assumption based on my observations.

**Comment by serversdepot** [comment]
Found a workaround on chrome not sure about firefox
1. make sure you are using the default view and not cinema mode or full screen mode.
2. In the quick controls section, click on Full Browser. This will get it to work as it should.
3. Put it in full screen pressing f or F11 on your keyboard.
