### ISSUE TITLE
Video quality and video thumbnail problem

### ISSUE THREAD

**Issue by mozkan007** [ParticleCore/Iridium#694]
Hi,
I am using Iridium 0.2.5 on Chrome v73 and my problem is that  I open a video on Youtube and when I try to change video quality, the first click does not change the quality and just after the second click changes the video quality and it occurs on all videos. So I mean that when I want to change the video quality, I have to click to the cogwheel 2 times to change the video quality. But when  I disable Iridium there is no problem. I hope I could tell my problem correctly. Thanks.

Edit: My second issue is that when I open a channel video page, I subscribed, which has newly added videos, the thumbnails of the newly added videos are empty. You can see the photos below. Thanks again.

![Capture1](https://user-images.githubusercontent.com/16270347/54238940-dc641400-452a-11e9-9639-aa4d43226428.JPG)
![Capture2](https://user-images.githubusercontent.com/16270347/54238942-dc641400-452a-11e9-96ed-59e95d9c0bc7.JPG)

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
