### ISSUE TITLE
Playlist controls are broken

### ISSUE THREAD

**Issue by KaiusWolf** [ParticleCore/Iridium#696]
All of the playlist controls, reverse playlist, shuffle and repeat, are stuck behind a little three dot button that doesnt work, meaning they are all inaccessible.
![image](https://user-images.githubusercontent.com/5022302/54475481-ae602780-47e9-11e9-8438-bd25f18c0f47.png)

**Comment by KaiusWolf** [comment]
Bump?

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/issues/673

Do not spam the issue tracker please.

**Comment by KaiusWolf** [comment]
> 
> 
> #673
> 
> Do not spam the issue tracker please.

Whatever. I found something else to use that actually does what it says it does so im uninstalling this
