### ISSUE TITLE
Toggle switch shows up in comment box when the script is enabled

### ISSUE THREAD

**Issue by Jyrka98** [ParticleCore/Iridium#7]
![screenshot_271](https://cloud.githubusercontent.com/assets/7345717/26172359/c754a38a-3b50-11e7-8bb3-d9f0e782efed.png)

**Comment by ParticleCore** [comment]
Ouch, rogue styles, gotta take care of that.

**Comment by ParticleCore** [comment]
I've updated the stylesheet to prevent this from happening. To load it all you have to do is press Ctrl + Shift + R on the YouTube page to force the download of the newest css file instead of loading from cache.
