### ISSUE TITLE
Page scrolling issues while trying to control volume when mouse is inside video player

### ISSUE THREAD

**Issue by greenscarf07** [ParticleCore/Iridium#700]
While the mouse is inside video player (even when not in full screen), when trying to change the volume the volume does change but the page also scrolls. This isn't such a problem for turning the volume up as there is no where to scroll above the top of the page - but there is more of an issue when trying to reduce the volume (i.e. scroll down). As once you scroll down after a certain point - and the page scrolls down as well - your mouse is no longer inside the video player so it cannot control the volume anymore.

Hopefully there can be a fix to prevent page scrolling while the mouse is inside the video player in a future update.

**Comment by Skaronator** [comment]
Same as #693?

**Comment by greenscarf07** [comment]
the original issue of 693 only talks about issues with scrolling in full screen. there might be a single fix to both of these issues but there also might be two different solutions to fix scrolling in full screen as well as in standard view.

**Comment by zuexo** [comment]
There was a recent change to wheel & mousewheel events. [They are now passive by default](https://www.chromestatus.com/features/6662647093133312).

Simple fix if you are using latest Userscript is to change [#L3562](https://github.com/ParticleCore/Iridium/blob/9211d7d0bb0d5304c7fc10a09293143e928e0791/src/Userscript/Iridium.user.js#L3562) to
`document.addEventListener("wheel", this.changeVolume.bind(this), {"passive": false});`

**Comment by lefontanals** [comment]
By far this is the best script for youtube. with out it watching youtube is unbearable. Now, I wish somebody could jump in and fix it. this is by far the most helpful feature. The fix abode only deactivate it. any other ideas on how to fix it?

**Comment by Suddow** [comment]
> There was a recent change to wheel & mousewheel events. [They are now passive by default](https://www.chromestatus.com/features/6662647093133312).
> 
> Simple fix if you are using latest Userscript is to change [#L3562](https://github.com/ParticleCore/Iridium/blob/9211d7d0bb0d5304c7fc10a09293143e928e0791/src/Userscript/Iridium.user.js#L3562) to
> `document.addEventListener("wheel", this.changeVolume.bind(this), {"passive": false});`

How do I do this if I install the addon through the chrome interface regularly?

**Comment by diskdusk** [comment]
Also here because of this. Does the suggested change fix the issue or just deactivate the sound control? If it helps, I'll dig into how to change the script manually. :)

**Comment by iMagic16** [comment]
this issue is incredibly frustrating. How do I fix it using the passive feature?

**Comment by IanFanning** [comment]
> There was a recent change to wheel & mousewheel events. [They are now passive by default](https://www.chromestatus.com/features/6662647093133312).
> 
> Simple fix if you are using latest Userscript is to change [#L3562](https://github.com/ParticleCore/Iridium/blob/9211d7d0bb0d5304c7fc10a09293143e928e0791/src/Userscript/Iridium.user.js#L3562) to
> `document.addEventListener("wheel", this.changeVolume.bind(this), {"passive": false});`

Is this able to be edited with Iridium downloaded through the chrome store and not directly through GitHub?

**Comment by twifty** [comment]
Any news on this? I installed this extension primarily for the volume control feature. It's a shame it's not working!

**Comment by iMagic16** [comment]
I'm still unable to edit it

**Comment by allansramblings** [comment]
Unfortunately, the fix posted above no longer works. At least in Brave.

**Comment by stom66** [comment]
This issue is still present in Chrome 76.0.3809.100 and Iridium 0.2.5.

**Comment by iMagic16** [comment]
Fixed the issue - Finally understood the above comment.  

You will need userscript support to do this. Greasemonkey or tampermonkey will do.

Uninstall chrome store version first!

Visit:
https://github.com/iMagic16/Iridium/blob/06ce0c54a89f155bd135c463374fc32c4f849f8d/src/Userscript/Iridium.user.js

Click "raw file" on this page and install to your userscript app, then visit youtube and click the |> in top right to configure again

You can export settings from the chrome version before you transfer over

Video proof: https://drive.google.com/uc?id=1Gnr37iXFIfZrslX-1X53Vxx7fQqMDiyY

Enjoy

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
