### ISSUE TITLE
[Feature Request] YouTube Dark Mode

### ISSUE THREAD

**Issue by Jowat97** [ParticleCore/Iridium#701]
Many people asked to set the YouTube Theme also to the Dark Mode if I choose Dark Mode in Iridium. You replied that there is no guaranteed method to force Dark mode on YouTube. However, it is possible to do so. You just need to use Cookie injection, so you can fource YouTube to use always the Dark Mode.
Because you don't want anyone to submit code to your project, I just can give you the Code and the Cookie-Prefs you need to implement this feature.
document.cookie="PREF=f6=400&f5=30000;path=/;domain=.youtube.com";

**Comment by thepcwiz101** [comment]
This is pointless as all you need to do is enable dark mode by clicking on your profile picture on the upper right corner of the website. You will need to do this again if you clear your cookies or change browsers.

**Comment by Jowat97** [comment]
@thepcwiz101 Well, thats not true at all.. 
First at all, you need a Google Account and need to be logged in to activate the dark theme in YouTube. Second, it will only enable it for the current session. So if you for example restart your Browser or delete the cookies, you would need to enable it again.

With the Cookie injection, it would inject the necessary cookie every time you visit YouTube! So even if you don't have a Google Account or are not logged in, the Dark Theme would sill be enabled, even if I would delete the Cookies. I coded my own YouTube-AddOn with a dark theme and Double Speed. For the dark theme I used cookie injection and for double speed I used a JavaScript function. And it works fine, with Firefox and Chromium Browsers.

**Comment by thepcwiz101** [comment]
I literally tested dark mode before i logged in to my google account a few days ago and i could enable it with no problem. just look next to the login button in the 3 dots menu. The dark mode option will be the first thing you see in that menu.

**Comment by thepcwiz101** [comment]
But yea force enabling dark mode would be a good idea as clearing cookies does make it return back to the default white theme.

**Comment by ParticleCore** [comment]
You do not require an account to enabe dark mode on YouTube

![image](https://user-images.githubusercontent.com/9222661/55955313-0f372000-5c2f-11e9-8d08-1e3ab3d1145c.png)

**Comment by Jowat97** [comment]
@ParticleCore Yes, you are right. My mistake. However, you need to to that every time after the cookies get deleted. If someone use tools like CCleaner etc. he would have to do this every time he visits YouTube.
Like I mentioned in my previous post, by using cookie injection it would automatically enable Dark Mode in YouTube every time you visit it.
**document.cookie="PREF=f6=400&f5=30000;path=/;domain=.youtube.com";**
Would it be possible to add this to your addon?

**Comment by nancydrewstark** [comment]
I have read some information at [rocketfiles.com](https://rocketfiles.com/articles/how-to-activate-youtube-dark-mode-in-chrome-firefox-edge-opera). If we are speaking about Chrome you can do this with the help of the developer mode. It na be enough to put ocument.cookie=”VISITOR_INFO1_LIVE=fPQ4jCL6EiE; path=/” in the Console Tab and activate dark mode in settings.

**Comment by ParticleCore** [comment]
Implementation is being done in #741

**Comment by ParticleCore** [comment]
This feature has been implemented in version 1.0.0
