### ISSUE TITLE
Channel block button won't block YouTube Movies from recommendations

### ISSUE THREAD

**Issue by slaugaus** [ParticleCore/Iridium#702]
Browser Name: Google Chrome

Browser Version: 73.0.3683.86 64-bit

Operating System: Windows 10

Software Type: Userscript

Software Version: 0.2.5

Userscript Manager: Tampermonkey

Userscript Manager Version: 4.8

Problem Description: The channel "YouTube Movies" can't be added to the channel blacklist using the block button. I never want to rent a movie on YouTube, so I'd rather have that space in my recommendations for actual videos.

Steps to reproduce: 
1. Have a movie in your recommendations.
2. Mouse over the thumbnail and click the block button.
3. Nothing happens!

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
