### ISSUE TITLE
Update to the Español de Latinoamerica

### ISSUE THREAD

**Issue by rayman89** [ParticleCore/Iridium#703]
There were a few untranslated words and some stuff that was not easy to understand in Spanish so I decided to share my changes hope it's useful and if the dev decides is good enough then implement it.

https://hastebin.com/aqevufimel.json

**Comment by ParticleCore** [comment]
The link is not working and please submit your suggestions via push: https://github.com/ParticleCore/Iridium/wiki/Locale-instructions
