### ISSUE TITLE
Iridium Causes YouTube To Constantly Reload

### ISSUE THREAD

**Issue by indigo15** [ParticleCore/Iridium#711]
**Browser Name:** Mozilla Firefox
**Browser Version:** 66.0.3 (64-bit) 
**Operating System:** Windows 10
**Software Type:** Add-on
**Software Version:** 0.2.5
**Problem Description:** Sometimes, when Iridium is enabled, it causes all YouTube tabs to constantly reload every few seconds, making YouTube unusable unless I disable Iridium. This has been a major problem over the last several weeks. I really like Iridium and this is the only issue I have with it.

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
