### ISSUE TITLE
Despite having a forced quality, when viewing the next video in a playlist it isn't enforced

### ISSUE THREAD

**Issue by fhlox** [ParticleCore/Iridium#712]
I have my forced quality setting on 1080p which works fine, but while watching videos that are in playlists, each one after the first goes back to auto. This occurs regardless of whether I am in fullscreen or not, or whether the video goes to next by finishing the previous one or clicking the next button.

**Comment by fragande** [comment]
See the pinned post at the top. Addon isn't being maintained and Youtube change stuff frequently. Until the maintenance is resumed by the creator or the project is forked you'll have too look for other alternatives or accept that functionality is severely broken.

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
