### ISSUE TITLE
No longer able to install

### ISSUE THREAD

**Issue by XEntombmentX** [ParticleCore/Iridium#713]
Browser Name: Firefox

Browser Version: 66.0.3

Operating System: Windows 10 64-bit

Problem Description: With the intent of reinstalling to attempt to fix the issue with the playlist buttons not appearing, I uninstalled Iridium. Upon trying to reinstall, the Firefox Add-on store told me that the download failed and to check my connection. My internet is working fine. Afterwards, I downloaded the add-on and tried to install from file, which gave me an error that says the add-on is corrupted.

Steps to reproduce: Try to download from add-on store, or try to install from file

**Comment by fullerspectrum** [comment]
This is a [Firefox issue](https://github.com/mozilla/addons/issues/978)

**Comment by XEntombmentX** [comment]
I was able to download other add-ons without any problems, though. And that doesn’t explain the extension file being labeled as corrupted.

**Comment by Squall-Leonhart** [comment]
its labelled as corrupt because the signing key is invalidated.

**Comment by MrPurpleGuy1987** [comment]
Yes, this is a Firefox issue.
