### ISSUE TITLE
No video playback with hovering over thumbnails

### ISSUE THREAD

**Issue by doyouseelights** [ParticleCore/Iridium#716]
Browser Name: Chrome

  Browser Version: 74.0.3729.131

  Operating System: Windows 10

  Software Type: extension

  Software Version: 0.2.5

  Userscript Manager: ?

  Userscript Version: ?

  Problem Description: In settings on the general page under the thumbnails heading, I have checked the options "Play videos by hovering the thumbnails" and "Shift key toggles audio on video thumbnail playback". However when I hover over thumbnails on youtube, I only get the default 3 second preview and not the full video playback. Additionally pressing shift does nothing.

  Steps to reproduce: Go to youtube and hover over any thumbnail

  Additional details: I have already tried restarting the browser, disabling and enabling the feature in question, disabling and reenabling iridium, disabling all other extensions.

**Comment by AtHeartEngineer** [comment]
Same on firefox 68 on mac

**Comment by Gabarito007** [comment]
No response about that until today?
Same here with Firefox 68 on Windows 7.

**Comment by DanieLoche** [comment]
Same here, Firefox 68 on Windows 10 and Linux (Ubuntu 18.04).

**Comment by JackDinn** [comment]
same :( Linux Manjaro KDE , firefox 69

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
