### ISSUE TITLE
clicking block button opens up the video and doesn't block anything

### ISSUE THREAD

**Issue by super-lurker** [ParticleCore/Iridium#717]
specs:
firefox 66.0.5 x64
iridium 0.2.5
windows 10 pro x64

**Comment by Paulaob79** [comment]
You mean the "cross button"? It works OK for me. I'm using Chrome 74.0.3729.169 and Iridium 0.2.5 from the Chrome store: https://chrome.google.com/webstore/detail/iridium-for-youtube/gbjmgndncjkjfcnpfhgidhbgokofegbl

Try them.

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
