### ISSUE TITLE
No video playback once Iridium is enabled

### ISSUE THREAD

**Issue by mrzed** [ParticleCore/Iridium#718]
Once Iridium as installed all YouTube videos stopped playing - only the spinning chasing line are displayed on a black background. I disabled ALL other extensions without any change. Once Iridium was disabled, all videos started playing back again. I have tested this with the same results in Chrome and Firefox. I have enabled and disabled each setting in Iridium without a change to the issue.

Firefox 67.0
Chrome 74.0.3729.169
Windows 10 Enterprise

I love the blacklisting portion of this extension, so I hope to find resolution for this soon. Thanks!

**Comment by ganego** [comment]
We know. Has been discussed to death.
Enable autoplay.  
And close the ticket.

**Comment by AlexFundorin** [comment]
No only autoplay, but also endless spinning circle on the black background. Doesn't happen with a script.

**Comment by ParticleCore** [comment]
Duplicate of #671
