### ISSUE TITLE
Fullbrowser mode is not activated until the video is paused

### ISSUE THREAD

**Issue by MammothJerk** [ParticleCore/Iridium#719]
Browser Name: Chromium

  Browser Version: 74.0.3689.0 (Official Build) (64-bit)

  Operating System: Windows 10

  Software Type: Userscript

  Software Version: 0.2.5

  Userscript Manager: Tampermonkey

  Userscript Version: v4.8.41

  Problem Description: 
When opening a video in a new tab with the full browser mode active, the video will start playing immediately but the full browser mode will not automatically activate. the icon will be lit and flicking it on and off does nothing. I have to first pause the video and as soon as i pause it the video snaps into the full browser mode

  Steps to reproduce: 
Have the full browser mode activated
open a video in a new tab
open the tab
the video should now start auto-playing
the full browser icon should be lit up but the video will not be stretched
pause the video and it should snap to the correct dimensions.

  Additional details: I think this is a problem with how the video loads, in Chromium the video auto-plays before the rest of the elements on the page is loaded, so i'm not quite sure how to fix this.

**Comment by kilara1988** [comment]
I also get this sometimes with Firefox. Maybe sometimes some settings get applied before others that later mess up the fullbrowser setting.

**Comment by MammothJerk** [comment]
to fix this problem i installed this userscript
https://greasyfork.org/en/scripts/811-resize-yt-to-window-size

would be nice if it could be incorporated into iridium since it's really nice

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
