### ISSUE TITLE
[suggestion] Modular development

### ISSUE THREAD

**Issue by MattSturgeon** [ParticleCore/Iridium#72]
I've noticed that this project is effectively a [very large js file][userscript].

While I'm sure this works fine, I can't help but feel it would be easier to maintain (and for new devs to contribute) if it were broken down into smaller modules then built by a build tool.

Using browserify or webpack would enable using modules and imports in development and then running a command to output a single js file. Using gulp or grunt would enable more robust/expandable build tasks, and could also build on top of browserify or webpack.

[userscript]: https://github.com/ParticleCore/Iridium/blob/a9014f59c4eb9296b54440ac7a36c8b04f7e9f40/src/userscript/Iridium.user.js

**Comment by ParticleCore** [comment]
The end result would be unfriendly code for amateur javascript developers that want to tinker with the source code. It would also be a nightmare to get it approved on AMO every time a new version is released.

It works well this way and I don't intend to change it.
