### ISSUE TITLE
Autoplay not working when opening a video in a new tab

### ISSUE THREAD

**Issue by Fooughhy** [ParticleCore/Iridium#720]
I believe this is a change by Youtube as, if I disable all extensions, this is the default behaviour. 

But if autoplay is enabled, my interpretation would be that if should autoplay even if a video is opened in a new tab.

To reproduce this:
Disable all extensions
Open youtube and Ctrl+click on a video

The video will not autoplay.

If this is done with only Iridium enabled, and autoplay is enabled, the same behavior is experienced.

Browser: Firefox 67.0
OS: Windows 10 (1809)

**Comment by Kenaestic** [comment]
So after dealing with this for an hour I found out Firefox is the culprit here. You have to allow [autoplay for the webpage.](https://i.imgur.com/RU83LQQ.png) It's not a bug, though. But rather a feature that's put in a pretty inconvenient place.

**Comment by BitGrub** [comment]
Kenaestic has the answer. It's not an Iridium issue, it's a Firefox feature.

**Comment by mikeloeven** [comment]
I am having a similar issue however its inverted. If autoplay videos is Enabled in Iridium the video will play normally however if auto play is disabled the video will not load properly and cannot be manually started figured i would mention it here since it seems like it may be related

**Comment by Fooughhy** [comment]
Yeah, changed the setting for Firefox, and it's working now!

**Comment by Fooughhy** [comment]
Not an Iridium issue.
