### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by swakefield81** [ParticleCore/Iridium#722]
I have no issue with the dev having to take a break from development, we use it for free after all but having to enable autoplay for the rest of it to work is annoying.

So is there a solution that anyone has that can prevent autoplay until the dev returns to active development and fixes it?

**Comment by EchoDev** [comment]
Enable autoplay in Iridium and disable autoplay in your browser.

Set media.autoplay.default to 2 for Firefox, don't know what it is for Chrome.

**Comment by ParticleCore** [comment]
Duplicate of #671
