### ISSUE TITLE
Disabling autoplay prevents videos from playing altogether.

### ISSUE THREAD

**Issue by Santademon** [ParticleCore/Iridium#724]
Browser Name: Firefox, Chrome

  Browser Version: 75 (Chrome), 67 (Firefox)

  Operating System: Windows 10

  Software Type: Home, 64 bit

  Software Version: 1809

  Problem Description: Videos don't play at all when autoplay is disabled

  Steps to reproduce: Attempt to play video with autoplay disabled.

  Additional details:

**Comment by karma12gaming** [comment]
Having the same issue. Turning autoplay on allows videos to play.

Browser: Firefox 67.0.4
Operating System: Windows 7 x64 Pro
Iridium: 0.2.5

**Comment by ParticleCore** [comment]
Duplicate of #671
