### ISSUE TITLE
what exactly is breaking the code?

### ISSUE THREAD

**Issue by wadawada** [ParticleCore/Iridium#725]
I like the scripts so much and I was really upset when I found out it broke and stop updating.
But then I figured enabling "play videos automatically" in settings can make it work again, at least the video is playing as expected now
I can find another script in greasyfork to stop youtube autoplay, so that is not a big problem

However, sometimes videos will keep loading without playing. I wonder if it's caused by some parts in the scripts. Does anyone figure what exactly is breaking the script so maybe we can add a  to disable that temporarily?
Or what are the options in iridium-settings that are broken so I can enable/disable it to avoid videos infinite loading?

And if someone know any alternative, please also message me in my repository, since I don't think you can post alternative here. I haven't found any scripts that provide more video info, like total video counts and thumbnails, that also work in the new version of YouTube.

Thanks!

Broken functions
stopped play videos automatically
Display uploaded videos number
Display how long the video was uploaded

**Comment by TTSKarlsson** [comment]
I've got Iridium on autoplay, but have disabled autoplay in firefox, this works for me as I tend to open a new tab to play any video (ie. using middle mouse button). The way Youtube is made though means that when you click a video it doesn't reload the page which means your click gives youtube permission to play the video, as if the thumbnail is a play button.

**Comment by bskyb-backport** [comment]
youtube will soon forbid all scripts so no one will make new ones - youtube developers and google chrome developers hate scripts because they are unsafe so they will kill all scripts in 2020

**Comment by TTSKarlsson** [comment]
Do you have any source for that, @bskyb-backport ? It would be interesting to know the details of how they're going to achieve banning Javascript on Firefox.

**Comment by bskyb-backport** [comment]
there is chrome roadmap site that also shows the stance from other browser developers and 3rd party software community - it shows huge list of soon to be deleted features in 2020 and all browser developers agreeing to it firefox included

**Comment by TTSKarlsson** [comment]
I'm sorry, I couldn't find anything online about that. The closest I came was some really old articles about Chrome wanting to remove flash all together in 2020, but nothing about that they will remove Javascript, DOM nor extensions.

I'm pretty sure that with JS we don't need Flash anyway, we can run Flash containers in JS if need be. I'm all for removing obsolete features and I would also understand if Youtube limited their API a little more to prevent mass downloads. They've been very generous with that so far except for banning extensions that help with that on their own chrome store. That kind of banning only makes people use better and safer browsers anyway.

**Comment by filips123** [comment]
@ParticleCore Can you change project licence to GPL or MIT? I'm sure people would like to contribute to it and create new features and bug fixes.

**Comment by wadawada** [comment]
> youtube will soon forbid all scripts so no one will make new ones - youtube developers and google chrome developers hate scripts because they are unsafe so they will kill all scripts in 2020

oh my god... really? do you have source for that?

**Comment by filips123** [comment]
@bskyb-backport Which scripts will they forbid? Do you mean Chrome extensions?

**Comment by wadawada** [comment]
Currently I'm blocking full browser and autoplay because it block the views of views# and I have other scripts for those functions

`//"<button id='iri-quick-control-auto-play'>" +
//"<svg viewBox='0 0 20 20' height='20' width='20'>" +
//"<polygon points='3 2 16.9 10 3 18'/>" +
//"</svg>" +
//"<div class='iri-quick-controls-tooltip' data-locale='text|button_auto_play'></div>" +
// "</button>" +
//"<button id='iri-quick-control-full-browser'>" +
// "<svg viewBox='0 0 20 20' height='20' width='20'>" +
//"<path d='M0 4v12h20V4H0z M12 12H2V6h10V12'/>" +
// "</svg>" +
// "<div class='iri-quick-controls-tooltip' data-locale='text|button_full_browser'></div>" +
//"</button>" +`

**Comment by wadawada** [comment]
//"<button id='iri-quick-control-auto-play'>" +
//"<svg viewBox='0 0 20 20' height='20' width='20'>" +
//"<polygon points='3 2 16.9 10 3 18'/>" +
//"</svg>" +
//"<div class='iri-quick-controls-tooltip' data-locale='text|button_auto_play'></div>" +
// "</button>" +
//"<button id='iri-quick-control-full-browser'>" +
// "<svg viewBox='0 0 20 20' height='20' width='20'>" +
//"<path d='M0 4v12h20V4H0z M12 12H2V6h10V12'/>" +
// "</svg>" +
// "<div class='iri-quick-controls-tooltip' data-locale='text|button_full_browser'></div>" +
//"</button>" +

**Comment by wadawada** [comment]
> @bskyb-backport Which scripts will they forbid? Do you mean Chrome extensions?
> 
> I do not know if they can afford something like this. But it will be great because more people would switch to Firefox. 😃

why do you think firefox is better than chrome? don't you think firefox is more bulky than chrome?

**Comment by filips123** [comment]
> 
> 
> > @bskyb-backport Which scripts will they forbid? Do you mean Chrome extensions?
> > I do not know if they can afford something like this. But it will be great because more people would switch to Firefox. 😃
> 
> why do you think firefox is better than chrome? don't you think firefox is more bulky than chrome?

Firefox changed a lot in the last few years. It's now as fast as Chrome or even faster on some websites. And a lot more customisable.

**Comment by mikeloeven** [comment]
@bskyb-backport 
They dont care about tampermonkey they want to remove foreign code execution to break adblockers and the scripts used to disarm anti adblock countermeasures because $$MONEY$$

**Comment by ParticleCore** [comment]
Closed due to #737
