### ISSUE TITLE
Alternatives?

### ISSUE THREAD

**Issue by Westward12** [ParticleCore/Iridium#726]
Can anyone recommend a similar alternative script to Iridium?
Everything I google search for ends up at other discontinued scripts or leading me on tangents to useless review sites...

**Comment by bskyb-backport** [comment]
youtube keeps killing scripts because they disable ads - it is impossible for regular developers to keep updating scripts against google attacks

**Comment by ParticleCore** [comment]
@Westward12 This issue tracker is not for advertising other's products as it will lead to people using it for support to those products as well. Please use other platforms for this kind of questions, I would suggest Reddit as it has a good community overall willing to help others.
