### ISSUE TITLE
"Display uploaded videos number" and "Display how long the video was uploaded" doesn't work anymore

### ISSUE THREAD

**Issue by welovfree** [ParticleCore/Iridium#728]
Windows 10 Version 1903 (OS Build 18362.239)
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Tampermonkey v4.8.41

**Comment by briank6932** [comment]
Yea I have the same problem, I'm on Chrome 75 and using the userscript on Tampermonkey

**Comment by wadawada** [comment]
yes... just noticed
sad...looking for alternatives

**Comment by eduzappa18** [comment]
Something changed in the `ytInitialData` object

https://github.com/ParticleCore/Iridium/blob/9211d7d0bb0d5304c7fc10a09293143e928e0791/src/Userscript/Iridium.user.js#L1585-L1586
I suppose it's something easy to fix...
I hope @ParticleCore can fix it asap.

**Comment by eduzappa18** [comment]
looks like youtube reverted back the changes
now it's working again

**Comment by bskyb-backport** [comment]
youtube auto generates uploads playlist for every channel you can find number of videos in it

**Comment by theorist-complex** [comment]
This seems to be broken again. :(

**Comment by wingfixer** [comment]
Yep, broken again.

**Comment by PaveMentman** [comment]
---
Broken again on my end also.
---
---

**Comment by welovfree** [comment]
Yeah! the problem manifested again.

**Comment by DanieLoche** [comment]
Same problem here.

But feels like the addon is no more updated...

**Comment by eduzappa18** [comment]
For the people using the userscript and @ParticleCore:
To fix the "Display uploaded videos number" issue. Go to the lines 1504  and 1656
and replace where it says `owner-container` with `text-container`
It worked for me on Firefox and Chrome

--- 
https://github.com/ParticleCore/Iridium/blob/9211d7d0bb0d5304c7fc10a09293143e928e0791/src/Userscript/Iridium.user.js#L1504
https://github.com/ParticleCore/Iridium/blob/9211d7d0bb0d5304c7fc10a09293143e928e0791/src/Userscript/Iridium.user.js#L1656

**Comment by theorist-complex** [comment]
> 
> For the people using the userscript and @ParticleCore:
> To fix the "Display uploaded videos number" issue. Go to the lines 1504 and 1656
> and replace where it says `"owner-container"` with `"text-container"`
> It worked for me on Firefox and Chrome
> 

Works perfectly. Thank you so much for this.

**Comment by DanieLoche** [comment]
> For the people using the userscript and @ParticleCore:
> To fix the "Display uploaded videos number" issue. Go to the lines 1504 and 1656
> and replace where it says `"owner-container"` with `"text-container"`
> It worked for me on Firefox and Chrome

I am currently using Iridum on Firefox (installed from Firefox Extension site) - Windows. Where can I find the code on my install to edit it ? I guess somewhere in %APPDATA%, but I found nothing manually...

**Comment by ParticleCore** [comment]
> 
> 
> > For the people using the userscript and @ParticleCore:
> > To fix the "Display uploaded videos number" issue. Go to the lines 1504 and 1656
> > and replace where it says `"owner-container"` with `"text-container"`
> > It worked for me on Firefox and Chrome
> 
> I am currently using Iridum on Firefox (installed from Firefox Extension site) - Windows. Where can I find the code on my install to edit it ? I guess somewhere in %APPDATA%, but I found nothing manually...

The fix @eduzappa18 shared is only for the userscript version. If you are using the extension version like you said then you'd have to extract the extension source code, modify it, repack it and then install it manually as an extension that you are developing. I'm, not going to explain how to do this step by step, there are plenty of instructions online and easy to find, but I'd advise you to install the userscript version instead since it will make all of this easier.

**Comment by wadawada** [comment]
> For the people using the userscript and @ParticleCore:
> To fix the "Display uploaded videos number" issue. Go to the lines 1504 and 1656
> and replace where it says `"owner-container"` with `"text-container"`
...
Thanks for you solution, 
but I think it only fixes "time updated" and still I can no longer see the uploaded videos number
Is it just me or it doesn't fix the count number?

**Comment by DanieLoche** [comment]
> 
> 
> > > For the people using the userscript and @ParticleCore:
> > > To fix the "Display uploaded videos number" issue. Go to the lines 1504 and 1656
> > > and replace where it says `"owner-container"` with `"text-container"`
> > > It worked for me on Firefox and Chrome
> > 
> > 
> > I am currently using Iridum on Firefox (installed from Firefox Extension site) - Windows. Where can I find the code on my install to edit it ? I guess somewhere in %APPDATA%, but I found nothing manually...
> 
> The fix @eduzappa18 shared is only for the userscript version. If you are using the extension version like you said then you'd have to extract the extension source code, modify it, repack it and then install it manually as an extension that you are developing. I'm, not going to explain how to do this step by step, there are plenty of instructions online and easy to find, but I'd advise you to install the userscript version instead since it will make all of this easier.

That's exactly the information I needed to know. :)
Being french and not really familiar with navigators extensions, I didn't know what "userscript" was. Thanks ! :) 

Now that you're here... Do you still plan in updating this amazing addon ? :p

**Comment by Yaanu** [comment]
The manual fix mentioned above works, but it seems to only work once, then carry over the video count onto other channels. That is, you can be watching Channel A and get Channel A's video count, then move on to Channel B while still seeing Channel A's numbers, as well as a link to Channel A's uploads tab on their main page.

I'd fix this myself but I'm not sure what to do.

**Comment by theorist-complex** [comment]
Im also experiencing the same issue as Yaanu. You have to reload the page specifically before the correct numbers/link populates after moving on to the next channel.

**Comment by ParticleCore** [comment]
Please don't use the issue tracker for topics that are outside the scope of the repository such as support for a fix that another user suggested.

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
