### ISSUE TITLE
Playlist controls are completely nuked

### ISSUE THREAD

**Issue by SpamCam** [ParticleCore/Iridium#731]
No matter what I alter in the settings, the shuffle, loop, and even the reverse button on YouTube playlists are simply missing.
![playlist controls](https://user-images.githubusercontent.com/53628142/62401125-df01ed00-b54f-11e9-8c60-69ad58869628.PNG)

**Comment by bskyb-backport** [comment]
change your browser user agent to Opera 33 then youtube will use older version of playlist controls and iridium reverse button will come back

**Comment by bskyb-backport** [comment]
something like this - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32

**Comment by XEntombmentX** [comment]
> 
> 
> change your browser user agent to Opera 33 then youtube will use older version of playlist controls and iridium reverse button will come back

Can you provide the user agent string for that?

**Comment by XEntombmentX** [comment]
> 
> 
> something like this - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32

Wouldn't that set the user agent to Opera 46?

**Comment by XEntombmentX** [comment]
> 
> 
> something like this - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32

Using this string value prevents anything on the page from showing, except for the video itself.
![image](https://user-images.githubusercontent.com/50261836/62626370-3cea5800-b8f5-11e9-9475-68beefe84ee9.png)

**Comment by XEntombmentX** [comment]
I got it to work; here's the correct string value for Opera 33: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36 OPR/33.0.1990.115

**Comment by XEntombmentX** [comment]
While this does get the controls to show up again, the reverse playlist function still does not work properly. After changing my user agent, it worked for one video and stopped.

**Comment by bskyb-backport** [comment]
sometimes i feel like youtube developers are spying on my attempts to hack their website - every time i find a user agent that brings back playlist controls the next day youtube devs ban it and force feed newest polymer

**Comment by ParticleCore** [comment]
Please don't use this repository for doing side scripting, do host your own solutions on your own repos or preferred host locations otherwise this will spam everyone subscribed to the issues.

**Comment by ParticleCore** [comment]
Closed due to https://github.com/ParticleCore/Iridium/tree/1.0.0
