### ISSUE TITLE
Adblock is Disabled

### ISSUE THREAD

**Issue by MemesDank456** [ParticleCore/Iridium#735]
Every time I launch Chrome, I have to uninstall and reinstall Adblock Plus because it keeps getting disabled. After I disabled Iridium, this stopped happening.

**Comment by Eisys** [comment]
Don't use ABP.
uBlock Origin is better.

**Comment by ParticleCore** [comment]
Iridium has no capability to disable other extensions, it would be a serious security issue and more importantly it is something that they would have to fix on their end, not here.
