### ISSUE TITLE
YouTube video don’t play with Iridium enabled anymore

### ISSUE THREAD

**Issue by DaneeBound** [ParticleCore/Iridium#738]
Browser Name: Firefox

Browser Version: Firefox 70.0b6

Operating System: Windows 10 19H1

Software Type: Extension

Software Version: 0.2.5 (latest)

Userscript Manager: none

Userscript Manager Version: none

Problem Description: starting today, YouTube video refuse to play with the extension enabled, the page loads fully, but the player just hangs at the loading circle even as I see the buffer progress bar advance.

Steps to reproduce: load any video with Iridium enabled.

**Comment by DaneeBound** [comment]
Update: tried the Userscript version of Iridium,
same issue.

**Comment by ParticleCore** [comment]
Closed due to #737
