### ISSUE TITLE
Iridium buttons block video post date on new youtube layout on lower resolutions

### ISSUE THREAD

**Issue by AlexFDR** [ParticleCore/Iridium#744]
https://i.imgur.com/14X1srC.png
Example above, at lower resolutions the buttons that are usually to the right cover the post date, the date's still there (if you select the views and drag to the right you can still select it and copy it) but it's just covered up by the buttons.

**Comment by ParticleCore** [comment]
That's the normal YouTube behavior, they have it configured to only show the most relevant information when the page size is too small.

Here's an example of the same behavior despite the extension not being installed.

![Screenshot_2019-09-30 Synthwave Emotions - Stranger Waves (Full Album - Official) - YouTube](https://user-images.githubusercontent.com/9222661/65865079-660dee80-e362-11e9-83df-df46d3a6a761.png)
