### ISSUE TITLE
WTF IS THIS NEW UPDATE?! TRASH!

### ISSUE THREAD

**Issue by ELECTROHAXZ** [ParticleCore/Iridium#746]
What happened to the nice addon?! I go to use youtube and see it's missing the features, then check the addon and you removed everything! What do you mean coming soon for EVERYTHING!? It's useless now, it does nothing more than regular youtube. It wasn't broke before, there was no need to fix it! Any way to get the old version back??

**Comment by BobbyWibowo** [comment]
> Any way to get the old version back??

https://github.com/ParticleCore/Iridium/issues/745#issuecomment-539180297

https://github.com/ParticleCore/Iridium/issues/737#issuecomment-539214098

**Comment by ELECTROHAXZ** [comment]
> 
> 
> > Any way to get the old version back??
> 
> [#745 (comment)](https://github.com/ParticleCore/Iridium/issues/745#issuecomment-539180297)
> 
> [#737 (comment)](https://github.com/ParticleCore/Iridium/issues/737#issuecomment-539214098)

Thank goodness! New update is dreadful, literally has nothing!

**Comment by N8Z7JMYLU** [comment]
Neither the new or old version are functional. The settings page lead to a not found error. Installing the user.js with Tampermonkey or Greasemonkey both fail.
