### ISSUE TITLE
Like/Dislike keyboard shortcuts

### ISSUE THREAD

**Issue by MattSturgeon** [ParticleCore/Iridium#75]
It would be really useful to have a keyboard shortcut to like/dislike videos.

Possibly `Shift+L` for like and `Shift+K` for dislike?

**Comment by 2tolik** [comment]
@MattSturgeon there is one [existing solution](https://greasyfork.org/en/scripts/34049-youtube-like-dislike-video-and-skip-ad-keyboard-shortcuts/code), not compatible with Iridium (as of now), unfortunately

**Comment by MattSturgeon** [comment]
Good spot @2tolik, that [script] should work fine when combined with iridium, however Iridium inserts the Quick Controls buttons where it searches for like/dislike buttons. They can be made compatible by having the script be more specific, e.g. looking for buttons in `ytd-video-primary-info-renderer 
 ytd-menu-renderer` instead of just `ytd-video-primary-info-renderer`. See my comment [here](https://greasyfork.org/en/forum/discussion/33581/x) or a [pastebin](https://pastebin.com/HyYmWYYx) of the script with a line added to make it compatible.

@ParticleCore should also be able to add similar functionality into Iridium pretty easily, since the [script] you linked shows how to find and activate the relevant buttons.

[script]: https://greasyfork.org/en/scripts/34049-youtube-like-dislike-video-and-skip-ad-keyboard-shortcuts/code
