### ISSUE TITLE
iridium not doing anything but making videos not autoplay

### ISSUE THREAD

**Issue by AshleighTheCutie** [ParticleCore/Iridium#751]
Huh, on both Windows and Linux I've had the same issue happen.
I open Youtube.
I open a video.
Iridium's added buttons look like oversized "OK" buttons from Windows XP.
Reload the page.
Everything Iridium adds not loading.
Videos not autoplaying.
Volume normalization broken.
No way to configure Iridium, as the settings page is "coming soon."

Any help here?

**Comment by ParticleCore** [comment]
Duplicate of #745
