### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by Hunam6** [ParticleCore/Iridium#752]
It's not really an issue as such but in the previous version, I found the settings not really intuitive, that's why as much as possible, please try to make the settings more organized.

**Comment by ParticleCore** [comment]
I only have my point of view to decide what can be intuitive. In which way could it be better organized in order to make them more intuitive?
I've even added an shortlink that allows the user to read a more detailed explanation for each feature if the summary is not very clear.

**Comment by Hunam6** [comment]
I made a "small" representation of my idea (it took me all afternoon because it's the first time in my life that I do this):

![image](https://user-images.githubusercontent.com/38606542/66509836-1357d380-ead4-11e9-898c-5ba10dfcfdda.png)
![image](https://user-images.githubusercontent.com/38606542/66509811-09ce6b80-ead4-11e9-9c55-768a377060e6.png)
Don't mind the left panel it's not very nice.


And here is also an example of option sorting, I did it according to the options of the old version of Iridium:

![image](https://user-images.githubusercontent.com/38606542/66509219-de974c80-ead2-11e9-91cb-aba97a5429a9.png)

**Comment by ParticleCore** [comment]
Thanks for the suggestions and the lengths you went through. I won't be implementing an advance section, I don't really think there is any need for that, but the organization will surely be taken into account.
