### ISSUE TITLE
Implement HFR (60fps) control

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#753]

**Comment by SAMGameDev** [comment]
disbaleing 60fps not working anymore

**Comment by ParticleCore** [comment]
@SAMGameDev This is not a feature that exists in version 1.x yet, it is still being developed, that's what this issue is about.

**Comment by SAMGameDev** [comment]
i see thanks, i was using this extension from a long time for this feature it was fine suddenly this feature stopped working that's why i asked
