### ISSUE TITLE
Suggestion: Add Github issue template(s)

### ISSUE THREAD

**Issue by juozaspo** [ParticleCore/Iridium#754]
Instead of using the issue template included in the firefox addon (Bug Report feature redirecting to github, triggering an XSS upon request) you should use the github issue template for new issues. Template can be added using eather internal github features or manually, by creating required files in `.github` directory. More documentation can be found in https://help.github.com/en/articles/creating-issue-templates-for-your-repository and other related pages linked from there.

**p.s.** The addon's internal issue template triggered an XSS alert in NoScript, I had to add an exception for that feature to work properly. It also crashed a tab once; possibly a conflict, bug or something else that I don't know.

**Comment by ParticleCore** [comment]
I already tried the Github issue template before, most didn't care to use it and I always had to ask them for system information which most also didn't give, know how to or never replied back.
The way it is set up right now the issue body is already pre-filled with the system information and a basic template.

I am sorry about the XSS situation, but there's no way around it given the nature of the options page being local in the user's browser, it'll have to be made an exception.
