### ISSUE TITLE
Allow autoplay when YouTube's Up Next Autoplay is turned on?

### ISSUE THREAD

**Issue by BobbyWibowo** [ParticleCore/Iridium#756]
Basically when the extension's "Prevent autoplay" is turned on.
Does that make sense?

Maybe also automatically allow autoplay on playlists?

I guess making them as separate toggles in the extension's settings would be the safest bet.

**Comment by ParticleCore** [comment]
The current auto play feature is not linked to the auto play next video: https://github.com/ParticleCore/Iridium/wiki/Features#autoPlayVideo

But I plan to implement an option to control that one as well, however there will not be combined options such as this one where one option overrides the other once it is on, it would be confusing and not really worth it to me.

I also do plan on adding the quick toggles back in the page to make it easier to toggle video auto playback, for example, so the user can just turn on auto-play whenever without having to go to the settings.
