### ISSUE TITLE
[Feature] Sync settings and blacklist across computers

### ISSUE THREAD

**Issue by ZonK256** [ParticleCore/Iridium#758]

**Comment by ParticleCore** [comment]
Do you mean via the Firefox's account sync feature?

**Comment by ZonK256** [comment]
Not necessarily (I've seen some apps that use cloud services like Google Drive etc.), but I guess that would be the most convenient solution both for you and users.

**Comment by ParticleCore** [comment]
Yeah the only option would be to use Firefox's own sync system, but last time I researched this would mean users would not be able to have different settings in different browsers.
I will consider adding a toggle for the user to choose which storage system to use (local or account sync), that way both users would have the control over what is synced.
Thanks!
