### ISSUE TITLE
YouTube embed is broken when autoplay is disabled

### ISSUE THREAD

**Issue by juozaspo** [ParticleCore/Iridium#760]
**software details:**
````
manifestVersion: 1.1.0
cookieEnabled: true
doNotTrack: 1
language: lt
buildID: 20191002193559
name: Firefox
vendor: Mozilla
version: 69.0.2
arch: x86-64
os: linux
````

**steps to recreate the problem:**

1. Install iridium 1.1.0 from github (download and install from file)
2. Visit a site/page that has a YouTube embed (e.g. https://www.pillowfort.social/posts/873605)
3. See a blank for the embed iframe when Iridium is enabled and option `Play videos automatically` is disabled

Video works fine after clearing cache (Ctrl+F5) when option `Play videos automatically` is re-enabled and/or Iridium is disabled

**Screenshots:**
![Screenshot_2019-10-12 kingkai](https://user-images.githubusercontent.com/6626242/66703162-3bd00f80-ed18-11e9-9a7c-7525b2a086be.png)
![Screenshot_2019-10-12 kingkai(1)](https://user-images.githubusercontent.com/6626242/66703220-f102c780-ed18-11e9-87f0-0b575f401d89.png)

**additional information that could be helpful:**
Same bug happens while in new firefox profile, firefox running Ubuntu 18.04 LTS with Xfce desktop

**Comment by ParticleCore** [comment]
It should not be acting outside the YouTube.com domain, will see what is going on and fix it.
