### ISSUE TITLE
Forced grid view for subscriptions

### ISSUE THREAD

**Issue by fragande** [ParticleCore/Iridium#764]
First of all, great too see that you're back!

This is a very small annoyance but it seems new Iridium forces grid view for Subscriptions (i.e. the preference setting is reset every time you open the subscription page and URL changes back to `feed/subscriptions` instead of `feed/subscriptions?flow=2`). I have confirmed that this only occurs when Iridium is activated.

I don't know if you want these kind of reports this early in development or not so excuse me if it's inappropriate.

**Comment by ParticleCore** [comment]
This one took longer than I thought it would.

The listener was attached to any `youtube.com` header request as it was designed, however I forgot to exclude header requests for anything that was not the page loading for the first and subsequent times, which meant it was also taking over any other requests such as `xmlhttprequest` or `script` or even `image`, thus causing problems when trying to enforce the `Dark theme` cookie.

Will be pushing the version with this fix asap.
