### ISSUE TITLE
"Play videos automatically" setting switch not working properly in 1.2.0

### ISSUE THREAD

**Issue by eberhardweber** [ParticleCore/Iridium#767]
The automatic playback setting in "Settings" > "Player" > "Play videos automatically" can currently only be clicked on once, and once it has been clicked it no longer switches position from on to off. Sometimes the switch looks like it will move but will then default back to the position it was in.

**Comment by ParticleCore** [comment]
Further inspection tells me this is the same issue as #768
When the fix is released let me know if this isn't fixed as well.
