### ISSUE TITLE
Settings hang when more than one YouTube tab is open

### ISSUE THREAD

**Issue by practik** [ParticleCore/Iridium#768]
I observed and tested this in 1.2.0, in the same new profile I described in #765. To reproduce:

1. Open Iridium settings plus two YouTube tabs.
2. Toggle any Iridium setting switch.
3. Toggle it back again.

Sometimes the switch gets "stuck" where you set it in step 2, as described in #767. Other times, the switch moves back normally, but the setting itself does not change back (you can test this with the Dark mode switch, which should show results immediately).

In the browser console, the message `onMessageListener undefined    content-script.js:17:21` appears, and the counter beside it quickly runs up into the thousands. CPU load for Firefox shoots up to 100% or more.

The only way out is to close one of the YouTube tabs. Now the following error messages appear in the console:
```
Promise resolved after context unloaded    content-script.js:16
IndexedDB UnknownErr: ActorsParent.cpp:12487
IndexedDB UnknownErr: ActorsParent.cpp:13188    content-script.js:17:21
```
That last error appears many, many times (presumably once for each instance of `onMessageListener undefined` that appeared previously).  CPU load drops down to normal, and you can toggle the setting normally again.

**Comment by ParticleCore** [comment]
Thanks for finding this one, it's an infinite loop that is taking place. It shouldn't, but it is happening. Will take care of it ASAP.
