### ISSUE TITLE
"play video automatically" feature blocks the page loading

### ISSUE THREAD

**Issue by Hunam6** [ParticleCore/Iridium#769]
When "play video automatically" feature is enabled, the page doesn't load.

![image](https://user-images.githubusercontent.com/38606542/66779915-c5760d80-eecf-11e9-87a6-bd715c69eee5.png)

Logs:

![image](https://user-images.githubusercontent.com/38606542/66780056-29003b00-eed0-11e9-8b72-52c4eb6c9c8f.png)

**Comment by ParticleCore** [comment]
Duplicate of #766
