### ISSUE TITLE
Reverse Playlist

### ISSUE THREAD

**Issue by WH17EW0LF** [ParticleCore/Iridium#770]
As far as I can see, there is no longer a reverse playlist option anywhere! I assume this is a bug and that it has not been removed intentionally as this is one of the key selling points for me.

**Comment by WH17EW0LF** [comment]
This wasnt a feature request as it was already in 0.2.5, Im not certain why you would choose to remove a bunch of features that everyone was happy with?! anyone else reading this, you can get the good version of this extension working fine again by going to 

https://addons.mozilla.org/en-GB/firefox/addon/particle-iridium/versions/

you then install the 0.2.5 version and once that is added, goto your addons page (ctrl+shift+A_ by default, once there click on the Iridium addon and set automatic updates to off. that way you can check back manually and see when its worth updating again.

**Comment by ParticleCore** [comment]
Please read https://github.com/ParticleCore/Iridium/issues/737#issuecomment-541321036
