### ISSUE TITLE
YouTube borked after disabling or removing Iridium

### ISSUE THREAD

**Issue by practik** [ParticleCore/Iridium#771]
Sorry for the nonspecificity of "borked," but I don't know a better way to describe it. To reproduce:

1. Install Iridium 1.2.1 on a new Firefox profile with default prefs and no other extensions.
2. Open YouTube tab, observe overcaffeinated white man:
![Screenshot_2019-10-15 I went AMD - YouTube](https://user-images.githubusercontent.com/12074235/66850584-57b0fc80-ef36-11e9-8bbc-020869fd30a1.png)

3. Disable Iridium and reload YouTube tab, observe uncaught exceptions:
![Screenshot_2019-10-15 YouTube](https://user-images.githubusercontent.com/12074235/66850756-a9f21d80-ef36-11e9-95ab-6f7bc7c9c8a8.png)
![Untitled 4](https://user-images.githubusercontent.com/12074235/66850965-0bb28780-ef37-11e9-9a97-983b5fa230b1.png)

4. Reenable Iridium and reload YT tab: Back to normal.
5. Uninstall Iridium and reload YT tab: Blank again.

That last step has real potential to piss users off: "I uninstalled your extension and YouTube is STILL broken!" To get back to normal, they'll need to go into Firefox prefs and delete all cookies and site data.

**Comment by Videaprojaekt** [comment]
I have the exact same issue, but it only happens, when Iridium is active. This happened after the update that was pushed either today or yesterday.

**Comment by ParticleCore** [comment]
I am afraid I am not able to recreate this issue, it might be due to an issue that I've already fixed so let me know if it is still occurring when 1.2.2 is out.

Also additional details will be more helpful: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by SpamCam** [comment]
Same problem. YouTube, on my end, is now dependent on Iridium to even load.

**Comment by thepcwiz101** [comment]
This issue is on youtube's end. I got this issue and i don't have iridium installed since i am on google chrome.

**Comment by ParticleCore** [comment]
@SpamCam Users are reporting having had this issue as a result of YouTube itself, unrelated to any extension. Can anyone confirm this is still happening?

Supposedly once the extension is removed it should not affect YouTube at all, which it doesn't to me, that's Firefox own behavior on uninstalled extensions. If it still acts up after being uninstalled then it is either a YouTube bug or a Firefox bug.

**Comment by Videaprojaekt** [comment]
> 
> 
> Same problem. YouTube, on my end, is now dependent on Iridium to even load.

Have you tried uninstalling/disabling the extension and then opening any video followed by pressing Shift + F5? This should fix the issue in most cases.

**Comment by ParticleCore** [comment]
I'm closing this one since it is not a problem the extension is causing:

https://www.reddit.com/r/youtube/comments/diy07n/bug_the_video_loaded_like_this_and_ran_at_about/

If anyone is still having this issue a force refresh should be enough to download the updated YouTube resources with the fix they implemented.

Other troubleshooting steps can be found here: 

https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

Thanks @eduzappa18 again for bringing the Reddit thread to my attention.

**Comment by SpamCam** [comment]
> 
> 
> > Same problem. YouTube, on my end, is now dependent on Iridium to even load.
> 
> Have you tried uninstalling/disabling the extension and then opening any video followed by pressing Shift + F5? This should fix the issue in most cases.

It works now
