### ISSUE TITLE
Dark theme setting doesn't take effect immediately

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#772]
Sorry to say it, but this isn't fixed on my end yet (although the null cookie error is no longer appearing). Details below, but basically the problem seems to be with the expiration date of the PREF cookie.

* I installed 1.2.1 on a newly created profile of FF 69.0.3, with all FF preferences set to defaults and no other extensions installed.
* I opened Iridium prefs to verify that dark mode was set to "on," then opened a YouTube tab: It opened in default mode.
* I toggled dark mode off and on in Iridium and checked the YouTube tab: Now it was in dark mode.
* I reloaded the YouTube tab: It loaded in default mode again.

After that I installed one other extension, Cookie Quick Manager, so I could see what was going on with the cookies. Now I could see that the PREF cookie was set when Iridium was enabled – AND that it was already expired. In fact, it was set to expire at the exact second the first YouTube tab was loaded.

I tried editing it to a later date, and voila, the pref worked as expected: All open YouTube tabs switched to the desired mode instantly, and new and reloaded tabs appeared in the correct mode as well.

_Originally posted by @practik in https://github.com/ParticleCore/Iridium/issues/765#issuecomment-542289015_

**Comment by ParticleCore** [comment]
@practik I completely forgot to add the time increment when saving the cookie. Let me check it again and I'll see what I can do.

**Comment by DebSec** [comment]
I need to reload the page to get the dark mode to work. Firefox 68.2.0esr Iridium 1.2.4

This script works great:
https://greasyfork.org/en/scripts/32954-automatic-material-dark-mode-for-youtube
