### ISSUE TITLE
New tab doesn't load

### ISSUE THREAD

**Issue by robsonsobral** [ParticleCore/Iridium#774]
software details:
````
manifestVersion: 1.2.1
cookieEnabled: true
doNotTrack: 1
language: en-US
buildID: 20191014171118
name: Firefox
vendor: Mozilla
version: 71.0
arch: x86-64
os: win
````
steps to recreate the problem:

Go to youtube home and open some videos on new tabs. They will freeza on skeleton loading layout.

**Comment by eduzappa18** [comment]
Read before reporting: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug#troubleshooting

> Disable the extension and restart the browser.
> * If the problem still persists then it is not related to the extension. It might be caused by another extension, browser setting or by the website itself
> * If the problem doesn't persist move to the next step

---

It was a youtube bug (unrelated to iridium), it lasted for few hours and now is fixed  
 [r/youtube [Bug] The video loaded like this and ran at about half fps](https://www.reddit.com/r/youtube/comments/diy07n/bug_the_video_loaded_like_this_and_ran_at_about/)

**Comment by ParticleCore** [comment]
Thanks @eduzappa18 for letting me know about this, sounds like this might be a duplicate of #771 too.
@robsonsobral Can you confirm if your problem is still happening even with the extension disabled/uninstalled?

**Comment by robsonsobral** [comment]
Hi! Weird... Everything worked fine as soon as I disabled Iridium. Now, there's no problem at all. I guess I tested at the same time the problem was fixed at Youtube side.

Sorry, @ParticleCore .

**Comment by ParticleCore** [comment]
@robsonsobral No worries, glad to hear it's back to normal.
