### ISSUE TITLE
Small bug of the iridium icon on the youtube pages

### ISSUE THREAD

**Issue by Hunam6** [ParticleCore/Iridium#777]
When you click on the iridium icon on a youtube page, it opens the iridium settings page but if you return to the youtube page the iridium icon remains in clicked mode.

![image](https://user-images.githubusercontent.com/38606542/67163670-f5129300-f371-11e9-8d0a-b67135ee0995.png)

**Comment by ParticleCore** [comment]
This issue is a result of a bug in YouTube which makes it unable to handle this very quick succession of events on a custom/hacked button in their own layout.

The solution for this is to call `document.activeElement.blur();` before opening the extension settings.
