### ISSUE TITLE
Uninstalling Iridium breaks YouTube

### ISSUE THREAD

**Issue by ThomasTheHedgehog** [ParticleCore/Iridium#779]
Upon uninstalling Iridium, YouTube as a whole breaks entirely - the pages now fail to load unless Iridium is reinstalled
![image](https://user-images.githubusercontent.com/29693283/67206641-fb544e00-f409-11e9-848e-cb5f88ac3a56.png)

**Comment by ParticleCore** [comment]
Duplicate of #771
