### ISSUE TITLE
Request: Force 30fps

### ISSUE THREAD

**Issue by a9013** [ParticleCore/Iridium#781]
My computer can't handle 60fps, only 30fps. I have to use this script (https://greasyfork.org/en/scripts/23329-disable-youtube-60-fps-force-30-fps) to force the 30fps. If you have time, please add an option to force 30fps. I tried disabling the **_Allow HFR (60fps)_** feature but that doesn't work. Thank you!

![Untitled](https://user-images.githubusercontent.com/49474624/67253915-1e452900-f42f-11e9-82c1-2d3718c4a62f.png)
![Untitled](https://user-images.githubusercontent.com/49474624/67254077-e985a180-f42f-11e9-88f5-d3846ad9dcc6.png)

**Comment by ParticleCore** [comment]
The feature is working and was developed recently.

If it is not working for you then it's a bug and I'll need more information: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Just tested in the same video as yours and when the "Allow HFR" is disabled no 60fps stream show up

![ss1](https://user-images.githubusercontent.com/9222661/67266309-6f8d0100-f49f-11e9-83a7-7b8cb9c9b57c.png)

**Comment by a9013** [comment]
I tried everything on here (https://github.com/ParticleCore/Iridium/wiki/Report-a-bug) and still not working. It must be my old computer. I'm going to keep using the script.

**Comment by ParticleCore** [comment]
I don't know what system you are using, what browser you are using, what browser version you are using, what extension version you are using, I don't have any steps to recreate the problem, etc.

Without more information I can't do anything since I cannot make the problem occur on my end so far and if this feature is not working for you then there's no "force 30fps" feature that will work because that's the one that is already implemented and not working for you.

**Comment by Seiryuu-sama** [comment]
Browser version: Firefox 70.0 (64-bit)
Iridium version: 1.2.4
Fresh profile with only Iridium installed.

"Play videos automatically" is ON and "Allow HFR streams (60fps)" is OFF  = Videos will be 60FPS
"Play videos automatically" is OFF and "Allow HFR streams (60fps)" is OFF = Videos will be 30FPS

I also tried with Firefox's built in media autoplay Block Audio and Video, but the the player will still use 60FPS while "Play videos automatically" is on.

**Comment by a9013** [comment]
> 
> 
> Browser version: Firefox 70.0 (64-bit)
> Iridium version: 1.2.4
> Fresh profile with only Iridium installed.
> 
> "Play videos automatically" is ON and "Allow HFR streams (60fps)" is OFF = Videos will be 60FPS
> "Play videos automatically" is OFF and "Allow HFR streams (60fps)" is OFF = Videos will be 30FPS
> 
Yes, same as @Seiryuu-sama ^

**Comment by ParticleCore** [comment]
@Seiryuu-sama That's doing exactly what is suppose to do: Allow HFR Streams = 60fps shows if they exist and vice versa.

What is the problem?

**Comment by a9013** [comment]
If _Allow HFR streams (60fps)_ is **OFF** and _Play videos automatically_ is **ON** = Videos will be 60FPS

**Comment by ParticleCore** [comment]
@a9013 Oh, finally got it to happen to me, will see what is going on. Thanks for all the help.
