### ISSUE TITLE
Read and modify privacy settings permission request?

### ISSUE THREAD

**Issue by bitpixl** [ParticleCore/Iridium#786]
Hi,

Just wanted to update Iridium to the latest version and received this new permission request:

"Read and modify permission settings"

According to Mozilla this right is used for:

> Read and modify privacy settings
> 
> The extension could change privacy related settings controlling:
> 
>     Network behavior
>     Whether passwords are stored in the browser’s password manager
>     The way the browser interacts with websites 
> 
> Extensions requesting this permission might:
> 
>     Disable browser storage of passwords as part of an enhanced password manager
>     Help protect your privacy by managing the information made available in real-time chat and video applications
>     Offer additional tracking protection features 

Can you please explain why this permission is now needed?

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/issues/773

https://addons.mozilla.org/firefox/addon/particle-iridium/privacy/

**Comment by travisterrell** [comment]
Thanks for the very quick reply! (Which I unfortunately only just noticed I received. :/ )

For anybody reading in the future and too lazy to click, the helpfully referenced issue and updated privacy policy cites that the permission is necessary "for the purpose of detecting when the user has FirstPartyIsolation enabled to enforce the Dark Theme cookie with success."

(It's worth mentioning that ParticleCore indeed [lamented ](https://github.com/ParticleCore/Iridium/issues/773#issuecomment-543393894 )the fact that this permission was required.)

I'm fine with such a non-intrusive use of the permission set, but those paranoid could very easily modify the [manifest ](https://github.com/ParticleCore/Iridium/blob/master/src/manifest.json) to remove it, if desired (potentially breaking the dark theme, of course, depending on browser settings).
