### ISSUE TITLE
Video quality got bad

### ISSUE THREAD

**Issue by ViperCode7** [ParticleCore/Iridium#794]
Just recently I noticed videos were looking bad, as in heavily blocky and displaying color gradient bands, not really noticeable on lighter scenes, but heavily noticeable on darker ones. Top with Iridium active, botton standard Youtube player, standard print screen capture. I've checked videos offline as well, and other sites like Vimeo, this issue doesn't exist in these cases, and with and without hardware acceleration in chrome flags, same issue when iridium is active.  While the integrated screen capture, 2nd picture, looks as if Iridium was off. Even more, the quality is somewhat worse than what I managed to capture, the shadows under the arches is of a higher contrast when viewing the video than it is in the screen capture.

Comparison with Iridium on and off:
![what](https://user-images.githubusercontent.com/6399179/68066964-ca98e080-fd48-11e9-9432-6dbcbd98c84b.jpg)

Integrated screen capture:
![screenshot](https://user-images.githubusercontent.com/6399179/68066992-5b6fbc00-fd49-11e9-8825-47865132cd27.png)

**Comment by ParticleCore** [comment]
The extension does not change video quality unless you enabled the option to disable HFR streams and even then it only filters the available streams that are HFR, it does not encode the video on the fly or anything similar.

Please right click on the video player on YouTube, select "Stats for nerds" and screenshot what it shows with Iridium disabled and enabled.

Unless I can recreate the problem I cannot find a solution, so the exact steps to recreate this are required, I cannot make it happen on my end.

**Comment by ViperCode7** [comment]
It's OK, not an Iridium issue, just a dirty chrome profile... again.

**Comment by ParticleCore** [comment]
Glad to hear you found the problem, but be aware that support only exists for Firefox from version 1.x.x
