### ISSUE TITLE
code donation

### ISSUE THREAD

**Issue by raingart** [ParticleCore/Iridium#799]
Hello!
I heard that the version for Chrome (like chromium) is no longer supported.
I can offer my version of a similar extension. You can take parts of it for your new version. It seems to work.
I hope my work will be useful.
If you have questions, write down. We have one goal, I see no reason not to help.

https://github.com/raingart/New-Horizons-for-YouTube-extension

**Comment by ParticleCore** [comment]
Thanks for the help, but I think I will based the features mostly off of the previous version.
