### ISSUE TITLE
Youtube Big Icons

### ISSUE THREAD

**Issue by HatoryHanz** [ParticleCore/Iridium#800]
Youtube testing new look. But its complete horrbile. 
Does it have a solution to undo it?

**Comment by ParticleCore** [comment]
It's not something I'm interested at the moment, but you should always send them feedback, they actually listen like when they gave us grid + list subscription layouts.

**Comment by HatoryHanz** [comment]
Yea i know. It's what i already did. Soo will see. But thx for response. You do good job, keep working!
