### ISSUE TITLE
Fixed the issue with the play button not responding when autoplay is off 

### ISSUE THREAD

**Issue by praised** [ParticleCore/Iridium#801]
I'am on the latest Maxthon beta ( I know!) and when i disables autoplay no video would play and play button would be unresponsive. Unless I re-enable it, nothing plays. So, after some playing around with the code I managed to fix it by just commenting a few lines. Here they are, line 2785:

```
/*if (!document.querySelector(".ad-showing,.ad-interrupting")) {
                                            return function () {
                                            };
                                        }*/ 
```

**Comment by ParticleCore** [comment]
- This extension is only being supported for stable versions of Firefox 57+, there are no plans to support any other browser in the future, including any browser forks. If you are using a different browser then try running the extension in supported version mentioned above.

https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
