### ISSUE TITLE
Playlist controls are reduced

### ISSUE THREAD

**Issue by AfroDisco** [ParticleCore/Iridium#802]
While a playlist is running, the buttons for random order and loop are not available.

This seems to be features that are removed by the extension. As you can see on the following images.

![Playlist-vanilla](https://user-images.githubusercontent.com/24570663/69329410-57043800-0c51-11ea-942c-79bd9cf74444.PNG)
![Playlist-extension](https://user-images.githubusercontent.com/24570663/69329411-57043800-0c51-11ea-8819-e6124637e30a.PNG)

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
