### ISSUE TITLE
Videos no longer autoplay

### ISSUE THREAD

**Issue by ShadowBullet** [ParticleCore/Iridium#804]
As the title says, it seems as though, autoplaying videos has stopped working.
---

software details:
````
manifestVersion: 1.2.4
cookieEnabled: true
doNotTrack: 1
language: en-US
buildID: 20191202093317
name: Firefox
vendor: Mozilla
version: 71.0
arch: x86-64
os: mac
````

steps to recreate the problem:
Load a video

additional information that could be helpful:

**Comment by ParticleCore** [comment]
Autoplay is working for me, since you closed the issue I assume it is working for you as well.

**Comment by ShadowBullet** [comment]
> Autoplay is working for me, since you closed the issue I assume it is working for you as well.

I closed the issue as the second I clicked on another it had worked, however upon further testing, it works properly when you click a video and it starts from that same page. It appears to not autoplay when you open the video in a new tab. I have reproduced the issue every time in this scenario.

**Comment by ParticleCore** [comment]
I've tried with autoplay enabled:
 - Opening a new video in a new tab by clicking on the video using the mousewheel button
   - Once I switch to the tab the new video was opened the video starts playing
 - Opening a new video in a new window
   - The video starts playing as soon as the window is opened

I will need more details in order for me to recreate the issue on my end.

Also remember to see if the same issue happens with the extension disabled, if it does then it is not related to the extension.

Do note that Firefox no longer plays videos automatically on tabs that are opened on the background until you switch to that tab.

**Comment by ShadowBullet** [comment]
Ah! I found it, it was that setting for firefox for youtube specifically to allow autoplay, once enabled it works perfectly now!
