### ISSUE TITLE
Iridium YouTube Toolbar Missing

### ISSUE THREAD

**Issue by SmithJake466** [ParticleCore/Iridium#809]
Hello, I hope you're doing well. I am heavy user of the Toolbar features for Iridium (awesome tool for easily grabbing YT thumbnails as well as screenshots) but unfortunately after updating it a while back it disappeared. I followed the troubleshooting instructions including making a new profile and installing it but the toolbar still doesn't pop up. I also tried installing older versions but that didn't work either. I apologize for the inconvenience.
---

software details:
````
manifestVersion: 1.2.4
cookieEnabled: true
doNotTrack: unspecified
language: en-US
buildID: 20191202093317
name: Firefox
vendor: Mozilla
version: 71.0
arch: x86-64
os: win
````

steps to recreate the problem:
Don't really know how to recreate the problem. Firefox notified me up an update for Iridium, I let it go through and the toolbar disappeared, this was a few weeks ago.

additional information that could be helpful:
The rest of the features still work (dark mode, video play settings, etc.), just the toolbar is no longer there.

**Comment by travisterrell** [comment]
@SmithJake466 Did you read the main page of the project before posting this issue? He explains in-depth what happened and what you can do about it. (If this somehow doesn't apply to your problem, feel free to add more detail...but I'm 99.9% sure this is exactly what you're experiencing.)

https://github.com/ParticleCore/Iridium/blob/master/README.md

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/blob/master/README.md
