### ISSUE TITLE
Disallow HFR streams no longer working

### ISSUE THREAD

**Issue by eduzappa18** [ParticleCore/Iridium#810]
**software details:**
````
manifestVersion: 1.2.4
cookieEnabled: true
doNotTrack: 1
language: en-US
buildID: 20191202093317
name: Firefox
vendor: Mozilla
version: 71.0
arch: x86-64
os: win
````

**steps to recreate the problem:**
turn off the `Allow HFR streams (60fps)`  option
play any 60 fps video

The player will load the 60 fps version of the video instead of the 30 fps one

---
Tested on a new firefox profile, only Iridium installed (default settings except Allow HFR streams)

**Comment by Anasastu** [comment]
`Play videos automatically`, disabled, fixed this for me

**Comment by eduzappa18** [comment]
> 
> 
> `Play videos automatically`, set to disabled, fixes this for some videos: https://www.youtube.com/watch?v=mMgzpAlfjk0
> but not others: https://www.youtube.com/watch?v=UxM6kwT7gUg

I didn't noticed that till now. Weird

**Comment by SameGhost** [comment]
> Firefox 74.0
> Mac OS High Sierra 10.13.6
> Iridium 1.2.5 (re-installed just minutes ago directly from Github rather than from Mozilla)

Disallow HFR hasn't worked in months for me. "Fix" mentioned above has no effect to any video I tried.

Disabling all other extensions changed nothing.

Fiddling with cookie permissions changed nothing (not idea if it would, I'm just desperate and tech-ignorant).

Not sure if there's anything else I should try...

Does it actually work for anyone, or is the feature just plain broken as of now?

**Comment by ParticleCore** [comment]
YouTube changed the way the streams are distributed to the users and I finally got that change recently, will see what I can do to fix this issue.
