### ISSUE TITLE
Coming soon

### ISSUE THREAD

**Issue by Ghis1964** [ParticleCore/Iridium#811]
How "late" is "soon"?

software details:
````
manifestVersion: 1.2.4
cookieEnabled: true
doNotTrack: unspecified
language: en-CA
buildID: 20191202093317
name: Firefox
vendor: Mozilla
version: 71.0
arch: x86-64
os: win
````

steps to recreate the problem: Iridium > settings > channels

additional information that could be helpful: Iridium > settings > blacklist

**Comment by ParticleCore** [comment]
I work on the features whenever I have free time. The past three weeks had other priorities over this project that left me with no free time left.
