### ISSUE TITLE
not working on Firefox?

### ISSUE THREAD

**Issue by BusterTheBusta** [ParticleCore/Iridium#814]
Hello, 

for a couple of months now, YouTube now starts up with the normal Iridium logo at the top right and the Auto Play button right next to the "Save to playlist" button, but all the other buttons and functions are not appearing anymore. I have disabled it, restarted Firefox, and reenabled it and all my other extensions are not for YouTube, yet the problem still continues. Is this intentional for a new version or a beta or is this a bug?

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
