### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by Johnnycyan** [ParticleCore/Iridium#815]
Every once in a while only while Iridium is enabled Youtube video pages will just not load anything on them. All I see are placeholder areas for where things should be but no content at all. Disabling Iridium fixes it.
![Screenshot_2020-01-11 YouTube](https://user-images.githubusercontent.com/24556317/72209097-defc0680-3478-11ea-8119-6bcf4080b347.png)

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
