### ISSUE TITLE
blacklist not working.

### ISSUE THREAD

**Issue by nathgit** [ParticleCore/Iridium#816]
When I try to click on the [X] button to blacklist something it doesn't do anything. I just noticed I hadn't been using it & reactivated it & it doesn't work. Is it related to the missing api mentioned in issue #737 ?

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by nathgit** [comment]
To clarify, If you even look at these at all I could've posted this as a bug report, but I didn't because I figured it wouldn't be fixed anyway (if possible) since it's being discontinued on chrome anyway so I posted here to ask if it was related to the missing api or whatever it is that is why you're discontinuing it for chrome in the first place or if it was something else that **could** be fixed because it had worked when I used it in the past. If I could've labeled it as just _a question_ I would have but I can't.
