### ISSUE TITLE
player pop-up button

### ISSUE THREAD

**Issue by urfausto** [ParticleCore/Iridium#819]
when disabling player pop-up options, the button remains visible in the interface. should be removed instead no?

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by urfausto** [comment]
closing the issue will not make it go away. tried both webstore and script version of the extension.

**Comment by ParticleCore** [comment]
> 
> 
> closing the issue will not make it go away. tried both webstore and script versions of the extension.

Clearly you didn't even bothered to read what I linked and for that I won't bother with this as well.

**Comment by urfausto** [comment]
> > closing the issue will not make it go away. tried both webstore and script versions of the extension.
> 
> Clearly you didn't even bothered to read what I linked and for that I won't bother with this as well.

it's funny because i've read it even if i'm not native english and i can't find any bug report button where it is said, alike the features and localization pages which are dumped and out of date.

**Comment by ParticleCore** [comment]
> 
> 
> > > closing the issue will not make it go away. tried both webstore and script versions of the extension.
> > 
> > 
> > Clearly you didn't even bothered to read what I linked and for that I won't bother with this as well.
> 
> it's funny because i've read it even if i'm not native english and i can't find any bug report button where it is said, alike the features and localization pages which are dumped and out of date.

Number 1: You said you already tried the webstore and userscript version, but the extension is now only supporting Firefox webextension, as per the instructions:

> **This extension is only being supported for stable versions of Firefox 57+**

Number 2: The most recent version of the extension no longer has the player pop-up button at the moment for a wile, which you would know had you actually follow the instructions:

> **Make sure that you are using the most recent Iridium version. If you aren't then update it, restart the browser and see if the problem has already been fixed.**

Number 3: English not being your native language is not an excuse to not follow the instructions twice in a row or even to lie about it.
