### ISSUE TITLE
Runtime labels not showing up.

### ISSUE THREAD

**Issue by Santademon** [ParticleCore/Iridium#820]
Browser Version: Firefox 73.0.1

OS: Windows 10

Software Type: Home, 64 bit

Software Version: 1903

Problem Description: Video run-times aren't visible on related videos.

Steps to reproduce: Go to any video page with current version of Iridium.

Additional details: I'm sure this is caused by Iridium because the run-times are visible when Iridium is disabled. Also, this only seems to happen with the related videos on video pages.

**Comment by ParticleCore** [comment]
There is no Iridium version 1903, please follow the instructions as requested:

https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by Santademon** [comment]
That's the version of Windows 10 that I'm using.

**Comment by ParticleCore** [comment]
It's a YouTube bug, if you press play on the video the related video durations show up.
