### ISSUE TITLE
Your workaround doesn't seem to work!

### ISSUE THREAD

**Issue by def00111** [ParticleCore/Iridium#822]
https://github.com/ParticleCore/Iridium/blob/88b7eba497cba430dcab91006c788eb06abb2d71/src/js/background.js#L39

Your workaround for [Bug 1530408](https://bugzilla.mozilla.org/show_bug.cgi?id=1530408) doesn't
seem to work!

I have added another workaround in the bug.

**Comment by ParticleCore** [comment]
@def00111 I've yet to experience any issue since the workaround was implemented. Can you share how to recreate the issue with this workaround implemented and also can you share your workaround please?

**Comment by def00111** [comment]
With your workaround:
![reTER81eGo](https://user-images.githubusercontent.com/10849366/76147193-08f93000-609a-11ea-81ef-d1aacb4f4356.gif)

**Comment by def00111** [comment]
I used this code:
```javascript
function listener(details) {
  if (details.statusCode != 200) {
    return;
  }

  let decoder = new TextDecoder("utf-8");
  let filter = browser.webRequest.filterResponseData(details.requestId);
  let str = "";
  let original = "";

  filter.ondata = event => {
    str += filterCacheData(decoder.decode(event.data, {stream: true}));
    original += decoder.decode(event.data, {stream: true});
    filter.write(event.data);
  };

  filter.onstop = async event => {
    console.log(details, str, original);
    filter.close();
  };
}

browser.webRequest.onHeadersReceived.addListener(
  listener,
  {urls: ["*://www.youtube.com/*/base.js"], types: ["script"]},
  ["blocking"]
);

function filterCacheData(data) {
  return data != null && data.startsWith("\u0000") ? data.split("\u0000").pop() : data;
}
```

**Comment by ParticleCore** [comment]
> 
> 
> With your workaround:
> ![reTER81eGo](https://user-images.githubusercontent.com/10849366/76147193-08f93000-609a-11ea-81ef-d1aacb4f4356.gif)

Can you try the same with Firefox 75? I believe Firefox 73 had a bug that has already been corrected which was causing what you show.

**Comment by def00111** [comment]
With my workaround:
![2e7wex6iE2](https://user-images.githubusercontent.com/10849366/76147388-1adbd280-609c-11ea-9cd3-abb4d717d636.gif)

**Comment by ParticleCore** [comment]
> 
> 
> I used this code:
> 
> ```js
> function listener(details) {
>   if (details.statusCode != 200) {
>     return;
>   }
> 
>   let decoder = new TextDecoder("utf-8");
>   let filter = browser.webRequest.filterResponseData(details.requestId);
>   let str = "";
>   let original = "";
> 
>   filter.ondata = event => {
>     str += filterCacheData(decoder.decode(event.data, {stream: true}));
>     original += decoder.decode(event.data, {stream: true});
>     filter.write(event.data);
>   };
> 
>   filter.onstop = async event => {
>     console.log(details, str, original);
>     filter.close();
>   };
> }
> 
> browser.webRequest.onHeadersReceived.addListener(
>   listener,
>   {urls: ["*://www.youtube.com/*/base.js"], types: ["script"]},
>   ["blocking"]
> );
> 
> function filterCacheData(data) {
>   return data != null && data.startsWith("\u0000") ? data.split("\u0000").pop() : data;
> }
> ```

Unfortunately I cannot ignore anything that is not 200 responses because Firefox sometimes caches the resources modified by the script, but other times it does not and there's no way to know it.

**Comment by def00111** [comment]
I used this code:
```javascript
var redirectedUrls = new Map();

function listener(details) {
  if (details.statusCode != 200) {
    return;
  }

  if (!redirectedUrls.has(details.url)) {
    // https://bugzilla.mozilla.org/show_bug.cgi?id=1530408
    let redirectUrl = details.url + (details.url.includes("?") ? "&" : "?") + Date.now();
    redirectedUrls.set(redirectUrl, true);
    return {redirectUrl};
  }
  // already redirected
  redirectedUrls.delete(details.url);

  let filter = browser.webRequest.filterResponseData(details.requestId);

  let data = [];
  filter.ondata = event => {
    data.push(event.data);
    filter.write(event.data);
  };

  filter.onstop = async event => {
    let blob = new Blob(data, {type: 'text/javascript'});
    let str = await blob.text();
    console.log(details, str);
    filter.close();
  };
}

browser.webRequest.onHeadersReceived.addListener(
  listener,
  {urls: ["*://www.youtube.com/*/base.js", "*://www.youtube.com/*/base.js?*"], types: ["script"]},
  ["blocking"]
);
```

**Comment by ParticleCore** [comment]
> 
> 
> I used this code:
> 
> ```js
> var redirectedUrls = new Map();
> 
> function listener(details) {
>   if (details.statusCode != 200) {
>     return;
>   }
> 
>   if (!redirectedUrls.has(details.url)) {
>     // https://bugzilla.mozilla.org/show_bug.cgi?id=1530408
>     let redirectUrl = details.url + (details.url.includes("?") ? "&" : "?") + Date.now();
>     redirectedUrls.set(redirectUrl, true);
>     return {redirectUrl};
>   }
>   // already redirected
>   redirectedUrls.delete(details.url);
> 
>   let filter = browser.webRequest.filterResponseData(details.requestId);
> 
>   let data = [];
>   filter.ondata = event => {
>     data.push(event.data);
>     filter.write(event.data);
>   };
> 
>   filter.onstop = async event => {
>     let blob = new Blob(data, {type: 'text/javascript'});
>     let str = await blob.text();
>     console.log(details, str);
>     filter.close();
>   };
> }
> 
> browser.webRequest.onHeadersReceived.addListener(
>   listener,
>   {urls: ["*://www.youtube.com/*/base.js", "*://www.youtube.com/*/base.js?*"], types: ["script"]},
>   ["blocking"]
> );
> ```

This I cannot use, when I used it it quickly ran into memory problems causing the entire page to just not load any more. This API is memory intensive so generating anything during its process will escalate its memory use quickly, anything being processed in it must be as light as possible. Creating a file every time a resource is intercepted is not going to work reliably.

**Comment by ParticleCore** [comment]
@def00111 I just installed Firefox 73 and I cannot recreate your problem with stock settings + Iridium 1.2.4

Can you repeat your test with a default profile with only Iridium installed? It's possible there might interference from another addon.

**Comment by def00111** [comment]
He already tested: https://bugzilla.mozilla.org/show_bug.cgi?id=1530408#c9

**Comment by ParticleCore** [comment]
> 
> 
> He already tested: https://bugzilla.mozilla.org/show_bug.cgi?id=1530408#c9

The user you linked did not test the problem with Iridium, thus not with the workaround I have implemented. That user tested with your manifest, which does not contain my workaround.

Which is why I asked you to test on a fresh Firefox profile in version 73 with just Iridium installed. This is because on my Firefox 73 + Iridium, the issue you showed is not happening. Unless you test it the way I explained I have no other means to find out if your problem is taking place because another addon you have installed is interfering or if it is because of something else.

**Comment by ParticleCore** [comment]
> 
> 
> I used this code:
> 
> ```js
> function listener(details) {
>   if (details.statusCode != 200) {
>     return;
>   }
> 
>   let decoder = new TextDecoder("utf-8");
>   let filter = browser.webRequest.filterResponseData(details.requestId);
>   let str = "";
>   let original = "";
> 
>   filter.ondata = event => {
>     str += filterCacheData(decoder.decode(event.data, {stream: true}));
>     original += decoder.decode(event.data, {stream: true});
>     filter.write(event.data);
>   };
> 
>   filter.onstop = async event => {
>     console.log(details, str, original);
>     filter.close();
>   };
> }
> 
> browser.webRequest.onHeadersReceived.addListener(
>   listener,
>   {urls: ["*://www.youtube.com/*/base.js"], types: ["script"]},
>   ["blocking"]
> );
> 
> function filterCacheData(data) {
>   return data != null && data.startsWith("\u0000") ? data.split("\u0000").pop() : data;
> }
> ```

I also just noticed that in the test you did not copy my code correctly, which makes me believe this is not a problem with the extension, but with whichever implementation you are trying to do based on my workaround.

I will close this as such, unless you explain it otherwise.

As for your situation, your example of my workaround is incorrect, you forgot to include the Textencoder as wel, you cannot decode the original event.data more than once, it gets corrupted and you're writing the string at the wrong moment of the interception, you should only write on the stop, not during data.

So it should be more like this:


> ```js
> function listener(details) {
>   if (details.statusCode != 200) {
>     return;
>   }
> 
>   let decoder = new TextDecoder("utf-8");
>   let encoder = new TextEncoder();
>   let filter = browser.webRequest.filterResponseData(details.requestId);
>   let str = "";
>   let original = "";
> 
>   filter.ondata = event => {
>    let originalDecodedData = decoder.decode(event.data, {stream: true});
>     str += filterCacheData(originalDecodedData);
>     original += originalDecodedData;
>   };
> 
>   filter.onstop = async event => {
>     console.log(details, str, original);
>     filter.write(encoder.encode(str));
>     filter.close();
>   };
> }
> 
> browser.webRequest.onHeadersReceived.addListener(
>   listener,
>   {urls: ["*://www.youtube.com/*/base.js"], types: ["script"]},
>   ["blocking"]
> );
> 
> function filterCacheData(data) {
>   return data != null && data.startsWith("\u0000") ? data.split("\u0000").pop() : data;
> }
> ```

I do not intend to provide script lessons, so please do not use this repository for this purpose, it is only for the Iridium add-on.
