### ISSUE TITLE
Streaming doesn't start on live page

### ISSUE THREAD

**Issue by knoajp** [ParticleCore/Iridium#823]
If I visit the live streaming page of url format as below,
https://www.youtube.com/channel/{channel_id}/live
the video streaming doesn't start.

example:
https://www.youtube.com/channel/UCNsidkYpIAQ4QaufptQBPHQ/live

--
Iridium for YouTube 0.2.5
Google Chrome version: 80.0.3987.132 Official Build 64 bit
Mac OS X El Capitan

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
