### ISSUE TITLE
Iridium makes closed captions inoperative

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#829]
Firefox version: 75 beta
Iridium version: 1.2.5
Operating system: Ubuntu 19.10
Observed behaviour: Closed captions button does not do anything when iridium is enabled.

**Comment by ParticleCore** [comment]
The CC are working with Iridium 1.2.5

![image](https://user-images.githubusercontent.com/9222661/77232619-b20f5280-6b91-11ea-89be-5035859c687b.png)

Please follow the instructions for reporting a problem as requested:

https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
