### ISSUE TITLE
Perhaps something of interest about about the author of this extension.

### ISSUE THREAD

**Issue by Betsy25** [ParticleCore/Iridium#83]
[https://yro.slashdot.org/story/17/07/14/183237/popular-chrome-extension-sold-to-new-dev-who-immediately-turns-it-into-adware](https://yro.slashdot.org/story/17/07/14/183237/popular-chrome-extension-sold-to-new-dev-who-immediately-turns-it-into-adware)

**Comment by RoqueDeicide** [comment]
We all know this already, that is why this extension is in development.

**Comment by MattSturgeon** [comment]
See his response here: ParticleCore/Particle/issues/528. This doesn't relate to this project.

He (perhaps naively) sold the chrome extension portion\* of a mostly-abandoned\*\* project to a company who promised to disclose any changes upfront.

Sure, it's not the most integral move, however I understand that money can be a great influencer, even if not everyone likes to admit it.

\* the actual userscript and extensions for other browsers are still unsold, unchanged and [available](https://github.com/ParticleCore/Particle/wiki/Download#userscript)
\*\* the [new](https://www.youtube.com/new) youtube layout breaks the old project, this is the replacement

**Comment by ParticleCore** [comment]
I honestly don't know what to label this as, so I'll just leave this up for a few days and close it as invalid, should be enough for other users to be informed of.
