### ISSUE TITLE
Playback error when Iridium is installed

### ISSUE THREAD

**Issue by starcestus** [ParticleCore/Iridium#831]
With Iridium is installed for chrome i get this error the videos dont play until i refresh the page uininstalling iridium fixes the error but ive been using iridium for years now and i really dont want to stop
![image](https://user-images.githubusercontent.com/62255109/77239814-25768b80-6bb5-11ea-9585-81f3a00ad988.png)

An error occurred. Please try again later.

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
