### ISSUE TITLE
Multiple issues: Player errors (Chrome), blank interface (Firefox)

### ISSUE THREAD

**Issue by TheSalx1995** [ParticleCore/Iridium#832]
While browsing on Chrome, I began getting this annoying error very often:
![YTC](https://user-images.githubusercontent.com/62516544/77256373-72994280-6c33-11ea-89d6-27b9ce0c5c60.png)

I found Iridium to be the culprit of the problem. Uninstalled it and everything got fine, reinstalled it and the problems appeared once again.

I then switched to Firefox, and instead got this:
![YTF1](https://user-images.githubusercontent.com/62516544/77256377-73ca6f80-6c33-11ea-9438-edfc15b09346.png)
![YTF2](https://user-images.githubusercontent.com/62516544/77256379-74fb9c80-6c33-11ea-8ac2-786cf5458b06.png)

Again, it's Iridium messing up with YouTube, and this just began to happen this week. Did YouTube change something that prompts Iridium to bug the page, or is it just me? The only plugin I have other than Iridium is AdBlock Plus which, again, worked just fine for a long time until this week.

Note: I have the latest version of Iridium on both browsers.

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by romskidd** [comment]
I have the same problem..
