### ISSUE TITLE
"An error occurred. Please try again later." in Chromium

### ISSUE THREAD

**Issue by MasterPuffin** [ParticleCore/Iridium#837]
Since a few days whenever I click on a YouTube video I get the following error message: 
`An error occurred. Please try again later. (Playback ID: ***)
Learn More`
When I reload the page the video works without any issues. 
When disabling the Iridium extension the issue goes away, disabling other extensions does not help.
I'm using Vivaldi 2.10.1745.27 (Chromium based) and Iridium 0.2.5

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
