### ISSUE TITLE
Autoplay prevention and page loading broken after last youtube update

### ISSUE THREAD

**Issue by juozaspo** [ParticleCore/Iridium#838]
Youtube updated it's code and autoplay prevention is broken again. Not mentioning pages are not loading properly. Dark theme setting and iridium icon works ok, quick controls not all times (only if video page was loaded directly, e.g. after refresh or visiting a link).

software details:
````
manifestVersion: 1.2.6
cookieEnabled: true
doNotTrack: unspecified
language: lt
buildID: 20200309095159
name: Firefox
vendor: Mozilla
version: 74.0
arch: x86-64
os: linux
````

steps to recreate the problem:

- (optional) Create and load a fresh firefox profile
- Install iridium, make sure other addons are disabled
- Open youtube (notice it loads fine), then open any video
  - Notice video does auto-play automatically, addon't doesn't stop it, youtube's UI elements are missing, red loading bar stuck loading
  - Try loading youtube home page, notice no sidebar shown on left, audio of video played plays in background
  - Try loading other video, notice player is stuck on previous video
- Hit refresh while on a video, youtube loads ok but autoplay is not disabled
  - Visit youtube homepage after youtube initial load on video page, it loads ok
  - Go back, autoplay is disabled
  - Visit any other video instead of going back, no player or UI at all, infinite red loading bar
  - Click any related video while on video page (do not visit yt home page), page is stuck on previous video, also with infinite red loading bar and no UI

additional information that could be helpful:
Disabling iridium does not reset everything to default, dark theme is not disabled. Otherwise youtube is fully functional w/o Iridium all pages load fine. Screenshots with Iridium enabled:
![Screenshot_2020-04-04 YouTube](https://user-images.githubusercontent.com/6626242/78422205-5bf8df80-7666-11ea-93c6-19c02f85b1b0.png)
Whole bottom part of page is missing, including quick controls, red loading bar is stuck
![Screenshot_2020-04-04 YouTube(1)](https://user-images.githubusercontent.com/6626242/78422236-834fac80-7666-11ea-808d-847d833f7560.png)
Sidebar is not loaded
![Screenshot_2020-04-04 BRAWLSTARS ANIMATION DUO SHOWDOWN OF CHAOS](https://user-images.githubusercontent.com/6626242/78422449-0a515480-7668-11ea-8f75-ff29018a5efe.png)
If youtube loaded on video page, visiting home page then any other video youtube does not load player at all
![Screenshot_2020-04-04 BRAWL STARS ANIMATION - SPIKE AND SPROUT ARE BROTHERS ](https://user-images.githubusercontent.com/6626242/78422673-a4fe6300-7669-11ea-8724-a2a0664e722b.png)
Same after visiting any related video (skipping a visit of the home page), red loading bar is stuck, video, etc doesn't change.
![Screenshot_2020-04-04 YouTube(2)](https://user-images.githubusercontent.com/6626242/78423780-6cfb1e00-7671-11ea-99ce-aeeedcbcf488.png)
New firefox profile, dark theme broken on initial Youtube load.
![Screenshot_2020-04-04 YouTube(3)](https://user-images.githubusercontent.com/6626242/78423782-74222c00-7671-11ea-832e-b4ba13d26793.png)
Same results w/o dark theme working on fresh profile.

**Comment by ParticleCore** [comment]
Thanks for the detailed report, but I haven't had the issue yet, might be a matter of time until the YouTube changes you have reach me.

When the issue happens can you open the console and screenshot what it shows? Press F12 and select the "Console" tab.

Please be careful to not show any private information. It might not show any, but might as well be cautious before taking the screenshot.

**Comment by juozaspo** [comment]
The console shows no error (when requests and xhr all disabled, otherwise it shows bunch of requests, including xhr post of TypeError args.fflags is undefined) Screenshot:
![Saityno kūrėjų priemonės – YouTube – https:--www youtube com- 2020-04-04 12:10:05](https://user-images.githubusercontent.com/6626242/78423399-bac25700-766e-11ea-8074-58db79f911c5.png)

**Comment by ParticleCore** [comment]
>xhr post of TypeError args.fflags is undefined

That's a good clue actually, that is the internal YouTube error reporting logging an internal error in their code, which Iridium modifies. Thanks for the info, this should be enough for me to work some sort of a workaround.

**Comment by juozaspo** [comment]
<details>
<summary>Full contents of recent yt error log request, copied from console window on fresh profile, not logged in yet</summary>
Url parameters:

```
a "logerror"
t "jserror"
type "TypeError"
msg "args.fflags is undefined"
line "17:13"
level "WARNING"
client.name "1"
```

Form contents:
```
url "https://www.youtube.com/watch?v=kQFbt5UZdz8"
file "https://www.youtube.com/"
stack "window.modArgs@https://www.youtube.com/:17:13\nwindow.modifier@https://www.youtube.com/:136:16\nKB/a.w[b]@https://www.youtube.com/yts/jsbin/player_ias-vfl6MUxK7/lt_LT/base.js:1964:108\nuR/<@https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9777:50\ncAa@https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9768:215\ngAa@https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9775:424\ntR@https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9774:145\nbAa/a.createPlayerCallback_@https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9771:162\nbAa@https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9772:26\npR.prototype.loadNewVideoConfig@https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9765:24\npR/this.initialLoadConfigTimerId_<@https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9762:50\nxe/<@https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:447:63\n"
client.name "WEB"
client.version "2.20200402"
client.params "\"cueVideoByPlayerVars\""
session_token "[censored]"
```

</details>

**Comment by ParticleCore** [comment]
```
window.modArgs
 @https://www.youtube.com/:17:13
    window.modifier
 @https://www.youtube.com/:136:16
    KB/a.w[b]
 @https://www.youtube.com/yts/jsbin/player_ias-vfl6MUxK7/lt_LT/base.js:1964:108
    uR/<
 @https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9777:50
    cAa
 @https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9768:215
    gAa
 @https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9775:424
    tR
 @https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9774:145
    bAa/a.createPlayerCallback_
 @https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9771:162
    bAa
 @https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9772:26
    pR.prototype.loadNewVideoConfig
 @https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9765:24
    pR/this.initialLoadConfigTimerId_<
 @https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:9762:50
    xe/<
 @https://www.youtube.com/yts/jsbin/desktop_polymer_inlined_html_polymer_flags_v2-vfllLISrH/desktop_polymer_inlined_html_polymer_flags_v2.js:447:63
```

`window.modArgs` and `window.modifier` belong to Iridium, which means the assumption was right.

Thanks for that extra info, that was extremely helpful. Unfortunately that means the video attributes have changed and it is no longer finding them, I have to wait for the new changes to see if they changed location, changed name or both.

In the meantime I will be pushing a safe check (temporary fix) to prevent the rest of the script from stopping if the attributes are not located.

**Comment by ParticleCore** [comment]
Version 1.2.7 should mitigate this issue, but the autoplay feature might not work on first load, this means when the video is first opened, but should work on videos that are subsequently opened in the same page after that one. Will have to see how to fix that one.

**Comment by jonutella** [comment]
Any update on this issue yet?
