### ISSUE TITLE
Videos fail to load

### ISSUE THREAD

**Issue by resindrake** [ParticleCore/Iridium#839]
Iridium version: `0.2.5`
Browser: `Firefox 74.0.1 (64-bit)`

Issue: Videos fail to load whilst extension is enabled about 80% of the time. Refreshing the page fixes this issue.
Play videos automatically is enabled.

Screenshot:
![image](https://user-images.githubusercontent.com/62374268/78465537-3f2ddc00-773a-11ea-99c2-bd0b36487172.png)

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
