### ISSUE TITLE
Rename video previews to avoid confusion with YouTube's equivalent

### ISSUE THREAD

**Issue by MattSturgeon** [ParticleCore/Iridium#84]
YouTube has added video previewing on thumbnail hover (currently also [implemented](https://github.com/ParticleCore/Iridium/wiki/Features#thumbnail_preview) by iridium).

YouTube material now shows an approximate two second clip of the video when hovering over a thumbnail, before returning to the static thumbnail.

This means that even if video previews are turned off, they will still be on for vanilla youtube.

It may be worth looking into a setting to disable the youtube equivalent when Iridium's is off, since it may be confusing to turn off previews, yet still have them.

Alternatively you could simply disable the youtube version completely and just have users toggle your version. You could even rebuild your version on top of youtube's, if you are a perfectionist!

**Comment by ParticleCore** [comment]
Yeah, I was already aware of it before I decided to implement it and was on it once it went live: https://github.com/ParticleCore/Iridium/issues/63

I agree that as of now this might cause some confusion, I might rename it to "full video previews" to distinguish from YouTube's impelementation.

**Comment by MattSturgeon** [comment]
> Yeah, I was already aware of it before

Oops didn't spot #63 - my bad. Funny thing is I've looked at 2d8ef94 a few times before, never noticed from the commit message that it had anything to do with video previews... That's why I like commits to be small, single purpose, and well summarised, but I won't go off on a [rant](/ParticleCore/Iridium/issues/73) again ;)

> I might rename it to "full video previews" to distinguish from YouTube's impelementation.

+1 I'll rename this issue to that and open a separate feature request for fully disabling, in case anyone wants that.
