### ISSUE TITLE
State that the extension is obsolete/abandoned on Chrome extension store

### ISSUE THREAD

**Issue by jasonycw** [ParticleCore/Iridium#840]
Recently YouTube updated again and now most features are no longer usable anymore on Chrome with the very old Iridium 0.2.5
It would be better if the extension's description/title on https://chrome.google.com/webstore/detail/iridium-for-youtube/gbjmgndncjkjfcnpfhgidhbgokofegbl to be updated with "Obsolete" or "No longer supported" and link to https://github.com/ParticleCore/Iridium/issues/737

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by evulhotdog** [comment]
> This extension is only being supported for stable versions of Firefox 57+, there are no plans to support any other browser in the future, including any browser forks. If you are using a different browser then try running the extension in supported version mentioned above.

Well this sucks. This is literally the best youtube extension. MagicActions is literally malware.
