### ISSUE TITLE
youtube issue

### ISSUE THREAD

**Issue by gatekeeper1122** [ParticleCore/Iridium#841]
idk what youtube did to the add-on but everytime i watch a full video then it starts the next one if watching a play list the video will not load i also see that the page doesnt refresh like it does normally when a new video shows i have to manually refresh then works but makes it annoying when listening to music & gives this error (picture link below) it only happens when this add-on is enabled please fix this i enjoy using this i dont want to lose such agreat add-on for youtube
![PZQ8Dce](https://user-images.githubusercontent.com/16184353/78727511-13555680-78f2-11ea-993b-0637d9624854.png)

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
