### ISSUE TITLE
No videos play on FF76 beta

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#847]
All videos fail by gray error screen (player error code 1)
software details:
````
manifestVersion: 1.2.7
cookieEnabled: true
doNotTrack: 1
language: tr
buildID: 20200424000239
name: Firefox
vendor: Mozilla
version: 76.0beta
arch: x86-64
os: linux
DoH:dns.oscx.co
````

**Comment by ParticleCore** [comment]
Please follow these instructions

https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by erkinalp** [comment]
Next beta solved the problem. Turned out to be a Firefox issue.

**Comment by ParticleCore** [comment]
Thanks for letting me know!
