### ISSUE TITLE
Volume scroll also scrolling page

### ISSUE THREAD

**Issue by Suddow** [ParticleCore/Iridium#851]
To be more specific, the volume scroll only works going upwards, but it will scroll the page in either direction (as if it were normally scrolling).

Chrome app.

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by BeeeQueue** [comment]
I can confirm this on FireFox 84 with no other extensions installed
