### ISSUE TITLE
Can you update the old version of this add-on?

### ISSUE THREAD

**Issue by BitGrub** [ParticleCore/Iridium#852]
18 months ago, Iridium used to have features, and that version (0.2.5) of the extension used to work just fine until Youtube decided to change and break things (as it loves to do).

Can you please fix 0.2.5? I tried using youtube without Iridium but it's not even worth it. Youtube is such an awful site without it

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/issues/828
