### ISSUE TITLE
Basic playlist functions gone while listening 

### ISSUE THREAD

**Issue by Zovrah** [ParticleCore/Iridium#855]
Pretty much the title. The playlist sidebar has the shuffle+loop icons missing, and it doesnt look like theres anywhere else you could toggle them. 

looks like this: 
![image](https://user-images.githubusercontent.com/46391669/84823139-ba312f80-afd2-11ea-84bc-dd5ed9b764b0.png)

rather than this: 
![image](https://user-images.githubusercontent.com/46391669/84823277-efd61880-afd2-11ea-9d9c-155c543f7035.png)

**Comment by Binipped** [comment]
Same issue here. Just removes the few features that are available in firefox.

**Comment by KudaKeil** [comment]
Yep, this is still a problem. It's not a HUGE deal for me, but I like to loop my music playlists and it would save a click.
