### ISSUE TITLE
Option to bypass "Video paused. Continue watching?"

### ISSUE THREAD

**Issue by madmuffinz** [ParticleCore/Iridium#859]
I'm enjoying my playlist idly, and then YouTube just interrupts my playlist for when I'm busy doing stuff.
Can we have a feature to disable or bypass the "Video paused. Continue watching?" prompt?

**Comment by 5koder** [comment]
@madmuffinz try this script
https://greasyfork.org/en/scripts/391504-youtube-video-paused-continue-watching-nuker

**Comment by ParticleCore** [comment]
@5koder Please do not use this repository to advertise other software

**Comment by madmuffinz** [comment]
> 
> 
> @madmuffinz try this script
> <removed>

mind sharing it again?
I don't know why the dev removed a possible solution if they aren't going to apply the same feature with this addon.

**Comment by NekoAlosama** [comment]
@madmuffinz You can check the edit history of the comment above.

**Comment by ParticleCore** [comment]
> 
> 
> > @madmuffinz try this script
> 
> mind sharing it again?
> I don't know why the dev removed a possible solution if they aren't going to apply the same feature with this addon.

For the same reason you ended up asking for it again. This is not the right place for this purpose, and it always leads to thread derailment: people asking for links, then the links no longer work and ask for mirrors, then come in complaining something is not working right about what is linked here, and at this point the repository is being misused. There are people subscribed to the repository and being spammed with emails of your questions asking for software not related to this one.
Closing and locking to prevent this from derailing further. If you wish to obtain this kind of information further please ask the the user directly via private message instead.
