### ISSUE TITLE
Memorize player size, not functioning correctly

### ISSUE THREAD

**Issue by shonay** [ParticleCore/Iridium#86]
Hi there,
Not sure if you're aware that the Memorize Player Size option is not working as it used to in YouTube+.
Right now if you set the option turned on, it basically only memorizes the video size for that particular video, if I choose any other videos from youtube, those videos revert to the standard youtube size.
However, with the Memorize Player Size turned off, if I play a video in large mode, then youtube remembers my video size for that session and all videos are played in the large option i chose until I restart my browser.

Hope you are able to fix this somehow.
Thanks for your awesome work on this addon.

**Comment by MattSturgeon** [comment]
> However, with the Memorize Player Size turned off [...] then youtube remembers my video size for that session

It sounds like the toggle may be inverted? i.e. turning the setting on turns off the feature.

**Comment by MattSturgeon** [comment]
Hm, I can't reproduce this. In my testing I am unable to turn memorize video size off.

In my testing I have a control video open which I use to set the size and I open other random videos to see if they open with the same size as the control.

Regardless of memorize video size being on or off, and even after reloading the control video to update Iridium config, new videos always open the same size as the control.

**Comment by shonay** [comment]
Hi Matt, 
No the toggle isn't inverted. When the Memorize Player Size option is turned off it basically reverts to the standard feature of YouTube which is "remember the last size you used" however this is only remembered for the current session in Chrome. Once you close chrome, and reopen to a youtube video, the size sets back to standard. This is the normal way youtube videos process.

The Memorize Player Size option is found in the Video Settings tab, just above Memorize Player Volume.
Can I ask, where do you find the Control Video option? I can't seem to find that in my Iridium. Just checked my version right now and it seems i'm on the latest available Iridium which is 0.04b.

**Comment by MattSturgeon** [comment]
Yes, the latest version is [0.04b](https://github.com/ParticleCore/Iridium/blob/beta/src/userscript/Iridium.user.js) in the beta branch.

How new is the vanilla youtube memorize size feature? It may be conflicting with Iridium's version (similar to #63).

I've just continued some testing, it seems that with iridium memorize size enabled, the second video opened after setting the size to cinema will forget the size. i.e:

- Open video in new tab; set size to cinema; close tab
- Open video again; size remembered; close tab
- Open video third time; size forgotten

**Comment by shonay** [comment]
Yep that is the exact problem I am having. It keeps getting forgotten.

From what I can remember the vanilla youtube memorize size feature has always been around. The only problem with that one is that it forgets the size after the session ends.
Youtube+ corrected this by always remembering the size.

I'm sure the developer will figure it out again - I'll just wait it out, wanted him to know that although the option i there, it isn't working correctly.

**Comment by ParticleCore** [comment]
yep, it's bugged out, will check on it to see what went wrong in recent updates.

**Comment by shonay** [comment]
Hi there,
I know you marked this issue as closed with version 0.0.5b however the problem is still there. It works for the first and second time you play a youtube video, and then on the 3rd video, it reverts back to default small-sized youtube video.

**Comment by ParticleCore** [comment]
With this fix, I have tested with over 20 videos, in sequence and alternating with opening in a new window. It always kept the theater mode if that was the last mode it was changed to.

Unless I can reproduce your problem I am not able to fix it. Make sure your version is up to date and follow the instructions for reporting a problem: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by shonay** [comment]
I don't know what to tell you either, cos it's not working right now. I've installed the new plugin on my main system, on virtual boxes, as well as on my laptop and work desktop, and the feature doesn't save the Player Size on any of them.
The browser I am testing on is Google Chrome version: 59.0.3071.115 (stable)
The UserScript manager I use is the latest TamperMonkey (I have disabled all other scripts as well and left only your script to run to to avoid conflicts if any).
I also disabled all other Chrome extensions and left just TamperMonkey running.

The problem is produced on all of my systems.

**Comment by ParticleCore** [comment]
Please follow the instructions in the link I provided above, all the steps, otherwise this becomes pointless. It is possible that your Chrome profile settings might be causing this, but I can never know if you don't follow all the steps in the instructions.

If I can't reproduce this problem then I can't fix it. Without your exact instructions on how to make this happen on my end there is nothing I can do.

Does the same problem also happen if you use it on Firefox?

**Comment by shonay** [comment]
Hi sorry, I forgot to mention that I have been through all the steps in the link you provided. The only change that I had to make following those instructions is that now I am on Google Chrome version 60.0.3112.78 (Official Build) (64-bit) - this just updated about 2mins ago for me.

In order to reproduce the problem, this is the exact steps which I do.
1- Open youtube.com and click on the Iridium icon
2- Go to Videos tab on the left and make sure "Memorize Player Size" option is "blue" (turned on)
3- Close the Iridium tab and click on any YouTube video
4- Change video size by clicking on the Cinema Mode icon on the bottom left of the video
5- While the video is now playing in Cinema Mode, I then close the video and relaunch youtube.com
6- Click on any video (it opens up in Cinema Mode - as I would expect)
7- Hit play, and it all works fine
8- Play any video after this and the video size is changed back to default (small sized video)

This occurs on all of the computers I have tested on with my Google Chrome profile enabled on my browser as well as with the profile disabled as if its a new user using the browser.

* With Memorize Player Size turned on, it always reverts back to small default size on the 3rd video onwards (since enabling the option)

* With Memorize Player size turned off, it will play the video in the size you set for your current session until the browser is closed and reopen, which you will then have to set the size once again.

I unfortunately haven't tested it out in Firefox yet. I will get back to you with that one as I don't have Firefox installed right now.

**Comment by ParticleCore** [comment]
After you are done, share your settings. I am wondering if there is some sort of setting combination that might be causing this problem.

**Comment by shonay** [comment]
Hi there,
I've just tested Iridium out in a vanilla Firefox installation using GreaseMonkey extension.
I left all Iridium settings as default and made sure that "Memorize Player Size" was set to on.

It worked great for the first few videos and then suddenly around the 5th of 6th video I played, the video size was set back to the default small player. So the problem still persists with a vanilla version of Firefox with all default Iridium settings.

On Chrome, I tested with default Iridium settings and the problem still persists after 3 videos played.
The settings I would normally enable/disable are as follows (although the above tests were done without any changes to these settings):
- Default Channel Tab: Videos
- Disable Square Profile Pictures
- Disable Blacklist
- Default Video Quality: 720p
- Allow Annotations on Videos: ON
- Allow Subtitles on Videos: ON

**Comment by MattSturgeon** [comment]
For me this seems even worse after the update. Now the memory seems encapsulated within the tab, other tabs have no idea what the latest size setting is.

---

With Memorise enabled: I open a video, set it to cinema mode, then sometimes close the video, other times leave it open.

I then return to youtube in another tab and open a new video, invariably it opens in normal mode, not cinema.

---

However, if I open new videos in the _same tab_ as the cinema video, these open in cinema mode, so the setting is remembered _within_ a single tab (testing on chrome).

Open a video and set it to cinema mode, open another video in a new tab (opens in normal mode), close the new video and return to cinema one, open another video in the same tab (opens in cinema mode).

---

I clicked on approximately 20 recommended videos within a single tab, and each one started in cinema mode, however whenever I opened on in a new tab it opened in normal mode. The original tab still remembered cinema mode when I continued with it.

**Comment by ParticleCore** [comment]
After resetting it to default I was able to reproduce this problem again, but only by opening the videos in new tabs. Will have a go at it again to see what is going on. Sorry for all this trouble.

**Comment by shonay** [comment]
No need to apologize. We are here to help. Love the extension and will continue to support it.

**Comment by ParticleCore** [comment]
The latest version should finally fix this bug for good, let me know if it works for you as well.

**Comment by shonay** [comment]
That was quick. Now working perfectly for me. Thank you!
