### ISSUE TITLE
Video not starting

### ISSUE THREAD

**Issue by q1k** [ParticleCore/Iridium#860]
I use the userscript version on Chrome installed from greasyfork.
The videos don't start when clicking.
I don't like the "prevent autostart playing", so I have it set to start automatically (as it should be by default), but videos don't actually start, I have to reload the page.

Other features probably don't work either, but this one is the most irritating.

Please fix so we can keep using the script.

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by q1k** [comment]
What? Please just remove the autostart playing feature, so we can keep using the script.
Thanks
