### ISSUE TITLE
Update the userscript at greasyfork.org

### ISSUE THREAD

**Issue by prostobobb** [ParticleCore/Iridium#862]
Please update the script at greasyfork.org to the current version of the original extension. In its current form, the script is inoperable

**Comment by NexusRevZ** [comment]
Hi Creator. I would also appreciate this update. Im using Maxthon browser and this script is awesome. But, lately the recent update in YouTube is destroying my seemless music exp. Really hope you can quickly update the scripts. Thanks. Much appreciated.

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
