### ISSUE TITLE
Firefox 82 Breaks Iridium

### ISSUE THREAD

**Issue by d4v1dv00** [ParticleCore/Iridium#865]
The add-ons simply just won't work but settings are able to load/save

**Comment by erkinalp** [comment]
Also reproducible by me. #bug

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by erkinalp** [comment]
83 beta and still the same problem.
Locale: Turkish
OS: Ubuntu 20.04
Iridium version: 1.2.7
