### ISSUE TITLE
Chrome automatic playback not working

### ISSUE THREAD

**Issue by jonutella** [ParticleCore/Iridium#866]
Whenever you click a video to play you get this error: ''An error occurred. Please try again later. (Playback ID: 6TkAlkZ4fIdW33YR)'' It is said this has been resolved for other browsers but not for Chrome. I am unsure how to fix it and would love to keep using all of Iridiums functionalities within Chrome.. however this renders it a bit useless :/ Hoping to get help from someone. Many thanks!

**Comment by ParticleCore** [comment]
https://github.com/ParticleCore/Iridium/wiki/Report-a-bug
