### ISSUE TITLE
Feature to hide Premium status

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#867]
As you know, stylised text "Premium" replaces "YouYube" in the when you subscribe to YouTube Premium. This addon should have a feature to hide Premium status and show "YouTube" at all times. The logo replacement is implemented as a SVG path, so this should be easy. If possible, add this toggle in the account dropdown, like YouTube dark mode selector. When enabled, it should also hide the "Originals" hamburger menu item.

**Comment by ParticleCore** [comment]
Unfortunately I do not have a Premium account to check this for myself. If I happen to subscribe to one I will revisit this option since it seems relatively easy to accomplish.
