### ISSUE TITLE
Officially cannot play videos anymore - infinite buffering.

### ISSUE THREAD

**Issue by JoshS-dev** [ParticleCore/Iridium#869]
I've tried to stick with this extension as long as possible, but since yesterday night I cannot run youtube videos with Iridium installed. The 'error has occured' thing has been no big deal, just refresh, but this infinite buffering simply is not helped with refreshing the page; and it makes it so I just can't watch youtube videos with this extension anymore.

**Comment by nicktaylor1** [comment]
Issue is active on my side as well, though I am using Google Chrome. I see on the main page that Firefox is the only supported browser, so this could relate. Have not tested Iridium in Firefox.

Will have to disable script because videos are unplayable.

**Comment by dan400man** [comment]
I just added Iridium to FF 82.0.3 and am having the same problem.  Disabled this extension, and youtube videos work again.

**Comment by dertommie** [comment]
Same issue on chromium. Updating chromium did not fix the issue.

**Comment by ParticleCore** [comment]
Locking to prevent further "same" replies.
