### ISSUE TITLE
Something broke the extension today

### ISSUE THREAD

**Issue by joridiculous** [ParticleCore/Iridium#87]
I have been using this UserScript and the Particle Addon for Chrome, _With the new YouTube layout_, without any real issues at all until today, when both extensions stopped working.
(All was working fine 8-9'ish hours ago, around 3-4-5P M PDT, Very proximate (Im in Europe))

Easy to see its not working. The settings button disappeared and https://www.youtube.com/iridium-settings goes no-where. (generic YouTube "404"-page)
Guess the hipsters at Google changed something, again. :/

Hope it is a quick fix. Cant Stand YouTube without disabled AutoPlay!

**Comment by ParticleCore** [comment]
Please follow the instructions as requested: https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by ParticleCore** [comment]
Please follow the instructions as requested: https://github.com/ParticleCore/Particle/issues/537
