### ISSUE TITLE
IridiumForYouTube in French

### ISSUE THREAD

**Issue by euzzeud** [ParticleCore/Iridium#877]
// EN

Hello ! I translated the extension into French. It's a json file that you can import into the extension's language settings.

// FR

Hello ! J'ai traduit l'extension en français. C'est un fichier json que vous pouvez importer dans les réglages de langue de l'extension.

Link/Lien : https://codeshare.io/5M7Mj3

**Comment by FunMLG** [comment]
Ça irait plutôt dans les Pull requests mais je vais tester de suite !

**Comment by ParticleCore** [comment]
I appreciate the translation, but it has to follow the instructions here: https://github.com/ParticleCore/Iridium/wiki/Locale-instructions

However, hold on until a new version is updated since it will be undergoing significant changes.
