### ISSUE TITLE
auto-hides based on ratings, shows % that rated, auto-filter by time, auto-skip by % of video time

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [ParticleCore/Iridium#88]
hey particle, could you please have these few things in the new version:

* auto-hides/filters videos below a certain percentage (there are other extensions that show the percent or ratings ratio, auto-hide/filter is so much more helpful)

* on search results and maybe video page (of a channel), shows the % of 'how many rated a video' relative to the total view, so (100 rated a video * 1000 views = 10% rated) -- likely would need to multiple number that rated by 100 or something so that the outcome is easy to read/see

* on search results and video page, auto-filters videos below a certain total time like (this extension doesnt seem to work anymore, not sure why) -- https://chrome.google.com/webstore/detail/youtube-pickalen/hgdcfacmniokkeaaojkgpeohkbabkigd?hl=en 

this last one is helpful when looking for 10-19mins videos, but the first one of auto-hiding is the single most important one

there hasn't been any extensions that does these and it would be really really helpful, been needing it for years

* also auto-skipping the video to 50% or 70-80% in would be helpful as well

---

i was responding to https://github.com/ParticleCore/Iridium/issues/83 -- but decided a new post would be better

"im still on the 'old' layout since im never logged in so does Iridium work on old layout or no?

i never used many of the functions of particle so hopefully this new version could be more minimalist 

i was one of the very early users that found particle and i talked with the dev at least on one occasion in the long past

youtube takes up ~30% of my total web time, 16h a day - https://chrome.google.com/webstore/detail/webtime-tracker/ppaojnbmmaigjmlpjaldnkgnklhicppk

here are the sites i've banned (i focused on the high views ones so i dont run into them again), banning smaller, lower-views, channels is pretty pointless, same with google results or any results. the frequency in comparison with higher-views results is too low:

{
  "UC-p_KoeP5vB44RMfYD7k1Zg": "scum",
  "UC4EY_qnSeAP1xGsh61eOoJA": "YaleCourses",
  "UC7_YxT-KID8kRbqZo7MyscQ": "Markiplier",
  "UC9CswYtb5rL31CHwyVoyJvQ": "The Museum of Modern Art",
  "UCCjyq_K1Xwfg8Lndy7lKMpA": "TechCrunch",
  "UCCqnN6ApN4VO9uKOpCoDxww": "LORE",
  "UCDMOEj6lneZWgrp-r8KqXIQ": "Ravi Zacharias International Ministries",
  "UCDVPcEbVLQgLZX0Rt6jo34A": "Mr. Kate",
  "UCEBb1b_L6zDS3xTUrIALZOw": "MIT OpenCourseWare",
  "UCEfASxwPxzsHlG5Rf1-4K9w": "Effective Altruism",
  "UCFNm26OW87Dm3fZ1txX1vGA": "UCD - University College Dublin",
  "UCGaVdbSav8xWuFWTadK6loA": "vlogbrothers",
  "UCGoxKRfTs0jQP52cfHCyyRQ": "Center for Brains, Minds and Machines (CBMM)",
  "UCHnyfMqiRRG1u-2MsSQLbXA": "Veritasium",
  "UCIBpItHxTpuug31geLR8Ymg": "Atheist vs Theist Debates",
  "UCJdKr0Bgd_5saZYqLCa9mng": " Rubin ",
  "UCJx5KP-pCUmL9eZUv-mIcNw": "GameTrailers",
  "UCKmkpoEqg1sOMGEiIysP8Tw": "Evan Carmichael",
  "UCKy1dAqELo0zrOtPkf0eTMw": "IGN",
  "UCNAxrHudMfdzNi6NxruKPLw": "Sam Harris",
  "UCNnUnr4gwyNmzx_Bbzvt29g": "Linux Scoop",
  "UCNye-wNBqNL5ZzHSJj3l8Bg": "Al Jazeera English",
  "UCQlRhZk3WxSLPKxrFUGfUlw": "Barnard  ☢️ on ⚠️girl",
  "UCRcHDNWSvYi9aL9OQ5FSoNg": "Global Silicon Valley",
  "UCSlVFs-sx_DLNhdigHajWAw": "♛ Sam Harris",
  "UCTfabOKD7Yty6sDF4POBVqA": "Joe Collins",
  "UCVYUMiOc0vgnpKOOsoay3yA": "Divine Munchies",
  "UCW1C2xOfXsIzPgjXyuhkw9g": "Simons Institute",
  "UCW2eNKQeNIvl6MgFNKwLgBQ": "cmurobotics",
  "UCW4lQ2ZZh9EaVNpVtA6hX1Q": "World Government _",
  "UCY70MMJ8Rj4wtwt7bVN6hIA": "Bank of England",
  "UCaLfMkkHhSA_LaCta0BzyhQ": "Munchies",
  "UCakbhT1zJqJ9iod01nFEYhw": "Lee Kuan Yew School of Public Policy",
  "UCaqcvH8EvUtePORpN03jLMg": "iqsquared",
  "UCb2EYjrzI6WpNAmPZeihhag": "The Film Archives",
  "UCbObxjfi3W9YKnDS0PgadNA": "LibraryOfCongress",
  "UCbu2SsF-Or3Rsn3NxqODImw": "GameSpot",
  "UCczFdwWpVEpoqb-eMm4c4dQ": "Matt Steffanina",
  "UCd1Em1-LmLiRwe1eGIUsYxw": "MMOBomb",
  "UCduCK7RYHL6ysV_t_BD5zPw": "psimanjuntak",
  "UCh6KFtW4a4Ozr81GI1cxaBQ": "☢️  Tv (UCTV)",
  "UCikhT43Ik2-D0XciaakTnCw": "UBS Center",
  "UCimxROEIlNsiRqT9X5tg2XQ": "iBioEducation",
  "UCkkhmBWfS7pILYIk0izkc3A": "This Week In Startups",
  "UClsDufMxcJeIkE7pJ2BkExQ": "AGHA Tutorials",
  "UCn9ZEpFW7sKH-IJX4kWP1mQ": "Ryan Geldermann",
  "UCoiTVuiMdqBRMSBGMEcmxCw": " Aspen Institute",
  "UCpGDRwjxrOJxfPUykX8qdKg": "Theology, Philosophy and Science",
  "UCpwvZwUam-URkxB7g4USKpg": "RT",
  "UCsJezu3tK45jPs0ywrq0S0Q": "The Veritas Forum",
  "UCs_uxxQ3l4osUmLgOcF7jXA": "Philosophical Overdose",
  "UCsooa4yRKGN_zEE8iknghZA": "TED-Ed",
  "UCu_u-P3cBFO7D-sAjxd_I-w": "The Agenda with Steve Paikin",
  "UCvQECJukTDE2i6aCoMnS-Vg": "Big Think",
  "UCw-_ba5d6gmjlfQMNAgXS6w": "ayabaya",
  "UCw-kH-Od73XDAt7qtH9uBYA": "World Economic Forum",
  "UCw8ZhLPdQ0u_Y-TLKd61hGA": "1MILLION Dance Studio",
  "UCy1Ms_5qBTawC-k7PVjHXKQ": "TotalBiscuit, The Cynical Brit",
  "UCyJi3YHZPNkZGAYIix4FRLw": "DLDconference",
  "UCzuqE7-t13O4NIDYJfakrhw": "Democracy Now!"
}

**Comment by ParticleCore** [comment]
>For any issue created it must only refer to one issue only.

https://github.com/ParticleCore/Iridium/blob/master/CONTRIBUTING.md

**Comment by SolveAllProblemsRightNow** [comment]
..............

**Comment by ParticleCore** [comment]
Please do not spam the issue tracker.
