### ISSUE TITLE
Feature request: Change default video speed

### ISSUE THREAD

**Issue by jeffhgit** [ParticleCore/Iridium#881]
Similar to the option to set a default video quality, it would be extremely useful to be able to set the default video speed to 1.5x, etc for those of us who use that. 

PS love the project! Donated

**Comment by gorbiWTF** [comment]
There hasn't been any activity for almost a year, no updates in two years…

**Comment by ParticleCore** [comment]
Will tackle this one next. Seems like YouTube now allows custom speed too, so I will explore that to see if it's worthwhile, otherwise I'll just keep it simple:

![image](https://github.com/ParticleCore/Iridium/assets/9222661/7fa576e0-db8e-4c43-9e6d-bd90609ca3da)

**Comment by ParticleCore** [comment]
For now I've kept it simple, did not see much benefit in letting it select a specific speed with more detail as of now, but will be open to consider enhancing this in the future.

![image](https://github.com/ParticleCore/Iridium/assets/9222661/dcaaa208-5f04-4677-9621-b440702bea4e)
