### ISSUE TITLE
Manifest v3 support

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#884]

**Comment by ParticleCore** [comment]
The new redesign will be focused on being compatible with Firefox's and the extension requirements.

As far as I can see, the API I prioritize appears to not have been tampered with in manifest v3 for non-chromium browsers: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json

If that is the case then the manifest will be upgraded to v3, but for the time being it will be reworked using v2.

**Comment by ParticleCore** [comment]
I have no idea why I closed this.

**Comment by ParticleCore** [comment]
The new manifest v3 appears to have some problems, mainly one of the host permissions is never prompted to the user and it is required for the extension to work properly.

![image](https://github.com/ParticleCore/Iridium/assets/9222661/d0d989ad-e529-40f5-95f9-66dfc2f4001e)


Honestly I don't even know how to resolve this, and the available documentation does not show any hope of solving this issue, so I think for now it will have to be on a learning curve basis and explain users they need to manually give that permission, unless I have overlooked something. This is extremely not user friendly and I hope Firefox will improve this soon.

**Comment by ParticleCore** [comment]
I've had to revert this upgrade due to the issues outlined in #907
