### ISSUE TITLE
Redesigning extension and cleared most outdated issues

### ISSUE THREAD

**Issue by ParticleCore** [ParticleCore/Iridium#885]
Currently evaluating the redesign effort for the extension.

Since most issues were very old they would no longer be relevant and have been closed.

There is currently no timeline on when the release will be published, still have lots of information to catch up both from the YouTube side as well as Firefox side.

**Comment by erkinalp** [comment]
Any roadmap on planned features?

**Comment by ParticleCore** [comment]
That issue was mainly due to a feature that required setting a value in an existing YouTube cookie (so not even our own cookie) where they required the feature to be opt-in, which would made it impossible to deal with.

Right now none of these features I plan on working will be undergoing the same issue, but we will see.

I would love to have the new version listed on AMO since it makes it easier for my friends and family, but no promises until I'm able to have something working.

**Comment by ParticleCore** [comment]
An update to make things easier to follow from here, any features that I am considering, working on, or completed for the upcoming release can be checked here: https://github.com/ParticleCore/Iridium/projects/1

**Comment by ParticleCore** [comment]
New version 2.0.0 is out: https://github.com/ParticleCore/Iridium/releases/tag/2.0.0

Will keep this announcement here for a while until I finish updating the rest of the repository documentation.
