### ISSUE TITLE
Working download button for everyone

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#906]
Using the WASM version of yt-dlp

**Comment by ParticleCore** [comment]
I am considering re-implementing #780 and I might explore a very basic integration with ffmpeg if it's not too big of a deal, but this is definitely not an immediate priority.

**Comment by ParticleCore** [comment]
Unfortunately the complexity required for integrating something that would be barely functional (and very limited) makes it not worth it when there are plenty of very powerful and configurable solutions already available.
