### ISSUE TITLE
Full screen mode

### ISSUE THREAD

**Issue by anotherduckling** [ParticleCore/Iridium#909]
Is it possible to add full screen mode in this extension like [this script](https://greasyfork.org/en/scripts/442089-pkga-youtube-theater-mode)? It makes the theater mode full screen which is helpful.

![image](https://github.com/ParticleCore/Iridium/assets/57977673/2ed88f90-a789-4fae-a627-4798adae75a6)

**Comment by ParticleCore** [comment]
I'm not really interested in this specific type of feature, but I am considering re-implementing the full browser mode the extension had previously in which the player fills the entire page.

**Comment by ParticleCore** [comment]
Oh wait, do you mean to fill the browser and also keep the chat visible? Sorry, the images were not loading for me at the time I read this issue and I thought of something very different than what you were showing.

**Comment by anotherduckling** [comment]
Yea. Like twitch. The script does it, but it can be a good feature to have. I havent used the old one, so didnt it was there.

**Comment by anotherduckling** [comment]
>If it's livestream

https://github.com/ParticleCore/Iridium/assets/57977673/19218586-d492-46c3-8ed7-96ebfd9d8981

>If it's a normal video

https://github.com/ParticleCore/Iridium/assets/57977673/20ce9128-3f7f-4a8a-b29a-78e51a0ab376

**Comment by ParticleCore** [comment]
I've begun developing the full browser feature and targeted it for 2.0.5 

I will try to make this one into it as well, but no promises. If it takes time it might be added in another version.

**Comment by ParticleCore** [comment]
I've been able to come up with something that is not overly complex to make this work:


https://github.com/ParticleCore/Iridium/assets/9222661/4e61620f-ff1c-43cc-9131-0defb3a28b74


Still trying to figure out how to approach the option to show/not show it (different than show/hide chat). I might just make it a simple toggle in the extension settings, but would like to have a button over the player that allows the user to right there and then show/hide the chat. I will see if I can create something for this that is not too much of an headache.

**Comment by ParticleCore** [comment]
@anotherduckling would you be willing to test the new version? I've implemented 2 new features that are enabled by default; super theater and sidebar chat. You can find it attached, this is meant to be used with Chrome. If you want to test with Firefox let me know.

[Iridium1.zip](https://github.com/ParticleCore/Iridium/files/14379247/Iridium1.zip)

To test this version:

- extract the files
- in your Chrome browser go to your extensions page `chrome://extensions/` 
- enable developer mode
![image](https://github.com/ParticleCore/Iridium/assets/9222661/2754f74b-30f6-4e48-bd2b-c7e56af45aa4)
- and on the left click on load unpacked
![image](https://github.com/ParticleCore/Iridium/assets/9222661/5c9e8345-802a-4b12-9ce3-bf2479427dd4)
- select the folder with the files you extracted and that should be it

remember before testing this to disable any extensions you have that might conflict, including your previous Iridium version

**Comment by ParticleCore** [comment]
YouTube is pushing a new UI that makes these new features break: https://www.reddit.com/r/youtube/comments/1awxci3/the_hells_going_on/

I will try to update them to account for the new changes.

**Comment by ParticleCore** [comment]
Please use this version instead, it contains fixes to make the extension compatible with thew new layout:

[Iridium2.zip](https://github.com/ParticleCore/Iridium/files/14381639/Iridium2.zip)

**Comment by ParticleCore** [comment]
I will close this as the feature has been implemented in #936 and is heading to release
