### ISSUE TITLE
Missing Pop-Out video window.

### ISSUE THREAD

**Issue by bcaplin83** [ParticleCore/Iridium#926]
Will this be coming back in 2.x? I used the feature all the time as I hate going into videos and watching there.

**Comment by ParticleCore** [comment]
Do you mean this feature?

![unnamed](https://github.com/ParticleCore/Iridium/assets/9222661/5203f1d9-b851-4bff-9dd0-fa56d9e2b208)


I did not invest in that feature again because both Firefox and Chrome now have PIP natively.

**Comment by bcaplin83** [comment]
Any chance of adding the little shortcut button back on video thumbnails?, going into a video everytime is getting old quickly

**Comment by ParticleCore** [comment]
Likely not going to happen in the near future, but I will keep in mind.

**Comment by bcaplin83** [comment]
Will watch out for but in that case I'm going back to the previous version, it worked for me and my way of watching youtube.

**Comment by ParticleCore** [comment]
I was almost certain no features were working anymore from the previous version, in that case it might make things easier. Will take a look at it in the next version or the one after.

**Comment by JoshS-dev** [comment]
Before I put the request in a new thread, would this be referring to the mini-player that Iridium used to have such that when you scrolled down while watching a video, a tiny player would appear in the bottom-right? I quite liked that feature for when I was reading comments on the same page.

This may be something entirely different but Im not sure, if so I'll just add a new thread haha.

**Comment by ParticleCore** [comment]
@JoshS-dev that would be the always visible player, it is different than this one here.

I thought I already had one issue opened for that, but seems like I don't. You can go ahead and open it and I'll track the implementation there, I do want to bring back that feature.

**Comment by ParticleCore** [comment]
I have not forgotten about this feature, but with the thumbnail previews making it a nightmare to place a button on, and the video page UI changing I have not been able to make anything worth implementing at this point.

**Comment by bcaplin83** [comment]
> I have not forgotten about this feature, but with the thumbnail previews making it a nightmare to place a button on, and the video page UI changing I have not been able to make anything worth implementing at this point.

Thats a pitty, It really is the one thing I really want :(

**Comment by ParticleCore** [comment]
Will park this one on the side for now, I cannot get to a good estimate on whether this can be done relatively easy at this time.

**Comment by bcaplin83** [comment]
I was holding out but I guess I go back to a old version, I can't watch youtube without it, going into every video just to use the pop-out player is beyond annoying.
