### ISSUE TITLE
Opera video pop out

### ISSUE THREAD

**Issue by adeep** [ParticleCore/Iridium#93]
Browser Name:  Opera Beta 
  Browser Version:  47.0.2631.31 (PGO)
  Operating System: Windows 10 creators update 64bit
  Software Type:  Userscript
  Software Version:  0.0.7b
  Userscript Manager: Tampermonkey
  Userscript Version: v4.2.5291

  Problem Description: Opera has video pop up option for video site. In Youtube you can pop up video. But after 0.0.7b, that button pops up the video is hiding when hover the mouse over it.

  Steps to reproduce:  In Opera enable Settings - Website - Video Pop Out, Enable video pop out. Play Youtube video and try to click pop out button at the top-middle on video. 
![screenshot_3](https://user-images.githubusercontent.com/374042/28755986-b1480a3e-756e-11e7-94cf-3faa5ef3b73e.png)

  Additional details: I reinstall 0.0.6b again and it work without problem. Something in 0.0.7b cause that probably.

**Comment by ParticleCore** [comment]
>This extension is only being supported for **stable versions** (...)

https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

I have also decided that I will not provide bug support for Opera, having three browsers is too much for me.
