### ISSUE TITLE
'Change volume using the mouse wheel' cannot stay disabled

### ISSUE THREAD

**Issue by ColonelGerdauf** [ParticleCore/Iridium#94]
While it saves all the other parameters just fine, the scroll wheel volume function (which I need disabled for convenience reasons) is giving me trouble. 

To put this short; I click on the Iridium button and go to Iridium>Video to disable the function. I leave the 'Iridium Settings' tab open. I refresh the tab to see that it is indeed reported as disabled. Then I refresh the window of the video I was watching only to find that it is still enabled. I refresh the Iridium page again, and it seems to insist that it was never disabled at all. If I close the tab instead and reload it after testing, the same thing happens.

I did not see anything of this context being reported/explained, leading me to believe that this is unexpected and abnormal behavior. Does scrolling in the video re-enable the function?

**Comment by ParticleCore** [comment]
That's not the expected behavior, it shouldn't enable itself unless you explicitly want to. I will give it a look and see what might be causing this.

**Comment by ColonelGerdauf** [comment]
After some further testing, I managed to disable the function for good. It required me to close the YouTube web page before changing the setting in the Iridium page.

That tells me that there is an issue with the function failing to register a boolean change and instead overwriting it with what is already there, likely relevant to session cookies.

**Comment by ParticleCore** [comment]
Sorry for the delay, a solution for this one took quite some thinking to get to. I hope this time it is at least better and this fix comes with a room for improvement in the future, or recent future if needed. For now I want to see how it behaves before thinking about adding more bloat to the code if it reveals to be unnecessary.
