### ISSUE TITLE
Scroll volume amount

### ISSUE THREAD

**Issue by a0w89fwa0f** [ParticleCore/Iridium#944]
Is it possible to add a way to adjust the interval the volume increases / decreases when using the Scroll volume feature. As of now it only changes in an interval of 5 where maybe I would want to set it as 1?

**Comment by ParticleCore** [comment]
This should be simple enough to implement, it is totally controllable from our side. I will see what can be done.

**Comment by ParticleCore** [comment]
By the way, the upcoming version 2.0.5 will change the scroll volume behavior to `Shift` + `scroll` from anywhere in the page. New features were added as well which would be impossible to work correctly if the default scroll volume behavior was kept.

**Comment by ParticleCore** [comment]
The feature seems to be working fine. I know a dropdown is not the best solution for a list of numbers, but for now it will do and I'll consider improving it in the future.

The feature is limited between 1 and 10 steps, I think 10 is quite fast enough for anyone and 1 is the smallest it can go.


https://github.com/ParticleCore/Iridium/assets/9222661/31803f80-378b-4047-933a-1a8e32c1b74f
