### ISSUE TITLE
Autoplay when video is on a playlist

### ISSUE THREAD

**Issue by eduzappa18** [ParticleCore/Iridium#949]
It would be nice to always autoplay videos when they are in a playlist, regardless of the autoplay setting.
Or to have a new autoplay setting for playlist only

**Comment by ParticleCore** [comment]
I'll be implementing #939 soon, this will provide users with a button on the video page where the autoplay setting can be quickly turned off and on. This should make it easier for situations when users want autoplay enabled, such as while in a playlist, or disabled for everything else. Would that work?

The idea of adding another setting for this scenario will increase the complexity of an already complex feature, and I would like to avoid that.

**Comment by eduzappa18** [comment]
that sounds good.
and sorry, I should've checked the other issues first

**Comment by ParticleCore** [comment]
No worries, that's perfectly ok.

**Comment by ParticleCore** [comment]
Feature has been completed in #939 and will be out in version 2.0.7
