### ISSUE TITLE
Feature request: Option to sort Playlists and Subsctriptions by name

### ISSUE THREAD

**Issue by S-ed** [ParticleCore/Iridium#95]
Greetings.
It would be nice to have the ability to sort alphanumerically Subscriptions and Playlists (not videos within a playlist).

i.e. Now Youtube only shows playlists in the order of most recent update, it's really hard to navigate for me (50 playlists all assorted randomly)
I am talking only about this two menus:

![screenshot 1501678037](https://user-images.githubusercontent.com/3008353/28874357-32122294-779a-11e7-992d-6387c1d4789e.png)

Optional features:
1) checkbox if 'Watch Later' playlist should be shown first (since it could not be renamed)
2) option that allows setting 1-5 most recent playlists to be shown on the top of the list (preferably a copy)

- Watch Later
- _Playlist 34_
- _Playlist 23_
- Playlist 1
- Playlist 2
- Playlist 3
- Playlist 4
- Playlist 5

Thank You!

p.s. Maybe there's already such option and I just could not find it?

**Comment by MattSturgeon** [comment]
For reference, here's a [jsfiddle](https://jsfiddle.net/gabrieleromanato/eJf55/) I found that sorts html lists alphabetically.
