### ISSUE TITLE
[Feature Request] channel video count

### ISSUE THREAD

**Issue by eduzappa18** [ParticleCore/Iridium#957]
It's something that I loved about the old userscript, specially for having the link to the channel using the channel id

I'd love to see that feature back

**Comment by ParticleCore** [comment]
Seems like the old logic will still work, they keep the same information available in the YouTuber page:
![image](https://github.com/ParticleCore/Iridium/assets/9222661/94989532-7354-4612-a020-4faff6936710)

Unsure about any edge cases, but just like before if it does not find anything then it won't show it.

Still need to check the new YouTube video page UI to ensure it will be positioned in the right place.

**Comment by ParticleCore** [comment]
The feature is working correctly, I'll keep the same style as in the past, which is how it is displayed in the channel page

![image](https://github.com/ParticleCore/Iridium/assets/9222661/6fb86954-ef63-4473-b5f0-46e66a1edf18)

There might be space limitations when the page size is too small, but it wouldn't be worth trying to resolve that so it will remain with that limitation.

Still need to implement the ability to click it and open the channel video tab.
