### ISSUE TITLE
Video not starts

### ISSUE THREAD

**Issue by francesco-cadei** [ParticleCore/Iridium#962]
Firefox 115.7.0esr (64-bit)
Debian 12

**Comment by ParticleCore** [comment]
Sorry but you provide no information for me to use, can you follow the instructions? https://github.com/ParticleCore/Iridium/wiki/Report-a-bug

**Comment by francesco-cadei** [comment]
Troubleshooting not solve.
Version 2.0.7.

**Comment by ParticleCore** [comment]
I am sorry but everything is working ok for me on the latest Firefox version, both stable and nightly.

The information you have provided so far is not enough for me to find out what is the problem you are having and how to replicate it.

**Comment by francesco-cadei** [comment]
Thanks, autoplay solve the problem.

**Comment by ParticleCore** [comment]
Ah perfect, glad you got your issue solved, I will close this now then.
