### ISSUE TITLE
Black screen on upcoming Livestreams

### ISSUE THREAD

**Issue by BradyThe** [ParticleCore/Iridium#968]
- Iridium version: 2.0.7
- Browser: Firefox 124.0
- Troubleshoot Environment: 
   - New Profile
   - Only Iridium add-on installed
   - Test 1: Default add-on configuration
   - Test 2: Default add-on configuration with autoplay enabled
   - Any [upcoming livestream](https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig/livetab?ss=CKMK)

As the title suggests, the video player is completely black and the countdown is missing. The user has to refresh the page after the livestream start, to be able to start the stream (when enabled, autoplay doesn't appear to be working).  
(I suspect video premieres will be affected by the same problem, but I cannot confirm that.)

Cheers for restarting work on this extension!

**Comment by ParticleCore** [comment]
Yes, I believe I addressed this just yesterday in #966 can you confirm it is the same issue you were describing? It will be released in 2.0.8

**Comment by BradyThe** [comment]
> Yes, I believe I addressed this just yesterday in #966 can you confirm it is the same issue you were describing? It will be released in 2.0.8

I just tested this change locally and it works. I apologize for opening an unnecessary issue. I can't explain how I overlooked #966.

**Comment by ParticleCore** [comment]
No worries, since at least one user (you) is already having this issue I will try to push the new version today and work on the other items for the next version, thanks for confirming it.

**Comment by ParticleCore** [comment]
Seems like the Firefox addon store has been going fast lately, version 2.0.8 is now available for update on AMO:

![image](https://github.com/ParticleCore/Iridium/assets/9222661/aa394344-e134-43d7-bf4a-d34299e31973)
