### ISSUE TITLE
Clicking on a channel name on a recommended video should open the channel

### ISSUE THREAD

**Issue by JoshS-dev** [ParticleCore/Iridium#973]
![image](https://github.com/ParticleCore/Iridium/assets/34352316/dd973875-6108-4cad-be21-39931758fd34)

In a case like this, when the youtube channel name is visible in a tooltip, I think that the youtube channel should open rather than the video. If one wants to go to the video, they should click on the video title or thumbnail. I double checked, this does not happen in vanilla youtube and it does not happen in Iridium currently either. Would be a handy feature to save some extra navigation.

**Comment by ParticleCore** [comment]
I did a quick check on their code and it would be too much trouble to be worth the feature itself (the entire description is inside the link itself), I'm not too into it at this moment:

![image](https://github.com/ParticleCore/Iridium/assets/9222661/d93a813a-f2c2-407e-b79b-b71b3778f2c5)

![image](https://github.com/ParticleCore/Iridium/assets/9222661/4132c858-b808-449a-a735-2642e9c8e34d)
