### ISSUE TITLE
Issue with nav bar width in super theater mode

### ISSUE THREAD

**Issue by Piripe** [ParticleCore/Iridium#975]
The nav bar has a static size in super theater mode.

I'm using Firefox 124 with Iridium 2.0.9.

Example screenshots:
![image](https://github.com/ParticleCore/Iridium/assets/77517308/fa0d3547-642e-4ef8-8c3e-764fb77149db)
![image](https://github.com/ParticleCore/Iridium/assets/77517308/46eeb747-6f8e-4579-bff3-00b38e9b6d42)

**Comment by ParticleCore** [comment]
Hi, sorry about this but can you clarify what you mean? I am having a hard time understanding what you're explaining to me.

**Comment by Piripe** [comment]
Currently, when I resize the window, the nav bar keeps the same size. So when I resize the window to a smaller width, the nav bar overflows (and when I resize to a larger width, the nav bar doesn't take up the whole width of the window)

**Comment by ParticleCore** [comment]
Oh, now I get it, it happens when resizing the window. I will check it out and see what is happening.

**Comment by ParticleCore** [comment]
Actually, checking your second screenshot shows an odd thing, a scrollbar (I am assuming that's a scrollbar) that is not the normal one:

![image](https://github.com/ParticleCore/Iridium/assets/9222661/911613a0-387b-41a9-bf81-5074bbb1a426)


vs the normal scrollbar in the previous screenshot

![image](https://github.com/ParticleCore/Iridium/assets/9222661/10f8e5ae-3a41-42e0-8f96-62c7d3016761)

Seems like the window is being resized in a way that is not like my window. Can you take a screenshot of the entire browser window when resized?

**Comment by ParticleCore** [comment]
On a second thought, it looks like you have some other YouTube extensions, so let's rule out the possibility of this being a problem caused by Iridium.

Test the issue with Iridium disabled (remember to refresh YouTube), does the issue still happen?

Test the same issue with Iridium enabled, but all other extensions disabled (including Stylus, for example), does the issue still happen?

**Comment by Piripe** [comment]
The scrollbar in the first screenshot is a scrollbar from the video I was watching, not my browser's scrollbar, and the scrollbar in the second screenshot is the Firefox's scrollbar, my actual browser scrollbar.

And yeah, I have a lot of extensions. I tried in a private window with only Iridium enabled. And the issue persists.
I also have more precise steps now, after trying to reproduce the issue.
It happens when closing the live (or VOD) chat

Here's the nav bar with the chat open:
![image](https://github.com/ParticleCore/Iridium/assets/77517308/98ebb206-fde8-4028-b15a-84bbe96df545)

And here's the nav bar without the chat:
![image](https://github.com/ParticleCore/Iridium/assets/77517308/c87402ca-b329-4a68-aa87-906242a5d7d9)

And while trying to reproduce the issue, I found a conflict with another extension but I don't know which one, I'll make an issue if I haven't found a solution and if I have more info about it.dd

**Comment by ParticleCore** [comment]
Perfect, thank you for the steps, that was exactly what I needed. I will fix this asap.

**Comment by ParticleCore** [comment]
Logic excludes updates when the chat is no longer visible: 

https://github.com/ParticleCore/Iridium/blob/dfaa5dff87bc1d8600449bd67283d766eb5d2d95/src/firefox/js/background-inject.js#L993

Will have to reset the size to normal behavior when that happens, currently that scenario is not being taken into account.

**Comment by ParticleCore** [comment]
@Piripe I have not forgotten about this issue, it will be resolved along with #976 which is a bigger one and was discovered thanks to this one you opened. I intend to have a new version for these fixes by the end of this week.

**Comment by ParticleCore** [comment]
Issue should be resolved, seems like during my previous implementations with that feature the reset portion was still using old code. 

https://github.com/ParticleCore/Iridium/commit/9d5a6551a7eb54b67f3a61ead9437333f3f3c901#diff-64234f092fc31df67bfb1b6c9d2ae604e01f21ebc0a378a0a390f359b335e3a4R1046-R1053

I'll be pushing the new version with this fix today.
