### ISSUE TITLE
[Feature Request] Add option to force only one video playing simultaneously 

### ISSUE THREAD

**Issue by Termuellinator** [ParticleCore/Iridium#980]
First of all: nice to have you back! <3

V2 already works pretty well for me, the only feature i'm really missing compared to improvedtube (that i used in the meantime) is the ability to have only one video playing at a time.
So if i press play on a video in tab A while another video is playing in tab B, the video in tab B would automatically be paused.
Don't know how hard that would be to implement of course, but i would really appreciate it :)

**Comment by ParticleCore** [comment]
I understand the purpose of the feature, but I am not very interested in adding it to Iridium, at least not for now. I am trying to move away from browser APIs to maybe be able to port the extension back to Userscript model, and working around that (cross communication between tabs/windows) for this feature would be too complex to be worth it for me.
