### ISSUE TITLE
Scroll volume does not persist

### ISSUE THREAD

**Issue by LazyBoot** [ParticleCore/Iridium#982]
Changes to volume using (shift +) scroll does not persist between videos, unlike the normal arrows or clicking the volume bar.

Tested on iridium 2.1.0 (chrome 125.0.6422.26)

**Comment by ParticleCore** [comment]
Thanks for letting me know, I will see what is going on.

**Comment by ParticleCore** [comment]
Issue was a small change to the player API, fix will be available in the next release.
