### ISSUE TITLE
No longer able to click on videos to open them, only their titles.

### ISSUE THREAD

**Issue by JoshS-dev** [ParticleCore/Iridium#986]
I can no longer open videos, either in a new tab with middle click or the current one with left click, by clicking on the thumbnail/video, ONLY by clicking the title. I am not sure if this has to do with the thumbnails autoplaying but the option simply isn't there.

![image](https://github.com/ParticleCore/Iridium/assets/34352316/52e12945-6ac1-4cc4-a535-1b22d8a556d5)

^ This is what shows when I right click the video. There is no 'open' or 'open in new tab'.

**Comment by ParticleCore** [comment]
Does the same issue happen after you disable Iridium and refresh the page?

**Comment by JoshS-dev** [comment]
It was fixed... but when I turned Iridium back on it is working again as well. So I am kinda confused.

**Comment by ParticleCore** [comment]
I believe it was something perhaps temporary on YT side of things that changed again when you refreshed, so it is back to normal regardless of Iridium being enabled or not. Glad to hear it's back working, I have been super busy for the past month and another issue right now is not something I would be looking forward to!

**Comment by JoshS-dev** [comment]
Haha I can never be sure! Sorry if I caused any additional stress, love the work you do here!

**Comment by ParticleCore** [comment]
Not at all, I appreciate letting me know when something might be wrong with the extension, don't fret about it!
