### ISSUE TITLE
Showing the creator's name under YouTube Shorts videos

### ISSUE THREAD

**Issue by JoshS-dev** [ParticleCore/Iridium#987]
It would be nice if, under youtube shorts videos, it would show the creators name. Useful if the title and thumbnail look similar to someone you follow but actually are not them. I've thought I was clicking on a certain person's videos when I actually wasn't one too many times.

![image](https://github.com/ParticleCore/Iridium/assets/34352316/e74710de-5cdb-45ca-ac1a-574a02afa4af)
![image](https://github.com/ParticleCore/Iridium/assets/34352316/7bdbea05-d1e7-40cf-acce-0199fc6fa80f)

**Comment by ParticleCore** [comment]
To be honest I am not really a big fan of shorts so I never invest too much time on it, but will keep it in mind in the future if I reconsider investing more time in that section of content.
