### ISSUE TITLE
The ability to block videos from search results by regular expression

### ISSUE THREAD

**Issue by kqvanity** [ParticleCore/Iridium#988]
It would be great if one could block all videos if their title/comments/channel name matched a certain regular expression.

**Comment by ParticleCore** [comment]
Sorry, closed this one but didn't even commented. The extension currently has some performance impact, which would be made worse if regular expressions were to be implemented, along with the complexity of adding another logic to store the regular expressions as well.

It does sound interesting, and practical, but not something I am interested on doing for now.
