### ISSUE TITLE
Feature: Force more eager caching

### ISSUE THREAD

**Issue by erkinalp** [ParticleCore/Iridium#993]
When enabled, force caching as much of the video in one go as possible while the video is being viewed.

**Comment by ParticleCore** [comment]
I've attempted to do this in the past, but the biggest challenges then, and now as well, are the constant changes to the logic that instructs when to fetch more parts of the video, as well as the signature/secret algorithm which has been causing headaches, especially for downloaders. It is not something I'm interested in doing at this time.

**Comment by erkinalp** [comment]
@ParticleCore You could copy the logic from yt-dlp (it somehow manages to fetch all parts)
