### ISSUE TITLE
[Firefox] Can't select quality above 720p

### ISSUE THREAD

**Issue by phraggers** [ParticleCore/Iridium#996]
When Iridium is active, I can't select any video quality over 720p

example with iridium enabled:
![Screenshot 2024-09-13 002322](https://github.com/user-attachments/assets/5961a09e-0817-4277-af8b-888d816b942b)

same video with iridium disabled:
![Screenshot 2024-09-13 002423](https://github.com/user-attachments/assets/5e9e4ae1-e1dc-43a4-ac5d-c6c3da4faccb)

I've tried disabling all other extensions and being in private browsing mode.
browser version:
![Screenshot 2024-09-13 002658](https://github.com/user-attachments/assets/2847d153-308c-48e6-82cd-2e856f034398)

**Comment by ParticleCore** [comment]
It looks like you have the option to exclude 60fps enabled in the Iridium settings, which is a limitation of the website because they no longer offer non-high fps options for anything above 720p when there's only high fps high quality.

Can you confirm if you don't have that option active in your settings?

**Comment by phraggers** [comment]
You are super active here, that's awesome thanks for the fast reply!
Is this the setting here?
![Screenshot 2024-09-13 014718](https://github.com/user-attachments/assets/4336661b-424c-40b1-8c9c-1362549358f1)

**Comment by phraggers** [comment]
Answered my own question by switching it on, sorry didn't see that before! Thanks so much!

**Comment by ParticleCore** [comment]
No worries, I just happened to be working on the project when you opened the issue. Glad to hear you got it sorted out.
